### ISSUE TITLE
Run Qupath on server

### ISSUE THREAD

**Issue by muntesco** [qupath/qupath#100]
Hello everyone. Is it possible to run Qupath software on a server. I mean, if I have a collection of digital slides on an internal server (inside an organisation), is it possible to run it from different client PCs as if it were a web viewer? to access and analize digital slides?
Thank you.

**Comment by Svidro** [comment]
It certainly is, although there are different methods for doing so.  It mostly involves how much overlap you want your users to have in terms of annotations.
1.  Have all images on a server, and all QuPath projects on the client computers.  This means each person will have access to the same images, but will not share any cell generation or annotations.  Safest and easiest to set up, but probably least useful.
2.  Map the same network drive to the image location on all client computers (say, S: drive for your server), and use the same shared QuPath directory (say, Q: drive) created for each project on every computer.  This would mean that every user would have access to all images and modifications done through QuPath, but there are some fairly heavy caveats here.
 2A.  There is NO file copy protection AT ALL.  All users would have equal access to overwriting the current .qpdata file, and for all I know, they might attempt to save two different versions at the same time, creating a mess.  
2B.   If your .qpdata files are large (can get up to 3GB or so fairly easily with SLICs) you may have network bandwidth problems accessing both images and data files.  Actually, access to the images alone could be problematic depending on your hardware.  Multiple users accessing data on a single hard drive through a 1gigabit network connection can cause slowdowns in refresh rate.

**Comment by Shushalsec** [comment]
Hey all,
I have a similar question about running QuPath scripts on a server. If I have groovy scripts and images on a server, would it be possible to get QuPath on a UNIX server and batch process the images I need on a server instead of a local computer? Any help would be much appreciated!
