### ISSUE TITLE
TMA dearrayer putting cores off slide

### ISSUE THREAD

**Issue by dnmason** [qupath/qupath#101]
I'm just learning how to use QuPath (0.1.2), looks like a fantastic piece of software. However, I'm stumbling at the first hurdle with the TMA dearrayer which in this sample (of quite non-uniform TMA) puts some cores off the slide:
![tma cores](https://user-images.githubusercontent.com/7047957/30740362-937313de-9f88-11e7-897f-4bde72b7b27f.PNG)
These can be selected but cannot be moved. Is there a way to get them back onto the slide?

Related, it is possible to assign a TMA core manually (eg from an annotation) or 'crop' a section of the slide and do TMA dearraying only within that section?

Many Thanks!

**Comment by Svidro** [comment]
I think most of the useful information on TMA manipulation can be found here: https://github.com/qupath/qupath/issues/77
I am fairly sure you could find a way through scripting to edit each selected Core X-Y coordinates individually, but it might be better to just find one slide that works "well enough" and duplicate that data file.

**Comment by dnmason** [comment]
Thanks for the quick reply, great idea to use a 'dummy' file. Thanks for the link.
