### ISSUE TITLE
Get file name and scene name from script

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#102]
Dear all,

I am trying to, from a script, get the file name **AND** the scene(image) name so I could save a result for each slide scene(image) .
I know how to get the filename:
`
// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()

// Get the file name from the current server
def name = server.getShortServerName()
`
But in case I have multiple images (scene) inside each file, it will return the same file name without to distinguish which image it is currently processing.
So I would like to add the scene name as well (or eventually the image name from the image list that is processed when I run the script for the whole project containing multiple file which contain multiple image s(scene).
maybe something like:
project.getCurrentlySelectedImageName() (which doesn't exist)

I know I can already do:
`
for (def entry in project.getImageList()) {
    // Get lower case name
    def imageName = entry.getImageName()
    def name = imageName.toLowerCase()
    println(name)
}
But it it not OK to get inside the script the name of the image that I could use to save let say the measurement for each image of each file.
`

Is there a way to get this information ?

**Comment by petebankhead** [comment]
You can get the full path like this:
```groovy
// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()

String path = server.getPath()
print path
```

It so happens that for multi-scene images the bit you want should be added at the end, after ```::```.
Therefore you could extract it with something like the following:

```groovy
print path[path.lastIndexOf(':')+1..-1]
```

The reason why it's included in the path is that the path is used when caching image tiles, and so needs to be unique for each image - including each scene.  The ability to handle multiple scenes arose quite late in QuPath's evolution, and I think is restricted to occasions when Bio-Formats is used.  This approach gave a workaround that meant that caching tiles still works, without the built-in mechanism needing to be changed.

**Comment by bpavie** [comment]
Thanks a lot Pete, it is exactly what I was looking at.
Just for information, what is the difference between the QPEx and the QP class ?``

**Comment by petebankhead** [comment]
Good!  To answer your question:

```QP``` is inside the 'core' modules, which means it doesn't know anything about the GUI.

```QPEx``` is a subclass of ```QP``` that lives inside the GUI module - which has access to all the core modules too.  Therefore ```QPEx``` adds extra GUI-related methods (e.g. to request the QuPathGUI instance, or viewers) that aren't available within ```QP```.

*Potentially*, if you only rely on ```QP```, you could run a script headlessly, and completely independent of the QuPath GUI.  If instead you run your scripts from QuPath directly, then you may as well use ```QPEx```.  It should do the same, but also give you access to more stuff if you need it.

**Comment by bpavie** [comment]
Thanks for your fast answer Pete! We started to train people to use QuPath in our institute for a research purpose, so far I've got really go feedback! Thanks again for having release this great software and in opensource!
Could we find somewhere the API like the ImageJ project did ( https://imagej.nih.gov/ij/developer/api/index.html ) ?

**Comment by petebankhead** [comment]
Great, thanks!

The API documentation would be good... although I'm not entirely sure where/how to arrange to get it hosted.  I guess you may already have things set up with IntelliJ as described on the Wiki (if not, you probably should!), and through that there may be a way to generate javadocs... or at least browse the code directly.

In moments of desperation when I'm relying only on QuPath's editor, I use Java reflection to get a list of methods.  Here, for example, is a script to generate a list of all the methods in QPEx, with a little bit of cleanup to reduce redundancy:

```groovy
import qupath.lib.scripting.QPEx

def objectMethods = Object.getMethods() as Set

def replacements = [
    'qupath.lib.scripting.QPEx.' : '',
    'qupath.lib.scripting.QP.' : '',
    'public static ' : '',
    'java.lang.': '',
    'java.io.File': 'File',
    'java.util.List': 'List',
    ',': ', '
]

def sb = new StringBuilder('Methods:\n')
for (m in QPEx.getMethods()) {
    if (m in objectMethods)
        continue
    def method = m.toString()
    for (entry in replacements.entrySet())
        method = method.replaceAll(entry.getKey(), entry.getValue())
    sb << method
    sb << '\n'
}
    
print sb
```

One day I hope to get this documented better and available on the Wiki (like ImageJ's macro reference)...

**Comment by ChristophNeuner** [comment]
Thanks a lot to you two! You saved me a lot of time and struggle.

Here the two working scripts for future readers of this topic:

To json:
```
// workaround for a bug in current version: https://forum.image.sc/t/export-import-re-export-annotation-question/44075/2
def defaultColor = getColorRGB(200, 0, 0)
getAnnotationObjects().each {
   if (it.getColorRGB() == null) {
     def newColor = it.getPathClass() == null ? defaultColor : it.getPathClass().getColor()
     it.setColorRGB(newColor)
  }
}
fireHierarchyUpdate()


//filter out Tiles in annotations
def annotations = getAnnotationObjects().findAll {it.getName() == null || !it.getName().startsWith("Tile ")}
boolean prettyPrint = true
def gson = GsonTools.getInstance(prettyPrint)

import org.apache.commons.io.FilenameUtils
//get the wsi name without the type extension
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
String wsi_path = server.getPath()
String wsi_name = FilenameUtils.getBaseName(new File(wsi_path).getName());

def output_path = "./" + wsi_name + ".json"
def file = new File(output_path)

file.write(gson.toJson(annotations))

print "Done!"
```

-------------------------------------------------------------------------------------------------------------

and to csv:

```
import java.util.stream.Collectors
import org.apache.commons.io.FilenameUtils;

//get the wsi name without the type extension
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
String wsi_path = server.getPath()
String wsi_name = FilenameUtils.getBaseName(new File(wsi_path).getName());


def output_path = "./" + wsi_name + ".csv"
def header = "Annotation ID,nPoints,Points"
def listOfPoints = getAnnotationObjects().findAll {it.getName() == null || !it.getName().startsWith("Tile ")}.stream().map(e -> e.getROI().getAllPoints()).collect(Collectors.toList())

int index = 0
new File(output_path).withWriter { fw ->
    fw.writeLine(header)
    listOfPoints.forEach { points ->
        fw.write(index++ + "," + points.size() + ",")
        String line = points.stream().map(e -> String.format("(%f,%f)", e.getX(), e.getY())).collect( Collectors.joining(",") )
        fw.writeLine(line)
    }
}

print "Done!"
```
