### ISSUE TITLE
QuPath v0.3.2 does not open vsi files

### ISSUE THREAD

**Issue by MalgorzataSzolkowska** [qupath/qupath#1020]
## QuPath v0.3.2 does not open vsi files
**Describe a bug**
While opening a vsi slide the application crashes.

**To Reproduce**
1. Go to 'File'
2. Click 'Open'
3. Choose a file in vsi format
4. Double click on an image or click 'Open'

**Expected behavior**
Image should be downloaded and opened for viewing. 

**Screenshots**
Find attached. The screenshot presents a moment when the application stops working.

<img width="1160" alt="Fig1" src="https://user-images.githubusercontent.com/109394240/179327300-fa8522c2-021d-44a1-a061-4114b74b63cd.png">

**Desktop:**
 - OS: macOS 11.5.2 (however, my colleagues using Windows reported the same problem)
 - QuPath v0.3.2

**Additional context**
Version v0.3.0 does not have such a problem. The problem does not exist if you create a project first and add images.

**Comment by petebankhead** [comment]
Thanks @MalgorzataSzolkowska , this comes from the same underlying bug as these:
* #894 
* #904 
* #973

I've already fixed it in the code, so it should work in the next release.

**Comment by MalgorzataSzolkowska** [comment]
Thank you for your prompt response!

When I was searching for resolution of similar bug in previous issues I couldn’t find any. Perhaps because I thought the problem appears only for vsi (Olympus) format. I agree #894 refers to the similar problem as mine although they were launching Hamamatsu slides.

Looking forward to the next release of my favourite platform QuPath! 😊

Have a nice weekend,
Malgorzata Szolkowska
____________
Malgorzata Szolkowska, MD, PhD, DSc, Assoc. Prof.
The Institute of Tuberculosis and Lung Diseases
Department of Pathology
Plocka 26
PL-01138, Warsaw, Poland
Tel.: +48 22 43 12 257

**Comment by petebankhead** [comment]
Thanks! And yes, I found the previous reports hard to find as well, even though I remembered writing them :) I've just reopened
* #894 

and changed the wording to make it easier to find until v0.4.0 is available.
