### ISSUE TITLE
czi file opens at low resolution

### ISSUE THREAD

**Issue by Snotworm** [qupath/qupath#1023]
* [x ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x ] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
In QuPath 0.2.3 *.czi files (produced from Zeiss Axioscan) open in full resolution. In QuPath 0.3.2 the same file opens in low resolution (highly pixelated) and can not be viewed at higher resolution. 

**To Reproduce**
1. Open QuPath 0.3.2
2. Drag and drop *.czi file
3. *.czi file shows in low resolution

**Expected behavior**
The file should open at appropriate resolution as it does in QuPath 0.2.3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - QuPath Version [0.3.2]

**Additional context**
![Screen snapshot Qupath 0 2 3](https://user-images.githubusercontent.com/109750856/180259298-960d5dd7-2abc-4ea6-8688-3421e453a4e7.png)
![Screen snapshot Qupath 0 3 2](https://user-images.githubusercontent.com/109750856/180259377-d308150d-c89c-4bba-a715-f080f5fb5f80.png)

**Comment by petebankhead** [comment]
@Snotworm it might be another manifestation of https://github.com/qupath/qupath/issues/894

Can you try opening the image in a project instead?

**Comment by Snotworm** [comment]
@petebankhead As you suspected, the images open fine when loaded from a project so could be #894. In this instance there are also multiple images in each file and I think it is opened with Bio-formats. Sorry for the extraneous bug report.

**Comment by petebankhead** [comment]
No problem! The same bug has turned up in surprising ways, but all should be resolved in the next release.

Thanks for confirming the workaround works for now!
