### ISSUE TITLE
Saving optimised algorithms

### ISSUE THREAD

**Issue by mnolan1989** [qupath/qupath#105]
Hi,

I've optimised a positive cell count algorithm for use on my tissue (human brain). Is there anyway you can save algorithms within the program so you don't have to manually adjust each time you analyse a new slide?

Thanks!

**Comment by petebankhead** [comment]
It sounds like you need a simple, one-line script that contains your settings.

QuPath should already record these settings for you under the 'Workflow' tab.  Double-clicking an entry there should open/run the corresponding command with the appropriate settings... but this is only available for commands you've already run for the current image.

To transfer settings across an image, press *Create script*.  The automatically-generated script will probably contain too many lines, but you can simply delete the ones you don't want; for example, just keep the last line if the last thing you did was run the cell counting algorithm.

The script you end up with probably looks something like this:
```groovy
runPlugin('qupath.imagej.detect.nuclei.PositiveCellDetection', '{"detectionImageBrightfield": "Hematoxylin OD",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Nucleus: DAB OD mean",  "thresholdPositive1": 0.2,  "thresholdPositive2": 0.4,  "thresholdPositive3": 0.6,  "singleThreshold": true}');
```

You can then save this as a file with the extension ```.groovy``` and drag it onto QuPath again to open it.  Press *Run &rarr; Run* from the top menubar to apply it.

There is some more information under https://github.com/qupath/qupath/wiki/From-workflows-to-scripts
