### ISSUE TITLE
NPE if GeometryTools.refineAreas() is called with a non-area geometry

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1060]
## Bug report

**Describe the bug**
The exception thrown when passing a linear or point geometry to [`GeometryTools.refineAreas(Geometry geometry, double minSizePixels, double minHoleSizePixels)`](https://github.com/qupath/qupath/blob/v0.3.2/qupath-core/src/main/java/qupath/lib/roi/GeometryTools.java#L723) isn't exactly informative, e.g.

```
NullPointerException at line 6: Cannot invoke "org.locationtech.jts.geom.Geometry.getNumGeometries()" because "geometry" is null
qupath.lib.roi.GeometryTools.flatten(GeometryTools.java:453)
    qupath.lib.roi.GeometryTools.removeInteriorRings(GeometryTools.java:487)
    qupath.lib.roi.GeometryTools.refineAreas(GeometryTools.java:736)
    org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
    Script21.run(Script21.groovy:7)
```

**To Reproduce**
Code to reproduce the behavior:

```groovy
// Create a Line ROI
var roi = ROIs.createLineROI(0, 0, 100, 100, ImagePlane.getDefaultPlane())
// Alternative to create a Point ROI (also fails in a similar way)
// var roi = ROIs.createPointsROI(0, 10, ImagePlane.getDefaultPlane())
var geom = roi.getGeometry()
GeometryTools.refineAreas(geom, 1000, 1000)
```

**Expected behavior**
The faulty input should be caught earlier and an `IllegalArgumentException` thrown with a more informative message.

This is what happens with the closest method from [`RoiTools`](https://github.com/qupath/qupath/blob/v0.3.2/qupath-core/src/main/java/qupath/lib/roi/RoiTools.java#L268), i.e. calling
```groovy
var roi = ROIs.createLineROI(0, 0, 100, 100, ImagePlane.getDefaultPlane())
RoiTools.removeSmallPieces(roi, 1000, 1000)
```
results in
```
IllegalArgumentException at line 3: Only area ROIs supported!
qupath.lib.roi.RoiTools.removeSmallPieces(RoiTools.java:382)
    org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
    Script23.run(Script23.groovy:4)
```

However there are at least two problems with the javadoc for the `RoiTools` method:
* the `IllegalArgumentException` isn't mentioned
* it isn't obvious that the method returns null if the entire ROI is removed (rather than an empty ROI) - so this should be documented

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version: v0.3.2 (and earlier)

**Additional context**
I first became aware of the issue at https://forum.image.sc/t/exporting-ndpi-ndpa-annotation-files-from-qupath-code-attached/55418/11

Potentially, the method names for `RoiTools` and `GeometryTools` should be standardised since they do much the same thing, and tests should be added.

**Comment by zindy** [comment]
Hi Pete,

If I create a polygon ROI with an empty `points_list` (or any number of points added to it), `GeometryTools.refineAreas()` is absolutely fine with it.

```
import qupath.lib.geom.Point2

def points_list = []
//points_list.add(new Point2(0, 0))
//points_list.add(new Point2(1000, 1000))
//points_list.add(new Point2(0, 1000))
//points_list.add(new Point2(1000, 0))
var roi = ROIs.createPolygonROI(points_list, ImagePlane.getDefaultPlane())

var geom = roi.getGeometry()
GeometryTools.refineAreas(geom, 1000, 1000)
```

From the from the `getGeometry()` operation. we just get:
> INFO: Result: POLYGON EMPTY

**Comment by petebankhead** [comment]
This should be fixed now, at least as well as it's going to be. The behavior has been changed to return empty ROIs rather than null, if the entire region disappeared. It also strips away points and lines if changing a ROI/Geometry, instead of throwing an exception.
