### ISSUE TITLE
The legend colors do not match the Pie chart colors

### ISSUE THREAD

**Issue by ajay1685** [qupath/qupath#1062]
## Bug report

**Describe the bug**
When using ```Charts.pieChart()``` the colors of the chart match the colors for that class of objects. However, the colors of the legend do not match!

**To Reproduce**
1. Run Positive cell detection on an image
2. Use the following code to create a pie chart:
```
    chartData = getDetectionObjects().countBy(p -> p.getPathClass())
    Charts.pieChart()
        .title('Test Chart')
        .data(chartData)
        .show()
```

**Expected behavior**
The colors of the legend shall match the colors of the pie.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/10900214/192350181-ebb62218-af1a-4031-b107-fe255d5efd69.png" width="450">
</p>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version: Tested on v2.3 and the latest snapshot

**Additional context**
More details on the forum:
https://forum.image.sc/t/pie-chart-legend-colors/72051

**Comment by petebankhead** [comment]
Thanks @ajay1685 for reporting this!

**Comment by petebankhead** [comment]
Just adding for reference that this self-contained script shows the problem as well:

```groovy
def chartData =
     [(getPathClass('Negative')): 5,
     (getPathClass('1+')): 2,
     (getPathClass('2+')): 3,
     (getPathClass('3+')): 4]
     
Charts.pieChart()
    .title('Test Chart')
    .data(chartData)
    .show()
```
[Also learned that non-string keys in Groovy need to be in (brackets)...]

**Comment by petebankhead** [comment]
This should be fixed now... along with a hidden bug that gave the wrong legend colors with pixel/object classifiers if more than 8 classes were used (which admittedly would probably not work well anyway).
