### ISSUE TITLE
QuPath down list problems

### ISSUE THREAD

**Issue by sahibzan** [qupath/qupath#1067]
## IMPORTANT!

Please the photo. macOS Monterey Version 12.6.

<img width="1392" alt="Screen Shot 2022-10-03 at 3 38 29 PM" src="https://user-images.githubusercontent.com/114953348/193666849-47190166-5637-4e02-8c86-0014775abc0b.png">

**Comment by petebankhead** [comment]
Hi @sahibzan could you check this discussion please, and see if it helps resolve the issue?
* https://github.com/qupath/qupath/issues/866

**Comment by petebankhead** [comment]
I'll close this issue because of a lack of response - and it seems to me to be a general JavaFX/font problem, as discussed in the other thread.
