### ISSUE TITLE
wrong meta data in .tif files

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#107]
Hello, 

if I open .tif files within qupath, meta data are readed wrong. I get by far to large pixel sizes. 
![grafik](https://user-images.githubusercontent.com/16352785/31247636-7f6dfa32-aa11-11e7-9041-b5ee90993e91.png)

And the magnification is wrong. 
Is there a way to change the .tif or do change anything in QuPath to get right pixel values?

If I open the .tif in paint, do nothing but save it again as .tif with other name, where will be no meta data at all and i can work with pixel based sizes and parameters. 
Best
David

**Comment by petebankhead** [comment]
A few questions:
* Do you know what the right values are?
* Do you know which software wrote the TIFF?
* What are the pixel sizes if you open the image in Fiji - the same as shown in QuPath, or different?

In general, I wouldn't recommend opening the image in Paint - but you can open it in Fiji/ImageJ, go to *Image &rarr; Properties* and edit the pixel size there.  If you aren't sure of the true values, then you can enter the pixel width and height as being 1 pixel.
