### ISSUE TITLE
Send only tumour annotation to ImageJ

### ISSUE THREAD

**Issue by oriolarques** [qupath/qupath#108]
Hi,
On a whole-slide-image I use simple tissue detection to select the whole tumour area, then positive cell selection to identify positive cells and finally I train a classifier to distinguish between tumour and stromal cells.
I would like to know if it is possible to send to ImageJ ONLY the annotation of tumour cells because when I click send region to ImageJ i get all annotations as overlays even if I remove stromal annotations using Toggle dispaly class.
Thanks

**Comment by Svidro** [comment]
Would it work for your analysis to export all of the information you need on the stromal cells (and whatever else you are studying) first, and then delete everything that is not pathClass Tumor?  That is the simplest way I can think of to prevent the other overlays from being sent to ImageJ.

**Comment by petebankhead** [comment]
It seems that you have two options... either remove the stromal cells in QuPath (so they can't be sent), or remove them from the overlay in ImageJ after they have been sent.

Here's an ImageJ macro that might work to remove them from the overlay:
```java
i = 0
while (i < Overlay.size) {
	Overlay.activateSelection(i);
	name = Roi.getName();
	if (indexOf(name, "Stroma") >= 0)
		Overlay.removeSelection(i);
	else
		i++;
}
```

Alternatively, to remove the cells in QuPath, this script could work
```groovy
def stromaCells = getDetectionObjects().findAll {it.getPathClass() == getPathClass("Stroma")}
removeObjects(stromaCells, true)
```
Although once removed, you can't get the cells back... so best use that script with caution (and save your data before running it, if in doubt).

**Comment by Svidro** [comment]
Another way would be to change the opacity of the stromal (etc) colors to 1%.  It refuses to allow 0% for full transparency, but if you double click on the color in the annotation tab, select Custom Color, you can manually turn down the opacity to 1%, which may be good enough.  I am not sure how to do this in a script, however.

**Comment by oriolarques** [comment]
Thanks for the quick response! 
I think the script to work in QuPath will be the easiest way to do it.
