### ISSUE TITLE
Update 'Unique ID' to 'Case ID' for TMA cores

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1114]
[`TMACoreObject`](https://github.com/qupath/qupath/blob/v0.3.2/qupath-core/src/main/java/qupath/lib/objects/TMACoreObject.java) has a 'Unique ID' property, which was always confusingly named.

Its original purpose was to uniquely identify cores belonging to the same patient - which meant that multiple cores could (and often should) have the same unique ID. Which meant a curious interpretation of 'unique'.

It's useful because it makes it possible to group cores with the same ID, e.g. to compute summary measurements. I used this a lot in the original QuPath *Scientific Reports* paper, but haven't really used it myself much since then.

Since all `PathObject` instances now have an ID property, which should be unique, the use of 'Unique ID' as a property for a TMA core becomes even more confusing. I'd like to change it as soon as possible. Doing so now fits with recent work to rename key methods to improve consistency and reduce ambiguity, e.g.
* https://github.com/qupath/qupath/pull/1109
* https://github.com/qupath/qupath/pull/1111

My proposal is to change **Unique ID** to become **Case ID**.

I know others use the TMA functionality more often than me (e.g. https://github.com/qupath/qupath/issues/1083) so I want to leave this issue here for a day or two to a) give a reference explaining the change, and b) ask for feedback as to whether it's a good/bad idea, or there's a better name than than *Case ID*.

I'd like to stay away from *Patient ID* because it feels quite human-specific to me, and I have some concerns that it encourages the use of identifiers that might be sensitive - and really any identifier used in QuPath ought to be anonymised.

Making the change involves an extra decision. The easy bit is to create methods for `TMACoreObject.setCaseID(id)` and `TMACoreObject.getCaseID()` - the old methods can remain temporarily, but emit a warning if they are called*. The trickier choice is whether to update the name used internally to store the value; I'd like to change it, but it means that IDs saved in QuPath v0.4.0 won't be recognized in older versions.

@ajay1685 @Svidro @saramcardle @zmikulski (not sure who is using the TMA functionality...)

*-**Note to self!** @petebankhead Need to decide on `getID()` or `getId()` and ensure this is consistent...

**Comment by petebankhead** [comment]
Thanks @ajay1685 - I also think the sooner the better for the changes, which is why I'd like to squeeze them into v0.4.0.

I don't know of any reason why someone would need to go back from v0.4.0 to v0.3.x... unless some troublesome bug emerges in v0.4.0 - but then I'd rather the solution would be v0.4.1 instead.

**Comment by saramcardle** [comment]
I actually didn't know that TMAs had a UniqueID property. I recently used TMAs with multiple cores from the same patient and I had to write my own work around for this. It seems it's not available in right click menu GUI, where it would be most natural (for me) to input them?

That being said, I think the changes you made are useful. I would prioritize clean code into the future over the ability for older versions to read new projects. If I have a project with TMAs in 0.3.2, will this change leave me unable to open in in 0.4?

Also, I vote that ID is capitalized in set and get functions.

**Comment by petebankhead** [comment]
Thanks @saramcardle! My lack of using TMAs for years means that the documentation for the ID is only for v0.1.2 at https://github.com/qupath/qupath/wiki/TMA-CD3-analysis

> If I have a project with TMAs in 0.3.2, will this change leave me unable to open in in 0.4?

That shouldn't be a problem. It could potentially also update the IDs to use the v0.4.0 key. It's just that if you go back to v0.3.2, the IDs will seem to have been lost and needed added again.

> Also, I vote that ID is capitalized in set and get functions.

Thanks! Me too I think. Do you feel the same about URI...?

I tried to check what Java itself does and it seems a bit inconsistent with both of those.

**Comment by petebankhead** [comment]
Made the changes now - thanks again!
