### ISSUE TITLE
Using hamamastu ndpis files with QuPath

### ISSUE THREAD

**Issue by shadyamigo** [qupath/qupath#113]
First of all I would like to say thank you providing such great software for us all to use. With my DAB images it has saved so much time and is a joy to use.

However, most of our work is now using fluorescent hamamtsu scans i.e. ndpis files. These are aligned ndpi files. I tried to use the bio-formats extension but this will also not open them.

I have successfully got very good detection of DAPI nuclei on the individual dapi scan. What I would like to do is take these nuclei and overlay them on the over channels/images.
I did have some success opening up the qpdata file in notepad++ and changing the file name to a corresponding other channel e.g. FITC but the detection measurements are not recalculated.
So I guess my question is:

Is there a script I can use to import the dapi hierarchy from the dapi.qpdata file and overlay it on the other channels and then subsequently force re-measurement of  the features e.g. intensity measures etc?

Thank you so much

**Comment by Svidro** [comment]
I am not familiar with that file format, but have you tried using _Analyze->Calculate Features-> Compute Intensity Features_ when in the new image?  As long as you can use whole cell information and do not need cytoplasm vs nuclear localization I think that should be fine.  The latter could also be done, but involves some scripting.

**Comment by shadyamigo** [comment]
Thank you Svidro, that has helped a great deal and I have now calculated the measurements as you suggested.
I'll try and write some scripts to automate the qpdata renaming and analysis-any help would be greatly appreciated.
Thanks again

**Comment by Svidro** [comment]
Pete's suggestion in #114 might be useful here if you wanted to do a little
image reshuffling.

1. Have all of the aligned ndpi files named the same exact thing, but with
the images in different folders called DAPI, TRITC etc.

2. Use multiple project files, each pointing to one of those channel
folders depending on which channel you want to work in (DAPI.qpproj etc.).
Then you never need to move or edit the qpdata files, just do some renaming
at the start and open the project file for the channel you want to work in
later.

**Comment by petebankhead** [comment]
@Svidro beat me to it with the link to #114 
The multiple projects could help.  It could be scripted as well, if you don't mind going a bit more deeply into the QuPath code, but probably best see if the workaround... works.

(Incidentally, I didn't know about ndpis until a couple of weeks ago... but I think this is the third time I've heard of the problem now.  Certainly I will look into a longer term solution, and it's good to have it logged here as an issue now.)

**Comment by shadyamigo** [comment]
Thanks Svidro,
I will give that a try.
Best wishes

**Comment by shadyamigo** [comment]
Sorry Peter. I missed your reply-I will give the multiple projects a try. But I am also keen to script it. I have a c# background but have downloaded the java source to see if I can get my head around it. I can supply the ndpis Giles if you would like to do any testing. Basically it's just a text file that links multiple ndpi files that came from the same scan run (i.e. different filter per ndpi  file)

**Comment by petebankhead** [comment]
Thanks, it should definitely be possible to open the files as separate channels of the same image.  I looked at the QuPath Bio-Formats extension last night and saw where the problem might be, but have not yet managed to resolve it fully.  I suspect the trouble lies in the [QuPath extension code](https://github.com/qupath/qupath-bioformats-extension/blob/master/src/main/java/qupath/lib/images/servers/BioformatsImageServer.java), but not in QuPath itself nor in Bio-Formats.

I will look into it some more, but should probably admit that I won't realistically be in a position to fix it for at least two months or so.  In the meantime if you want to resolve things sooner and have any questions I can help with, just let me know.

**Comment by shadyamigo** [comment]
Thanks for looking into, would be amazing if they did work natively so that I could use the classifiers.
Thanks again.

**Comment by petebankhead** [comment]
Hopefully this is fixed now.  At least it works for the one the ndpis example I've got, although with many other performance improvements.

There's more info [here](https://groups.google.com/d/msg/qupath-users/78PpZuu2J1s/su6ZjY0mAgAJ).

**Comment by shadyamigo** [comment]
thanks so much for doing this-it is working very well
