### ISSUE TITLE
Tiles to annotations bug in .svs file

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#115]
Hello all, 

i had a bug running the tiles to anntoations function on a large .svs
Only parts of the image are processed. My hardware might be to weak and maybe the reason for it. Anyhow, there was no information about an error.
The image looks like this: 

![grafik](https://user-images.githubusercontent.com/16352785/32601114-e93bbd14-c541-11e7-9b6e-c41d78c56c28.png)

**Comment by Svidro** [comment]
I would first check the log file (View-> show log), but it does look like you might have run out of memory. 

It is also possible that *sometimes* the detection creation functions run into problems with "small" tiles, and the entire process stops.  To get around this (or test for it) I would recommend choosing slightly different settings in your Simple Tissue Detection (more smoothing, requested pixel size change, etc.).
