### ISSUE TITLE
Select Annotation from a script

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#116]
Dear All,

Having 2 annotations, how could I perform the cell detection from a script on a particular annotation:
The create command for script gave me the following line:

`runPlugin('qupath.imagej.detect.nuclei.WatershedCellDetection', '{"detectionImageFluorescence": 1,  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 100.0,  "watershedPostProcess": true,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');`

This command require to select annotation in advance.
I am aware I can add the line :

`selectAnnotations();`

But that's select **all** the annotation, when I would like to perform the cell detection on only **1** specific annotation.

How could I perform that?

Best,

**Comment by Svidro** [comment]
Largely covered here, I think.  There may be more details in a few other topics, but that should cover it fairly well.

https://groups.google.com/forum/#!topic/qupath-users/R4Qx77Ev3oA

**Comment by bpavie** [comment]
Thanks a lot,
I have just to add 
`fireHierarchyUpdate()`

I didn't know they was a forum : https://groups.google.com/forum/#!forum/qupath-users

Thanks
