### ISSUE TITLE
TMA 

### ISSUE THREAD

**Issue by Tkilvaer** [qupath/qupath#117]
Hi
First I will take the opportunity to salute the maker of such a formidable piece of software. It hits its audience right on the mark. Easy enough for those puking of computers and powerful enough for those willing to go the extra miles and code some themselves.

I was working on a TMA project with 11 TMAs and about 600 patients with 4 cores each. I can open each individual TMA in TMA data viewer and play around with the summary statistics. But when I try to import from current project my computer slows down to a crawl. After increasing the amount of memory available to qupath to 5GiB import from current project will eventually work. 

I guess it is the TMA core images that makes this process so memory hungry. Is it possible to turn of this feature?

**Comment by petebankhead** [comment]
Thanks!

For the TMA data viewer troubles, to be honest I entirely forgot that the *Import from current project (experimental)* option is there...  it probably isn't a very good idea.

I'd suggest doing the following instead:
* Use *File &rarr; Export TMA data* for each of your images, using the same output directory (it's also scriptable)
* Drag the export directory into the TMA data viewer

That way, the data viewer doesn't need to bother with QuPath objects (potentially hundreds of MB per TMA), nor with accessing the whole slide scans.  Rather, it will work with small, exported JPEGs and parsed text files, and hopefully behave much better.

**Comment by Tkilvaer** [comment]
The solution worked  flawlessly!
