### ISSUE TITLE
List of scripts infinitely grows with duplicates when switching from one to another

### ISSUE THREAD

**Issue by Rdornier** [qupath/qupath#1175]
## Bug report

**Describe the bug**
When we search for a script in a folder via 'Automation -> Shared Scripts' , the list of scripts corresponds exactly to those inside the folder. But if we move the mouse on another folder, and then go back on the first folder, the list of scripts has now doubled in size, with duplicates of scripts. Doing like this many times, it adds duplicates of scripts at each iteration. The list can be re-initialized when you exit from 'Automation -> Shared Scripts'.

**To Reproduce**
1. Go to 'Automation -> Shared Scripts' 
2. Select on folder but do NOT OPEN any script
3. Move your mouse to another folder
4. Move your mouse back to the first folder
5. See that the list of available scripts is now doubled with duplicates of scripts.

**Expected behavior**
Should only display the list of available scripts, without any duplicates, even if we select this folder more than once.

**Screenshots**
![QuPath040_bug_script](https://user-images.githubusercontent.com/64911638/205653051-987a1ec2-42ee-4729-ad02-13077204879f.gif)

**Desktop**
 - OS: Windows 11
 - QuPath Version: 0.4.0

**Comment by petebankhead** [comment]
Thanks for the clear description, I'll try to fix this for v0.4.1 :)
