### ISSUE TITLE
Save all marked objects (nuclei) in a FISH image as separate file

### ISSUE THREAD

**Issue by saanasum** [qupath/qupath#118]
Dear all,
Many thanks for providing such a great tool for free!

Is it possible  for each identified/detected object from an original input image to save all objects as sub-images via individual image files.

My goal is to mark all nuclei in a FISH image and then export each nuclei as separate file. The saving needs to be done in one step.

**Comment by Svidro** [comment]
Aside, have you tried the _Subcellular detection_ command or ImageJ macro runner for identifying the spot counts in QuPath?  In case you were exporting the images for the FISH analysis.

Otherwise, there are some decent options for scripts picking out objects and exporting them as individual files found at https://github.com/qupath/qupath/issues/97 although that is mostly if you want an image of the bounding box area.

If you want the nuclei and no other image data, I am less certain, although there is probably a way to do so using the ImageJ macro runner and saving them via ImageJ using the commands there to remove the area outside of the nucleus ROI.

**Comment by saanasum** [comment]
Thanks for your answer. 

For segmentation I use **DoG superpixel creator** which gives nice results on detecting individual nuclei. 

Afterwards I try to use the one line macro as proposed in #85 : 
`saveAs("tif", "/Users/peteb/Desktop/export/" + getTitle())`
to save the detected nuclei as separate image file. One exampel is shown in the follwoing screenshot (2 nuclei of interest):

![01](https://user-images.githubusercontent.com/20478730/33028565-92f4738c-ce16-11e7-8fe5-88f1325027d2.PNG)

However, the macro does only save annotations and segmented nculei are not classified as annotations (as objects instead?). 

Is there a way to transfer the type/class of segmented nuclei to annotation type/class? This would make the macro work (I guess).

**Comment by saanasum** [comment]
I tried to modify the script proposed in #97 for the case demonstrated in the following figure:

![02](https://user-images.githubusercontent.com/20478730/33174622-18c2a36e-d059-11e7-9972-ee1a58d4fe01.PNG)

Script:
```
import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath("XXX/TESTFOLDER")
mkdirs(dirOutput)

// Write the nuclei
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (Polygon in selectDetections()){
    // Stop if Run -> Kill running script is pressed   
    if (Thread.currentThread().isInterrupted())
        break
    // Write the image
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, Polygon.getROI()))
    ImageIO.write(img, 'PNG', new File(dirOutput, Polygon.getName() + '.png'))
}
print('Done!')
```
I substituted _core_ from the original script with _Polygon_ and `getTMACoreList()` with `selectDetections()` to   make it working for detections. 

There is no error message in the script but it doesn´t work. Does anyone have an advice? Thank you!

**Comment by Svidro** [comment]
Glad you made it that far!  I have not played with exporting images much, but for cycling through the detections I think you want getDetectionObjects().  I do not think selecting them returns them, so your script is not actually running through anything.  You can test it by putting a print statement inside the loop too.

**Comment by saanasum** [comment]
Thanks! Now it partially works using this code:

```
import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest
// Define resolution - 1.0 means full size
double downsample = 1.0
// Create output directory inside the project
def dirOutput = buildFilePath("XXX/")
mkdirs(dirOutput)
// Write the nuclei
def server = getCurrentImageData().getServer()
def path = server.getPath()
getDetectionObjects().parallelStream().forEach({Polygon ->
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, Polygon.getROI()))
    ImageIO.write(img, 'JPEG', new File(dirOutput, Polygon.getName() + '.jpg'))
})
print('Done!')
```

**However it only saves one Polygon** (more or less randomly, out of ca. 20). I guess its because the Polygons do not have unique names. 

Is there a way to include a command in the above mentioned script that gives each Polygon an unique name?

**Comment by saanasum** [comment]
I think I got it. The point was to give each Plygon an individual name so that each Polygon can be saved as indivual image file.

This works for me:

```
import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath("L:/FALK/DeepLearning_FZ/Testdatensaetze/FISH-HER2/")
mkdirs(dirOutput)

// Write the nuclei
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (Polygon in getDetectionObjects()){
    roi = Polygon.getROI()
    print(roi)
    area = roi.getArea()
    print(area)
    name = ("Polygon_" + area)
    print(name)
    // Stop if Run -> Kill running script is pressed   
    if (Thread.currentThread().isInterrupted())
        break
    // Write the image
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, Polygon.getROI()))
    ImageIO.write(img, 'PNG', new File(dirOutput, name + '.png'))
}
print('Done!')

```

**Comment by Svidro** [comment]
That will work as long as you never have two with the exact same area.  I would recommend using the X Y coordinates, or creating a dummy variable where i = i+1 each time through the for loop with i going into the image name instead of area.  I suppose the chances of that being important depend on how many nuclei you are studying per image.

**Comment by saanasum** [comment]
Good idea. Thank you! I still need to get more in touch with QuPath-scripting for making those ideas possible: https://github.com/qupath/qupath/wiki/Scripting-examples

**Comment by Svidro** [comment]
That will work as long as you never have two with the exact same area.  I would recommend using the X Y coordinates, or creating a dummy variable where i = i+1 each time through the for loop with i going into the image name instead of area.  I suppose the chances of that being important depend on how many nuclei you are studying per image.

**Comment by Svidro** [comment]
Ah, for the i method, you could use a line just above the for loop:
def i = 1
And at the very last line of the loop after the image write:
i = i+1

Then the only other change should be replacing "area" in "name" with i.  Or whatever you chose to call i. 
Pete showed using the XY coordinates in another posting, but I am not sure where at the moment (on my phone).

**Comment by saanasum** [comment]
In the meantime this might work:

   ```
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (Polygon in getDetectionObjects()){
    roi = Polygon.getROI()
    print(roi)
    area = roi.getArea()
    print(area)
    CentroidX = roi.getCentroidX()
    print(CentroidX)
    name = ("Polygon_" + area + CentroidX)
    print(name)
```

**Comment by saanasum** [comment]
Yes, the i -method:

```
import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath("L:/FALK/DeepLearning_FZ/Testdatensaetze/FISH-HER2/Kerne/single_nuclei/")
mkdirs(dirOutput)

// Write the nuclei
def server = getCurrentImageData().getServer()
def path = server.getPath()
i = 0
for (Polygon in getDetectionObjects()){
    roi = Polygon.getROI()
    print(roi)
    area = roi.getArea()
    print(area)
    CentroidX = roi.getCentroidX()
    print(CentroidX)
    name = ("Polygon_" + i)
    print(name)
    // Stop if Run -> Kill running script is pressed   
    if (Thread.currentThread().isInterrupted())
        break
    // Write the image
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, Polygon.getROI()))
    ImageIO.write(img, 'PNG', new File(dirOutput, name + '.png'))
i = i + 1
}
print('Done!')
```

**Comment by petebankhead** [comment]
Hi, joining a bit late.... part of one of the suggestions above contained:
```groovy
getDetectionObjects().parallelStream().forEach({Polygon ->
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, Polygon.getROI()))
    ImageIO.write(img, 'JPEG', new File(dirOutput, Polygon.getName() + '.jpg'))
})
```

If you want to keep that kind of concise way of looping, `eachWithIndex` might help.  The corresponding part might look something like this:
```groovy
getDetectionObjects().eachWithIndex {pathObject, index ->
    def img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, pathObject.getROI()))
    def name = pathObject.getDisplayedName() + '_' + index + '.jpg'
    ImageIO.write(img, 'JPEG', new File(dirOutput, name))
}
```

I also used `getDisplayedName()`; if no name has been set, this will try to come up with something else useful for that object (e.g. the classification).  And I added `def`, which you don't really need but it keeps the variables local (otherwise you could likely access them after the loop).

**Comment by saanasum** [comment]
Perfect! Thank you!
