### ISSUE TITLE
Script editor commands Insert->Imports do not work

### ISSUE THREAD

**Issue by zmikulski** [qupath/qupath#1183]
## Bug report

**Describe the bug**
Script editor commands Insert -> Imports -> QP, QPEx, All default do not paste code into the script editor

**To Reproduce**
1. Go to 'Script Editor'
2. Click on 'Insert'
3. Click on 'Imports' and any of the options
4. The code does not get copied to the script editor

**Expected behavior**
In 0.3.2 default imports were pasted into the script editor window. I assume this is a new and not intended behavior in 0.4.0

**Desktop (please complete the following information):**
 - OS: [Windows]
 - QuPath Version: [0.4.0]

**Additional context**
I found this bug in a snapshot version of 0.4.0 which was built on 2022-07-21. I don't think the bug is harmful or high priority as 'Include default imports' is selected by default, and everything seems to work with that setting enabled.

**Comment by petebankhead** [comment]
Ah yes, well spotted - that [`\\ TODO: Fix`](https://github.com/qupath/qupath/blob/b4274452efbf7e1e7a1ed5bae1bb502b4bfdb376/qupath-gui-fx/src/main/java/qupath/lib/gui/scripting/DefaultScriptEditor.java#L1970) in the code is rather telling....
