### ISSUE TITLE
Project entries don't appear in project browser

### ISSUE THREAD

**Issue by davystrong** [qupath/qupath#1184]
## Bug report

**Describe the bug**
Really this bug so specific it may be too much effort to fix in the meantime, but I thought I'd better document it and what I've discovered about it.

When I open a project, QuPath fails to show the project entries in the sidebar (under specific circumstances - see below) until I somehow update the UI state: resize the window, click one of the toolbar buttons or (weirdly) move my mouse from within the viewer slowly over the red viewer border.

**To Reproduce**
1. Have enough extensions (or whatever) that enough buttons have been added to the toolbar to cause it to overflow (show the two little expansion arrows) when QuPath is first opened. In my case, I had added a button with "Convert" on it.
2. Open QuPath
3. **Don't** resize the window
4. Open a project
5. The project entries don't show up unless you perform one of the actions mentioned above

**Expected behavior**
Entreis should appear immediately

**Desktop (please complete the following information):**
 - OS: macOS (Apple Silicon)
 - QuPath Version: 0.4.0

**Additional context**
* Git bisect shows that the bug was introduced by commit 56243921831ca8d2db2507ec3604735dd4b4a608, but only because it added a "Show names" button to the toolbar.
* v0.3.2 doesn't seem to have the issue, even if I add a "Show names" button. **However**, (and probably the cause of the problem) I can't compile 0.3.2 for ARM, so it's running on x86. I also can't compile the previously mentioned commit on x86, only ARM, so I can't test if it was simply this difference. Also, my x86 SDK is temurin 16 and my ARM SDK is temurin 17.
* If I go to qupath-gui-fx/src/main/java/qupath/lib/gui/panes/ProjectBrowser.java, the root TreeItem appears to be added but the rest of the items aren't, until I cause a state change.

**Comment by petebankhead** [comment]
Intriguing - if you download the x86 build does it have the same behavior? I guess you may have to rename any Apple silicon installation beforehand (I'm not sure if/how the general package installer deals with multiple installations with the same name).

**Comment by davystrong** [comment]
Weirdly I can't get it to open. MacOS says '"QuPath.app" is damaged and can't be opened. You should move it to the bin'. Even when I go into the package and manually run the QuPath script from the terminal I get the same error. I'll maybe try installing Java JDK 17 x86 and see if I can compile it, unless you have another suggestion.

**Comment by petebankhead** [comment]
Did you try right-click, as described at https://qupath.readthedocs.io/en/0.4/docs/intro/installation.html#installation ?

**Comment by davystrong** [comment]
Thanks, that worked. I had to right click on QuPath.app and click open, twice, as you suggested. The same issue occurs, so it doesn't seem to be an x86 vs ARM issue.

**Comment by petebankhead** [comment]
I haven't been able to replicate this - but I was trying to do it by adjusting screen size, and not installing extensions (since creating an extension to add a button would be quite a hassle...).

Questions:
* How are you opening the project (e.g. button, menu, drag & drop), and does it matter?
* Can you see the issue *without* any custom extensions installed?

**Comment by davystrong** [comment]
The method of opening the project doesn't matter. I just tested drag&drop, open dialog and recent dialog. All have the same problem.

Regarding your other question, only if I add enough buttons to the source to cause the problem. For example, if I add
```java
nodes.add(ActionTools.createToggleButton(ActionTools.createAction(() -> {
	}, "something", IconFactory.createNode(QuPathGUI.TOOLBAR_ICON_SIZE, QuPathGUI.TOOLBAR_ICON_SIZE,
	PathIcons.BRUSH_TOOL), null), true, true));
nodes.add(new Separator(Orientation.VERTICAL));
nodes.add(ActionTools.createButton(ActionTools.createAction(() -> {}, "Convert"), false));
```
(sorry for the formatting) to qupath-gui-fx/src/main/java/qupath/lib/gui/ToolBarComponent.java line 170 (just before `toolbar.getItems().setAll(nodes);`) it demonstrates the issue. This is simply adding one toggle button, one separator and one text button to the end (sorry, I'd forgotten about the toggle button). I have no actions on these buttons which would interfere, nor any accelerator etc.

**Comment by petebankhead** [comment]
Thanks for exploring, although I'm now a bit lost in the details.

One possibly-important thing that seems missing: what size/resolution of display are you using?

I still haven't managed to replicate the problem on two computers (13" MBP & Mac Studio with Studio Display. I tried a few different screen resolutions, and adding extra buttons to the toolbar code. The project entries always show up immediately, even whenever the toolbar contains more buttons than can be shown at once.

Am I right that the bug appears for you only when
* There is precisely one button too many in the toolbar when QuPath is launched (more or fewer & the bug doesn't appear)
* The QuPath window is not resized at all prior to opening the project

Also, does it appear for every project you try? Have you been able to test it on a second computer?

**Comment by davystrong** [comment]
* My display is the M1 Macbook Pro 16", so 3456x2234. However, after your suggestion I switched my main display to a 24" 1920x1080 display I have and was still able to replicate the problem (after adding the appropriate number of buttons).
* Yes, there needs to be precisely one too many buttons. If the buttons only just fit in the toolbar, no problem. If I have two buttons in the overflow, also no problem.
* Yes, nothing should be done to update the state before opening the project. If, before opening the project, I (slowly) mouse over the red border it will then work, likewise clicking a toolbar button or resizing the window (actually, just clicking when the resize cursor appears is enough - I don't actually have to change the size).
* Yes, it happens on every project.

**Comment by petebankhead** [comment]
Thanks @davystrong I finally managed to replicate the issue. Extremely obscure and not sure if the origins are in QuPath or JavaFX, but the PR above fixes it for me.

**Comment by davystrong** [comment]
That fixes it for me too. It does seem like a JavaFX issue, but who knows. That's great! Thank you!
