### ISSUE TITLE
Smart quotes can be overly enthusiastic

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1188]
## Bug report

**Describe the bug**
The script editor in v0.4.0 can automatically close quotes, to help ensure strings are valid.

This is mostly helpful, but can sometimes be inconvenient if the closing quote is added when it isn't needed.

**To Reproduce**
1. Open a script editor and type `forgot to start"`
2. Move the caret to the start of the text
3. Type `"` and note that you get `""forgot to start"`

**Expected behavior**
Reduce the enthusiasm of the smart quotes to make them smarter.

One simple strategy that I think should help is to only add a closing quote if the preceding and following characters are either whitespace or the end of the text itself.

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version: 0.4.0

**Comment by MichaelSNelson** [comment]
Thanks!
