### ISSUE TITLE
Fast-red subcellular ISH detection

### ISSUE THREAD

**Issue by mnolan1989** [qupath/qupath#119]
Hi,

I'm attempting to quantify a chromogenic ISH method that uses a fast-red signal. I have tried using the subcellular detection tool but it appears geared towards DAB signal detection. Is there a workaround/does anybody have any suggestions?

Thanks!

Matthew

**Comment by Svidro** [comment]
The interface will generally use the second color vector as its detection channel for the subcellular detection, so make sure that color vector is set to your fast red.  If you need to do 2 color, I recommend setting the image type to Brightfield Other, though that has its own dangers!   You are not locked into using DAB.  I think changing the name of the color vector also changes the description in the subcellular detection dialog.

**Comment by mnolan1989** [comment]
Thanks! Changing this solved it.

I'm now trying to quantify the number of dots as a ratio of nuclear:cytoplasmic location. I'm using the script at the bottom of this page:

https://github.com/qupath/qupath/wiki/Spot-detection

This tells me the location of the spot when it is selected. However, I want to know the number of nuclear vs cytoplasmic dots when the cell is selected. I guess the nearest measure of this (using the above script) is just the Nuclear DAB OD mean vs Cytoplasmic DAB mean, but I'd like to know the actual number of dots as a nuclear:cytoplasmic ratio if possible?

Apologies if this is a simple question!

**Comment by Svidro** [comment]
I think you want something like the top script onhttps://github.com/qupath/qupath/wiki/Scripting-examples

You cycle through all cells, and then using measurements from each cell, you add another measurement.  I do not have good ISH images handy to test it out, but I hope the example is easy enough to modify.  One warning is to be very careful about the amount of whitespace in the measurement names, as it can vary by a space or two between different parts of extended measurement names.

**Comment by mnolan1989** [comment]
Thanks. I've used this and come up with a measurement that is an expression of the Cell DAB OD mean:Nucleus DAB OD mean. This is an alright proxy, but doesn't account for variances in the OD of the dots themselves. 

Ideally I would have a measurement of the absolute number of dots within the nucleus vs cytoplasm for every cell I click on. However I can't work out how to write a script for this as these measurements aren't visible when a cell is selected, only when a dot is selected. How do I add these measurements (number of dots in the nucleus and number of dots in the cytoplasm) so that I can combine them using the script you mentioned?

Apologies again if this is a simple question. Thanks for your help

**Comment by Svidro** [comment]
Ah, no, you are absolutely correct.   I normally would handle this by exporting the detections file and processing it in R.  But if you want to visualize the ratio (with view measurements etc) you will need to update the cell measurements once you have determined the nuclear/cytoplasmic localization.

Roughly speaking, you need to either cycle through all cells, and sum/average their stats for that cell, or cycle through all subcellular detections, and update the parent cell as each one is processed.  I only know how to do the latter.

You already have the loop for all cells from the previous example, and a loop for all clusters from the first.  I will start with the loop for all clusters since I have some idea how that would work.  Note that this does not summarize stain OD or actual spot area, just estimated spot count.  It also only works if the second stain is labeled as DAB!  After that, you should have the two values you need to get your ratio.

```
import qupath.lib.scripting.QP
def NuclearSum = "Nuclear Spot Sum"
def CytoSum = "Cytoplasmic Spot Sum"

//Probably not necessary when using putMeasurement, but I liked to have this loop for completeness, plus it will reset all values to zero when rerunning the script.
for (def cell : QP.getDetectionObjects()) {
    def ml = cell.getMeasurementList()
    ml.putMeasurement(NuclearSum, 0)
    ml.putMeasurement(CytoSum, 0)
    ml.closeList()
}
def clusters = getObjects({p -> p.class == qupath.imagej.detect.cells.SubcellularDetection.SubcellularObject.class})

// Loop through clusters
for (c in clusters) {
    // Each subcellular detection can have one parent
    def cell = c.getParent()

    def ml = cell.getMeasurementList()
    
    //Important note:  This value (Num Spots) will be heavily influenced by the Estimated Spot Size when running the
    //subcellular detection command.  you may instead want to use the Area measurement which you can find
    //by clicking on a subcellular detection
    double thisCluster = c.getMeasurementList().getMeasurementValue("Num spots")

    //find out if this subcellular detection is nuclear or cytoplasmic, then add the area of that detection to the cell measurement
    def location = c.getPathClass().getName()

    if (["Nuclear"].contains(location)) {
    double nuclear = cell.getMeasurementList().getMeasurementValue(NuclearSum);
    nuclear = nuclear+thisCluster
    ml.putMeasurement(NuclearSum, nuclear)
    ml.closeList()
    }
    if (["Cytoplasmic"].contains(location)) {
    double cyto = cell.getMeasurementList().getMeasurementValue(CytoSum);
    cyto = cyto+thisCluster
    ml.putMeasurement(CytoSum, cyto)
    ml.closeList()
    }
    
}   
println("Done summarizing")




```
