### ISSUE TITLE
QuPath 0.4.1 on macOS: .tif files are black

### ISSUE THREAD

**Issue by grossleo** [qupath/qupath#1200]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [ ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ ] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS, Ubuntu...]
 - QuPath Version: [e.g. 0.2.2]

**Additional context**

**Comment by petebankhead** [comment]
There's no information here that I can work with. It's certainly not the case that .tif files generally are black on macOS (I've just opened two and they are fine).

Please use the forum at https://forum.image.sc/tag/qupath to discuss any specific problems you might have, and provide an example image that illustrates the issue.
