### ISSUE TITLE
3D spheroid analysis

### ISSUE THREAD

**Issue by IevaPal** [qupath/qupath#121]
Hi,

I'm trying to find a way to analyse the spheroids I have cultured and I feel like there must be a way to make QuPath tell these larger shapes with multiple cells inside apart from the scaffold they're in. Ideally, I would like it to detect amount of spheroids within a region and their size. Is this possible in any way? I've attached an example image of the spheroids for reference.

Thanks,

Ieva

![he_ch_17d_2](https://user-images.githubusercontent.com/34248337/33568732-c0439fc2-d927-11e7-8fc0-361db860aa8e.jpg)

**Comment by DavidMHaumann** [comment]
Hi Ieva, 
That shall defenitely be possible. You can generate regions of interest for each spheroid. That works via superpixel approach: Analyse > Region identification > Tiles & Superpixels > SLIC or DoG

You generate superpixels: 
![grafik](https://user-images.githubusercontent.com/16352785/33573958-c45aa460-d937-11e7-8d4f-1d13d89a5e61.png)

Change the image type in the image tab into "Brightfield H&E". 
Then feed it with statistics. 
Analyse > Calculate features > add intensity features.

Use these checkboxes: 
![grafik](https://user-images.githubusercontent.com/16352785/33574028-0b866eb4-d938-11e7-820d-3629d339a516.png)

and run it for detections. 

Next step is to train a classifier to detect the spheroids: First create a class "Spheroid" in the annotation tab by rightclick onto the list of classes: 
![grafik](https://user-images.githubusercontent.com/16352785/33574089-3396762e-d938-11e7-8665-d2eef84ae60b.png)


Then use the polygon and draw a circle around spheroids can set class of the polygon to "Spheproid"
and paint polygon in the whitespace and set class to other or whitespace: 
![grafik](https://user-images.githubusercontent.com/16352785/33574170-7e522f3c-d938-11e7-9a84-d75add61bf04.png)


Now go to menue "Classify" > "create detection classifier". 
Press advanced options and then "use all". Then build and apply. 
![grafik](https://user-images.githubusercontent.com/16352785/33574202-9c0ac8a4-d938-11e7-822b-a9706b8cf600.png)


The first result looks like that: 
![grafik](https://user-images.githubusercontent.com/16352785/33574227-a943d70e-d938-11e7-84a0-f4aef4baa9b1.png)


after enough training you can convert the spheroid reagions into real regions of interest and afterwards for example count cells: 

That is done by: 
![grafik](https://user-images.githubusercontent.com/16352785/33574256-c49afc1c-d938-11e7-8dfc-f03f1967c133.png)


choose only spheroids to be converted to roi: 
![grafik](https://user-images.githubusercontent.com/16352785/33574300-e2ee9d72-d938-11e7-9130-871b14ac3036.png)

The image looks like that now: 
![grafik](https://user-images.githubusercontent.com/16352785/33574325-f333fc72-d938-11e7-961f-0bafbeda1595.png)


the brown areas are the speroid ROIs. 
You can now rund celldetection for example. 
Or just count spheroids and measure their size by "Measure" "Show Annotation Measurements". 

Best
David

**Comment by Svidro** [comment]
That looks like the sort of thing that Simple Tissue Detection might work for with the correct settings.  Something around 220 threshold maybe, with a medium requested pixel size and minimum area (keep setting these lower until you are picking up all of what you want).  Also you will probably want to uncheck Single annotation.  The requested pixel size is probably the most important measurement to play around with if you use this method.

David beat me to it!  His method is also probably better in the long run, though this gives another, slightly simpler method.  I would also be careful about using too many features in your classifier, or at least make sure your training set is significantly larger than the number of features you use!

**Comment by DavidMHaumann** [comment]
ah right, Svidro! simple tissue detection is the much faster and more convenient way to do it!  I was thinking to complicated ^-^

**Comment by Svidro** [comment]
Oh, definitely not too complicated, as we don't really know what the rest of the slides look like.  Your method is far more robust, and if there are other dark blotches or other unwanted clumps of cell pellets/detritus on the images, a classifier would be able to pick that up, while simple tissue detection will simply look for "anything" that is "dark." 

It does go to show how QuPath has multiple ways to accomplish the same task though, depending on your needs!

**Comment by IevaPal** [comment]
Hi,

Thank you both very much for your comments, I've gone for the more robust longer method. That seems to work better for these samples as I can adjust the selection better. It works really well, thank you for the quick responses!

Ieva
