### ISSUE TITLE
How to open a *.qpdata ?

### ISSUE THREAD

**Issue by nirmaljith** [qupath/qupath#122]
I have some annotations done using qupath, saved in *.qpdata format. I wanted to use those annotations in my python code, how to read the qpdata using python

**Comment by erexhepa** [comment]
I was also wondering how to do this.

**Comment by petebankhead** [comment]
The `.qpdata` files use Java serialization, so it probably isn't very feasible to read them in Python unless some kind of bridge to Java is involved.

The easiest approach is likely to be to export the annotations in a Python-friendly form using a QuPath script (written in Groovy).  Then you can choose your representation, e.g. JSON, binary images, something else.

There are relevant pieces of Groovy code on GitHub or Google Groups already to export annotations, but if you would like to describe in more detail what exactly you want to be able to bring into Python then I can give some more detailed suggestions.

**Comment by nirmaljith** [comment]
@petebankhead I am using Qupath for annotating whole slide images. Later these annotations are need to be used in my python code, to crop the region from WSI for training the ML algorithm.

**Comment by petebankhead** [comment]
From that description, it sounds like you need bounding boxes.  I assume you'd also need the classification for each annotation.

The following script will print this information in the format `classification, x, y, width, height` using the pixel coordinates in the full resolution image, for all annotations currently shown in QuPath:
```groovy
def result = ''
for (annotation in getAnnotationObjects()) {
    def pathClass = annotation.getPathClass()
    def roi = annotation.getROI()
    result += String.format('%s, %.2f, %.2f, %.2f, %.2f',
        pathClass, roi.getBoundsX(), roi.getBoundsY(), roi.getBoundsWidth(), roi.getBoundsHeight())
    result += System.lineSeparator()
}
print result
```

If you want to out them to a file, you can just use:
```groovy
def file = new File('/path/to/file.csv')
file.text = result
```

For other kinds of annotation export see #95, or [here](https://groups.google.com/d/msg/qupath-users/EOdNLyP7ixc/WmCBzy7uDwAJ) on Google Groups.

**Comment by nirmaljith** [comment]
@petebankhead Thank you very much for your prompt response. I will come back after trying these things you mentioned above.

**Comment by erexhepa** [comment]
@petebankhead thanks for the explications above. I'm scripting on groovy to convert Aperio XMLs into QuPath and it is working nicely. 

I was going through the WIKI and saw you mentioned interaction with CellProfiler. Is it something you have tried, calling CellProfiler from QuPath ?  I guess it has to be done via Javabridge. To my experience on the other direction, calling ImageJ from CellProfiler there were some issues with javabridge.

**Comment by petebankhead** [comment]
@erexhepa good that the conversion is working!

Regarding CellProfiler, is interaction between it and QuPath something you'd need/want?  If so, it would be good to add a new feature request here to draw attention to it, and maybe try to spark some discussion on how it should look.

I personally never managed to get Javabridge set up successfully, and I didn't have any sufficiently important CellProfiler pipelines to work further on the integration myself.  But it should be manageable in a few ways.  The easiest might be to write out temporary image files (with Groovy) and then launch CellProfiler from the command line, before reading back in the results.  However, early next year I plan to work more on streamlining the interaction between QuPath and Python, in which case the use of [CellProfiler as a Python package](https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package) could be helpful.

**Comment by erexhepa** [comment]
What is really interesting with the interaction with Cellprofiler is first we could use already developed and validated pipelines without starting from scratch. We have delopped a few extra CP python modules to handle specific analytical problems. The new version of CP is entirely python based. They do not support ImageJ anymore (no need to deal with javabridge which was a headache for us for while) and very attractive to deploy on a cluster environment. But what you suggest is a good idea, i.e. add it as a new feature request and see how it goes from there.

But to my opinion the really interesting aspect with CP and the underlying python+addition libraries (so far) is the computational one, i.e. memory consumption and parallelisation. It would be more efficient to handle a very granular analysis (down to cell/organelle level) in python. We are running with up to 1*10^6 #objects per slide and you quickly go up to 12GB of RAM consumption for a single process. The tiling of the slide before analysis is something I'm exploring with QuPath.

The streamlining of QuPath and python is an excellent idea. It would allow interaction with CellProfiler modules and other python packages. 

Great work. It's being very helpful to us. The interface is great and the other technical problems you can always find a solutions in one way or another even if it is not optimal.

**Comment by petebankhead** [comment]
That sounds like a very convincing argument, I've added the issue at #123
