### ISSUE TITLE
'Synchronize viewers' ignores z and t positions

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1220]
## Bug report

**Describe the bug**
It's possible to synchronize multiple viewers, so that panning and zooming are related.

Unfortunately, for z-stacks or time-series the z-slice and timepoint aren't synchronized.

See https://forum.image.sc/t/qupath-synchronize-viewers-z-t-lut-and-b-c/76462

**Expected behavior**
z-position and timepoint are considered when synchronizing viewers.

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version: v0.4.2 (and probably all earlier versions)

**Additional context**
One complexity: should the synchronization handle *offsets* in z and t, or use absolute values?

By this I mean that panning works with 'delta x' and 'delta y', rather than centering the viewers around the same x and y coordinate. This means that if the images don't fully align, some extra steps can be applied to roughly align the viewports before synchronization starts. And all the movement is relative to the viewport when synchronization is turned on.

In z and t that could be more difficult, especially since there tend to be few z-slices and timepoints... and it's not possible to navigate beyond these.

**Comment by MichaelSNelson** [comment]
Hard to say given the variety of ways in which this could be used. I would almost want a relative change in Z (top is top slice for all, bottom is bottom slice for all, everything else interpolates to nearest by fraction of total), though I could see offset also being important in some cases. Z can be even worse if depth correction is not applied and the distance between Z slices changes as you scan through the object. There will not be a way to fix that easily in post processing, though.

T should probably be offset.
Either one would probably want to handle the odd case where one viewer has a reference single frame image (no Z or T) and the user wants to cycle through the rest. Ick.
