### ISSUE TITLE
Fluorescent channels missing in .mrxs images

### ISSUE THREAD

**Issue by Mcrestani** [qupath/qupath#1223]
Hello, 

I am having trouble in visualizing more than 3 channels in .mrxs images. As I set the image type "fluorescence" the brightness and contrast panels visualizes by default only the default channels as follows

<img width="336" alt="Screen Shot 2023-02-01 at 17 21 16" src="https://user-images.githubusercontent.com/93928748/216101042-d205c4a2-a6dd-432c-aab7-da094c444cab.png">

given that I have 4 channels, I would expect a magenta channels as well. The .mrxs file has been imported along with its dedicated data folder.

Many thanks!

Regards

Michele

**Comment by petebankhead** [comment]
Hi @Mcrestani I'm afraid this isn't something that can be fixed in QuPath - I don't know of any open source reader that supports non-RGB .mrxs images.

There's some more info and some links in the docs at https://qupath.readthedocs.io/en/0.4/docs/intro/formats.html#mrxs-3d-histech
