### ISSUE TITLE
macOS Ventura 13.2 -> Message QuPath is damaged

### ISSUE THREAD

**Issue by Peter-Erik** [qupath/qupath#1228]
After installation you get an message "Qupath" is damaged and can't be opened.

![Screenshot 2023-02-07 at 11 56 23](https://user-images.githubusercontent.com/10047748/217226474-76131924-91e9-47a4-8478-0b8351d51e2f.png)

Fix for now is control-click on QuPath Application and select Open

**Comment by petebankhead** [comment]
This isn't really a bug, and is already covered in the documentation: https://qupath.readthedocs.io/en/0.4/docs/intro/installation.html#macos
