### ISSUE TITLE
Integrating QuPath & CellProfiler

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#123]
This issue represents a feature request to somehow get QuPath and CellProfiler to talk to one another (arising from #122).

One idea for the potential workflow is this:
* Open an image or project in QuPath
* Chop up either entire images or annotated regions into CellProfiler-friendly image tiles
* Launch CellProfiler analysis from a command line, passing a CP pipeline and the image tiles
* Bring the results back into QuPath for visualization (?)

The first parts should be possible to handle on the QuPath side with the addition of a (relatively) straightforward Groovy script*.  The last bit is trickier.  I am not sure if it is needed in general or, if it is, what kind of data needs to be brought back... and how standardized would it be?

Ideas and comments would be welcome.

_*- To begin with.  The script could become a built-in extension later, to achieve better user-friendliness._

**Comment by erexhepa** [comment]
Thanks for opening the feature request. Your suggestion it is a good starting point to see how cell profiler and QuPath could be integrated together and see for potential computational benefits of doing so. I will post some scripts I'm using with my local installation. I will be glad to help with anyway I can do so.

**Comment by Svidro** [comment]
Putting this here for future reference.

"Note: CellProfiler has limited capability with handling large, high-resolution images. We recommend using a field of view limited to a maximum number of two gigapixels in (x,y) to count cells and punctate dots present within cell boundaries. To perform whole slide image (WSI) analysis using your CellProfiler pipeline, Glencoe sells a plugin to allow you to interface CellProfiler with the open source platform QuPath. The plugin works through the OMERO + platform. Information on this plugin can be found by contacting Glencoe through their webpage: https://www.glencoesoftware.com/contact/. Other open source options to perform whole slide image (WSI) analysis include QuPath, Orbit, and SlideToolkit."
https://acdbio.com › files_force › TechNote_CellProfiler_20190920

**Comment by petebankhead** [comment]
Closing this partly due to lack of activity, but also because the `TileExporter` does at least some of the task: https://qupath.readthedocs.io/en/latest/docs/advanced/exporting_annotations.html

There remains a need for a good importer, but this isn't really CellProfiler-specific. There are a couple of threads on the forum about this, where it could be further discussed -- most recently https://forum.image.sc/t/will-tileexporter-have-a-tileimporter-sibling-in-qupath-0-2-0/38065
