### ISSUE TITLE
[macOS] version numbers damaged

### ISSUE THREAD

**Issue by core-code** [qupath/qupath#1250]
i've downloaded version 0.4.3 but when selecting it in the Finder it claims to be version 1 (in Quick Look, Column View and Get Info):
<img width="253" alt="Screenshot 2023-03-04 at 21 43 05" src="https://user-images.githubusercontent.com/1261954/222927870-ef6175d8-5665-46f3-b300-b60ad2eedd7a.png">
<img width="243" alt="Screenshot 2023-03-04 at 21 43 10" src="https://user-images.githubusercontent.com/1261954/222927871-494add8b-cbda-45ca-aafd-2f6b31fe19ae.png">

the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are damaged

**Comment by petebankhead** [comment]
Yes, at the time the build scripts were written it seemed to be impossible to have a version number starting with 0.x on macOS - at least when building using `jpackage`.

Attempting to do this would result in a "first number in a CFBundleVersion cannot be zero or negative" exception, as described at https://forum.image.sc/t/error-building-qupath-with-tensorflow-first-number-in-a-cfbundleversion-cannot-be-zero-or-negative/48713

The build script explicitly sets the wrong version number in an attempt to get builds working at all, see https://github.com/qupath/qupath/blob/v0.4.3/qupath-app/build.gradle#L40

I'll check if the situation has changed with more recent `jpackage` releases. If not, I'm afraid we're probably stuck with it until there's eventually a QuPath 1.x release, unless someone can come up with a solution that doesn't overly complicate the build/release process.

**Comment by core-code** [comment]
thanks, good to see this is on your radar :)

**Comment by petebankhead** [comment]
Yes - as a Mac user, it's annoys me too :)

Sadly, it looks like the version number is still enforced by `jpackage`. The relevant part is at:

* https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/macosx/classes/jdk/jpackage/internal/CFBundleVersion.java

Attempting to build results in the message:

```
Bundler Mac Application Image skipped because of a configuration problem: The first number in an app-version cannot be zero or negative. 
Advice to fix: Set a compatible 'app-version' value. Valid versions are one to three integers separated by dots.
```

**Comment by core-code** [comment]
ouch - not sure why they are doing this way but it may be quite hopeless to get this resolved upstream.

also the just-3-digit restriction has never existed in reality, even Apple's own apps often use more than 3 digits.

not sure how this build system works but unless it already spews out the signed binary, the version numbers could just be added after the build step, e.g.

`/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ...`

**Comment by petebankhead** [comment]
Thanks @core-code I've attempted a fix at https://github.com/qupath/qupath/pull/1344 by splitting the build into two parts and using `PlistBuddy` in between.

It seems to be working on my computer, so hopefully this will be working in the next release.

**Comment by core-code** [comment]
thanks!

**Comment by petebankhead** [comment]
Alas, in the end I had to revert these changes as they ended up causing much bigger problems, which only emerged when preparing the next release candidate.

More details at https://github.com/qupath/qupath/pull/1379

**Comment by core-code** [comment]
ouch :(

changes to the Info.plist must done before code-signature, not after

is there a build with the version numbers i could test to look into this?

**Comment by petebankhead** [comment]
We don't have a code signature step... release candidate must be available within the next couple of hours, ahead of a workshop next week, so won't have time to make any more changes ahead of that.

The easiest way to explore would be to build for source with gradle: https://qupath.readthedocs.io/en/0.4/docs/reference/building.html

The PR should point towards the parts that needed to be reverted to get things working.
