### ISSUE TITLE
Images exported as OME TIFF may have incorrect color format set

### ISSUE THREAD

**Issue by frmdstryr** [qupath/qupath#1254]
## Before we begin...

Before submitting your bug report, please check the following:

* [ ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ ] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**

When exporting the following image ( https://matthews.sites.wfu.edu/misc/graphics/formats/uncompr.tif) using the OME Tiff option the resulting file has the wrong color format causing it to be unreadable by other applications and viewers. 

I'm not sure if it is all images but it happened with every one I tried.

**To Reproduce**
1. Open an image (eg https://matthews.sites.wfu.edu/misc/graphics/formats/uncompr.tif)
2. Go to File Export -> OME Tiff and use default options (JPEG (lossy) downsample, 4.0, 256) 
3. Attempt to open exported file in another image viewer (eg Kirta)

**Expected behavior**

The image should be readable by other viewers that support tifs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - QuPath Version: 0.4.3

**Additional context**

As discussed here https://github.com/libvips/libvips/issues/3397 changing the PhotometricInterpretation  to YCrCb causes images to be displayed properly.

**Comment by petebankhead** [comment]
Hi, I can't replicate the problem on my Mac - at least, the exported image displays fine (in Preview, PowerPoint, PixelMator...).

Also, the thumbnail generated with `vipsthumbnail` looks ok to me.

Is there any chance you can check if it's Ubuntu-specific?

Also, can you try converting with Bio-Formats alone? The easiest way is likely with `bfconvert`: https://bio-formats.readthedocs.io/en/stable/users/comlinetools/conversion.html

It would be good to confirm if this is a bug that can be addressed in QuPath, or it requires any change in Bio-Formats. For example, this might be relevant:
* https://github.com/ome/bioformats/issues/3856

**Comment by frmdstryr** [comment]
Unfortunately I only have a linux system... Does the ome.tif from the attached tar.gz in https://github.com/libvips/libvips/issues/3397 look fine in those viewers (exported with QuPath)? 

Perhaps the image is exported differently on linux or maybe those viewers are able to detect and correct it.

**Comment by petebankhead** [comment]
`lzw.ome.tif` just appears all black in the other viewers (but looks ok in QuPath and Fiji).

**Comment by frmdstryr** [comment]
Oh, sorry. Yes it appears to be the same issue as in that thread so it is probably something with bioformats and not QuPath.
