### ISSUE TITLE
Get classify celltype  OD mean

### ISSUE THREAD

**Issue by BioCheng** [qupath/qupath#1257]
Thanks for developing this software!

This software is very practical, but I have some questions when using it to analyze immunohistochemical images. I
don't know how to  calculate the overall OD sum and OD mean of a certain type of cell after I classify it. At present, I can only get the overall number and proportion of positive cells, as well as the OD sum and OD mean of individual cells.

 How can I get the classify celltype information such as 
>>>Stromal: OD mean
>>>Tumor: OD mean

Just like this kind of information

![image](https://user-images.githubusercontent.com/122006615/230115042-5bf95c97-40c6-4380-9639-863251a62043.png)

which method can I use to calculate them. Did I need to use image J?

**Comment by MichaelSNelson** [comment]
Hi @BioCheng, as you probably saw from the label, please use the image.sc forum with the QuPath tag for questions! Generally, though, you would script it. There are quite a few examples of exactly this sort of thing on the forum.

**Comment by BioCheng** [comment]
thanks a lot for your help! @MichaelSNelson

**Comment by petebankhead** [comment]
Thanks, I'll close this as the discussion is now at https://forum.image.sc/t/calculate-the-od-value-in-classified-cell-types/79543

**Comment by BioCheng** [comment]
@petebankhead Okay,have a good day!Thanks for developing the software.
