### ISSUE TITLE
Workflow for counting cells with multiple fluorophores and puncta

### ISSUE THREAD

**Issue by achamess** [qupath/qupath#126]
Hi, 
QuPath looks like it could be an extremely useful tool for a standard analysis I do.

Basically, I want to:
- Identify cells in spinal cord tissue sections, either automatically or by manually.
    - I'm willing to draw ROIs by hand or some combination of auto-detect plus clean-up by hand. That's not horrible. But counting and finding overlaps, that is the part that I need to automate. 
- Identify the cellular staining: Usually, cells have (DAPI) and then one or more IHC signals (antibody) or ISH signal (RNAscope, which usually show as puncta)
- Count the overlapping events: I want to see which cells have combinations of fluorescent signals: red alone, red+green, green alone, etc. Sometimes this will be binary (yes/no) but it'd be nice to make more bins like absent, low, medium and high. 
- Optional for ISH: Count puncta inside of cells.

This is such a core analysis for a lot of neuroscience. I've tried to use Fiji and I still don't know how to do this in a straight forward way. I've resorted to just using Photoshop and manually counting, but that's a huge pain.

CellProfiler looks like it might have some cool features, and I presented the problem there too:
http://forum.cellprofiler.org/t/rnascope-in-spinal-cord-neurons-quantitation-of-overlap-between-different-in-situ-probes/5355/3

But could some combination of QuPath + Cell Profiler (or QuPath alone) get the job done? I feel like it can. 

Here is an example image:
![composite](https://user-images.githubusercontent.com/7445362/33910649-7b71bcc6-df5d-11e7-92e8-468649392c9d.jpg)

PS @petebankhead thank you so much for all your efforts. I've been enjoying the book you made on fluorescent image analysis as well.

**Comment by Svidro** [comment]
Generating the tissue annotation can be a little tricky, for fluorescent images I started sending a downsampled image to ImageJ and using blur+thresholding tools there to generate the initial annotation.  It worked well as long as the staining/nuclear density was great enough.

For the rest, QuPath should be easy as long as you have a multichannel image.  What format are you using?
Depending on the sensitivity you need, QuPath automatically includes your red and green channel mean intensities, so as long as you expand the cytoplasm out far enough, you will get a measure of how much stain is within that space.

For the kind of staining I see in your image, I would also recommend the Analyze->Cell analysis->Subcellular detection command, as it can generate a much more exact value for the "amount of stain above a threshold" within a given cell, without being diluted by empty space.  This command will only work, though, if your image has Pixel width and height included in the metadata.

Once you have the data you need on a cell to cell basis, it's as simple as creating a classifier, either with a training set and the classifier command, or creating your own, exact value, classifier.

The slower way of doing this is creating your own classifier through the menu system, which Pete shows:
https://github.com/qupath/qupath/wiki/Object-classifications
about half way down the page.  Using that setup, you can generate positive cells for each channel and a set of dual positive cells.

My preferred method is using a script to classify.  The following script is a toned down version of one Pete has posted elsewhere, but it generally gets the job done.  Plus you can expand it out as much as you want using the code that is currently there.  Want to classify based on two features? Add a "def myNewFeature" and a new "double val2" line inside the for loop.  You can make the if statments as convoluted as you have the time or desire for, and it is much easier than changing things through the menu classification system.
```

import qupath.lib.objects.classes.PathClass
import qupath.lib.objects.classes.PathClassFactory

def Positive = PathClassFactory.getPathClass("Positive")
def Negative = PathClassFactory.getPathClass("Negative")

//I honestly forget the exact text for the given fluorescence features
//but feature would be one of those
def feature = "Channel 2: Mean intensity"
def threshold = 0.1
def threshold2 = 1.5

// Loop through all detections *** Change this to getCellObjects() or getTileObjects() if you have a mix of both and only want to classify one type
resetDetectionClassifications()
for (def pathObject : getDetectionObjects()) {

       // Get the measurement value(s)
        double val = pathObject.getMeasurementList().getMeasurementValue(feature)

        // Set positive or negative class
            if (val < threshold || val > threshold2){
            pathObject.setPathClass(Positive)
            }else pathObject.setPathClass(Negative)
}
```
Hopefully that gets you started, let me know if you need anything else!
