### ISSUE TITLE
Project isn't appearing in folder, won't open in QuPath

### ISSUE THREAD

**Issue by dandrews-case** [qupath/qupath#1268]
I am unable to open a project file that was last opened two days ago (5/23/2023). The file is not visible in the folder it has been saved to, but the backup is still there. I tried opening it via recent programs but I get an error message (see below). I also tried copying the backup and changing the name to make it a regular project file, but it only has the blank LIF files and not the annotations and classifications that I have applied for analysis. Is there any way I would be able to retrieve the original file? I haven't had any issues with it until now and redoing the analysis would be a huge inconvenience.
![Screenshot (1)](https://github.com/qupath/qupath/assets/134634667/d6facfc3-79c7-4d43-9eff-f331d11b4631)

Thank you in advance.

**Comment by petebankhead** [comment]
There should be a 'data' folder in the project folder that contains the annotations - they aren't in the `project.qpproj` file anyway.

Is the data folder there, and does it contain `data.qpdata` files inside subfolders?

If you open an image and can find an associated `data.qpdata` file, then dragging the `data.qpdata` file should allow you to import the objects.

**Comment by dandrews-case** [comment]
> There should be a 'data' folder in the project folder that contains the annotations - they aren't in the `project.qpproj` file anyway.
> 
> Is the data folder there, and does it contain `data.qpdata` files inside subfolders?
> 
> If you open an image and can find an associated `data.qpdata` file, then dragging the `data.qpdata` file should allow you to import the objects.

For some reason, that worked for all of the images except one. That's better than doing it all over again for the whole project. 

Again, thank you for your help.
