### ISSUE TITLE
Export arbitrarily large region to JPEG via Export Image Region

### ISSUE THREAD

**Issue by nathanin** [qupath/qupath#127]
I'm using QuPath's basic functions to replace Aperio ScanScope on Ubuntu. My use case is viewing and exporting regions from .svs format slides. Is there a way to export, using `Export Image Region`, an arbitrarily large region? Currently the size is capped ~10MB. 

I get the following message in console:
```
08:54:35.252 [JavaFX Application Thread] [ERROR] q.lib.gui.helpers.DisplayHelpers - Export image region: Requested export region too large - try selecting a smaller region, or applying a higher downsample factor
```

**Comment by petebankhead** [comment]
So long as 'arbitrarily large' is still small enough to work as a single image (not a pyramidal whole slide image), then it should certainly be possible.  Image pyramids can't be written with QuPath currently.

One way to get a larger image may be via [Send region to ImageJ](https://github.com/qupath/qupath/wiki/Working-with-ImageJ#sending-image-regions-to-imagej) - from memory I think there's still a size limitation, but it should be bigger.

Otherwise, it is necessary to run a script.  The closest matching script I can think of is [this one](https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d).  By default, it will export the entire image at a very low resolution because of these lines
```groovy
// Aim for an output resolution of approx 20 µm/pixel
double requestedPixelSize = 20
...
// Calculate downsample factor depending on the requested pixel size
double downsample = requestedPixelSize / server.getAveragedPixelSizeMicrons()
def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, 0, 0, server.getWidth(), server.getHeight())
```

You can switch it to export only the region corresponding to the selected object, at full resolution, as follows:
```groovy
// Calculate downsample factor depending on the requested pixel size
double downsample = 1.0
def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, getSelectedROI())
```

Let me know if that doesn't do what you need, and hopefully some other script change could help.  Personally, I'd use the ImageJ method for exporting isolated regions occasionally, and a script if I wanted to export lots of regions in a single batch.

> Note: I've tagged this as *enhancement* because I think it would make sense to increase the export size limit through the user interface to make this easier.  I had forgotten the existing limit was so small...

**Comment by petebankhead** [comment]
Actually #62 could be useful.
Also https://groups.google.com/d/msg/qupath-users/pBEmidv0Wow/QxFMo4-RAgAJ

**Comment by 80Ultraman** [comment]
> So long as 'arbitrarily large' is still small enough to work as a single image (not a pyramidal whole slide image), then it should certainly be possible. Image pyramids can't be written with QuPath currently.
> 
> One way to get a larger image may be via [Send region to ImageJ](https://github.com/qupath/qupath/wiki/Working-with-ImageJ#sending-image-regions-to-imagej) - from memory I think there's still a size limitation, but it should be bigger.
> 
> Otherwise, it is necessary to run a script. The closest matching script I can think of is [this one](https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d). By default, it will export the entire image at a very low resolution because of these lines
> 
> ```groovy
> // Aim for an output resolution of approx 20 µm/pixel
> double requestedPixelSize = 20
> ...
> // Calculate downsample factor depending on the requested pixel size
> double downsample = requestedPixelSize / server.getAveragedPixelSizeMicrons()
> def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, 0, 0, server.getWidth(), server.getHeight())
> ```
> 
> You can switch it to export only the region corresponding to the selected object, at full resolution, as follows:
> 
> ```groovy
> // Calculate downsample factor depending on the requested pixel size
> double downsample = 1.0
> def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, getSelectedROI())
> ```
> 
> Let me know if that doesn't do what you need, and hopefully some other script change could help. Personally, I'd use the ImageJ method for exporting isolated regions occasionally, and a script if I wanted to export lots of regions in a single batch.
> 
> > Note: I've tagged this as _enhancement_ because I think it would make sense to increase the export size limit through the user interface to make this easier.  I had forgotten the existing limit was so small...

I have almost the same need as @nathan. I have some .tiff WSI want to convert them to ndarray. I downloaded the 0.1.2 version( 0.2.3 wouldn't work with the script above) and run the script. The script "QuPath_export_images.groovy" gave me downsampled image as it should. I followed your answer here adjust the script and it gave me sort of a blank image with some lines in it(I was doing regular image before just starting to deal with bioimage recently). Can you give me some instructions about how to export the whole image as jpg, png, or regular tif, so I can convert them to ndarray.

Thank you in advance!!

**Comment by petebankhead** [comment]
@80Ultraman v0.1.2 is more than 4 years old now and a lot has changed!
There are relevant docs for v0.2.3 at https://qupath.readthedocs.io/en/0.2/docs/advanced/exporting_images.html 
And an active community for discussions at http://image.sc/tag/qupath
There's also [paquo](https://github.com/bayer-science-for-a-better-life/paquo) for connecting QuPath to Python, and https://pypi.org/project/napari-lazy-openslide/ for reading WSI.
