### ISSUE TITLE
MacOS Ventura 

### ISSUE THREAD

**Issue by ReganFulton** [qupath/qupath#1281]
I recently updated to MacOS 13.5 (Ventura), on my desktop mini (M1 processor).
Now my QuPath program doesn't work at all.
I get a message saying "This file is corrupted and should be moved to the trash"
I've tried re-downloading QuPath, as well as re-downloading the OS to no avail.
Any advice?

**Comment by ReganFulton** [comment]
Thanks Pete,

As you can see, I'm not a sophisticated github user, but I love QuPath!

I'll try again.

Regan


Regan Fulton, M.D., Ph.D.
CEO and Co-Founder
Array Science, LLC
475 Gate 5 Road, #100
Sausalito, CA 94965
(415) 577-7360



www.arrayscience.com

**Comment by petebankhead** [comment]
No problem, glad you like it! I know other open-source projects have the same macOS complications.
