### ISSUE TITLE
Add a region on an already created Training image 

### ISSUE THREAD

**Issue by RodiTabudi** [qupath/qupath#1285]
i hope someone help me with this. I already made a training image in QuPath with 29 regions. I made many annotations on that image. I was wondering is there a way to add 2 or 3 regions to my already created Training image without the need to make a new traning image and lose all of my annotations. 
I would be greatfull if anyone answerd.

**Comment by petebankhead** [comment]
I don't think it's possible to do what you want, but there could be alternatives.

This isn't the best place to discuss it, since it's only for bug reports and development - please post your question at https://forum.image.sc/tag/qupath
