### ISSUE TITLE
Strange behaviour in color deconvolution

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#131]
Dear all, dear Pete, 

in the meanwhile it happened quite some times that the color deconvolution display in channel 2, 3 and 4 behaves stranges. I can not exactly say whan it starts and if it once started, the only chance to come back to nomality is to close the whole QuPath Software and restart. 
Even reset of image type and all color vectors does by a script does not help to repair the phenomen. 

It starts, when I read out the color vectors directly from a rectangle. 

Here an example: 
![grafik](https://user-images.githubusercontent.com/16352785/34652666-a8449302-f3e1-11e7-83b0-8a4255cd7612.png)

These are the color vectores that worked very well before I started to use the function "Set stain vector from ROI?"
![grafik](https://user-images.githubusercontent.com/16352785/34652670-c4ba3226-f3e1-11e7-8e4c-f4f2ad859c54.png)

Afterwards the channels look like that: 

![grafik](https://user-images.githubusercontent.com/16352785/34652674-d6bb919a-f3e1-11e7-88b5-ad94312ffa60.png)
for red
and for brown-yellowish: 
![grafik](https://user-images.githubusercontent.com/16352785/34652677-e22da1bc-f3e1-11e7-8cdf-5f5f7d30f151.png)
and for green: 
![grafik](https://user-images.githubusercontent.com/16352785/34652684-f75ddeee-f3e1-11e7-97a5-64b56b184c4c.png)

Normally the display can become better by manual adujstion in the "Brightness Contrast" Settings: 
![grafik](https://user-images.githubusercontent.com/16352785/34652696-0fa3d620-f3e2-11e7-8182-33f2998c4cb1.png)

But once the "bug" appeared, that is not possible anymore. 

Does somebody have an assumption what might cause this problem?

**Comment by DavidMHaumann** [comment]
I disovered that the redout of the absolute pixel vallues experiences a very unrealistic value far beyond the theoretically maximum of 255: 

![grafik](https://user-images.githubusercontent.com/16352785/34652724-629261ee-f3e2-11e7-8503-88f92f71fd82.png)


Probably the problem is connected with that?

**Comment by petebankhead** [comment]
I'm not able to reproduce it - could you generate a script (under the 'Workflow' tab) and send the relevant lines?  Just the `setColorDeconvolutionStains` and `setImageType` parts should matter.

Did I understand correctly that the bug only occurs after opening the Brightness/Contrast window?  It does generate and cache a histogram, and it will only regenerate that histogram when QuPath is restarted.  So I guess that it somehow creates an evil histogram and won't let go of it... but I'm not sure yet why that happens.

**Comment by petebankhead** [comment]
You could try running the script below to brutally reset the histograms:
```groovy
def display = getCurrentViewer().getImageDisplay()
display.cachedHistogramMaps.clear()
display.histogramMap.clear()
```
It might help you avoid a restart, but I'm not sure...

**Comment by DavidMHaumann** [comment]
Hi Pete, 
Thanks for the script. I will try it, as soon as it happens next time.  Actually i do not know how to reproduce it by plan. It just happens from time to time. So at the moment I do not have a vectorcombination, that caused the problem, since i restarted QuPath. 
I did not succeed in reproducing the problem yet. 

It is defenitely not connected to the opening of the brightness & Contrast menu. 
Only to the ""Set stain vector from ROI?" function. 

Your assumption about the histogramm sounds plausible. Could that also happen, if i dont open the brightness & Contrast menu?

**Comment by Svidro** [comment]
I have also experienced this when frequently playing around with the color channels.  I even managed to swap the behavior of Brightfield Other and Brightfield HDAB, such that you could click on the residual stain to edit it in Brightfield HDAB.  I'll try to reproduce this.  One thing that strikes me though is that I suspect you are in Brightfield Other since the color vectors do not seem to add up correctly for a locked in Residual?  Or if you are still in Brightfield HDAB, maybe you have reproduced the above behavior since the Residual stain seems to not have been autocalculated.

**Comment by Svidro** [comment]
Hmm, I haven't managed to duplicate the main problem, but my previous comment about being able to edit the Residual is reproducible by script.  All you need to do is run a setColorDeconvolutionStains with 3 vectors in it, and Brightfield (H-DAB) will start to behave like Brightfield Other.  It will allow you to set the Residual stain vector from an ROI, which normally is locked and autocalculated.

**Comment by petebankhead** [comment]
Closed due to inactivity (and maybe it was fixed...). Please reopen if the problem resurfaces, ideally with steps to reproduce if possible.
