### ISSUE TITLE
Detachable viewers (good or bad?)

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1317]
### Is your feature request related to a problem? Please describe.
QuPath was designed to have one main window. If there are to be multiple viewers, these are embedded in a grid.

The original thinking was that we couldn't handle too many images simultaneously, since they tend to be big.

But QuPath is now used for lots of different things, including with images of different sizes... and often with multiple monitors. The 'single window' could become very limiting. 

### Describe the solution you'd like
Not so much the 'solution I'd like' as the one I'm proposing: adding support for detaching viewers.

Here's a **very rough** example of it in action, hacked together with minimal code changes:

<img width="1188" alt="Detachable viewer demo" src="https://github.com/qupath/qupath/assets/4690904/933e5528-4bf9-461b-855d-04eeb6fe8ad2">

### Additional context
This isn't so much a feature request as an invitation for feedback.

My feeling is that it's worth exploring, but I'm not sure if it helps or just creates confusion.

My main questions are:
* Is this a feature anyone really wants?
* Is it likely to be more helpful or confusing for new users?
* If implemented, should it work by
   * Detaching one viewer (and leaving the rest of the 'viewer grid' intact), or
   * Breaking up the UI entirely, so that there is no longer a grid and instead we have separate windows (including for the toolbar and analysis pane, more like ImageJ)
* Is there a need to have the *same* image open in multiple viewers?
   * Note that this wouldn't permit having different objects or display modes (e.g. different kinds of overlays), but rather it would just allow different image regions to be visualized at the same time. That is already kind of possible with *View &rarr; Show mini viewer* - except the mini viewer doesn't support all the kinds of interaction that are possible with a full viewer.

**Comment by Rylern** [comment]
I think it can be helpful because this feature is already present in several software like ImageJ, and I don't think it will be confusing for new users as I guess it will just require to add a new button to implement this.

Is that a request that has already been mentioned on the Image.sc forum? If not, shouldn't we ask the opinions of the QuPath users there? I'm not using QuPath like a regular user so my opinion here may not reflect theirs.

**Comment by alanocallaghan** [comment]
> Is this a feature anyone really wants?

The answer to that is almost always "yes"; the better question is whether it is worthwhile to implement given the refactoring/maintenance burden it entails.

> Is it likely to be more helpful or confusing for new users?

It seems like the sort of thing that would be confusing if done accidentally, so we should try to make that difficult if possible, but as Leo says in imaging software it's common to have multiple images open.

> Detaching one viewer (and leaving the rest of the 'viewer grid' intact)

Does this mean that you'd have (eg) one button that toggles visible annotations on both images? If so, this seems restrictive, though I don't know if it would be annoyingly so.

> Breaking up the UI entirely, so that there is no longer a grid and instead we have separate windows (including for the toolbar and analysis pane, more like ImageJ)

It seems to me like at least some UI elements should be broken up across windows. For example I'd want to be able to view/edit the object hierarchy in each image separately (e.g. for training classifiers). If we wanted to emulate the other mode you described, then being able to hide UI elements would be a good start.

> Is there a need to have the same image open in multiple viewers? 

Probably a natural behaviour, as long as we lock the imageData when a viewer is interacting with it.

There's a related issue in here to improve support for this kind of behaviour in tiling window managers, but I suspect I'm the only person who cares about that right now

**Comment by alanocallaghan** [comment]
Final thought is, if we implement this, we need to consider what should be the advantage of having one QuPath instance with two viewers over having two QuPath instances open each with one viewer, and we should probably aim our design in that direction. Otherwise it could both be a lot of work and even end up with ambiguity in user experience (eg "if I press this button, which image is affected...? or both...?")

**Comment by petebankhead** [comment]
Thanks @Rylern and @alanocallaghan !

I've made a PR at https://github.com/qupath/qupath/pull/1318 in case anyone wants to try it out.
You can see the code changes are pretty small. You would detach a viewer by right-clicking on it.

It's just intended for exploration - I suspect there will be niggly issues.

> I think it can be helpful because this feature is already present in several software like ImageJ, and I don't think it will be confusing for new users as I guess it will just require to add a new button to implement this.

I think you're right, although in ImageJ there *is* no main window. In QuPath there is, so having a viewer separated from it feels a bit weirder to me - if nothing else is open, there's a big area of empty space.

> Is that a request that has already been mentioned on the Image.sc forum? If not, shouldn't we ask the opinions of the QuPath users there? 

Not that I remember - I thought here would be good to start the discussion, could move to the forum if it proves controversial / we need a vote :)

> > Detaching one viewer (and leaving the rest of the 'viewer grid' intact)
> 
> Does this mean that you'd have (eg) one button that toggles visible annotations on both images? If so, this seems restrictive, though I don't know if it would be annoyingly so.

This isn't exactly what I meant, but anyway: it's already the case. You can use *View &rarr; Multi-view... &rarr;* to create a grid of viewers, and the toggles apply across all of them. I agree it's sometimes restrictive, but my feeling is that it would cause more trouble if that didn't happen.

What I really meant though was that a single viewer could be extracted into its own window, but the main QuPath window would remain as it always was. That's the approach in the PR.

The alternative was that viewers are either all in grid mode or all in 'detached' mode (floating windows), but not a combination of both.

> Final thought is, if we implement this, we need to consider what should be the advantage of having one QuPath instance with two viewers over having two QuPath instances open each with one viewer, and we should probably aim our design in that direction. Otherwise it could both be a lot of work and even end up with ambiguity in user experience (eg "if I press this button, which image is affected...? or both...?")

We already have the ambiguity - it's 'resolved' by there being a red boundary around the 'active' window, and it's also the title in the title bar. But we might need to make this much more prominent, and I think the PR currently has some focussing surprises (I guess because bringing the main window into focus can grab it away from the detached viewer that we previously had active).

I guess the advantage of two QuPath instances is hinted at by your previous comment: that would free you from having synchronized display settings.

But it's pretty hard to get two instances launched on macOS - I can get them via the terminal, but double-clicking the app is stubbornly singleton.

The big *disadvantage* of multiple QuPath instances is that there are no measures taken to 'lock' projects, and stop things getting messed up by incompatible changes being made in different instances. But I guess that's another problem (and an important one, since people may use QuPath with a project on a server somewhere).

**Comment by alanocallaghan** [comment]
Easily docking/undocking windows and a more modular UI in general would probably be good here. Although personally I don't like most of the dockable UIs I've used, they're very popular so presumably if you get used to them, they're good

**Comment by petebankhead** [comment]
Yeah, I'm not generally a fan of very dockable UIs myself... and there's no native JavaFX support. Lots of docking makes me thing of complex IDEs, which I'd expect only a minority of QuPath users to feel comfortable with (I'm not sure if I'm even one of them, and I use complex IDEs all the time).

An entire UI overhaul is certainly a good idea, but much more long term - I'm thinking here about stuff we could do within the next couple of weeks that would meaningfully improve the UX.

Meanwhile, the PR shows me there are definite bugs with my proposed approach - at least when it comes to stuff like cell detection, when windows change focus before the processing is complete. The fact that is broken suggests the underlying code to run parallel tasks ought to be strengthened though, so I'm tempted to persist a bit longer with the PR - irrespective of whether we end up exposing the 'detachable viewer' part through the UI or not.

**Comment by petebankhead** [comment]
Ok, much revised and extended PR at https://github.com/qupath/qupath/pull/1318

Please do check out the explanation of the changes.

I *think* it's a substantial improvement to handling multiple viewers, and other aspects of the code should be healthier than they were before. But there's a good chance it could be improved - and potentially things are broken in ways I haven't yet spotted.

Unless something terrible emerges, I will merge the PR soon so there is still a reasonable amount of time to explore and fix anything it before release.

**Comment by petebankhead** [comment]
Sorry @MichaelSNelson I entirely missed this until @finglis mentioned it :)

> One of the things I have often preferred about QuPath is how neatly it arranges most of the windows into a single UI, where I don't have to fight with "is what I want to use on top and accessible" like with Fiji and MicroManager etc.
> 
> If implemented, there really should be ways to quickly and easily organize the windows, like the Tile and Cascade options in Fiji.

I strongly agree - if you try https://github.com/qupath/qupath/pull/1318 I'd be curious as to whether you think it gets the balance ok.

> > Is there a need to have the same image open in multiple viewers?
> 
> This has been one of the things I have often wanted to be able to do for multiplex images (along with synchronize for panning). Having the same image open, but with different sets of channels visible in each MultiView.
> 
> It was something I remember being able to do in earlier versions that has since been removed.

I don't remember that ever being there by design, but it certainly could have been there as a bug :)

**Comment by MichaelSNelson** [comment]
> but it certainly could have been there as a bug :)
Yes, I think it went away when you looked into some other bugs with the multiviewer, but it was extremely useful while it lasted! 

The channel viewer helps now, of course, but it is not quite as useful for looking at the biological implications of multiple channels. For now I have scripts/buttons for the 18plex images that switch between "Tumor" "Immune" and "Structural" so I can quickly flip between sets of 3-5 channels. Being able to see the three sets of markers in different windows yet pan around would be useful, but it would also probably be specific to high plex data sets.
