### ISSUE TITLE
how to read files by scripts

### ISSUE THREAD

**Issue by cs123951** [qupath/qupath#132]
here I have several .qpdata files with several annotations, and i want to export these annotation.

i have already know how to export annotations from one .qpdata file, 
but don't know how to export annotations from batch .qpdata files by scripts.

**Comment by petebankhead** [comment]
From the script editor, you can choose *Run &rarr; Run for project* and then select all the images.

You just need to be careful what your export file name is to avoid overwriting it for each image.  Something like the following will include the name for the current image in the project in the export:
```groovy
pathExport = buildFilePath(PROJECT_BASE_DIR, 'exported', getProjectEntry().getImageName() + '.txt')
print pathExport
```
