### ISSUE TITLE
Show input display and Insert into hierarchy share accelerator

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath#1324]
Before submitting your bug report, please check the following:

* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
`Multiple actions registered for Shift+Shortcut+I, will keep Show input display and drop Insert into hierarchy`

**To Reproduce**
1. Launch latest main build
2. View log

Or, see: https://github.com/search?q=repo%3Aqupath%2Fqupath%20shortcut%2Bshift%2Bi&type=code

**Expected behavior**
No multimapped accelerators. Suggest adding alt to the one that's considered less important

**Desktop (please complete the following information):**
 - OS: Linux
 - QuPath Version: 0.5.0-SNAPSHOT

**Comment by petebankhead** [comment]
Looks like v0.4.x didn't have any accelerator for *Show Input Display*, so I guess just removing it is an option. No one should miss it...

**Comment by petebankhead** [comment]
Yes, it's handy to be able to bring it up quickly during demos / tutorials (especially when forgetting to launch it before starting...), but perhaps not important enough to earn a precious accelerator of its own.
