### ISSUE TITLE
Region too big for ImageJ macro runner

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#133]
![image](https://user-images.githubusercontent.com/319932/34761999-668e7b88-f5e6-11e7-90af-a37a66fd6c61.png)
This regions is by far not too large, and ironically, this works if I just ask to send a region to imageJ. This message should be disabled I think...

**Comment by lacan** [comment]
Suggested fix in https://github.com/qupath/qupath/pull/134

**Comment by petebankhead** [comment]
Thanks, I totally agree about the limit being too low.  I'll check out the fix and respond more there...

**Comment by petebankhead** [comment]
Closing this as I understand it has now been resolved.
