### ISSUE TITLE
Cannot open CZI files on Mac or PC

### ISSUE THREAD

**Issue by amdiarlz** [qupath/qupath#135]
I wonder if you can help. I have to apologise but I am not the most computer literate but I have some CZI files from Zen I would like to analyse in QuPath. I have downloaded the bioformats extension and package and attempted to download the visual c++ redistributable but I keep failing at this step. I cannot install this and my only option is to repair, which it attempts and then fails giving me a log code which I can provide if required.

I have also tried installing qupath on my mac with the same problems. I have downloaded the bioformats package and extension and still cannot open said files. 

Please help.

**Comment by Svidro** [comment]
It has been a while, but I do not think you should have to install anything for Bioformats.  All you need is the JAR file off of their website, and the JAR file from Pete, both at: https://github.com/qupath/qupath-bioformats-extension
And as it says, just drag them into the open QuPath window to add them to QuPath.  I am not sure why you are having issues with a visual C++ redistributable; I am not entirely sure if that is related.  At least, I do not recall having to install anything else when adding bioformats to QuPath, even when it was one of the first things I put on my computer.

Is the error a QuPath error?  It would probably be best to include a picture or at least the text of the error, and exactly when the error pops up (when you drag the bioformats extension into the QuPath window?  when you try to open the CZI file?).

**Comment by petebankhead** [comment]
There is indeed a need to install the redistributables on Windows, as far as I know - it's mentioned [here](https://github.com/qupath/qupath/wiki/Supported-image-formats#zeiss-czi).  But the Mac trouble suggests it's something else.

I know that the support for CZI in QuPath using the Bio-Formats is pretty varied.  Sometimes it works, but I've learned of cases recently where it doesn't.  I think TMAs (with lots of scenes?) are especially troublesome.

I have spotted a few ways to fix the QuPath Bio-Formats extension that I believe will help, and I hope to have these changes made by the middle/end of next week, and I'll write another update here.  Hopefully they will fix the issue with your files, but if not then I will investigate further.

**Comment by amdiarlz** [comment]
Thank you both for your response. I would preferably like to run the software on the mac but have access to PC too if this is more suitable .

The original files I wanted to work with were TMAs with multiple scenes but I cannot even open a jpg file. I am at home now and I am on my mac and it is still not opening the jpg files. 

Thank you for looking into addressing the qupath bio-formats extension. In the meantime, should I need to download any extensions to run the software on the mac? I know in your tutorial for start ups you suggest you do but I have had no joy with this 

Thank you again

**Comment by petebankhead** [comment]
Oh dear, that sounds worse - I am using a Mac, and no extra extensions should be needed.

Does the software start ok?  I have seen a problem on some older Macs where it wasn't possible to start QuPath because of an incompatibility with OpenCV... but if the window opens at all then that shouldn't be the issue.

You should be able to open a JPEG just by dragging it onto the main QuPath window.

Could you try with the image *CMU-1.svs* that is suggested at https://github.com/qupath/qupath/wiki/First-steps ?
If there are problems, could you also choose *View &rarr; Show log* and report back if you see any error messages?

The CZI problem sounds like the one I met before, and will try to resolve next week.

**Comment by amdiarlz** [comment]
Ive just downloaded and re-installed on my mac and its working now! What a pallava! I think I was tried to add extensions on the mac where they weren't needed and it seems to be working now. Ive just had a look at some tissue detections and it seems to be functional! I will continue using the software and would you mind if I checked in again if I continue having problems?

Thank you again

**Comment by petebankhead** [comment]
Ah ok, glad it's solved!
And sure, ask any time.  This is the best place for problems that could be bugs.  For general questions and announcements there is also https://groups.google.com/forum/#!forum/qupath-users 

I'll write on both when there are further CZI developments.

**Comment by amdiarlz** [comment]
Great thank you. I have a couple of questions to ask so I will direct them to the other forum!

**Comment by petebankhead** [comment]
There's a new Bio-Formats extension now [here](https://github.com/qupath/qupath-bioformats-extension/releases/tag/v0.0.4).  It may help with the CZI files.

**Comment by amdiarlz** [comment]
Thank you! I managed to get things working as it happens however. I removed and re-installed several times and it seemed to like that!
