### ISSUE TITLE
Javadocs labelsToConnectedROIs text

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#1354]
The text at https://qupath.github.io/javadoc/docs/qupath/imagej/processing/RoiLabeling.html#labelsToConnectedROIs(ij.process.ImageProcessor,int)
suggests the labelsToConnectedROIs does not function like... labelsToConnectedROIs.

> public static [Roi](https://javadoc.io/doc/net.imagej/ij/1.53v/ij/ij/gui/Roi.html)[] labelsToConnectedROIs([ImageProcessor](https://javadoc.io/doc/net.imagej/ij/1.53v/ij/ij/process/ImageProcessor.html) ipLabels,
>  int n)
> Create ROIs from labels in an image.
> 
> This differs from **labelsToConnectedROIs** in that the ROIs created may be disconnected and contain holes.
> 
> Parameters:
>     ipLabels - 
>     n - 
> Returns:
Maybe it was intended to mention getFilledPolygonROIsFromLabels ?

**Comment by petebankhead** [comment]
Thanks, I've updated the javadoc to
```java
        /**
	 * Create ROIs from labels in an image.
	 *
	 * @param ipLabels the labeled image; generally this should be a ByteProcessor or ShortProcessor
	 * @param n the total number of labels; often this is equal to the maximum value in the image
	 * @return an array of length n; output[i] is the ROI for label i+1, or null if no Roi is found
	 *         with that label.
	 */
```
The class generally remains awkward to use and could benefit from some less ambiguous methods, but they aren't really used much for any new QuPath commands.
