### ISSUE TITLE
Javadoc search links don't work in v0.5.0

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1358]
## Bug report

**Describe the bug**
The search feature in the embedded javadocs is broken in v0.5.0-SNAPSHOT.

It returns search results, but clicking a link doesn't do anything. However
* Clicking *other* links (without search) works.
* And search works if the Javadocs are stored online or in a directory - just *not* in a .jar file.

The ugly workaround is to run the following one-line script to use the online Javadocs instead:
```groovy
qupath.lib.gui.JavadocViewer.javadocPath.set("https://qupath.github.io/javadoc/docs/")
```
This uses a persistent preference, so its setting should be retained.

**To Reproduce**
1. Open a script editor
2. Choose *Help &rarr; Show Javadocs*
3. Enter something in the search bar (top right)
4. Click a link... and nothing happens

**Expected behavior**
Links work like they did in v0.4.x.

**Desktop (please complete the following information):**
 - OS: macOS, Windows (probably Linux)
 - QuPath Version: v0.5.0-SNAPSHOT

**Additional context**
The source of the issue appears to be in JavaFX or webkit. Searching works fine when using JavaFX 19, but breaks in JavaFX 20 and 21.

It is specific to the case where the javadocs are being read directly from a .jar.

**Comment by petebankhead** [comment]
Closing this as it is 'fixed'... inasmuch as the links work when using JavaFX 20. Sadly, they don't when moving to JavaFX 20.0.1, so this is likely to resurface in the future.

**Comment by alanocallaghan** [comment]
Do you have any idea why this is happening? I can look into debugging the web pages if not

**Comment by petebankhead** [comment]
Since I think the trouble started with JavaFX 21.0.1, from the [release notes](https://gluonhq.com/products/javafx/openjfx-21-release-notes/#21.0.1) my guess was the webkit update... but not sure..
