### ISSUE TITLE
How to align multi-view of two WSI with the same size

### ISSUE THREAD

**Issue by yil8** [qupath/qupath#138]
Hi there,

I have pairs of WSI, one is the original image and the other is the annotation mask with the same size, and I want to open these two together. But the problem is they don't often align well, even if I used Multi-view -> check Synchronized viewer -> Add column. Sometimes, the two red boxes of focus on the two columns are the same region, but some times they aren't. It's a bit of random luck. How can I enforce the strict alignment between these two columns of images?

Thanks

**Comment by Svidro** [comment]
While viewers are unsynced, this should get you started.  Maybe Pete will have a way to sync based on the current center of one viewer, but this will temporarily lock them together.  Use your own X Y coordinates for pixel location and your desired downsample.  Just click into each one of the viewers in turn and run:

```
def viewer = getQuPath().getViewer()
viewer.setCenterPixelLocation(10000, 10000);
viewer.setDownsampleFactor(2)
```
Then check the sync box.

**Comment by Svidro** [comment]
Side note, if you want to do this without the script, try syncing the two images when you first open them, without clicking in to them.  They should start out at the same point and be synced.  As soon as you start moving around.. you lose the default image opening coordinates.

**Comment by yil8** [comment]
Yes, pre-create two separate empty vieweres first and then load image into each viewer solves the issue!
