### ISSUE TITLE
Folder based Dicom WSI open as independent dcm images when added to a project

### ISSUE THREAD

**Issue by donn-deciphex** [qupath/qupath#1397]
## Bug report

**Describe the bug**
DICOM WSI is a multifile format comprised of a few DCM files linked by metadata within each file to define a complete WSI.  However it is not being treated as one image when in project mode in QuPath.

**To Reproduce**
1. Create a project in QuPath
2. Hit Add images and select the 1 Dicom WSI (all files .dcm from the containing folder need to be added)
3. Observe the one WSI it displays as N .dcm images (each pyramid level and embedded image is displayed separately).

**Expected behavior**
It should display as 1 WSI for every unique Dicom WSI you add, just like SVS or NDPI etc.  

**Screenshots**
None

**Desktop (please complete the following information):**
Version: 0.4.4
Build time: 2023-08-31, 05:46
Latest commit tag: '647f7ac'
Java version:		17.0.8
Operating system:		Windows 11  -  10.0
Architecture:    		amd64

**Additional context**
None

**Comment by petebankhead** [comment]
Are there public example images to replicate this issue?

QuPath v0.5.0 will include OpenSlide 4.0.0, and this provides dicom WSI support. So the behavior may change then - but we have no examples to test with.

**Comment by donn-deciphex** [comment]
You can try these. Just download and unzip.  https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/

**Comment by petebankhead** [comment]
Thanks, can you try the QuPath v0.5.0 release candidate - https://github.com/qupath/qupath/releases/tag/v0.5.0-rc1 ?

This behaves different from v0.4.4, using OpenSlide to read the image.

To me, it appears to behave properly - although has the limitation that if you add more than one of the dicom files, then the same image is effectively duplicated in the project. I'm not sure if that's expected or acceptable, but addressing it is probably not straightforward. Dicom is the only format I know that behaves in this way, and QuPath tries to avoid having to treat formats as a special case (relying upon OpenSlide or Bio-Formats to untangle the meaning of the image file paths provided).

**Comment by donn-deciphex** [comment]
Thanks for your help, yes that (QuPath v0.5.0 release candidate) seems to be opening the WSI as one image rather than several separate dcm images. However like you said it still displays the list of dcm files in the Image List which may not be desired.  

Not sure what's next in terms of this ticket - the main concern is addressed but the open UX issue may want to be handled separately.

**Comment by petebankhead** [comment]
Thanks, I'll close this issue since the main concern is addressed. We don't really have the capacity to tackle the UX issue, since it is a particularly awkward one. Any 'quick' solution would likely add considerable complexity to import code that is already very convoluted, and any 'thorough' solution could take weeks of effort - so for the foreseeable future it'll need to be up to the user to select just one dcm file.
