### ISSUE TITLE
Can I import/export annotations in form of coordinates of polygons?

### ISSUE THREAD

**Issue by yil8** [qupath/qupath#140]
Hi there,

I'm wondering how can I import annotations in the format of level 0 pixel coordinates of polygons?
 What's the supposed format? I guess there exists this functionality somewhere, but I couldn't find them on the wiki. If you can point me to some link will be great as well. Also, I know how to create polygon annotations using GUI within QuPath, but I don't know if I can export them into text files on disk either.

Thanks!

**Comment by Svidro** [comment]
I do not think there is a standard format for other programs, so part of the problem is where you want to import the annotations to/from.

https://github.com/qupath/qupath/issues/95 shows the most basic way to save annotation coordinates and you can then save lists to text files.

On the forum Pete gave a nice way to transfer annotations within QuPath in the second post of (https://groups.google.com/forum/#!searchin/qupath-users/export$20annotations%7Csort:date/qupath-users/UvkNb54fYco/E-wn_7ZWAAAJ)

https://github.com/qupath/qupath/issues/128 and https://github.com/qupath/qupath/issues/61 covers importing certain objects from Aperio.

**Comment by yil8** [comment]
@Svidro Sorry to trouble you again. I've tried hard to code some Groovy script, but it's still quite mysterious to me. I'm wondering if you could show me the code to do the simple task of drawing a polygon on an opened image? I'll then try my best to follow up on your code. Assuming the coordinates of the polygon is X: [1, 2, 3, 4, 5], Y: [1, 2, 3, 4, 5].

Thanks so much~

**Comment by Svidro** [comment]
```
import qupath.lib.objects.*
import qupath.lib.roi.*

// Any vertices
def x = [100, 200, 300] as float[]
def y = [150, 350, 250] as float[]

// Create object
def roi = new PolygonROI(x, y, -1, 0, 0)
def pathObject = new PathAnnotationObject(roi)

// Add object to hierarchy
addObject(pathObject)
```

Seems to work for me.  Referencing https://groups.google.com/forum/#!topic/qupath-users/j_Wd1hy4eKM

**Comment by yil8** [comment]
@Svidro Really appreciate your code!!! I guess it's little bit too much to ask, but I'm wondering if you could do me a final favor to teach me the code of reading coordinates from a json format like:
```json
{
"tumor": [
  {
   "name": "Annotation 0",
   "vertices": [
    [
     100,
     150
    ],
    [
     200,
     250
    ],
    [
     300,
     350
    ]
   ]
  },
  {
   "name": "Annotation 1",
   "vertices": [
    [
     1000,
     1500
    ],
    [
     2000,
     2500
    ],
    [
     3000,
     3500
    ]
   ]
  }
 ]
}
```

I tried to use import groovy.json.JsonSlurper; But it gave me error of
`Script1.groovy: 5: unable to resolve class groovy.json.JsonSlurper`
With this part done, my entire issue should be resolved.

**Comment by petebankhead** [comment]
If you find the Groovy jar containing `JsonSlurper` and drag it onto QuPath, it should be added to the extensions directory and you can use it then.  But it isn't included by default.

However, assuming all your annotations can be represented by polygons, the following should work without needing to add anything extra:
```groovy
import com.google.gson.Gson
import qupath.lib.geom.Point2
import qupath.lib.objects.PathAnnotationObject
import qupath.lib.roi.PolygonROI
import qupath.lib.scripting.QPEx

def text = """
{
"tumor": [
  {
   "name": "Annotation 0",
   "vertices": [
    [
     100,
     150
    ],
    [
     200,
     250
    ],
    [
     300,
     350
    ]
   ]
  },
  {
   "name": "Annotation 1",
   "vertices": [
    [
     1000,
     1500
    ],
    [
     2000,
     2500
    ],
    [
     3000,
     3500
    ]
   ]
  }
 ]
}
"""

// Read into a map
def map = new Gson().fromJson(text, Map)

// Extract tumor & annotations
def tumorAnnotations = map['tumor']

// Convert to QuPath annotations
def annotations = []
for (annotation in tumorAnnotations) {
    def name = annotation['name']
    def vertices = annotation['vertices']
    def points = vertices.collect {new Point2(it[0], it[1])}
    def polygon = new PolygonROI(points)
    def pathAnnotation = new PathAnnotationObject(polygon)
    pathAnnotation.setName(name)
    annotations << pathAnnotation
}

// Add to current hierarchy
QPEx.addObjects(annotations)
```

**Comment by yil8** [comment]
@petebankhead Great! I think I should be able to work from this code. So much appreciated!
