### ISSUE TITLE
Command to break objects Hierarchy 

### ISSUE THREAD

**Issue by ofrag** [qupath/qupath#1411]
Hi

When running cell detection on Annotation with child annotation, the child annotation is being deletd.
An optional way to overcome this is by  using 
`def annotations = getAnnotationObjects()
removeObjects(annotations, false)
addObjects(annotations)`

as suggested for example in [this image.sc post](https://forum.image.sc/t/qupath-scripting-annotations-deleted-when-running-cell-detection/41292/6)

I was thinking that resetting the object Hierarchy before cell detection and resolving it again afterward may be an alternative solution 
Is there a command that let you reset the object Hierarchy ? 

Thanks
Ofra

**Comment by petebankhead** [comment]
Good question... there's no command for that currently.

I think a 'Flatten hierarchy' command would make sense, but I'm not 100% sure if we should add it. The risk I can think of is that objects wouldn't necessarily end up where they started in terms of the hierarchy after using 'flatten-then-resolve', and that might be confusing.

Another option is to use *Objects &rarr; Annotations... &rarr; Duplicate selected annotations* (Shift + D).

The duplicated annotations have no child objects, so you can detect within them - and then delete the new annotations afterwards if you want to, and resolve the hierarchy then if you need to. That should work both through the user interface and scripting.

Would that work as an alternative in your case?

**Comment by ofrag** [comment]
Hi Pete, 

Thanks for the suggestion. using duplicate works well, and it is better solution for me than deleting all the annotations and restoring them back. 

as a comment for others: 
I didn't find an easy way to select the all the duplicated annotations (as only one is selected after duplication) 
so I had to loop through the selected annotations and for each of them : Select, Duplicate, run StarDist, Delete.

`    
def Anns = getAnnotationObjects().findAll{it.getPathClass().toString()==Class1 || it.getPathClass().toString()==Class2 }
for (ann in Anns) {
        selectObjects(ann)
        duplicateSelectedAnnotations()            
        dup_ann = getSelectedObjects()
        stardist.detectObjects(imageData, dup_ann)
        removeObjects(dup_ann, true) // keep children of the removed annotation
} 
`
best
Ofra

**Comment by petebankhead** [comment]
> (as only one is selected after duplication)

That's strange, when I try with two annotations selected, I see that both the duplicated annotations are selected (and I can run cell detection immediately on both of them).

Although either way i'm glad it works :)

Will think some more about a flatten hierarchy command for the future.
