### ISSUE TITLE
Issue can be deleted - it was a handling error

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#142]
Problem solved

**Comment by DavidMHaumann** [comment]
ah sorry, 
I found the reason. The outer grey ROI does not belong to the external ROI, but was just another ROI sourrounding the tissue spot. In this way there were 2 annotations with different calls. Then the inner one got the class of the outer. 

No unexpected behavior of QuPath. 

I did not find a way to delete this issue. If there is, it can just be deleted, to prevent any confusion.

**Comment by Svidro** [comment]
https://stackoverflow.com/questions/34010565/how-do-i-close-a-github-issue-without-making-a-commit
Should work for you, or Pete can close it.  I do not think you can delete an issue, but as author you could change the title and or delete the text.
