### ISSUE TITLE
Saving in TIF format

### ISSUE THREAD

**Issue by swvanderlaan** [qupath/qupath#143]
Hi,

I just recently discovered your software-tool. I want to use it to view slides, and save an image of it. I can see in the menu an option to export/save the viewer image. But that is rather low resolution (1128x789) and only in PNG-format. Can I save the image in the viewer (with the overview picture and scale bar) as a larger resolution TIF image? 

Thanks!

Sander

**Comment by swvanderlaan** [comment]
Ah apologies, I see that there is another similar question. Should I try to export to ImageJ?

**Comment by petebankhead** [comment]
If it's TIFF you want, then it's best to send it to ImageJ and save from there.

There's still a size limit, so if you want to export especially large regions and that still doesn't work then let me know... in the short term you might need a script to work around that limit.

Two extra notes:
* QuPath can't export regions that are approaching the size of a whole slide yet at all; i.e. it can handle thousands of pixels along each dimension, but not tens of thousands.
* If the *Downsample factor* is 1 and the image is RGB, then *Export image region* should give you the same pixels in the PNG as you'd get in the TIFF, at the full resolution.
