### ISSUE TITLE
Menu command: Select all childs

### ISSUE THREAD

**Issue by iwbh15** [qupath/qupath#1438]
It is often necessary/helpful to select all child objects of annotations, e.g. to delete or classify them.

The selection of child objects in the object list on the Hierarchy tab is tedious and error-prone - especially when the number of objects is large.

A function (in the menu and in the context menu of annotations) for selecting all child objects of all selected annotations would be desirable and helpful.

Until now this selection can be done via scripting:
```
childs = getSelectedObject().getChildObjects()
selectObjects(childs)
```
In my opinion, the function described is so basic that it should be available in the menu.

**Comment by petebankhead** [comment]
Should selecting all child objects *also* keep the parent selected?
Would that need to be two different commands, or one command with a checkbox when run interactively?

**Comment by iwbh15** [comment]
Personally, I would like to see a single command and an option in the preferences:
`Keep parents selected when using 'Select childs'`

**Comment by petebankhead** [comment]
Hmm, I worry about burying the option in the preferences. It reminds me of ImageJ's 'Black background' option where a hidden preference causes different results for different users, making it harder to give instructions to anyone else.

If you want to run as script as a command (with menu item), you can use this:
```groovy
getQuPath().installGroovyCommand("Objects>Select children", 
    """
    def children = getSelectedObject().getChildObjects()
    selectObjects(children)
    """
)
```

To make it always available without the hassle of creating an extension, you can include it in a startup script file - basically any Groovy file, which can be set in the preferences under 'Startup script path'.

This should allow you to add multiple custom commands in menus of your choosing, to run any short scripts.

**Comment by iwbh15** [comment]
That's perfect Pete.
No need to include a new menu command if I can create it myself :-)

Here is my final startup script:

```
getQuPath().installGroovyCommand("Objects>Select...>Select children", 
    """
    def selectedObjects = getSelectedObjects()
    if (!selectedObjects)
        return
    def children = []
    for(obj in selectedObjects) {
       if (obj.isAnnotation()){
           //println obj
           def tmpchilds = obj.getChildObjects()
           children += tmpchilds
       }
    }
    selectObjects(children)
    """
)
```
