### ISSUE TITLE
M1 github actions runner now available

### ISSUE THREAD

**Issue by kaczmarj** [qupath/qupath#1458]
hello friendly qupath team, i wanted to let you all know that github actions now has an apple m1 runner. this might be useful to package qupath on arm macs -- though i see that qupath already has arm releases for apple.

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by petebankhead** [comment]
Thanks @kaczmarj ! Closing this now as @alanocallaghan has taken care of it in https://github.com/qupath/qupath/pull/1464
