### ISSUE TITLE
Positive cell detection on multiple annotations

### ISSUE THREAD

**Issue by MrGrishenko** [qupath/qupath#148]
Hi, I'm trying to do something very simple (I think). I have slidescanner images from which I select 10 annotations which each have around 4,000 cells in. I want to run positive cell detection on all annotations however Qupath will not process more than 2 at a time. I'm using a 3.2GHz i5 with 8GB of ram.

I've tried merging the annotations then running the positive cell detection. This sometimes works but is unreliable.

I also thought I could write a script which processes each annotation individually however I don't know the code to select the first annotation, run detection, select 2nd annotation, run detection, etc....

Any help much appreciated!
Al

**Comment by petebankhead** [comment]
Closing this issue as it is being answered at [Google Groups](https://groups.google.com/d/msg/qupath-users/49jz2vnTG38/OjqdCSs1CAAJ)
