### ISSUE TITLE
Undo/Redo unexpected behavior after importing from file

### ISSUE THREAD

**Issue by SquidXTV** [qupath/qupath#1487]
Before submitting your bug report, please check the following:

* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
If you import objects from a file, then select an object like a rectangle and change/move it and then finally using
undo it weirdly going to delete all added objects instead of undoing the change/move.

**To Reproduce**
1. Loading image using `Open...`
2. Loading objects using `Import objects from file`
3. Double click (select) any object
4. Move/Change the selected object, like transforming a rectangle or whatever
5. Undoing the action

**Expected behavior**
Undoing the move/change of the object.
Instead it just deletes all objects.

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: 0.5.1

**Comment by SquidXTV** [comment]
I also noticed that if you just do the first two steps (loading image and objects) that you won't be able to undo loading the objects anyway. The undo action gets available after doing something else, even selecting and deleting an object.

Pretty weird to me, where is that undo action coming from? It is unrelated to actions later. I think it is storing a state with no objects at all somewhere.

**Comment by petebankhead** [comment]
QuPath's undo support is pretty bad - I spoke about it recently in this video: https://youtu.be/zFTnfv_XWg4?t=41

Fixing it _properly_ will likely involve making some scarily-large changes to the core behavior, but we'll explore whether it can be made less bad in this specific scenario.

**Comment by SquidXTV** [comment]
Ah I see.

> [..] but we'll explore whether it can be made less bad in this specific scenario.

No need for me specifically, I just noticed that issue, but it seems to be a larger issue with the current implementation anyway.

**Comment by petebankhead** [comment]
@Rylern figured out what's going on, and #1578 helps address this bit of undo/redo weirdness. The fix should be available in v0.6.0.
