### ISSUE TITLE
Problems with multilayer file from Olympus in .vsi

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#149]
Hi Pete, 

QuPath can not read multilayer .vsi files from Olympus. Do you know already about this problem and do you plan to make it compatible with QuPath?

Best
David

**Comment by petebankhead** [comment]
I don't know about the problem, and didn't know about multilayer .vsi files.  Single-plane .vsi images should work via the Bio-Formats extension.

I would need example images to be able to investigate this.  I do not know if Bio-Formats supports multilayer .vsi; if not, it is not something that can be solved on the QuPath side only.
