### ISSUE TITLE
Channel drop-down box right click

### ISSUE THREAD

**Issue by finglis** [qupath/qupath#1498]
## Bug report

**Describe the bug**
When right clicking the drop down box to toggle channel selection for pixel classifier (see below), the channel options and the intended options show at the same time causing overlap. Note: using a macbook and a trackpad. 

**To Reproduce**
1. Go to "train pixel classifier"
2. Click on "edit" next to "features"
3. Right click on channels 
4. Both the channels and the Select all/none options appear
<img width="820" alt="image" src="https://github.com/qupath/qupath/assets/42358257/dd15195c-ebfb-4118-948a-202b7c2ff5b2">

**Expected behavior**
<img width="824" alt="image" src="https://github.com/qupath/qupath/assets/42358257/3d10e366-524c-42cb-a438-8741abeb7434">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - QuPath Version: 0.5.1

**Additional context** 
Unsure if it's specific to mac and/or the trackpad

**Comment by petebankhead** [comment]
This requires a fix in `qupath-fxtras` - I think this does it (at least on macOS): https://github.com/qupath/qupath-fxtras/pull/31
