### ISSUE TITLE
java core dump 

### ISSUE THREAD

**Issue by centredecalcul** [qupath/qupath#150]
My nodes run CentOS, so I can't use Qupath due to the version of libc :

> QuPath
>  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by QuPath)

So I try to run Qupath in a Ubuntu container, and java core dump : 
> singularity exec ubuntu_1604.simg .../QuPath/QuPath 
> A fatal error has been detected by the Java Runtime Environment:
> 
> SIGBUS (0x7) at pc=0x00007fc8990a9ca1, pid=95904, tid=0x00007fc8ab79e740
> 
> JRE version:  (8.0_111-b14) (build )
> Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
> Problematic frame:
> j  java.lang.Object.<clinit>()V+0
> 
> Core dump written. Default location: .../QuPath/app/core or core.95904
> 
> An error report file with more information is saved as:
>  .../QuPath/app/hs_err_pid95904.log
> Memory fault (core dumped) 

Any idea ?

**Comment by petebankhead** [comment]
I'm afraid my access to systems running Linux is pretty limited, but I hope to give it a bit more attention in a few weeks...

In the meantime, I'd suggest trying to build QuPath from source.  You could try it from the main repo here (which [involves eclipse + Maven in a fairly cumbersome way](https://github.com/qupath/qupath/issues/84)), or from my fork [here](https://github.com/petebankhead/qupath).  On my fork I've tried to greatly streamline the process of building the software using [Gradle](https://github.com/petebankhead/qupath#building-qupath-with-gradle), which should also make it easier to investigate the changes that may be necessary to get it to really work cross-platform.

This might also help: https://github.com/qupath/qupath/issues/51

**Comment by centredecalcul** [comment]
Thank you !
With Gradle the build ends properly despite some warnings and It ran in a CentOS 7, with some errors, but it ran :

```
$ QuPath
13:20:05.914 [main] [INFO ] qupath.QuPath - Launching QuPath with args: 
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
13:20:06.362 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale FORMAT set to fr_FR
13:20:06.366 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale DISPLAY set to en_US
13:20:06.396 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Tile cache size: 3568,00 MB
13:20:07.893 [JavaFX Application Thread] [ERROR] qupath.opencv.OpenCVExtension - Unable to load OpenCV libraries!
java.lang.UnsatisfiedLinkError: /soft/c7/qupath/0.1.3/app/libopencv_java310.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /soft/c7/qupath/0.1.3/app/libopencv_java310.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at qupath.opencv.OpenCVExtension.loadNativeLibrary(OpenCVExtension.java:59)
	at qupath.opencv.OpenCVExtension.addQuPathCommands(OpenCVExtension.java:72)
	at qupath.opencv.OpenCVExtension.installExtension(OpenCVExtension.java:116)
	at qupath.lib.gui.QuPathGUI.refreshExtensions(QuPathGUI.java:1099)
	at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:645)
	at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:437)
	at qupath.lib.gui.QuPathApp.start(QuPathApp.java:63)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
13:20:08.246 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Selected style: Modena Light
13:20:08.246 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Performing update check...
13:20:08.256 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathApp - Starting QuPath with parameters: []
13:20:17.509 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Calling Platform.exit();
```


In Centos 6, I found some information about the error message "j  java.lang.Object.<clinit>()V+0"  : this may be a stack problem. I tried to change the thread stack size with -Xss in QuPath.cfg [JVMOptions], but I can not do it : 

```
13:11:03.460 [main] [INFO ] qupath.QuPath - Launching QuPath with args: 
QuPath Error invoking method.
QuPath Failed to launch JVM
```

**Comment by petebankhead** [comment]
Ok, good, since it's building ok can you have a look for a `.jar` file inside QuPath starting `qupath-extension-openslide` and then move/rename it (so that QuPath won't find it)?  My hope is this will prevent QuPath trying to load the troublesome library.

You may not be able to open whole slide images then (although adding the [Bio-Formats extension](https://github.com/qupath/qupath-bioformats-extension) could work around that, at least for some formats).  But if it at least starts ok then hopefully you could install OpenSlide with your package manager, and the problem changes to getting QuPath to find it whenever you put the `.jar` file back...

**Comment by petebankhead** [comment]
Well, clearly I didn't actually read the error message, sorry... looks like it's OpenCV and not OpenSlide that seems to be triggering the trouble.
Could you replace `openslide` with `opencv` in those last instructions...?

Or if you are feeling particularly bold you could also try switching to the `java9` branch on my fork, where I am trying out a different version of OpenCV - which might possibly avoid the problem entirely.

**Comment by petebankhead** [comment]
Basically, you can hide any jar that has `extension` in the name and QuPath should still work - it will just be missing whatever functionality the jar provided.  In the OpenCV case, the main things are the detection classifiers and wand tool.

**Comment by centredecalcul** [comment]
I tried to delete extensions, but the error remains.
It does not matter, the program works and seems to suit the user.
Thank you.
