### ISSUE TITLE
Rebuild against OpenSlide head / > 3.4.1 to support new file types

### ISSUE THREAD

**Issue by jil24** [qupath/qupath#151]
I have a bunch of PreciPoint .vmic slide files, and I see that OpenSlide implemented support for this format about a year ago. However, Qupath cannot read these files, and Openslide has not actually had a release since this implementation was merged (3.4.1 was almost 3 years ago). Can Qupath be rebuilt against the "head" version of Openslide or does it need additional changes to support a new filetype?

**Comment by petebankhead** [comment]
I'm afraid my cross-platform software building abilities are pretty poor (Java never forced me to improve...); if you (or anyone) would be able to create the appropriate build scripts for OpenSlide only that would be *fantastic*.  On the QuPath side it should just be a matter of packaging up the binaries in a way that Java can find - which is something I am happy to help with.

**Comment by kwiechen** [comment]
as a workaround for 0.2.0-m2: try to replace app/libopenslide-0.dll or with the appropriate libopenslide-0.dll file from https://github.com/Markus-PP/openslide-vmic.  I have tested with my .vmic files and it seems to work

**Comment by petebankhead** [comment]
Closing this since it has been quiet for a year - and because OpenSlide has been quiet for even longer. It seems it may no longer be maintained.
