### ISSUE TITLE
Possibility to save annotation measurements for all project images to one xls / csv?

### ISSUE THREAD

**Issue by juhahama** [qupath/qupath#152]
Hi!

I managed to do cell detection and intensity analysis with 3 tresholds to all of my project images (about 70 images) with scripting. Now the question is that can I get the annotation measurements somehow written to one summary file so that there would be separate row for each images' measurements? Ideally excel-file.  For the purpose now at hand I am only interested for one specific measure (H-Score), so can I filter somehow file building that only one/few wanted measures would be included?

**Comment by petebankhead** [comment]
When you run *Measure &rarr; Show annotation measurements*, you can type the contents of a column header to filter out other columns.  Then if you save the measurements, only those columns should be included.  In a script, it could look like this:
```groovy
saveAnnotationMeasurements('/path/to/output/file.txt', 'H-score')
```
You should also be able to specify extra columns there if necessary, e.g. 
```groovy
saveAnnotationMeasurements('/path/to/output/file.txt', 'H-score', 'Positive %')
```

The alternative approach is just to export everything, and then combine the tables later.  That requires two scripts: one to export the table (which you can *Run for project* in the script editor to batch export for all your images), and one to combine the exported tables.
* A script to export is [here](https://gist.github.com/petebankhead/a473b817eac36caabdffc21daf93231d)
* A script to combine is [here](https://gist.github.com/petebankhead/2ef44747f979607e23f50f278aeffd22)

There is also [a recent discussion here](https://groups.google.com/d/msg/qupath-users/GEI99RECuAc/e6ka2zFrCwAJ) where I first posted those links.

While the end result isn't an Excel file, it should be a tab-delimited file that Excel can import relatively easily - either by opening the file directly, or copying & pasting the contents.

**Comment by juhahama** [comment]
Ah - thank you! I am new to QuPath and to the community so I missed the Google group discussions totally. For the future needs I will have a look also to those discussions before posting issue here.

**Comment by petebankhead** [comment]
No problem :)
I intended to post the information here too, was just waiting for the right question...
