### ISSUE TITLE
Issue Changing Custom Color for Channel

### ISSUE THREAD

**Issue by ipaine01** [qupath/qupath#1539]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
"Custom color" window closes when trying use a custom color either by typing in a box, clicking on a slider, or clicking on the color picker. 

**To Reproduce**
1. Go to "Brightness and Contrast"
2. Click on the color next to a channel and click "Custom color..."
3. Try to adjust a slider, use color picker, or type in one of the text boxes
4. See error (window immediately closes)

**Expected behavior**
It is expected that the window remain open while dragging a slider, moving the color picker, or typing in one of the boxes such that a color can actually be customized and adjusted. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - QuPath Version: 0.5.1

**Additional context**

**Comment by petebankhead** [comment]
Hi @ipaine01 this sounds like the issue reported at https://forum.image.sc/t/bug-channel-name-changed-when-changing-color/95010/6

If so, I have already fixed it at https://github.com/qupath/qupath/pull/1508 and the fix will be available in the next QuPath release.

In the meantime, the workaround is to double-click on the channel (rather than clicking the color box) since this will allow you to choose a custom color in a different way.

**Comment by ipaine01** [comment]
Thanks so much! Yes, it was the same issue as already reported-- I didn't realize it was already posted. The other way is working for me in the mean time.
