### ISSUE TITLE
Calculate Intensity features - choose square/circular tiles does not work for me

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#154]
In the calculate intensity features menu one can select ROI/square tiles/circular tiles for the computation of statistics. 
In case of square tiles and circular tiles, QuPath shall consider the size information below, to calculate the features for e.g. a square tile around the object with 200px X 200px. 

Every time, I choose this option, no features are generated for the objects. 
Why is that?

Maybe I do something wrong?

![grafik](https://user-images.githubusercontent.com/16352785/37051422-aae10d80-2176-11e8-8158-97628d195071.png)

Best
David

**Comment by petebankhead** [comment]
I admit I haven't tested it, but I think I see the problem in the code [here](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-processing-awt/src/main/java/qupath/lib/algorithms/IntensityFeaturesPlugin.java#L341).

Basically, QuPath is looking for a parameter called `tileSizePx` when the actual name it should be looking for is `tileSizePixels`.  I guess it was changed at some point in one place but not the other.

If this is correct, then it *should* work if you have pixel size (µm) information in the image, but fail if you don't.  That might also explain why it went unnoticed for a while.

Does that match with what you see?  If so it should be a relatively small fix in the code to make it work for images that lack pixel size information.

**Comment by DavidMHaumann** [comment]
Hi Pete, 
yes indeed. It works if pixel size information is available. 

I work with jpg´s without pixel size information at the moment.

**Comment by petebankhead** [comment]
Addressed in https://github.com/qupath/qupath/commit/65efc7e82347f826c53083750f5c897cb9dec0bc
