### ISSUE TITLE
How to package a program into exe file from source code?

### ISSUE THREAD

**Issue by happywt** [qupath/qupath#1542]
Hello, I was wondering how to package the program into an exe file from the source code of QuPath? I don't mean just download the installer you provide, but I want to package it directly from source into an exe file myself. Is there any good way? How did you do it? Your answer is very important to me, thank you!

**Comment by alanocallaghan** [comment]
1. Clone or download the repository (and extract if necessary)
2. Open a command prompt in the downloaded folder
3. Run `gradlew clean jpackage`

See https://qupath.readthedocs.io/en/0.5/docs/reference/building.html

**Comment by petebankhead** [comment]
Duplicate of https://forum.image.sc/t/how-to-package-source-code-as-an-exe-file/97618 (please post questions only on the forum)
