### ISSUE TITLE
cell detection always segments white areas instead of colored areas,why?

### ISSUE THREAD

**Issue by daddaswdadw** [qupath/qupath#1545]
![1971ff8de5e71a5fd8f1f7600bdee9b](https://github.com/qupath/qupath/assets/97733609/10c61a6a-a427-40d1-80ae-a4ee54c1b3af)

**Comment by alanocallaghan** [comment]
Questions like this are better posted on the [ImageSC forum](https://forum.image.sc/), and should generally have more context than a title and a screenshot.
