### ISSUE TITLE
alt+wand function not working

### ISSUE THREAD

**Issue by Fran-code-web** [qupath/qupath#1546]
## Bug report

**Describe the bug**
When I press the alt+wand to erase from annotations, the feature doesn't work. Instead, the selected annotation is highlighted but nothing happens

**To Reproduce**
1. Click on 'Wand' tool
2. Hold on 'alt gr' 
3. Brush over selected wand annotation  '....'
4. See the selected annotation (yellow) be highlighted but nothing happens

**Expected behavior**
I expect that smaller objects within the annotation should be erased

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - QuPath Version: [ 0.5.1]

**Comment by petebankhead** [comment]
This works fine for me on my Mac, and I'm pretty sure it works on Windows too.

Note that the [docs](https://qupath.readthedocs.io/en/0.5/docs/reference/shortcuts.html#the-alt-key) specify you should hold the `Alt` key, *not* `Alt Gr`.

Note also that annotations [can be locked, and would need to be unlocked for editing](https://qupath.readthedocs.io/en/0.5/docs/reference/commands.html#lock-selected-objects).

And finally
>  expect that smaller objects within the annotation should be erased

That isn't the purpose of the `Alt` trick - rather, it subtracts from an existing annotation as shown [in this old video](https://youtu.be/lGj3uyxUdgs?t=99).

Please try these. If you are still sure there is a bug, please describe in more details your exact steps - including how you generated the annotation originally, preferably with screenshots.

**Comment by Tkilvaer** [comment]
Works on Ubuntus 18-23.10 too

tor. 20. juni 2024, 06:54 skrev Pete ***@***.***>:
