### ISSUE TITLE
multiplex ihc (5 colors), suggestions appreciated

### ISSUE THREAD

**Issue by schmolze** [qupath/qupath#155]
I'm working with some multiplex (brightfield) immunohistochemistry whole slide images that are stained with five colors (brown, purple, teal, red, black). Here's an example:

![penta qupath 1](https://user-images.githubusercontent.com/3537118/37111528-c6c69b68-21f4-11e8-8543-f9e54bcaa5f0.png)

Analyze -> Cell analysis -> Cell detection does an acceptable job of identifying cells:

![penta qupath 2](https://user-images.githubusercontent.com/3537118/37111535-c9b80622-21f4-11e8-9cb9-a5eca67f3a4e.png)

I would like to classify them by color, ideally with a script. I'm aware that QuPath doesn't have built-in support for multiple colors at this time. Also aware that Estimate stain vectors can be used to change what colors QuPath considers to be, for example, DAB.  However, I don't think this would work for 5 colors.

I can loop through the detected cells no problem. Is it possible to extract mean pixel intensity separately for the red, green, and blue channels? Something like:

```
for (def cell: getCellObjects()) {

	double r = cell.getMeasurementList().getMeasurementValue("Cell: Mean Red Intensity")
	double g = cell.getMeasurementList().getMeasurementValue("Cell: Mean Green Intensity")
	double b = cell.getMeasurementList().getMeasurementValue("Cell: Mean Blue Intensity")
	
	if (isBrown(r,g,b)) {
		cell.setPathClass(Brown)
	}
	...
}
```

From `getAvailableFeatures(getCellObjects())` it doesn't seem like it. Any other suggestions are much appreciated!

**Comment by petebankhead** [comment]
That's a very nice image... not entirely sure how to work with it, but it looks great.

You could try using *Analyze &rarr; Calculate features &rarr; Add intensity features (experimental)*.

For the parameters, I guess you would keep the region as *ROI* and possibly decrease the *Preferred pixel size* value because the ROIs will be small.  (From memory, I believe the actual ROI used will be that of the cell, not the nucleus.)

You can then choose the features and color transforms you want, and can reuse these in an interactively-trained classifier if necessary.

Out of interest: do you know where the positive staining for each color is expected to be localized within the cell in each case, and do you expect double/triple etc. positive cells?

**Comment by petebankhead** [comment]
One reason I ask is that, depending upon the expected localization, there might be an argument for making the intensity measurements in a very small circular/rectangular region at the highest resolution, so as to make a measurement just around the cell centroid - not across the full region.

The other reason is that I'm currently quite interested in adding the ability to detect different stains by providing sample colors - without any color deconvolution step.  I'm not sure how relevant or helpful it would be here though.

**Comment by schmolze** [comment]
Thanks Pete, I'll give that a shot.

They're all cytoplasmic stains, without any expected overlapping (thankfully!). I have quite a few of these multiplexed whole slide images, I can share if you think they would be useful for development testing.

**Comment by petebankhead** [comment]
They certainly could be useful... I'd be interested to explore a bit if sharing is not a problem.

Under *Brightness/Contrast*, the *Normalized OD color* transform looks borderline helpful, but unfortunately not for black.

Optimistic question: Would area measurements of each individual stain be of any value?  Or to be meaningful must the final readout be classified cell counts (or something else that's more difficult)?

**Comment by schmolze** [comment]
_Normalized OD color_ looks like it might be useful. Black is the least important and will be the hardest to accurately count I think (they are follicular dendritic cells with tentacle-like extensions, not a typical cell shape).

The final readout has to be classified cell counts unfortunately.

**Comment by schmolze** [comment]
Thanks for the tips Svidro, I will definitely continue to play with these images. I'll try to get one uploaded somewhere soon as well.

**Comment by AAkarca** [comment]
Hi, I have an image to analyse but do not have hematoxylin and wonder if I can do cell segmentation by using other colour detection? If yes then how can I change the script

**Comment by petebankhead** [comment]
@AAkarca please use http://forum.image.sc/tag/qupath for questions.
