### ISSUE TITLE
Thread leak in RenderedImageServer

### ISSUE THREAD

**Issue by jraufeisen** [qupath/qupath#1561]
* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
I encountered some reproducible crashes on macOS (Macbook Air, M1) when running the below script for ~100 images within a project.

The script will run fine at first. After ~100 images, an exception will be thrown. And after a few more executions, the app will crash.

> ERROR: unable to create native thread: possibly out of memory or process/resource limits reached". 

**To Reproduce**

```groovy
import qupath.lib.gui.viewer.overlays.HierarchyOverlay
import qupath.lib.gui.images.servers.RenderedImageServer

def viewer = getCurrentViewer()
def imageData = getCurrentImageData()

def name = GeneralTools.getNameWithoutExtension(imageData.getServer().getMetadata().getName())
def pathOutput = <output_path>

double requestedPixelSize = 15
double downsample = requestedPixelSize / imageData.getServer().getPixelCalibration().getAveragedPixelSize()

def display = qupath.lib.display.ImageDisplay.create(imageData)
def server = new RenderedImageServer.Builder(imageData)
    .display(display)
    .downsamples(downsample)
    .layers(new HierarchyOverlay(viewer.getImageRegionStore(), viewer.getOverlayOptions(), imageData))
    .build()

```

**Expected behavior**
The above script can run for the whole project without crashing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS (MacBook Air, M1)
 - QuPath Version: 0.5.1-arm64

**Additional context**

Stack trace
```
ERROR: unable to create native thread: possibly out of memory or process/resource limits reached in thread_leak_repro.groovy at line number 25
java.base/java.lang.Thread.start0(Native Method)
    java.base/java.lang.Thread.start(Unknown Source)
    java.base/java.lang.System$2.start(Unknown Source)
    java.base/jdk.internal.vm.SharedThreadContainer.start(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
    qupath.lib.gui.images.stores.AbstractImageRegionStore.requestImageTile(AbstractImageRegionStore.java:374)
    qupath.lib.gui.images.stores.DefaultImageRegionStore.paintRegionCompletely(DefaultImageRegionStore.java:104)
    qupath.lib.gui.images.servers.RenderedImageServer.readTile(RenderedImageServer.java:363)
    qupath.lib.images.servers.AbstractTileableImageServer.lambda$prerequestTiles$2(AbstractTileableImageServer.java:462)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    qupath.lib.images.servers.AbstractTileableImageServer.prerequestTiles(AbstractTileableImageServer.java:464)
    qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:295)
    qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:60)
    qupath.lib.images.writers.AbstractImageIOWriter.writeImage(AbstractImageIOWriter.java:82)
    qupath.lib.images.writers.PngWriter.writeImage(PngWriter.java:42)
    qupath.lib.images.writers.AbstractImageIOWriter.writeImage(AbstractImageIOWriter.java:96)
    qupath.lib.images.writers.PngWriter.writeImage(PngWriter.java:42)
    qupath.lib.images.writers.ImageWriterTools.writeImage(ImageWriterTools.java:163)
    qupath.lib.scripting.QP.writeImage(QP.java:3365)
```

`jstack -l` lists 4096 threads of the following kind
```
"region-store-1" #4103 [2125611] prio=5 os_prio=31 cpu=0.27ms elapsed=19.36s tid=0x000000031cc05800 nid=2125611 waiting on condition  [0x000000052a866000]
"region-store-2" #4104 [2239747] prio=5 os_prio=31 cpu=0.20ms elapsed=19.36s tid=0x000000031cc06000 nid=2239747 waiting on condition  [0x000000052aa72000]
"region-store-3" #4105 [2239235] prio=5 os_prio=31 cpu=0.27ms elapsed=19.35s tid=0x000000011bea7a00 nid=2239235 waiting on condition  [0x000000052ac7e000]
"region-store-4" #4106 [2125827] prio=5 os_prio=31 cpu=0.08ms elapsed=19.35s tid=0x000000011bea8200 nid=2125827 waiting on condition  [0x000000052ae8a000]
...
```

I guess the problem lies in [RenderImageServer.java](https://github.com/qupath/qupath/blob/96c452d1fe643d09bd1127fd3559219d81d6e7f7/qupath-gui-fx/src/main/java/qupath/lib/gui/images/servers/RenderedImageServer.java#L310C1-L311C1), where new region stores are created but never closed/disposed.

**Comment by jraufeisen** [comment]
I was able to fix this by adding an explicit
```
server.store.close()
```
at the end.

Would it be possible to automatically invoke this close() call when a `RenderedImageServer` is disposed?

**Comment by petebankhead** [comment]
Thanks for your report and tracking down the problem. We definitely should close any new image tile store that is being created here, although we shouldn't have to if the 'main' tile store used by QuPath is used instead.

Could you try modifying your rendered server builder as shown below please?
```java
def server = new RenderedImageServer.Builder(imageData)
    .display(display)
    .downsamples(downsample)
    .store(viewer.getImageRegionStore()) // The new line!
    .layers(new HierarchyOverlay(viewer.getImageRegionStore(), viewer.getOverlayOptions(), imageData))
    .build()
```
I haven't tried it, but from reading the description I think it might help work around the issue.

**Comment by jraufeisen** [comment]
Thanks for getting back so quickly. I gave it a try and can confirm that adding `.store(viewer.getImageRegionStore())` also works.

**Comment by alanocallaghan** [comment]
re:

> Would it be possible to automatically invoke this close() call when a RenderedImageServer is disposed?

`ImageServer`s are `AutoCloseable` objects, so ideally they should be used in "try-with-resources" blocks, though the script editor won't lint that for you

**Comment by jraufeisen** [comment]
But would that also close the RegionStore? As far as I can see, RenderedImageServer does not override `Close`

**Comment by petebankhead** [comment]
Yes, I think we'd need to override `close()` to close the store for `ImageServer.close()` to work - but then we should only close the store if it's created internally within the `RenderedImageServer`, and not if it is provided elsewhere.

Or maybe a different approach would work better, e.g. using a [`Cleaner`](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/lang/ref/Cleaner.html), or by rethinking `DefaultImageRegionStore` entirely (since it evolved in a weird way over the years).

Not sure what exactly we should do, it'll probably take some thought to figure out.
