### ISSUE TITLE
ImageOps.Core.replace() does not work as expected

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#1564]
**Describe the bug**
As can be seen from https://github.com/qupath/qupath/blob/f12b38a32906e0257a34ea380e9a66d67e58ae75/qupath-core-processing/src/main/java/qupath/opencv/ops/ImageOps.java#L2189

The logic seems to be broken as `newValue` is never initialized, I think it should be
```
ReplaceValueOp(double originalValue, double newValue) {
	this.originalValue = originalValue;
	this.newValue = newValue;
}
...
```

**Comment by petebankhead** [comment]
Should be fixed now by https://github.com/qupath/qupath/pull/1565, thanks!
