### ISSUE TITLE
QuPath unable to open images using symbolic links

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [qupath/qupath#1586]
Hey

I'm trying to open an image through a symlink. I've created symlinks for both the folders with the metadata and the .vsi files, but I'm getting an error:

![image](https://github.com/user-attachments/assets/329325f0-7e2c-4c82-b9f4-76f0745578e6)

How can one create/open symlinks? I can open the images on the original paths just fine, but can't open the symlinks

Thanks

**Comment by petebankhead** [comment]
I've merged a proposed fix at https://github.com/qupath/qupath/pull/1620 which will be in the next QuPath release.
