### ISSUE TITLE
Require ability to sub-classify any detections according to intensity

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#16]
Currently, *Classify &rarr; Create detection classifier* has the option to immediately sub-classify detections according to intensity - but *only* if these are classified as *'Tumor'*.

This is a result of the original primary application of QuPath being in the scoring of biomarkers selectively within a tumor cell population (e.g. to calculate H-scores, or Ki67 labelling indices).

Currently, classifying (or sub-classifying) detections in a general way according to staining intensity is only possibly by writing a script to do so.

It would be helpful to be able to do so more easily, and in a scriptable manner (i.e. in a way that gets logged in the workflow).

**Comment by petebankhead** [comment]
While there is still no way to classify easily by intensities through the GUI, starting from [v0.1.2](https://github.com/qupath/qupath/releases/tag/v0.1.2) several new functions make it very easy by scripting, e.g. [this one](https://github.com/qupath/qupath/blob/master/qupath-core-processing/src/main/java/qupath/lib/scripting/QP.java#L1156).

For example, to classify all cells as negative, 1+, 2+ or 3+ according to nuclear DAB staining, you may use
```groovy
setCellIntensityClassifications("Nucleus: DAB OD mean", 0.2, 0.4, 0.6)
```

Or to classify cells as positive or negative after running the new subcellular detection command, you could try
```groovy
setCellIntensityClassifications("Subcellular: DAB: Num spots estimated", 2.5)
```

Finally, a more sophisticated example where the classifications for all cells are first reset, and then a reclassification according to intensity for tumor cells applied:
```groovy
// Reset all existing intensity classifications
resetIntensityClassifications()

// Select all tumor objects
def tumor = getPathClass("Tumor")
def tumorObjects = getObjects({p -> tumor.isAncestorOf(p.getPathClass())})

// Apply intensity classification
setIntensityClassifications(tumorObjects, "Nucleus: DAB OD mean", 0.2, 0.4, 0.6)

// Fire an update event to see the results
fireHierarchyUpdate()
```

**Comment by petebankhead** [comment]
Hi Jennie, with that command you can only use one measurement (e.g. "Cell: Channel 1 mean").

What is the final output that you want to see?
Also, do you have a TMA, microscope image, whole slide scan of a large tissue section, or something else?

**Comment by JennieCarson** [comment]
In the end I am hoping for summary data on all channel intensities to be in the annotations measurement table. with that command I indeed only see channel 1 data. My images are from a TMA but I have each core in a separate image. 
Thanks for the speedy reply!

**Comment by petebankhead** [comment]
Ah, does that mean it's a .czi file, or is there another scanner/source that produces this...?

Anyway, a couple of suggestions:
* You could export summary results three times, and then merge them together into a single table later... but then you won't have any info about whether individual cells are positive in multiple channels (just summary results for each channel independently)
* You can use *Measure &rarr; Show detection measurements* to get all the details for every cell in each image, and explore how to summarize this elsewhere (e.g. in Excel, with R, with Python).

If you take the second approach, whatever method of summarizing you choose could then potentially be worked back into becoming a QuPath script.  But there isn't any built-in way to do that currently (and I'm not sure what would be the appropriate, general-purpose way to summarize this kind of data).

**Comment by JennieCarson** [comment]
i initially started with the detection measurements and manually summarized what i wanted to take from that on excel, but i have ~900 cores to analyze and thought their must be a more efficient way. Can this step be automated?

**Comment by Svidro** [comment]
Something that is a little more complicated that I have done in cases like this (when I did not want to look into sub-classifications) was create a per-cell measurement for positivity in each channel.  The additional measurements would look something like:
Ch1 Positive 1
Ch2 Positive 0
Ch3 Positive 0

Then I would use another putMeasurment command to place a summary measurement in the parent annotation for each value.  For my purposes I would create a single Percent Positive per channel for the annotation, so ended up with 3 new annotation measurements (that would only update when I ran the script).  This way, I could keep re-running the script with different thresholds, though they would only update when the script is run (deleting cells or recreating the cells does not change the annotation measurements until you rerun the script).

**Comment by Svidro** [comment]
You can of course build extra measurements, for example percentage Ch2+Ch3 positive, or whatever you are interested in.

**Comment by petebankhead** [comment]
@JennieCarson if it can be defined precisely, it should be possible to automated it.
Can you say step by step how you calculated the summary value in Excel (assuming you are happy with it)?

**Comment by JennieCarson** [comment]
Ok first i ran this script in Qupath

selectAnnotations();
getDetectionObjects() each {detection -> detection.setName(detection.getParent().getName())}
removeMeasurements(qupath.lib.objects.PathCellObject, "Cell: Channel 1 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 std dev", "Nucleus: Channel 2 max - Smoothed (FWHM 25 µm)", "Cell: Eccentricity", "Cytoplasm: Channel 4 mean", "Nucleus: Eccentricity", "Cell: Channel 3 min", "Cell: Channel 1 min", "Cell: Circularity - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 mean", "Cell: Channel 4 std dev", "Nucleus: Channel 3 range", "Cytoplasm: Channel 4 min - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 sum - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 range - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 range - Smoothed (FWHM 25 µm)", "Nucleus: Circularity - Smoothed (FWHM 25 µm)", "Cell: Channel 3 max", "Cytoplasm: Channel 4 std dev", "Nucleus: Channel 1 min - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 min", "Nucleus: Channel 4 mean - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 3 min", "Nucleus: Max caliper - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 sum", "Nearby detection counts (radius 25 µm)", "Cell: Channel 2 max - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 4 max - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 3 mean", "Cell: Max caliper - Smoothed (FWHM 25 µm)", "Cell: Channel 1 min - Smoothed (FWHM 25 µm)", "Smoothed denominator (local density, FWHM 25 µm)", "Cell: Channel 1 std dev", "Cell: Perimeter - Smoothed (FWHM 25 µm)", "Nucleus/Cell area ratio - Smoothed (FWHM 25 µm)", "Cell: Channel 3 max - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 mean", "Nucleus: Channel 3 max", "Cell: Max caliper", "Nucleus: Channel 3 sum - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 min", "Cytoplasm: Channel 4 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 max - Smoothed (FWHM 25 µm)", "Nucleus: Eccentricity - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 std dev", "Nucleus: Channel 2 sum", "Cell: Channel 3 min - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 3 max", "Cytoplasm: Channel 4 mean - Smoothed (FWHM 25 µm)", "Cell: Channel 1 max", "Cytoplasm: Channel 3 std dev", "Nucleus: Circularity", "Nucleus: Channel 2 mean", "Cell: Channel 2 min - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 range - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 mean - Smoothed (FWHM 25 µm)", "Nucleus: Channel 3 mean - Smoothed (FWHM 25 µm)", "Nucleus: Area", "Nucleus: Channel 4 sum - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 3 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Min caliper", "Cell: Channel 2 min", "Cell: Channel 4 max", "Cell: Channel 2 std dev", "Nucleus: Channel 4 std dev - Smoothed (FWHM 25 µm)", "Cell: Channel 4 min - Smoothed (FWHM 25 µm)", "Nucleus: Min caliper - Smoothed (FWHM 25 µm)", "Nucleus: Perimeter - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 2 max - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 4 min", "Cell: Perimeter", "Cell: Eccentricity - Smoothed (FWHM 25 µm)", "Cell: Channel 1 mean - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 2 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 std dev", "Cell: Channel 4 min", "Cell: Channel 4 max - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 min - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 max - Smoothed (FWHM 25 µm)", "Nucleus: Channel 3 sum", "Nucleus: Channel 3 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 3 min", "Nucleus: Channel 4 range", "Cell: Channel 2 mean - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 min - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 2 std dev", "Nucleus: Channel 4 max - Smoothed (FWHM 25 µm)", "Cell: Channel 4 mean - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 std dev - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 2 mean - Smoothed (FWHM 25 µm)", "Nucleus: Channel 3 range - Smoothed (FWHM 25 µm)", "Cell: Min caliper - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 2 min", "Cytoplasm: Channel 1 max", "Nucleus: Channel 2 max", "Cell: Channel 4 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 min", "Nucleus: Channel 3 std dev", "Cell: Circularity", "Cytoplasm: Channel 3 max - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 3 min - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 sum", "Nucleus: Channel 2 mean - Smoothed (FWHM 25 µm)", "Nucleus: Channel 3 mean", "Cell: Channel 3 std dev", "Cytoplasm: Channel 2 max", "Nucleus: Channel 3 min - Smoothed (FWHM 25 µm)", "Cytoplasm: Channel 1 min", "Nucleus: Channel 4 mean", "Nucleus: Channel 1 max", "Cell: Channel 3 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 range", "Cell: Area - Smoothed (FWHM 25 µm)", "Nucleus: Channel 4 max", "Nucleus: Perimeter", "Cytoplasm: Channel 2 mean", "Cytoplasm: Channel 4 max", "Cytoplasm: Channel 3 mean - Smoothed (FWHM 25 µm)", "Cell: Channel 1 max - Smoothed (FWHM 25 µm)", "Cell: Area", "Nucleus: Max caliper", "Cell: Channel 2 std dev - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 mean - Smoothed (FWHM 25 µm)", "Nucleus: Area - Smoothed (FWHM 25 µm)", "Nucleus: Channel 1 sum - Smoothed (FWHM 25 µm)", "Cell: Channel 2 max", "Nucleus: Channel 3 max - Smoothed (FWHM 25 µm)", "Nucleus/Cell area ratio", "Cytoplasm: Channel 1 std dev", "Cytoplasm: Channel 2 min - Smoothed (FWHM 25 µm)", "Cell: Min caliper", "Cell: Channel 3 mean - Smoothed (FWHM 25 µm)", "Nucleus: Channel 2 range", "Nucleus: Channel 2 min - Smoothed (FWHM 25 µm)");

//create dectection results//
saveDetectionMeasurements('D:IFproject_0_19', )

this resulted in a text file being saved with the core name, then i opened it in excel and deleted all remaining columns until i was left with "class", "cell channel 1 mean"-"cell channel 4 mean"
(I am not actually interested in channel 4, that is my nuclear stain).
i sorted the table by 'class' and separated tumor and stroma cell detections, i counted the number of detections for each class type and and summed the intensities for each channel. i divided the intensity for each channel by the totally number of detections in that class. Just to obtain a simple relative amount of the marker within that tissue type.

**Comment by Svidro** [comment]
Not sure if this is exactly what you want, and don't have a great sample to test it on right now, but: 

```
//This assumes there is only one parent annotation for the cell.  Multiple annotations would require some adjustment.
ch1 = "Cell: Channel 1 mean"
ch2 = "Cell: Channel 2 mean"
def ch1Total = 0
def ch2Total = 0

def stromaCells = getCellObjects().findAll{it.getPathClass() == getPathClass("Stroma")}
def tumorCells = getCellObjects().findAll{it.getPathClass() == getPathClass("Tumor")}
stromaCells.each{
     ch1Total = it.getMeasurementList().getMeasurementValue(ch1)+ch1Total
     ch2Total = it.getMeasurementList().getMeasurementValue(ch2)+ch2Total
}
tumorCells.each{
     ch1Total = it.getMeasurementList().getMeasurementValue(ch1)+ch1Total
     ch2Total = it.getMeasurementList().getMeasurementValue(ch2)+ch2Total
}

//Assuming there is only one annotation object:
annotation = getAnnotationObjects()[0]
annotation.getMeasurementList().putMeasurement("Mean Ch1 Tumor", ch1Total/tumorCells.size)
annotation.getMeasurementList().putMeasurement("Mean Ch2 Tumor", ch2Total/tumorCells.size)

annotation.getMeasurementList().putMeasurement("Mean Ch1 Stroma", ch1Total/stromaCells.size())
annotation.getMeasurementList().putMeasurement("Mean Ch2 Stroma", ch2Total/stromaCells.size)
```
If you combine that with the export script from: https://petebankhead.github.io/qupath/scripting/2018/03/04/script-annotation-export.html

and after that run: https://petebankhead.github.io/qupath/scripting/2018/03/05/script-annotation-results-merge.html

hopefully you will get the output for your entire project.

You will probably want to add in the third channel, and rename some of the values as desired, but hopefully that is enough of a starting point.

**Comment by JennieCarson** [comment]
Thank you so much, this look great!

Jennie
