### ISSUE TITLE
Automated cell counting

### ISSUE THREAD

**Issue by eramel** [qupath/qupath#161]
Hello,
i've just started using the program recenlty and have issues with setting automatic quantification of PDL1 positive cells... or any positive cells in that matter. The wiki didn't help enough, unfortunatelly..

Thank you!!!

**Comment by eramel** [comment]
Thank You for the quick response, will do!

**Comment by petebankhead** [comment]
There's a description of how I've done it in the past in the [Scientific Reports paper](https://www.nature.com/articles/s41598-017-17204-5).

In particular, see the [Supplementary material](https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-017-17204-5/MediaObjects/41598_2017_17204_MOESM1_ESM.pdf) - especially around p 13.

The supplementary material also shows a really elaborate script on p15... but actually it's *much* simpler now:
```groovy
setCellIntensityClassifications('Cell: DAB OD max', 0.35)
```

However, all of that is too complicated If you are will to draw regions of interest, and don't need to bother with separating out epithelial/non-epithelial cells (which may be really difficult and not accurate enough in brightfield images for PD-L1).  In that case, it should be much easier to simply run *Positive cell detection* as described [here](https://github.com/qupath/qupath/wiki/Detecting-objects).  The only thing you should need to chnage is the measurement at the bottom (*Nucleus: DAB OD mean* probably isn't right, *Cell: DAB OD max* or *Cell: DAB OD mean* should do better).

**Comment by petebankhead** [comment]
I'm written a bit about how I would approach this [on the blog](https://petebankhead.github.io/qupath/tips/2018/03/22/setting-positive.html).

I'm curious about other opinions and ideas on this.

**Comment by eramel** [comment]
Great, thank you! Next week I'll look into it at more detail!

Much appreciated!

Egle

Am 23.03.2018 01:48 schrieb "Pete" <notifications@github.com>:
