### ISSUE TITLE
Measurement is not performed over 3 channels

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#164]
Dear All,

I was analyzing a fluorescent tissue with 4 channels and after having performed Tissue detection followed by Watershed Cell detection, I realized that the detection measurement table doesn't contain the intensity features of my 4th channel.
It looks like by default it is done for 3 channels maximum.
Is there a way to by pass this limitation?

Using the Compute intensity features is not an option since it will not distinguished cell from nucleus from cytoplasm but measure on the whole ROI.

I attached a small sample (an ome.tif file) : [Triple_Stained_Tumor_subset_07_small.ome.tif.zip](https://github.com/qupath/qupath/files/1902098/Triple_Stained_Tumor_subset_07_small.ome.tif.zip)

The following has been performed:
`
setImageType('FLUORESCENCE');
runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 4,  "requestedPixelSizeMicrons": 5.0,  "minAreaMicrons": 100000.0,  "maxHoleAreaMicrons": 1000000.0,  "darkBackground": true,  "smoothImage": true,  "medianCleanup": false,  "dilateBoundaries": false,  "smoothCoordinates": false,  "excludeOnBoundary": false,  "singleAnnotation": true}');
selectAnnotations();
runPlugin('qupath.imagej.detect.nuclei.WatershedCellDetection', '{"detectionImageFluorescence": 1,  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 50.0,  "medianRadiusMicrons": 5.0,  "sigmaMicrons": 0.5,  "minAreaMicrons": 100.0,  "maxAreaMicrons": 2000.0,  "threshold": 10.0,  "watershedPostProcess": true,  "cellExpansionMicrons": 10.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');
`

Thanks

**Comment by Svidro** [comment]
In the short term, you might try one of the scripts for my IF assay that I keep putting off writing up!  It should give roughly correct cytoplasmic and nuclear stain **mean only** for every channel.

https://gist.github.com/Svidro/6171d6d24a85539d3af5d417bc928d50#file-step-3-groovy

If you edit the "Add colors" function on line 9, you should be able to add as many channels as QuPath can pick up, though I am not sure how this will mesh with the BioFormats problem.  Might be worth a try though, and it defaults to 4 channels, so it may work for you "as is."

**Comment by bpavie** [comment]
Thanks to both of you!

**Comment by petebankhead** [comment]
This issue is hopefully now resolved in [v0.0.6](https://github.com/qupath/qupath-bioformats-extension/releases).
