### ISSUE TITLE
Javadoc jars are missing from QuPath installations

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1652]
### Describe the bug
Because of some [JavaFX WebView awkwardness](https://github.com/qupath/qupath/issues/1497), we stop merging all the QuPath javadocs into a single jar, in favor of trying to bundle all the relevant jars with the app.

Unfortunately, for v0.6.0-rc1 and v0.6.0-rc2 lots of jars are missing.

### To Reproduce
1. Go to your QuPath installation
2. Look inside `app/docs`
3. Ask yourself "Is that all there is?"
4. Answer yourself "Yes, but there really should be others"

### Expected behavior
Javadoc jars for all the main QuPath classes are included.

### Desktop (please complete the following information):
 - OS: All (presumably; confirmed on macOS and Windows)
 - QuPath Version: v0.6.0-rc1, v0.6.0-rc2

**Comment by alanocallaghan** [comment]
With
```
./gradlew clean jpackage
```

I end up with what I guess is the full list:

```
ij-1.54k-javadoc.jar
    jts-core-1.20.0-javadoc.jar
    qupath-app-0.6.0-SNAPSHOT-javadoc.jar
    qupath-bioimageio-spec-0.1.0-javadoc.jar
    qupath-core-0.6.0-SNAPSHOT-javadoc.jar
    qupath-core-processing-0.6.0-SNAPSHOT-javadoc.jar
    qupath-extension-bioformats-0.6.0-SNAPSHOT-javadoc.jar
    qupath-extension-openslide-0.6.0-SNAPSHOT-javadoc.jar
    qupath-extension-processing-0.6.0-SNAPSHOT-javadoc.jar
    qupath-extension-script-editor-0.6.0-SNAPSHOT-javadoc.jar
    qupath-extension-svg-0.6.0-SNAPSHOT-javadoc.jar
    qupath-fxtras-0.1.5-javadoc.jar
    qupath-gui-fx-0.6.0-SNAPSHOT-javadoc.jar
```

If I add `-P package=installer` then I do wonder "Is this the life?" (by which I mean, I only get the shorter list).

**Comment by petebankhead** [comment]
Ah... that may explain why I was convinced it was fixed - until v0.6.0-rc3 proved it wasn't :(

Seems really bizarre. Strong chance I'm doing truly awful things [here](https://github.com/qupath/qupath/blob/main/qupath-app/build.gradle) but I couldn't figure it out.

**Comment by alanocallaghan** [comment]
I couldn't spot anything in the "package" parts that would change what's included in the output.

I can get that list into the output directory by adding `assembleJavadocs` to the gradle build command. I would've guessed that adding `tasks.jpackage.dependsOn("assembleJavadocs")` in `build.gradle` would work too, but apparently not...

I can update the github action for now, and try to fix the gradle logic after?

**Comment by petebankhead** [comment]
Sounds good to me, thanks!

**Comment by alanocallaghan** [comment]
So I was wrong previously, it's not that -P package="installer" changes anything, it's actually that assembleJavadocs is collecting all of the javadoc jars that are there when it's called, **but** it's called far earlier than gradle claims. If I check with `--console=verbose` or `--dry-run`, I see:

```
> Configure project :qupath-app
Calling JPackage for 'deb'
:qupath-core:compileJava SKIPPED
:qupath-core-processing:compileJava SKIPPED
:qupath-gui-fx:compileJava SKIPPED
:qupath-extension-bioformats:compileJava SKIPPED
:qupath-extension-openslide:compileJava SKIPPED
:qupath-extension-processing:compileJava SKIPPED
:qupath-extension-script-editor:compileJava SKIPPED
:qupath-extension-svg:compileJava SKIPPED
:qupath-app:compileJava SKIPPED
:qupath-app:processResources SKIPPED
:qupath-app:classes SKIPPED
:qupath-app:jar SKIPPED
:qupath-app:javadoc SKIPPED
:qupath-app:javadocJar SKIPPED
:qupath-app:sourcesJar SKIPPED
[processResources, classes, jar, javadoc, javadocJar, sourcesJar for all the other subprojects]
:qupath-app:assembleJavadocs SKIPPED
:qupath-app:generateLicenseReport SKIPPED
:qupath-app:startScripts SKIPPED
:qupath-app:installDist SKIPPED
:qupath-app:jre SKIPPED
:qupath-app:jpackageImage SKIPPED
:qupath-app:jpackage SKIPPED
:qupath-app:jpackageFinalize SKIPPED
```

but if I print out the list of jars that `assembleJavadoc` is copying, it's actually run at the very start, before `:qupath-core:compileJava`!

I guess the solution is to inject the task into the build process by making it a dependency of another task, but I can't figure out how to do that. If I specify for example `tasks.assembleJavadocs.mustRunAfter("jre")`, then I get: 

```
      > Project#afterEvaluate(Closure) on project ':qupath-core' cannot be executed in the current context.
```

which I think is gradle's way of telling me that I've got a circular block on execution.

You can fix all this by running gradle build twice in a row without running clean in between, but obviously that feels a bit suboptimal to say the least.

**Comment by petebankhead** [comment]
Closing because it should have been fixed by rewriting all the build stuff.
