### ISSUE TITLE
Export annotations as segmentation masks

### ISSUE THREAD

**Issue by rcasero** [qupath/qupath#166]
Hi,

Is there a way to export the annotations as an image, were each pixel contains an index for the class assigned to each annotation?

For example, let's have 3 annotation and 2 classes

* Area (AWT) - 14 objects (Tumor)
* Area (AWT) - 8 objects  (Tumor)
* Area (AWT) - 8 objects  (Whitespace)

I'd like to export this as a .tiff with the same size as the input image where the pixels without annotation = 0, pixels within Tumour class = 1, and pixels within Whitespace = 2.

Regards,

Ramon.

**Comment by rcasero** [comment]
Thanks, @petebankhead , looking into it. It looks like what I need.

**Comment by Svidro** [comment]
Neat idea, would love to see the script if you get this working!  I wonder how easily you could add the mask as an extra channel in the .tiff image and keep the original for reference as well?
