### ISSUE TITLE
PixelClassifier not working correct in 0.6rc2

### ISSUE THREAD

**Issue by r100gs** [qupath/qupath#1665]
### Describe the bug
PixelClassifier creates wrong overlays

I made a pixelclassifier in 0.6rc2 which shows me some strange overlay, so I opened the project in 0.51 and it looks quite well. I attached 2 screenshots and the used classifier MG Gewebe2.
If you need some additional information, please contact me.

Best regards,
Stefan

Qupath 0.5
![image](https://github.com/user-attachments/assets/cd747c68-3a3f-409b-a6ec-1ded2e4cc4a5)

Qupath 0.6rc2
![image](https://github.com/user-attachments/assets/3bcbd006-22cc-4b53-a228-0df9df66f465)

[MG Gewebe2.json](https://github.com/user-attachments/files/17199829/MG.Gewebe2.json)

**Comment by petebankhead** [comment]
Thanks @r100gs for reporting this, I could replicate the issue with `CMU-1.svs` and a pixel classifier trained at a very low resolution.

I have proposed a fix at https://github.com/qupath/qupath/pull/1666
