### ISSUE TITLE
Unlocking Multiple Annotations

### ISSUE THREAD

**Issue by dougzy** [qupath/qupath#167]
I had a look through the previous issues and couldn't see the answer to my question.

Is there any way to unlock multiple annotations at once for TMA cores? The "Annotations" option in the right-click context menu when you have a single annotation selected seems to disappear when they are all selected. Is it possible to batch-unlock all the annotations to save time when editing them?

This is primarily to speed up the time I spend with QC, removing vascular channels and artifact. 

Thanks in advance

**Comment by petebankhead** [comment]
This script should do the job to unlock all annotations in the image:
```groovy
getAnnotationObjects().each {
   it.setLocked(false)
}
fireHierarchyUpdate()
```

If you just want to unlock annotations that are currently selected, you can use this:
```groovy
getSelectedObjects().each {
   it.setLocked(false)
}
fireHierarchyUpdate()
```

**Comment by dougzy** [comment]
Thanks Pete! I'll give it a try when I get back to the image analysis computers.

**Comment by dougzy** [comment]
Works perfectly Pete, thanks! 

I'm just getting to grips with scripts, and putting together my workflow.
