### ISSUE TITLE
Choosing separate colours for two polygon sets

### ISSUE THREAD

**Issue by dorankhamis** [qupath/qupath#169]
I'm loading sets of polygons using the following commands:

`def pathObjects = [] `
`def roi = new PolygonROI(x1, y1, -300, 0, 0)`
`pathObjects << new PathDetectionObject(roi)`
`addObjects(pathObjects)`

By default each set is loaded as red (or more likely I have unwittingly selected red). Is it possible to load a second set of polygons with a different colour, so they are distinguishable when shown together?

Thanks in advance!

**Comment by Svidro** [comment]
One way would be to classify each set of polygons, as you can use `pathClass("yourclass").setColor(some_rgbColor)`

as seen here:https://groups.google.com/forum/#!searchin/qupath-users/setColor|sort:date/qupath-users/xfocO2S2kSQ/4FUYMvkSBwAJ

**Comment by dorankhamis** [comment]
Works a treat -- thanks :)
