### ISSUE TITLE
Version 0.4.4 has pixel classifier shows errors and does not process the annotations in the image.

### ISSUE THREAD

**Issue by MukherjeeLabs** [qupath/qupath#1691]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [ ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ ] I've checked for existing GitHub issues describing the same problem

### Desktop (please complete the following information):
 - OS: [e.g. Windows, macOS, Ubuntu...]
 - QuPath Version: [e.g. 0.2.2]

**Comment by alanocallaghan** [comment]
You need to fill out the issue template for us to be able to diagnose the issue. You could also try to download a more recent version of qupath (eg v0.5.1) which may resolve your issue.
