### ISSUE TITLE
Mini viewer isn't updated if the aspect ratio of its parent viewer is "portrait" rather than "landscape"

### ISSUE THREAD

**Issue by zindy** [qupath/qupath#1697]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [ x ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ x ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ x ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ x ] I've checked for existing GitHub issues describing the same problem

### Describe the bug
When an active viewer's height is greater than its width, the content of an associated mini viewer isn't updated if (I suspect) the cursor's Y distance from the top left corner of the viewer is greater than the viewer's width. This suggests a test on `Y > width` instead of `Y > height` somewhere in the code.

### To Reproduce
1. Go to 'View' -> 'Show mini viewer'
2. Open an image (any image)
3. Resize the QuPath window so that the aspect ratio of the active viewer is "portrait" rather than "landscape"
4. Slowly move the cursor from top to bottom and see that the mini viewer isn't updated past a certain point in the Y direction.

### Expected behavior
The expected behaviour is for the mini viewer to update whatever the aspect ratio of the active viewer (fine if the viewer's aspect ratio is "Landscape").

### Screenshots

[Video.webm](https://github.com/user-attachments/assets/40b77483-a9d5-4f0b-b6ce-75b25c1e3f68)

### Desktop (please complete the following information):
 - OS: Windows 10
 - QuPath Version: 0.5.1 and 0.6.0_rc3 (screenshot is of 0.6.0_rc3)

### Additional context
This issue also happens with the Pixel classifier's viewer update.

Cheers,
Egor

**Comment by petebankhead** [comment]
Thanks @zindy should be fixed now!
