### ISSUE TITLE
NullPointerException when closing pixel classifier without classified annotations

### ISSUE THREAD

**Issue by j-hudecek** [qupath/qupath#170]
When I open an image and immediately open pixel classifier without annotating any region and then try to close it I get this exception

    q.lib.gui.helpers.DisplayHelpers - QuPath exception
        java.lang.NullPointerException: null
        at qupath.lib.classifiers.gui.PixelClassifierGUI.destroy(PixelClassifierGUI.java:401)
        at qupath.lib.classifiers.gui.PixelClassifierGUI.lambda$createGUI$0(PixelClassifierGUI.java:152)

it seems like destroy method is the only place which doesn't check that helper is not null before using it

**Comment by petebankhead** [comment]
Thanks. There isn't a pixel classifier here, only on an experimental bit of a branch on my fork... but indeed I get the same error.  Fixed now, good to catch it early :)
