### ISSUE TITLE
GitHub Action (probably) needs updated for new build scripts

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1707]
Since the build scripts were updated to use Kotlin https://github.com/qupath/qupath/pull/1696 I suspect at least [this GitHub action](https://github.com/qupath/qupath/blob/main/.github/workflows/github-release.yml#L26) will need to be updated to request the QuPath version some other way.

@alanocallaghan could/should we store the version somewhere else entirely?

The Kotlin scripts might change again before release...

**Comment by alanocallaghan** [comment]
You can set variables in manually run actions like that, one moment

**Comment by alanocallaghan** [comment]
Any objection to me parameterising the version in the build script? Something like `var qupathVersion = findProperty("qupathVersion") ?: "0.6.0-SNAPSHOT"`

**Comment by petebankhead** [comment]
Don't do it yet - trying to get Gradle to behave properly is continuing to make me very sad.

**Comment by petebankhead** [comment]
@alanocallaghan I think this can now be closed, thanks to https://github.com/qupath/qupath/pull/1712 ?
