### ISSUE TITLE
Linux aarch64 mainline build regression

### ISSUE THREAD

**Issue by cbuscaron** [qupath/qupath#1725]
## Bug report
Gradlew output below:

`> Task :jpackageImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':jpackageImage' (type 'JPackageImageTask').
  - In plugin 'org.beryx.runtime' type 'org.beryx.runtime.JPackageImageTask' property 'jpackageData.resourceDir' specifies directory '/home/alafia/qupath/jpackage/linux-arm64' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
....

BUILD FAILED in 4m 47s
71 actionable tasks: 61 executed, 10 up-to-date`

### Describe the bug
Building from source fails to execute properly on Linux ARM64 platform. 

### To Reproduce
Follow instructions for building from source on ARM64 system:
https://qupath.readthedocs.io/en/latest/docs/reference/building.html

### Expected behavior
Gradlew should be able to execute build successfully.

### Screenshots
![Screenshot from 2024-12-09 10-29-28](https://github.com/user-attachments/assets/afba6207-6b60-4de7-9529-950ecf74e5ac)

### Desktop (please complete the following information):
 - OS: Ubuntu 24.04.1 LTS
 - Kernel: 6.8.0-48-generic
 - Architecture: aarch64
 - QuPath Version: v0.6.0 main source

### Additional context

Hi Pete and team, as discussed filing for tracking purposes. We will dig deeper and try to help resolve.

**Comment by petebankhead** [comment]
Thanks, could you try building from https://github.com/qupath/qupath/pull/1724 please?

**Comment by cbuscaron** [comment]
Hi Pete, thank you. Thought it had already been merged. Same behavior on petebankhead:openslide-blosc branch. 

Build barks at > Task :qupath-gui-fx:javadoc

Full trace at: https://scans.gradle.com/s/2iialc6w2tbjs#infrastructure

**Comment by cbuscaron** [comment]
Fixed and merged by: https://github.com/qupath/qupath/pull/1724
