### ISSUE TITLE
'Split annotations by lines' does not work for z-stacks or time-series if line thickness > 0

### ISSUE THREAD

**Issue by Pascal-bucketbreaker** [qupath/qupath#1729]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [ ] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ ] I've checked for existing GitHub issues describing the same problem

### Describe the bug
The "split annotations by lines"function can't work when not labeling in the first plane.

### To Reproduce
1. Label the first plane of the image.
2. Label the second plane of the image and use the function "split annotations by lines"
3. See error

### Expected behavior
It should work properly as the first plane.

### Screenshots
![e1daf3f1-6003-4480-a138-49976edc0955](https://github.com/user-attachments/assets/5d3ff55f-a4d3-4982-b6d7-6937c8b44939)

### Desktop (please complete the following information):
 - OS: [Windows 10]
 - QuPath Version: [e.g. 0.5.1]

### Additional context
Should I switch the "mark plane" in the UI? Do you have the "mark plane" switching icon?

**Comment by petebankhead** [comment]
Thanks, this should be fixed in the next release of QuPath.
