### ISSUE TITLE
Use command line to control Qupath

### ISSUE THREAD

**Issue by qigongFDA** [qupath/qupath#173]
Hi Officer,

We hope to use **command line** to control Qupath. Could you give me some guide lines or code to achieve following features:
1. open a WSI image
2. View a ROI by given x, y position and magnification
3. Draw annotation or apply an annotation (.xml) file on WSI.

Thank you,
Qi

**Comment by qigongFDA** [comment]
Thank you for your reply. I want to change the QuPath window displaying area (tissue), annotation mark...

I know in the QuPath window, I can you mouse to drag the image and use annotation buttons to draw annotation mark. However, I want to use command line to achieve these, as I want to combine QuPath with our software eeDAP

**Comment by petebankhead** [comment]
I think then you'll need a custom QuPath extension/script to act as the listener and respond to the events being sent.  You might use sockets, or set up a `WatchService` that looks for files being written to a specific directory and acts accordingly.  There is nothing currently built in to QuPath to do what you need and it would need to be developed... but I don't see any reason why it couldn't be done in a script or extension, and therefore it shouldn't require any core changes to the software.

**Comment by Svidro** [comment]
Just linked this in the forums as well, but if you can define how you want to draw the annotation within a text file (groovy script) you might be able to use:
https://groups.google.com/forum/#!searchin/qupath-users/command$20line$20|sort:date/qupath-users/lE5AJDcxA28/JR0UouPLAAAJ
to get started.

The following positions the viewer (although you need to create the viewer first, see the whole file in the link below):
```
viewer.setDownsampleFactor(downsample)
viewer.setCenterPixelLocation(xCoordinate, yCoordinate);
```
from: https://gist.github.com/Svidro/86fb224d69484ae5955631ce68d27054#file-slide-explore-groovy
which was modified from who knows where...  I think Pete's memory monitor.

Exporting simple annotations as coordinate arrays is fairly straightforward (and definitely on the forums somewhere), but I am not as sure about XML formatting...
