### ISSUE TITLE
Using OpenSlide, DICOM J2K wrong color with YBR_ICT and rejects YBR_RCT photometric interpretation

### ISSUE THREAD

**Issue by dclunie** [qupath/qupath#1732]
### Describe the bug
DICOM J2K ICT shows wrong colors and J2K RCT not opened when using OpenSlide rather than BioFormats

### To Reproduce
Set preferences to turn off BioFormats and load files

### Expected behavior
Load and display w. correct colors

### Screenshots
![CMU-1_SVS_DICOM_j2klossy_ScreenShot_WrongColors](https://github.com/user-attachments/assets/d2d10035-b049-4925-ae3c-6947e955479f)

### Desktop (please complete the following information):
 - OS: macOS
 - QuPath Version: QuPath-0.6.0-rc3-x64

### Additional context
Reported to OpenSlide as issue [#103](https://github.com/openslide/openslide/issues/646)

[ICT DICOM Files](https://www.dropbox.com/scl/fo/onomtza9dti57i7evkcst/AF9olYXlL0Wo8DrsIQuNgTA?rlkey=qf55xbeqbqwlrbq371sasevbo)
[RCT DICOM Files](https://www.dropbox.com/scl/fo/hrfs31c3jifptoj77sxmk/AHNQaCrBTZBiqx9Ulgi2Bqs?rlkey=0kyeux4ycvw12flh7hozw8i2p)

**Comment by dclunie** [comment]
Thanks Pete - I was assuming you would keep this open as a reminder to track and incorporate whatever fix OpenSlide makes to resolve this, since the bad behavior is still present (i.e., this is "closed, not fixed"; I guess github does not formally track such subtleties).

**Comment by petebankhead** [comment]
We already get notifications whenever OpenSlide or Bio-Formats are updated, and tend to always update to the latest versions of both unless some critical bug emerges. There are multiple issues with various file formats where a fix is outside our control, and I wouldn't want all of them replicated in our issue list. Across our various repos and the forum, it's already a lot to try to keep up with.

**Comment by alanocallaghan** [comment]
We will be shipping [OpenSlide 4.0.0.6](https://github.com/qupath/qupath/commit/8ddde08f4e51b84a2200a04805da2b7003bf1be8) in the next release candidate and likely the next full release; we're generally trying to stay up-to-date with core libraries like that (as long as it doesn't cause key problems for us)
