### ISSUE TITLE
Maximum Memory (GB) in QuPath Setup can not be adapted

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#175]
Hi Pete, hi all, 

I could not change the maximum allowed GB RAM, QuPath is using. 
Normally it can be changed in the QuPath Setup in the Maximum Memory line. 

It is a windows 7, 16 GB RAM computer. 
Preset is 4 GB RAM. 

I can not increase the number. If I do,  QuPath does just not take the new value. It keeps with 4. 

Did that happen to anyone before?
Best
David

**Comment by Svidro** [comment]
I have never seen this happen, but just to make sure, is it a 64bit version of Win7?

**Comment by petebankhead** [comment]
Are you using QuPath v0.1.2?
Does anything useful appear under *View &rarr; Show log*?

**Comment by DavidMHaumann** [comment]
Yes it is Version v0.1.2. 
I try to get the Log  information. It is not my own computer.

**Comment by petebankhead** [comment]
My best guess is that it's related to user permissions.  But I really don't know - I haven't seen this either.

There's also one obscure tip that might be relevant at the very bottom of [this page](https://github.com/qupath/qupath/wiki/Paths-&-configuration).  Basically, inside the QuPath installation there should be a file `QuPath.cfg`.  You could try opening that in a plain text editor and on a line below [JVMOptions] adding `-Xmx8G` for 8 GB (for example).

I haven't tested this to check it works, but then my memory settings are being read from my preferences so I can't replicate the exact problem.

**Comment by DavidMHaumann** [comment]
thanks for link and idea. 
I personally do not have access to this computer. Pity :)
But what I remember is, that for example the person who installed QuPath deleted the QuPath folder in the user folder. 
As far as I understood the text in the linked page, that seems not to be the reason. But maybe he changed also something else that I did not find. 

In case I find the reason, I will post it here. 

For now, the person in charge seems to prefer just to reinstall and see what happens.

**Comment by DavidMHaumann** [comment]
I did not get any feedback anymore. The issue can be closed.

**Comment by casualcoffeeaddict** [comment]
> My best guess is that it's related to user permissions. But I really don't know - I haven't seen this either.
> 
> There's also one obscure tip that might be relevant at the very bottom of [this page](https://github.com/qupath/qupath/wiki/Paths-&-configuration). Basically, inside the QuPath installation there should be a file `QuPath.cfg`. You could try opening that in a plain text editor and on a line below [JVMOptions] adding `-Xmx8G` for 8 GB (for example).
> 
> I haven't tested this to check it works, but then my memory settings are being read from my preferences so I can't replicate the exact problem.

I had a look in the QuPath.cfg file and reallocated the memory from 50% to 100%. 
This worked. Thanks for the help.
