### ISSUE TITLE
make measurements in one image using objects generated in reference image

### ISSUE THREAD

**Issue by AnthonyOrvedahl** [qupath/qupath#178]
I'm interested in analyzing serial sections for overlap of different IHC stains (or intensity of one stain in different populations). Is it possible to export the objects generated in one file and make measurements within these objects in a second image (with some rotation or adjustments as necessary to make them overlap?). Real world example, I have one slide stained for F4/80, and an adjacent section stained for cleaved caspase 3. I would like to compare the amount of cleaved caspase 3 signal in the F4/80 positive and F4/80 negative cells. Can I use the cell objects generated from the F4/80 image to measure signal in the cleaved caspase 3 image? I looked around the posts and didn't find an answer.

**Comment by Svidro** [comment]
It is possible, but depends on how regular the sequential sections are.  I have seen it done before, but the registration was not done in QuPath.  You can definitely take whole sets of objects and alter their position by translation and rotation, but determining how much of a translation and rotation are needed are somewhat up to you.

In short, I would recommend finding an external solutions to match up your images as perfectly as possible, and then you can copy and paste your detections between images, and use "Add Intensity Features" for whole cell measurements [or a script ](https://gist.github.com/Svidro/68dd668af64ad91b2f76022015dd8a45#file-nuclear-and-cytoplasmic-color-vector-means-groovy) for cytoplams/nuclear measurements to generate values using the new image data.

Further information, though much of it references each other.
https://github.com/qupath/qupath/issues/171
https://github.com/qupath/qupath/issues/162

A couple of posts on image registration in general.
https://groups.google.com/forum/#!searchin/qupath-users/registration%7Csort:date/qupath-users/5-JMvmCKRBo/6NeAyDwsBQAJ
https://groups.google.com/forum/#!searchin/qupath-users/registration%7Csort:date/qupath-users/VLJL6UCXqEk/lvu6LO0bBAAJ
