### ISSUE TITLE
Any way to add area measurement from several bruch tool areas ?

### ISSUE THREAD

**Issue by aliocha67** [qupath/qupath#179]
Hi, 
I would like to quantify the mucus staining (AB-PAS) that appears dark purple on my tissue. So I selected all the regions where I have this dark purple staining using the brush tool, so that I can determine the total area (um2) where I have mucus. Unfortunately, it seems to me that there is no way to have all the areas sum up as a single one. Adding up all the areas manually will be very time consuming,
Thanks a lot for your help !

**Comment by petebankhead** [comment]
There are a few options:
* Get the measurements from *Measure &rarr; Show annotation measurements*, copy them into a spreadsheet and add them up there
* When you're drawing with the *Brush* tool (or the *Wand* might be nicer, if you have good contrast between the purple stain and surroundings), hold down *Shift* to append to an existing annotation - if you're pressing *Shift*, different regions can be discontinuous but still counted as one (similarly, you can hold down *Alt* to use the *Brush* or *Wand* and subtract regions)
* Select all the annotations (either in the *Annotations* pane on the left, or by alt-clicking on them with the *Move* tool selected in the main image), right-click on the image and choose *Annotations &rarr; Merge selected annotations*

Hopefully one of those helps!

**Comment by aliocha67** [comment]
Hi Pete,


That's very helpful, thanks a lot ! It will make my analysis way faster.


Sincerely,


GOEPP Julie
Manager of the Primary Airway Cell Biobank (PACB)
Cystic Fibrosis Translational Research Center (CFTRc)<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>
McGill University - Department of Physiology
McIntyre Building, Room 1012
3655 Promenade Sir William Osler
Montreal – Qc – Canada – H3G 1Y6
(514) 398-4323 (ext #2 or 3)
PACB Website<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>

________________________________
De : Pete <notifications@github.com>
Envoyé : 21 juin 2018 11:23:17
À : qupath/qupath
Cc : Julie Goepp, Ms; Author
Objet : Re: [qupath/qupath] Any way to add area measurement from several bruch tool areas ? (#179)


There are a few options:

  *   Get the measurements from Measure → Show annotation measurements, copy them into a spreadsheet and add them up there
  *   When you're drawing with the Brush tool (or the Wand might be nicer, if you have good contrast between the purple stain and surroundings), hold down Shift to append to an existing annotation - if you're pressing Shift, different regions can be discontinuous but still counted as one (similarly, you can hold down Alt to use the Brush or Wand and subtract regions)
  *   Select all the annotations (either in the Annotations pane on the left, or by alt-clicking on them with the Move tool selected in the main image), right-click on the image and choose Annotations → Merge selected annotations

Hopefully one of those helps!

**Comment by aliocha67** [comment]
Hi Pete,


Now I noticed that when I have a polygon drawn and I want to select an area with the brush within the polygon, it does not let me, or it would increase the size of the polygon if the brush is used at the edges of the polygon. Is there a way to select an area with the brush, within the polygon area ?


Thanks again !


GOEPP Julie
Manager of the Primary Airway Cell Biobank (PACB)
Cystic Fibrosis Translational Research Center (CFTRc)<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>
McGill University - Department of Physiology
McIntyre Building, Room 1012
3655 Promenade Sir William Osler
Montreal – Qc – Canada – H3G 1Y6
(514) 398-4323 (ext #2 or 3)
PACB Website<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>

________________________________
De : Julie Goepp, Ms
Envoyé : 21 juin 2018 11:43:20
À : qupath/qupath; qupath/qupath
Cc : Author
Objet : RE: [qupath/qupath] Any way to add area measurement from several bruch tool areas ? (#179)


Hi Pete,


That's very helpful, thanks a lot ! It will make my analysis way faster.


Sincerely,


GOEPP Julie
Manager of the Primary Airway Cell Biobank (PACB)
Cystic Fibrosis Translational Research Center (CFTRc)<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>
McGill University - Department of Physiology
McIntyre Building, Room 1012
3655 Promenade Sir William Osler
Montreal – Qc – Canada – H3G 1Y6
(514) 398-4323 (ext #2 or 3)
PACB Website<http://mcgill.ca/cftrc/platforms/primary-airway-cell-biobank-pacb>

________________________________
De : Pete <notifications@github.com>
Envoyé : 21 juin 2018 11:23:17
À : qupath/qupath
Cc : Julie Goepp, Ms; Author
Objet : Re: [qupath/qupath] Any way to add area measurement from several bruch tool areas ? (#179)


There are a few options:

  *   Get the measurements from Measure → Show annotation measurements, copy them into a spreadsheet and add them up there
  *   When you're drawing with the Brush tool (or the Wand might be nicer, if you have good contrast between the purple stain and surroundings), hold down Shift to append to an existing annotation - if you're pressing Shift, different regions can be discontinuous but still counted as one (similarly, you can hold down Alt to use the Brush or Wand and subtract regions)
  *   Select all the annotations (either in the Annotations pane on the left, or by alt-clicking on them with the Move tool selected in the main image), right-click on the image and choose Annotations → Merge selected annotations

Hopefully one of those helps!

**Comment by petebankhead** [comment]
If you zoom in more, by default the brush will be effectively smaller and so it's easier to select a region without changing the shape.

Of you change just switch to the *Move* tool to select another region by double-clicking on it, without any risk of changing its shape.  You can toggle between tools by just pressing `M` and `B`.

In general, you might find 'locking' annotations helpful - that helps avoid changing them accidentally, and also allows you to draw _new_ regions inside an existing annotation with the brush.  To do so, select the annotation and then right-click on it, and choose *Annotations &rarr; Lock*.

Finally, if you are doing a lot of painstaking annotations be sure to save regularly (*Ctrl + S*)... or consider trying the beta/pre-release version [here](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html).  Installation is a bit more awkward, but it does provide (limited) undo support along with many other improvements - so may be worth it.

**Comment by Zhengmingxia** [comment]
First, draw a rectangle

Then select the area you want within the rectangle with the “Wand” tool (it will go out of the rectangle)

Next, zoom in the image, hold down the "Alt" key and use the "Brush" tool  in to erase the area outside the rectangle
