### ISSUE TITLE
Setting pixel size

### ISSUE THREAD

**Issue by JennieCarson** [qupath/qupath#180]
Under image properties the pixel width and height are "unknown", i would like to set them both to be 0.5um. Is there an easy way to do this in QuPath directly? or do i have to go through ImageJ?

**Comment by JennieCarson** [comment]
alright thank you for your help!

Jennie

**Comment by DavidMHaumann** [comment]
is it possible to set pixel size by scripting?

**Comment by petebankhead** [comment]
It should be possible to set pixel sizes _for images within a project_ in v0.2.0-m3.

To do this, you'd double-click on the corresponding entry under the 'Image' tab. If you have a selected annotation on the image, this can be used to help set the size (based on area or length).

Note that the pixel size is only maintained within a project (not individual .qpdata files), so for the size to persist a project should be used.

![image](https://user-images.githubusercontent.com/4690904/62522045-c41dca00-b828-11e9-898c-58b76edb8d21.png)

![image](https://user-images.githubusercontent.com/4690904/62522059-cb44d800-b828-11e9-9572-3f4e24ee6a52.png)
