### ISSUE TITLE
Hot Spot Analysis for IF

### ISSUE THREAD

**Issue by JennieCarson** [qupath/qupath#181]
I would like to create a Hot Spot analyses of my IF images that i have classified in QuPath. i have never done this before and was hoping for some insight into what might be the best way to go about this. 

Thank you,
Jennie

**Comment by Svidro** [comment]
Not entirely sure what you are looking at or want to accomplish, but maybe these will help:
https://github.com/qupath/qupath/issues/126
Using subcellular detections, and expanding on the current classification setup:
https://github.com/qupath/qupath/issues/146

In general, it sounds like you will want to use some sort of subcellular detection, and then classify based on the number or total intensity of subcellular objects?

**Comment by JennieCarson** [comment]
i need to analyze tissue spatially. I have certain cells classified as immune and then large regions classified as either tumor or stroma, with the immune cells peppered throughout the core. the tumor tissue is stained for many different markers and i would like to create a hot spot analysis of where the immune cells are in space with relation hot spots of various other makers.

**Comment by Svidro** [comment]
Oh.  I think I see... though I am not certain of how easy that will be.  One thing to look into is smoothed measurements.  _Analyze->Calculate features->Add smoothed features_

As long as your hotspots are roughly the same size, you should be able to get a smoothed measurement that peaks in small subsets of cells at the "center" of your hotspot.  Unfortunately, I am not sure how to proceed from there without some kind of data.  I am thinking you could perform a cluster analysis in R based on the XY coordinates.. or maybe a classifier.

I am pretty sure there is no built in way for QuPath to handle this, but it sounds like the sort of thing that could definitely be done with scripting.

Without scripting, you could do the _Add smoothed features_, and then _Measure->Show measurement maps_ and select one of your smoothed features (you may be able to do this without the smoothing, depending on your data/images).  You should be able to visually find the hotspots, and could then use the "Points tool" to mark the center of each hot spot manually.  Adding a different classification of spot for each type of marker would get you a set of points of various classifications, which you could then use to compare distances.

If your images are fluorescent, and you can split the channels, you might be able to run simple tissue detection on each individual channel to get centroid coordinates for hotspots (sufficient gaussian blur).  Also, if you were to simplify the question to "how many immune cells are within X um of my hotspot" you could generate the annotation, import it, then _Object->Expand Annotations_ and count how many immune cells are within that expanded annotation (which could all be automated).  It would no doubt be a bit trickier than that if you are dealing with overlapping hotspots.

There may be other ways as well, but that's be best first stab going in blind.

**Comment by JennieCarson** [comment]
ok thank you for you help!!

**Comment by Svidro** [comment]
I'll also add this, which I suspect uses QuPath to identify particular types of cells, then exports the coordinates+class.  It then uses a separate program/method for the hotspot analysis.  See the section titled "Hotspot identification" (though I have not read the paper thoroughly).

https://www.sciencedirect.com/science/article/pii/S0092867418304458?via%3Dihub

**Comment by Svidro** [comment]
I had forgotten about this, but someone [recently brought up](https://github.com/qupath/qupath/issues/185) something that could be used for hot spot analysis.  

QuPath does actually have a built in way of detecting what I think you are looking for, assuming you have cells that are classified.  If you are still working on this, you might be able to use the Delaunay clustering (with both boxes checked), to identify areas where you have clusters of cells that are the same class.  You could then use the "Cluster size" measurement to perform further classification and identify the hotspot, possibly by creating a list of all of the cell XY coordinates, and then taking the four outermost coordinates to form a "box" around your cluster.  That box would have a centroid of it's own which could be used for comparison with other hot spots, either further clustering of hot spots or distance analysis... etc.

![cluster analysis](https://user-images.githubusercontent.com/23145209/42777909-4a01c2ac-88f0-11e8-97ed-3b7176dcfef0.JPG)

Just a thought.
