### ISSUE TITLE
How to export the calculated features?

### ISSUE THREAD

**Issue by Zhouzhiling** [qupath/qupath#183]
For example, in the menu analyze→Calculate features→add intensity features, after the feature finishes calculating, how can I export it out into local files? Thank you so much!

**Comment by petebankhead** [comment]
It depends what kind of object you added the features to - but you can create measurement tables with _Measure &rarr; Show annotation measurements_ or _Measure &rarr; Show detection measurements_ and save the results from either table.

See also [Exporting results](https://github.com/qupath/qupath/wiki/Exporting-results) on the wiki.

**Comment by Zhouzhiling** [comment]
Got it. Thank you so much!
