### ISSUE TITLE
Channel Names Not Showing Channel ID in Brightness Form for OME Tiff

### ISSUE THREAD

**Issue by 2jour** [qupath/qupath#186]
File format: OME tiff
Extension : bioformats extension

Hi there,

We are using the bioformats extension to load our file. Our Channnel IDs in our OME Tiffs are protein markers.

When we look at the brightness form, we only see channel 1, channel 2 etc 

Is there any way to display the channel id instead of channel 1 , channel 2 etc etc :)?

Thanks

**Comment by petebankhead** [comment]
Currently no, but I agree this is needed. It was somewhere in the unwritten feature request list in my head, but I have flagged it as an enhancement here as that's probably a more useful place for it to be.

**Comment by 2jour** [comment]
Thanks :)

**Comment by petebankhead** [comment]
If you try the latest [Bio-Formats extension](https://github.com/qupath/qupath-bioformats-extension) you can get the channel names by scripting.

And if you combine it with my QuPath fork, you can see them in the _Brightness/Contrast_ window.

There are more details [here](https://petebankhead.github.io/qupath/2018/08/03/bioformats-update.html#support-for-32-bit-multichannel-images)

**Comment by petebankhead** [comment]
Channel names are included now in the v0.2.0 milestone releases.
