### ISSUE TITLE
TMA Dearrayer creating 1 object and not on any core

### ISSUE THREAD

**Issue by asasama12** [qupath/qupath#189]
When I run the TMA dearrayer on an H+E image of my TMA slide, it does not pick up any of the cores.  Any ideas for how to get it working? I've used qupath on a different computer/install of qupath and it had no problem with this file.  

![capture](https://user-images.githubusercontent.com/41748563/43268852-3dcb26e4-90b7-11e8-892d-890303bb0414.PNG)

**Comment by petebankhead** [comment]
The fact that the entire field of view isn't scanned, and the 'missing' bit is shown as black', is likely playing havoc with QuPath's image type estimation and also the automated thresholds in the dearrayer.

Did you use it with the same image?  What is the file format in this case?
Under the 'Image' tab, is the 'Image type' correct (i.e. Brightfield H&E), or is it something else?

**Comment by asasama12** [comment]
I did use the same file, however when I opened it previously, the different magnification scans showed up in the "Image List" and I chose the 40X image and used the Dearrayer on it.  On this computer, it doesn't show any images on the "Image List."  The file type is .scn  I corrected the Image type to H&E but it did not solve the issue

**Comment by petebankhead** [comment]
I suspect that one computer is opening the image with OpenSlide, and the other with Bio-Formats.
My guess is that this one (with the black background) is using Bio-Formats.

If you have a recent version of the Bio-Formats extension installed, you can force it not to be used (or always to be used) for the `.scn` files - there are instructions at the bottom of https://github.com/qupath/qupath-bioformats-extension

**Comment by asasama12** [comment]
That worked!  Thank you so much
