### ISSUE TITLE
java api

### ISSUE THREAD

**Issue by situbimo** [qupath/qupath#192]
How should I call the "java api" interface of qupath to identify and classify pathological images?

**Comment by petebankhead** [comment]
This question is too broad to answer well... QuPath is primarily a desktop application, which you can use to analyze whole slide images - interactively and by scripting. Once you've established what you want to do, you can batch process it.

To make QuPath accessible from IntelliJ, for Groovy scripting or potentially other reasons, see https://github.com/qupath/qupath/wiki/Advanced-scripting-with-IntelliJ

If this doesn't answer your question, please describe more fully what exactly you want to do.
