### ISSUE TITLE
Intensity measurements limited to first 8 channels of IF images

### ISSUE THREAD

**Issue by adrenalizer** [qupath/qupath#197]
Hi,

QuPath is brilliant and the recent updates for IF images have been very helpful - so thanks for all the work you've put into it.

I am now trying to get mean intensity values from manually annotated ROIs within multiplex IF images with 11 channels (with hopes to go up to 20-30 channels in the future). Unfortunately, it seems that QuPath can currently only provide mean intensity measurements for a maximum of 8 channels at the moment. Is it possible to overcome this limit?

I tried to do this using the following Groovy script:

`setImageType('FLUORESCENCE');
runPlugin('qupath.lib.algorithms.IntensityFeaturesPlugin', '{"downsample": 1.0,  "region": "ROI",  "tileSizePixels": 200.0,  "channel1": true,  "channel2": true,  "channel3": true,  "channel4": true,  "channel5": true,  "channel6": true,  "channel7": true,  "channel8": true,  "channel9": true,  "channel10": true,  "channel11": true,  "doMean": true,  "doStdDev": false,  "doMinMax": false,  "doMedian": false,  "doHaralick": false,  "haralickMin": NaN,  "haralickMax": NaN,  "haralickDistance": 1,  "haralickBins": 32}');`

This generated intensity measurements for the first 8 channels. However, I get the following error:

> WARN: Unable to set parameter channel9 with value true
> WARN: Unable to set parameter channel10 with value true
> WARN: Unable to set parameter channel11 with value true
> WARN: Unable to set parameter haralickMin with value NaN
> WARN: Unable to set parameter haralickMax with value NaN

A simple workaround would have been to switch the first few channels to "false" and the remaining channels to "true" in the above script. Sadly that didn't work either.

Would be grateful for your help with this.

Cheers,
Ashwin

**Comment by imagejan** [comment]
The measurement parameters are hard-coded here:

https://github.com/qupath/qupath/blob/dde631fded0192550420e2d541ee6f91b7bd4dc8/qupath-core-processing-awt/src/main/java/qupath/lib/algorithms/IntensityFeaturesPlugin.java#L126-L133

**Comment by adrenalizer** [comment]
That's fantastic, thanks - that did the trick!

Ashwin

**Comment by petebankhead** [comment]
> The measurement parameters are hard-coded

I'm afraid so, I'd forgotten about that... The workaround (not changing the code itself) would be to script it to use ImageJ, but if it's already solved for you that's good.

While I'm here, I've just added [three posts on my blog](https://petebankhead.github.io) that may be relevant... especially as your number of channels increases.

**Comment by petebankhead** [comment]
Remembered this a few days ago and tried to get the fix into the new milestone release: https://github.com/qupath/qupath/commit/45820e625872b14197e4f784dbb71a37e96ef17d

Closing this issue as it should now be fixed, but please reopen if you find it is not.
