### ISSUE TITLE
Mirror annotations

### ISSUE THREAD

**Issue by nienketegr** [qupath/qupath#199]
I am using annotations to select a tumor area and use the same ones on consecutive tissue slides to select the same tumor area. But some of my files are mirrored/flipped. Is there a way to flip/mirror an image or annotation in Qupath so I can still transfer the annotation and use it on the right area of the slide/tissue?

Best regards,
Nienke

**Comment by Svidro** [comment]
There is a 90 degree rotate image function in View, but from the sounds of it, you should either modify the image itself (QuPath does not modify or re-save images as far as I know) using the original software, or modify your data file by flipping your annotations.

For example, CZI files can be flipped and mirrored in Zen Lite.  I am not as familiar with other file formats at the moment.

**Comment by nienketegr** [comment]
Ok, thank you! And how about flipping annotations in Qupath, would that be possible?

**Comment by Svidro** [comment]
It is, though I think it would need to be scripted.  Something like find centroid for a given annotation, subtract 2*distance from Y and X coordinates independently, rebuild the ROI with the new coordinates.  It may be more or less complicated if you have an AWT/"annotation with holes or separate pieces" where the points aren't kept in a simple list.  Pete would probably know more, and I don't have a script ready built to do that, sorry :(

**Comment by petebankhead** [comment]
There's a _Objects &rarr; Rotate annotation_ command for interactively rotating annotations.

I've written a script that can also flip annotations - and which could be modified to apply any [AffineTransform](https://docs.oracle.com/javase/8/docs/api/java/awt/geom/AffineTransform.html):

https://gist.github.com/petebankhead/2cab4873e001ab42e03c864666284c5f

**Comment by nienketegr** [comment]
Yes it works! Thank you both!
