### ISSUE TITLE
Export image region using script.

### ISSUE THREAD

**Issue by starodekar1** [qupath/qupath#200]
Hi,

I want to save the image region using script (Jython ) in default script editor. I can do this operation manually by File -> Export Image Region. Can you suggest me something to automate this operation.

Thanks.

**Comment by petebankhead** [comment]
You could try this script as a starting point: https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d

Or the first script here: https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html

Both are written in Groovy, but I guess could be adapted for Jython.

If these don't do what you need, the answer will depend on the details of what you want to export and for what purpose, e.g.
* a downsampled version of the whole image, a selected annotation, or all annotations in the image?
* an RGB or multichannel fluorescence image; if fluorescence, then just a snapshot (appearance) or the original pixel values?
* how should the image files for each region be named?
* do you need the overlay (objects) painted on top or not?

**Comment by starodekar1** [comment]
Thanks for the quick reply.

I just want to run the simple tissue detection plugin and then save the result.

`runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 0,  "requestedDownsample": 5.0,  "minAreaPixels": 100000.0,  "maxHoleAreaPixels": 5000.0,  "darkBackground": true,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false,  "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}');`

This is the automated script for my operation.

**Comment by petebankhead** [comment]
Then I think the first script I posted should work.

**Comment by starodekar1** [comment]
yes it is a Fluorescence image. 

I am getting **Error at line 51: Width (0) and height (0) cannot be <= 0**. I checked the width and height with getWidth() and getHeight() functions and its not 0.

**Comment by petebankhead** [comment]
Note that there's a `requestedPixelSize` used to control the resolution - it's set for a whole slide image (with some pretty aggressive downsampling...).

You can either change the `requestedPixelSize` or `downsample`, where it is used later in the script.

**Comment by starodekar1** [comment]
It works perfectly.
Thanks for the help.
