### ISSUE TITLE
Panning with mouse blocked after "create full image annotation" in jpg with FL image content

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#201]
Hi Pete, 

if I create a full image annotation on the jpg image containing FL data of a czi file, panning with mouse is suddenly blocked. It is still possivle with the arrows. 

The czi was a 14 bit image - the fl image if 8 bit. Maybe this is any important information. 

Did that happen before?

**Comment by petebankhead** [comment]
It's blocked because QuPath wants to move the rectangle, but there's nowhere to move it.

Right-click on the annotation and set it to be locked, then it will work again.

**Comment by DavidMHaumann** [comment]
yes. true. thanks a lot for this fast response.
