### ISSUE TITLE
Best way to save core images of flourescent chanels

### ISSUE THREAD

**Issue by rawatenator** [qupath/qupath#202]
I'd like some help to modify the code from my previous question(https://github.com/qupath/qupath/issues/97) so that I can save each core as a multi-channel TIFF (ideal, or otherwise a tiff/png of each individual channel separately). I've tried this: and it's just not saving the files.

```

import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath(PROJECT_BASE_DIR, 'cores')
//outdir="C:/Users/VS120/Desktop/Qupath_Sample_images/"

// Create output directory inside the project
//def dirOutput = buildFilePath(outdir, 'cores/')

mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed   
    if (Thread.currentThread().isInterrupted())
        break
    // Write the image
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, core.getROI()))
    print(img);
    
    ImageIO.write(img, 'TIFF', new File(dirOutput, core.getName() + '.tiff'));
    print('Done!')
    
}

```

**Comment by petebankhead** [comment]
Yes, `ImageIO` can't write the images you need.

You can try this, which will use ImageJ instead:
```groovy
import ij.IJ
import qupath.imagej.images.servers.ImagePlusServerBuilder
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath(PROJECT_BASE_DIR, 'cores')
mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(server)
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed
    if (Thread.currentThread().isInterrupted())
        break
    // Request ImagePlus
    def imp = server.readImagePlusRegion(RegionRequest.createInstance(path, downsample, core.getROI())).getImage()
    IJ.save(imp, new File(dirOutput, core.getName() + '.tif').getAbsolutePath())
}
print('Done!')
```

**Comment by rawatenator** [comment]
Is there a way to modify the script so that it saves a tif/png/jpeg image that hs the same colors that I'm seeing on the screen in Qupath?

**Comment by petebankhead** [comment]
You can try this to bring across the original colors from QuPath, and use them to set the lookup tables for each channel of the image in ImageJ.  But I'm afraid it doesn't bring over any customizations you might have made with the Brightness/Contrast tool.

```groovy
import ij.CompositeImage
import ij.IJ
import ij.process.LUT
import qupath.imagej.images.servers.ImagePlusServerBuilder
import qupath.lib.awt.color.ColorToolsAwt
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath(PROJECT_BASE_DIR, 'cores')
mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(server)
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed
    if (Thread.currentThread().isInterrupted())
        break
    // Request ImagePlus
    def imp = server.readImagePlusRegion(RegionRequest.createInstance(path, downsample, core.getROI())).getImage()
    if (!imp.isComposite()) {
        def composite = new CompositeImage(imp, CompositeImage.COMPOSITE)
        for (int c = 0; c < server.nChannels(); c++)
            composite.setChannelLut(
                    LUT.createLutFromColor(
                            ColorToolsAwt.getCachedColor(server.getDefaultChannelColor(c))), c+1)
        imp = composite
    }
    IJ.save(imp, new File(dirOutput, core.getName() + '.tiff').getAbsolutePath())
}
print('Done!')
```

**Comment by petebankhead** [comment]
You can also try this one, which aims to bring over the brightness/contrast settings and channel colors from the current image viewer:

```groovy
import ij.CompositeImage
import ij.IJ
import ij.process.LUT
import qupath.imagej.images.servers.ImagePlusServerBuilder
import qupath.lib.awt.color.ColorToolsAwt
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QPEx

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath(PROJECT_BASE_DIR, 'cores')
mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(server)
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed
    if (Thread.currentThread().isInterrupted())
        break
    // Request ImagePlus
    def imp = server.readImagePlusRegion(RegionRequest.createInstance(path, downsample, core.getROI())).getImage()
    if (!imp.isComposite()) {
        def display = QPEx.getCurrentViewer().getImageDisplay()
        def composite = new CompositeImage(imp, CompositeImage.COMPOSITE)
        for (int c = 0; c < server.nChannels(); c++) {
            def channel = display.getAvailableChannels().get(c)
            def color = ColorToolsAwt.getCachedColor(channel.getColor())
            composite.setChannelLut(
                    LUT.createLutFromColor(color), c+1)
            composite.setC(c+1)
            composite.setDisplayRange(channel.getMinDisplay(), channel.getMaxDisplay())
        }
        composite.setC(1)
        imp = composite
    }
    IJ.save(imp, new File(dirOutput, core.getName() + '.tiff').getAbsolutePath())
}
print('Done!')
```

**Comment by rawatenator** [comment]
thanks Pete! very helpful. But actually, I'm just trying to export RGB Jpegs/PNGs.

**Comment by rawatenator** [comment]
Feel like there needs tob e one more command that goes from ompoiste image to an RGB image

**Comment by petebankhead** [comment]
Try adding
```groovy
imp = imp.flatten()
```
before `IJ.save`.

I haven't tested it here, but 'flatten' is the ImageJ command that converts to RGB.  But if you change the extension from `.tiff` to `.png` you might find that it flattens anyway.

**Comment by Cocomolch4000** [comment]
@petebankhead  How does one get the code, mentioned above, (https://github.com/qupath/qupath/issues/202#issuecomment-415312268 where the pictures with specific contrast/brightness settings are exported) to work in version 0.2.0-m2?
It has some import failures in my version and when I am deleting all imports and click on "include default bindings" it also does not work. Can you help or do I have to use an older/newer version?

**Comment by petebankhead** [comment]
It should be something like this:
```groovy
import ij.CompositeImage
import ij.IJ
import ij.ImagePlus
import ij.process.LUT
import qupath.imagej.tools.IJTools
import qupath.lib.color.ColorToolsAwt
import qupath.lib.projects.Projects
import qupath.lib.regions.RegionRequest
import static qupath.lib.gui.scripting.QPEx.*

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def project = getProject()
def dirOutput = buildFilePath(Projects.getBaseDirectory(project).getAbsolutePath(), 'cores')
mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed
    if (Thread.currentThread().isInterrupted())
        break
    // Request ImagePlus
    def imp = IJTools.convertToImagePlus(server, RegionRequest.createInstance(path, downsample, core.getROI())).getImage() as ImagePlus
    if (!imp.isComposite()) {
        def display = getCurrentViewer().getImageDisplay()
        def composite = new CompositeImage(imp, CompositeImage.COMPOSITE)
        for (int c = 0; c < server.nChannels(); c++) {
            def channel = display.availableChannels().get(c)
            def color = ColorToolsAwt.getCachedColor(channel.getColor())
            composite.setChannelLut(
                    LUT.createLutFromColor(color), c+1)
            composite.setC(c+1)
            composite.setDisplayRange(channel.getMinDisplay(), channel.getMaxDisplay())
        }
        composite.setC(1)
        imp = composite
    }
    IJ.save(imp, new File(dirOutput, core.getName() + '.tiff').getAbsolutePath())
}
print('Done!')
```
I'm afraid I haven't had time to track down an appropriate image and check it works; it doesn't work for brightfield but hopefully does with fluorescence.

(I'm trying to move away from GitHub for questions to use it properly as an issue tracker, so https://forum.image.sc/tags/qupath would be best for following up)

**Comment by Cocomolch4000** [comment]
@petebankhead Thanks a lot! Unfortunately, it does not work out (Startup error below).  Shall I then move this question to the new qupath forum? One more question: Is there a documentation of the qupath functions and classes?

```ERROR: Error: startup failed:
Script1.groovy: 7: unable to resolve class qupath.lib.color.ColorToolsAwt
 @ line 7, column 1.
   import qupath.lib.color.ColorToolsAwt
   ^

Script1.groovy: 8: unable to resolve class qupath.lib.projects.Projects
 @ line 8, column 1.
   import qupath.lib.projects.Projects
   ^

Script1.groovy: 6: unable to resolve class qupath.imagej.tools.IJTools
 @ line 6, column 1.
   import qupath.imagej.tools.IJTools
   ^

3 errors
`

**Comment by petebankhead** [comment]
Sorry, I should have said I tested it only with v0.2.0-m3 - where it works for brightfield only if I disable the brightness/contrast thing (which is where I'm only guessing it should work for fluorescence...). My guess/hope is that that is the source of the error if you were using v0.2.0-m2.

I've been working towards adding javadocs for all the public methods in QuPath and have written many hundreds so far, but still have many more to go... I'm afraid it will take a while.

I try to answer questions about the milestones as they change, but I'm afraid I can't really support the older ones (not least because it's hard to keep all the changes in my head, and set up a scripting environment for each). I'd really advise to switch from m2 as soon as feasible:
https://forum.image.sc/t/third-milestone-on-the-path-to-qupath-v0-2-0/27953/15

**Comment by Cocomolch4000** [comment]
@petebankhead Thanks! Will check it with version 0.2.-m3! So, I am guessing that there is yet no solution for brightfield images to save the brightness/contrast settings? (I always export them by hand by sending one TMA core to imageJ and save it there.)
Wow, looking forward to that docu!
Okay, will switch then! Thanks again for your answers!

**Comment by petebankhead** [comment]
Ah, I never really tend to change the brightness/contrast settings for brightfield images and I don't recall if this has been requested before... is this something you do routinely?

In the latest milestone version you can at least send multiple regions to ImageJ in one go (just select multiple cores before running the command to extract them).... although it does result in a whole lot of images open in ImageJ, it might help a bit and perhaps the actual adjusting/saving could be done in a macro.

**Comment by Cocomolch4000** [comment]
@petebankhead  Yes, what you describe for version m3 sounds very nice, because as you said, I have a macro for saving images in imageJ and if I can send all cores at one time it saves me a lot of time I think!
