### ISSUE TITLE
Sorting annotations

### ISSUE THREAD

**Issue by superjs5** [qupath/qupath#203]
In my QuPath file I have a lot of annotations. For future analysis it would be easier if the annotations could be sorted by name. However, I have not yet found this option in QuPath. Is it possible to sort the annotations?

Thank you in advance.

**Comment by petebankhead** [comment]
If you have a measurement table of annotations, you can click on the column heading (e.g. 'Name') to sort it.  Then you can also select annotations in the table and have them selected in the image.

If this doesn't do what you need, can you say more about where the annotations should be displayed sorted, and how this would help future analysis?

**Comment by superjs5** [comment]
Thank you for your quick reply. To answer your question. As I will have 184 annotations, sorting by name would make it a lot easier to find the annotations, select them in the main window, and to discuss those particular annotations with a colleague. However, I didn't think of the annotations table. Thank you for this solution.
