### ISSUE TITLE
CPU & GPU both used max. 35 % in training of Classifiers

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#206]
Hi Pete, 

QuPath never uses more than 35% of both, CPU and GPU if I train classifiers on e.g. superpixels with random forest. 

Do you know if it is possible to enable it for more?  
![grafik](https://user-images.githubusercontent.com/16352785/44622725-ca888f80-a8be-11e8-9e82-e1577cad76e9.png)

I train classifiers with far beyond 100.000 training objects which takes really a lot of time image by image and it would be helpful to speed it up by using more of the CPU and GPU. 

Best
David

**Comment by petebankhead** [comment]
I'm afraid not.  QuPath give access to a range of classifiers from OpenCV and (optionally, with the extension installed) Weka - any parallelization would need to happen in those libraries, and depending on the algorithm might not help much.  QuPath is also designed to make it possible to add new classifiers, so potentially newer, faster ones might be added one day... if someone makes them.

I'd suggest trying to reduce your number of training objects and/or features.  In the case of cells (for example), neighboring cells often have very similar features and including many similar cells probably doesn't help much... and it may even cause harm, by requiring even more training objects to learn something else.

There are discussions about training classifiers [here](https://groups.google.com/d/msg/qupath-users/MpsK44RCZcE/xE3nX4aJCAAJ) and [here](https://groups.google.com/d/msg/qupath-users/qM_JtrEW1dI/Jeb5iMRnAQAJ).  I also discuss a bit about improving the results when using the same training objects but fewer features [here](https://youtu.be/uj28wJSmntU?list=PL4ta8RxZklWk_O_Z7K0bZlhmHtaH73vlh).

I do plan to make some changes that should improve how quickly an existing classifier is reloaded (even if it does not change the training time), described [here](https://groups.google.com/d/msg/qupath-users/EkQNKOqUBVE/UqB0tcL8AQAJ).  But it's a fairly substantial change and a matter of finding enough time...
