### ISSUE TITLE
Corrupt file .qpdata extension

### ISSUE THREAD

**Issue by laavaa** [qupath/qupath#207]
After saving several files to my external disk there is one file (the one which cost me most hours of course....) that doesn't open anymore. The others file can be opened without any problem. Seems it is a corrupt file. Can anybody help me to open it? 

My version 0.1.2.
Operating system MacOS 10.13.6
There are no logs in QuPath that report a problem. 

Thanks!
Lauretta

**Comment by petebankhead** [comment]
Oh dear.... There are a few relevant discussions, hopefully one of them can help (although the answers are pretty similar):
* https://github.com/qupath/qupath/issues/58
* https://groups.google.com/forum/#!msg/qupath-users/CHhLIMHHzvo/ip9pm6hhEQAJ
* https://groups.google.com/forum/#!topic/qupath-users/sYzchFq-Y60

If you can find any way to replicate this, please let me know.  I haven't seen the problem myself (also using MacOS) for a very long time, and I don't recall seeing it at all with v0.1.2... I wonder if the external drive part significant?

**Comment by petebankhead** [comment]
Closed due to lack of activity & unable to reproduce. Hopefully resolved somewhere amidst all the changes since this was reported...
