### ISSUE TITLE
Scripting Classification

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#208]
I know it's possible to use a script load a classifier and apply it to detections, but is it possible to script the creation of a detection classifier, based on some existing annotations? I realize that this is a little off-piste, but it would be nice to automate this when you want to do slide-level classifications. 
My look through the code base suggests the answer is no, since the ClassifierCommand requires user input. 
Any workarounds?
Apologies if someone has already asked something similar, didn't find anything with a few searches. 

Best Regards,
Colin

**Comment by petebankhead** [comment]
It should be possible - the classifier interface is fairly simple, and once you've got a classifier you just need to update it.  See https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-processing/src/main/java/qupath/lib/classifiers/PathObjectClassifier.java#L69

The default is the [RTreesClassifier](https://github.com/qupath/qupath/blob/v0.1.2/qupath-processing-opencv/src/main/java/qupath/opencv/classify/RTreesClassifier.java), and there are some useful helper methods in the [PathClassificationLabellingHelper](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-processing/src/main/java/qupath/lib/classifiers/PathClassificationLabellingHelper.java) class.

**Comment by ClnSchlssr** [comment]
Ah Excellent. 
I clearly didn't look very deep... The ease of doing so many things via plugins seems to have made me lazy,
Thanks for putting me in the right direction.

**Comment by Svidro** [comment]
If you get it working I would be curious to see a sample script.  
For clarity since I have not played with this...  updateClassifier will add the input list of objects to the current list of objects from all previous slides?  Or restart the classifier with only the current slide input, but same choice of classifier and variables?
