### ISSUE TITLE
Cannot change colour of dots in points tool.

### ISSUE THREAD

**Issue by ksirinuk** [qupath/qupath#209]
It doesn't matter how you change the colour of the points, it is always yellow. Does anyone know a fix?

**Comment by petebankhead** [comment]
It's yellow to indicate that those points are selected.

If you select some other object (e.g. a rectangle, or a different set of points) then the color you set should be visible.

Under _Edit &rarr; Preferences_ you can also turn off the _Use selected color_ option if you'd rather have the selected points indicated by a rectangle around them, not a different color.

**Comment by ksirinuk** [comment]
Thank you Pete. That's clear.
