### ISSUE TITLE
Export region

### ISSUE THREAD

**Issue by HaisenWang** [qupath/qupath#212]
I have made some annotations in my project. But now I need to export those regions at one time . How can I do this? Sorry to bother you and thank you if you can help.

**Comment by petebankhead** [comment]
What do you mean by export, i.e. in what form?  Export images corresponding to the annotations?  Export the coordinates of the annotations?

**Comment by HaisenWang** [comment]
I mean I want to get the annotation region and save it as a picture.

**Comment by petebankhead** [comment]
You could try the first script here: https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html
(Or [here's](https://gist.githubusercontent.com/petebankhead/0b14beef131312042686c01056104b85/raw/8223a934f10761a885ef6cab20d71f786029bb84/QuPath-Export%20binary%20masks.groovy) a direct link to the script only.)

It should export the annotated regions, along with a corresponding binary image... so if you're not interested in the binary image you can just delete it.

It needs to be run inside a project, and the images are exported to a subdirectory inside the project called 'masks'.
