### ISSUE TITLE
About Storage path

### ISSUE THREAD

**Issue by HaisenWang** [qupath/qupath#215]
I have made  a qupath project , added many images and  made a lot annotations. But now I move the images to anothor storage disk.  How can I change the path the project stored? I mean how can I open the project and keep the annotations when the path of images changes?

**Comment by Svidro** [comment]
There are a few options: https://github.com/qupath/qupath/issues/114
If you store the images within the project folder, you should be able to move the folder anywhere and reopen it.

**Comment by Tkilvaer** [comment]
Hi
I had this same question. If the relative folder assossiations are always
the same. Eg.

/images/imageprojects/
/projects/someproject/projectfolder/

Or something similar. The solution in the link works wonderful. It requires
that you modify some files.

https://groups.google.com/forum/#!searchin/qupath-users/kilvaer%7Csort:date/qupath-users/y5qk2BAgLvU/gO9bM8evCQAJ

Den tir. 11. sep. 2018 kl. 07:40 skrev Svidro <notifications@github.com>:

**Comment by HaisenWang** [comment]
Thanks for your help. I have solved the  problem.
