### ISSUE TITLE
Immunohistochemistry of brain tissue- subcellular level

### ISSUE THREAD

**Issue by nicholasjmorriss** [qupath/qupath#220]
First of all, this software is incredible and has made analyzing previously impossible amounts of data almost easy. So thank you!

I am working with large animal brains, DAB IHC stains. The cellular-level detection is pretty straightforward, however, I am trying to get information about staining intensity in the axons of some neurons, which necessitates subcellular level analysis that may be far away from relevant cell bodies. Do you have a way to generate a quantitative measure of pixel intensity across an entire slide? I'm not really concerned with the cell bodies or nuclei at all, more so the relative intensities of the DAB stains between brain slices. 

I apologize if this is a foolishly simple question, but I have limited experience working with large slides such as these. Again, thank you for your excellent software!

Nick

**Comment by petebankhead** [comment]
Thanks Nick!

For an average DAB value (which [isn't terribly quantitative](http://www.mecourse.com/landinig/software/cdeconv/cdeconv.html)) you could create an annotation, then try _Analyze &rarr; Calculate features &rarr; Add intensity features (experimental)_.

For something area-based (which may be preferable), there is _Analyze &rarr; Region identification &rarr; Positive pixel count (experimental)_ or even _Analyze &rarr; Region identification &rarr; Create cytokeratin annotations (TMA, experimental)_. 

As you can tell from the _(experimental)_ in the names, I wasn't entirely convinced either of these was quite as refined as they ought to be.  I've done a bit of work to [improve the pixel count](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#more-useful-output-for-positive-pixel-count-experimental), but I plan to incorporate newer, better approaches for this kind of thing over the next few months.

Given those caveats and limitations, you might find it better to try [creating your own method with ImageJ](https://github.com/qupath/qupath/wiki/Working-with-ImageJ).

Finally, most questions & answers are at [Google Groups](https://groups.google.com/forum/#!forum/qupath-users) - you might try posting your question there (ideally with an example image/screenshot).

**Comment by nicholasjmorriss** [comment]
Ok, thank you for the tips! I'll give the region identification a shot, and failing that head to google groups. I appreciate the quick response!

Nick
