### ISSUE TITLE
Superpixel annoations and detections 

### ISSUE THREAD

**Issue by Shushalsec** [qupath/qupath#222]
Hey Pete,

I think this might be a bit too much to ask even from QuPath but is it possible to give training sample annotations of clusters of cells (instead of cell types) and get these regions detected (instead of individual cells though _Analyze -> Cell analysis_ but analogous in the type of outcome I want)?
So, for example here I have 2 types of tissue I have annotated:
![image](https://user-images.githubusercontent.com/20464068/46069903-e5c81280-c17c-11e8-95cd-c3a5e53cf124.png)
Would it be possible to extend this to all of the whole slide image to identify each region as the red type or the orange type? 

Alternatively, is it possible to classify cells within these training sample annotations then do cell detection then cell classification and somehow merge adjacent cells if they are from the same type?

Thank you for your time!
Shushan

**Comment by petebankhead** [comment]
Hi Shushan,

I think this relates to your last question: https://groups.google.com/d/msg/qupath-users/89AbDQSknm8/SCAbYzA2CAAJ
I've written a script linked to that tries to do the job of converting cells into region annotations.

The bigger question of creating full image annotations is one that I'm very interested in and (kind of) working on.  Currently, I often use [QuPath + ImageJ + conventional image processing](https://github.com/qupath/qupath/wiki/Working-with-ImageJ) to generate detailed annotations; I suspect that in your case, converting to 8-bit, Gaussian smoothing and thresholding would do a pretty good job of mimicking the red annotation; if you have that, then it's possible to 'invert' the annotation to get everything else - either for the entire image, or constrained to a larger (coarse, hand-drawn) annotation.  It's still quite a laborious process, but armed with QuPath, ImageJ and a few short scripts (e.g. to invert annotations) it's possible to create much better annotations than could be done by hand.

I've also made some steps towards creating brush/wand annotations that can't overlap but rather snap to the boundary of existing annotations when pressing a specific key (although it's hard to not get tangled up in the various keyboard modifiers this involves, so it may need more work).  I don't actually remember if it's included [here](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html) or is more recent... but it may be worth investigating if you haven't already.

Slightly further in the distance (but hopefully not too far), I've also got a prototype pixel classifier working... but again some more work needs to be done to convert this into something usable and annotation-generating.  And having a very large number of annotations across a full slide might raise some performance issues that needs to be addressed to.

Pete

**Comment by petebankhead** [comment]
Yes, that should certainly be possible.  This could help give some ideas, both for exporting regions and then generating objects from binary images created elsewhere: https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html

I generally prefer to create contours with ImageJ (as in the script above), rather than OpenCV - the explanation why is at https://petebankhead.github.io/qupath/technical/2018/03/13/note-on-contours.html
But certainly the main processing can be done with OpenCV, with ImageJ only getting involved at the very final, contour-generating step.

**Comment by petebankhead** [comment]
Even if you prefer OpenCV normally, if your steps are straightforward enough you can save time by using ImageJ only - [here's a video](https://www.youtube.com/watch?v=9o9cGh9uH1A&index=12&list=PL4ta8RxZklWkPB_pwW-ZDVAGPGktAlE5Y) showing it in action.

_Objects &rarr; Make inverse annotation_ in QuPath can already be used as well; if the annotation being 'inverted' is completely inside another annotation, the result will be clipped to the 'parent' annotation.

**Comment by Shushalsec** [comment]
Wow these links are exactly what I needed thanks a lot Pete!
