### ISSUE TITLE
WARN: Unable to parse magnification: null

### ISSUE THREAD

**Issue by SahPet** [qupath/qupath#223]
Hi!
I've had trouble with *.tiff files lacking um/pixel information (scale). I've been able to set um per pixel scale using ImageJ to create an OME TIFF, but the magnification info is still lacking in QuPath and I get an error message saying: "WARN: Unable to parse magnification: null" 
I think this is what makes it impossible to apply/calculate "Local Binary Pattern" and "Coherence texture" features. Any idea how to set magnification manually either in Qupath or with another program? Appreciate any input.

**Comment by Svidro** [comment]
That sounds like this: https://github.com/qupath/qupath/issues/221

**Comment by SahPet** [comment]
Thanks for the reply, Svidro! I've already read that post, but didn't find a solution there. I don't think it's a tiff file size issue as the files I'm working with are max 200 mb.

**Comment by petebankhead** [comment]
I think this is a different issue; somehow the magnification needs to be written to the OME-TIFF.  Unfortunately I don't know enough about OME-TIFF to do that...

I don't have another QuPath-based workaround myself.  There isn't a way to override what the image-reader gets from the image yet.

The problem exists because _Add Local Binary Pattern features_ and _Add Coherence texture feature_ come from a time when I was using magnification instead of 'Requested/Preferred pixel size' (as is now the case for _Add intensity features_); the pixel size is a better and more robust approach to define an appropriate resolution, but it seems I didn't update the other two commands to adopt it... not least because I didn't find a use for them myself.

I'm curious: do you find them to be particularly valuable, or are you just exploring if they are useful?  Lest the software become too bloated by options and confusing, I would be tempted to remove them rather than update them... but if they are very useful then I should probably resist.

**Comment by SahPet** [comment]
Thanks for the thorough response, Pete! I do find them quite useful. I use Weka for attribute selection and ranking of most valuable attributes and both coherence texture and local binary pattern steadily comes up as top 20 discriminating features, either alone or in combination with smoothing. Therefore I'd really like to keep using them also for tiff files.

**Comment by Svidro** [comment]
Oops, my mistake.  That's what I get for always posting as I wake up!

I have found them useful in SLIC classifications to automatically detect different types of tissue... and that is about it.  Which ones are useful and why, I don't really know as I tend to feed them into classifiers and have not yet found a way to extract information from the classifier regarding which measurements were most useful.  It was mostly trial and error based on what worked.

**Comment by SahPet** [comment]
Among the top about 20 discriminating features, not THE top discriminating feature :)

**Comment by SahPet** [comment]
I recommend trying Weka attribute selection, it's quite informative. https://youtu.be/-BKP0gpDlbI

**Comment by SahPet** [comment]
Thank you so much, Pete! I bet it works, you're amazing! I'll try it first thing in the morning.

**Comment by SahPet** [comment]
Do you think a similar script also could set um/pixel metadata in qupath so I don't have to go through imageJ?

**Comment by petebankhead** [comment]
:) I'd like to advise against it, but I can't think of a sufficiently good reason why not... and I imagine the extra pixel-setting step is pretty time-consuming.  So you might want to try something like this...
```groovy
// Set the magnification & pixel size (be cautious!!!)
def metadata = getCurrentImageData().getServer().getOriginalMetadata()
metadata.magnification = 40
metadata.pixelWidthMicrons = 0.25
metadata.pixelHeightMicrons = 0.25

// If you want to trigger the 'Image' tab on the left to update, try setting a property to something different (and perhaps back again)
type = getCurrentImageData().getImageType()
setImageType(null)
setImageType(type)
```
If this is performed at an early stage (before any measurements/analysis), I can't think of a reason why it would go wrong... although if you find one, please do let me know!

**Comment by petebankhead** [comment]
That's strange, it works for me on Windows (I've no idea if the magnification and pixel size are suitable for your image, but I don't think that should prevent it from working).

Are you using QuPath v0.1.2 or some other version?  Is it feasible to run one script, then the other - or do you need it to work with batch processing across a large number of images?

**Comment by SahPet** [comment]
Tried moving some  stuff around in the script and now it works - thank you, Pete! Made sure to more the calibration just before the "coherence feature" and "local binary pattern" part of the script and made sure everything above was defined as pixels and below as microns.

**Comment by petebankhead** [comment]
Closed due to lack of activity and at least some of the issue has been resolved :)
Next milestone release should support setting pixel sizes for images in a project from within QuPath by double-clicking them under the 'Image' tab.
