### ISSUE TITLE
Get detection measurements per annotation

### ISSUE THREAD

**Issue by leondeh** [qupath/qupath#225]
Hello!

First of all, this is a great piece of software! I am trying to write a script to export the nuclear area of nuclei detected within multiple annotations. However, I would like to have these measurements exported for each annotation rather than exporting the complete list of detection measurements altogether. If I just export the complete list I am no longer able to distinguish between the different annotations. I feel I am just simply overlooking something here, so I was wondering whether there is a piece of code to be able to do this?

Thank you very much!

Leon

**Comment by Svidro** [comment]
There should be a variety of ways to do this in a script.  One would be selecting each annotation in turn using getAnnotationObjects() and looping through them.  For each annotation you generate your detections, output detections, then clear detections.
Another way could be to use a loop to a classification for each annotation (Class1, Class2, etc) and then you will end up with one data file, but the detection entries would be easily separable based on the classification column.
In version 1.3, there is a column that names the parent annotation for each detection, which could also be used to select certain detections without creating a classification.
Version 1.3 installation instructions (it is a test version!) can be found here: https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html

**Comment by Svidro** [comment]
In case Leon is still checking this and in need of a rough script, I posted one here: https://github.com/qupath/qupath/issues/234
