### ISSUE TITLE
Positive cell detection setup parameters

### ISSUE THREAD

**Issue by VeerleH** [qupath/qupath#226]
Hey, 

I noticed with the reopening of my Qupath that for (positive) cell detection - setup parameters - 'choose detection channel' shows as option (as seen below). How can I put it back to the original 'Choose detection image - (Hematoxylin OD)' option?

<img width="1428" alt="screen shot 2018-10-04 at 12 38 31" src="https://user-images.githubusercontent.com/43847524/46469005-6ec0f880-c7d2-11e8-9a27-0983207cf3ac.png">

**Comment by petebankhead** [comment]
The darkish background seems to be causing QuPath to estimate the wrong image type; double-click where it says 'Fluorescence' in the left tab of your screenshot, and change this to something more appropriate.  Then reopen the cell detection command and the correct options should appear.

(There is some more explanation of this at the start of the new [video tutorials](https://petebankhead.github.io/qupath/2018/08/22/qupath-video-tutorials.html))

**Comment by VeerleH** [comment]
Thank you so much! :)
