### ISSUE TITLE
measurements of area already classified

### ISSUE THREAD

**Issue by simonesteffens** [qupath/qupath#229]
Hey,
first of all,I totally like your software. But I need your help, maybe you have an idea...:
I´m trying to get the measurements of the area which I already classified as stroma or tumor.
Maybe you understand what I mean if you have a look at the picture.
Is there a possibility to get these measurements? Do you have a script I could use?
Thank you so much for your help :)
Simone

[Picture.pdf](https://github.com/qupath/qupath/files/2483008/Picture.pdf)

**Comment by Tkilvaer** [comment]
Hi
From your picture it seems to me that you:
- have detected cells in an elipse
- started making a classifier (the small red and green circles)
- are satisfied with the classifier (the cells are classfied correctly)

It seems that you already got some measurements registered in the oval like total number of stromal and tumor cells and probably also number of cells per mm^2. What additional measurements are you after? 

- Cell measurements?
- Measurements specific to certain classified cells?
- Measurements specific to certain areas?

Much is possible. You probably have to do some scripting if you want something tailored to your specific needs. I think you might find more answers in the [qupath google group](https://groups.google.com/forum/#!forum/qupath-users)

**Comment by Svidro** [comment]
Pete has a script that doesn't follow the borders you drew quite so tightly, but will classify area by the nearest cell, seen here: https://gist.github.com/petebankhead/e23393125fa57fe91c67f5003cbea3e2

You may be looking for something more like superpixel segmentation and classification, however, if you want to create regions that follow the general tissue outline more closely.  I have used this several times to create annotations that separate two different types of tissue, either based on texture or coloration.  It can be a bit tricky, however, and requires a bit of troubleshooting and decisions on what measurements to apply to the SLICs.  Based on your image, the difference is fairly clear-cut and you might be able to get away with something as simple as OD Sum.
The specific tool is _Analyze->Region Identification->Tiles and superpixels_ and then either DoG or SLIC Superpixel segmentation.  I tend to prefer SLICs for tissue segementation.

Note that this WILL remove all detections (your cells, in this case) and should generally be done before any cell creation in a script.

Essentially it makes a jigsaw puzzle of the selected annotation based on the flow of the colors in the tissue.  
![image](https://user-images.githubusercontent.com/23145209/47020475-4b6d4600-d10e-11e8-8ec7-fccdd85860c6.png)

You can then apply color measurements to each of those tiles and then classify them.  
![image](https://user-images.githubusercontent.com/23145209/47020737-e1a16c00-d10e-11e8-868c-9d1255766fce.png)

Finally you could merge all classified SLICs (which are detections) back into annotations using the _Tile classifications to annotations_ in the same menu, and perform cell detection within the new annotations.  These annotations will have your area measurements as normal.  If you want to apply a sum of all Tumor etc areas to the parent annotation, that will require another script.

I am pretty sure this is discussed in more detail on the forums somewhere including scripts.

*Runs and hides*

**Comment by DavidMHaumann** [comment]
Does this help?

If you need to fuse measurements for many slides, there is also a combine script from Pete. 
The following script works only within projects!

//Script to save annotations results inside a results folder inside the project folder: 

import qupath.lib.scripting.QPEx
// Create the output directory, if required
def path = QPEx.buildFilePath(QPEx.PROJECT_BASE_DIR, "annotation measurements")
QPEx.mkdirs(path)

// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
// Get the file name from the current server
def name = server.getShortServerName()
def path2 = buildFilePath(PROJECT_BASE_DIR, "annotation measurements", name)
saveAnnotationMeasurements(path2 + ".txt")
print('annotation results saved in results folder')

def path3 = QPEx.buildFilePath(QPEx.PROJECT_BASE_DIR, "detection measurements")
QPEx.mkdirs(path3)

def path4 = buildFilePath(PROJECT_BASE_DIR, "detection measurements", name)
saveDetectionMeasurements(path4 + ".txt")
print('detection results saved in results folder')

**Comment by simonesteffens** [comment]
Hey Guys,

thank you so much for your answers, that was super quick!!! It helped a lot. Most of it the idea of Tile classifications to annotations...
Your great 👍
