### ISSUE TITLE
calculation breaks off again and again

### ISSUE THREAD

**Issue by simonesteffens** [qupath/qupath#232]
Hey Guys,

could an image or annotation be to large for any analysis/computation? Because I tried to calculate my images on different computers but all of them stopped around 80% of the calculation.

I talked to some IT-experts but they told me that these computer power (RAM, Processor unit etc.) should able to handle that.

Anyone had that problem before?

Greetings and thanks a lot.
Simone

**Comment by Tkilvaer** [comment]
Have you set qupath to use the available ram?

Den lør. 20. okt. 2018, 13:09 skrev simonesteffens <notifications@github.com

**Comment by Svidro** [comment]
There are a variety of things it could be, but we would need more information.
What is your resulting qpdata file size?
Which functions are you using and which version of QuPath?  1.2 and positive pixel counting, for example, have a known issue.
