### ISSUE TITLE
Image Export Query

### ISSUE THREAD

**Issue by eamonpm** [qupath/qupath#233]
Hi all. Thanks again for an excellent app - making life a lot easier around our building.

I have (what I hope is) a very simple query. I have multiple images in a project. Each image has 12 annotations (rectangles), as per the below.

![image](https://user-images.githubusercontent.com/44374335/47304270-feadd180-d61d-11e8-99a9-d12a8b3085e0.png)

I want to export individual images for each annotation - I know this is simple enough when done manually (File...Export Image Region...) where i then specify the downsample and save directory. The file (PNG) is then automatically named with the Image Name, downsample, and coordinates (very handy).

What I'd love to know is if there a simple script to export all 12 regions from an individual image, or even from an entire project in one go?

**Comment by petebankhead** [comment]
It's definitely possible, as long as each annotation is of some manageable size (which it is here).

A couple of blog posts are relevant:
* https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html
* https://petebankhead.github.io/qupath/scripting/2018/03/07/script-extracting-image-regions-to-imagej.html

For the first one, you can remove the `ImageIO.write(imgMask, 'PNG', fileMask)` bit if you don't need a binary image (which wouldn't be very meaningful here...).

For the second you'd need to uncomment the `//IJ.save(imp, '/path/to/save.tif')` part, choose a sensible output name, and avoid showing the image through ImageJ.

It should be possible to _Run &rarr; Run for project_ in both cases, so long as your image files all have distinct names.

A recent script from Sara might help too: https://groups.google.com/d/msg/qupath-users/aHcikTZF9HE/dkcn0BoFBwAJ

**Comment by eamonpm** [comment]
Thanks so much Pete - the first option has worked perfectly across the project.

I had come across that blog post but mustn't have connected the dots!
