### ISSUE TITLE
Merge .qpdata

### ISSUE THREAD

**Issue by vqdang** [qupath/qupath#235]
Hi, we have a TMA and we arranged 2 people to annotate two different set of cores using their local machines via QuPath. This process generated 2 different .qpdata. Is there anyway we can merge them together?

Thanks

**Comment by Svidro** [comment]
You might consider something like this:
https://groups.google.com/forum/#!searchin/qupath-users/copy$20annotations%7Csort:date/qupath-users/UvkNb54fYco/ixWuDPhXAwAJ

**Comment by DavidMHaumann** [comment]
I extended the export-import Script from Pete to be able to to export import of annotations in batch mode for many images - dependent on their names. The scripts create annotation folders and create annotation databanks. 

**Script for anotation export (without detections or cells):** 

import qupath.lib.scripting.QPEx
// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
// Get the file name from the current server
def name = server.getShortServerName()

def path = QPEx.buildFilePath(QPEx.PROJECT_BASE_DIR, "annotations")
QPEx.mkdirs(path)

def path2 = buildFilePath(PROJECT_BASE_DIR,"annotations", name +'_annotations')
def annotations = getAnnotationObjects().collect {new qupath.lib.objects.PathAnnotationObject(it.getROI(), it.getPathClass())}
new File(path2).withObjectOutputStream {
    it.writeObject(annotations)
}
print 'Done!'



**This script is for import the annotation - works only with corresponding image names:** 

import qupath.lib.scripting.QPEx
// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
// Get the file name from the current server
def name = server.getShortServerName()

def path = buildFilePath(PROJECT_BASE_DIR, "annotations", name + '_annotations')
def annotations = null
new File(path).withObjectInputStream {
    annotations = it.readObject()
}
addObjects(annotations)
print 'Added ' + annotations
