### ISSUE TITLE
How to use script to get full path of the current slide image?

### ISSUE THREAD

**Issue by hongyiyu** [qupath/qupath#239]
How to use script to get full path of the current slide image?

**Comment by Svidro** [comment]
https://gist.github.com/Svidro/5e4c29630e8d2ef36988184987d1028f#file-export-file-by-image-name-groovy

That might help, there is a line in there for images.

**Comment by hongyiyu** [comment]
@Svidro 
`String imageLocation = getCurrentImageData().getServer().getPath()`

This line works. 
Thanks a lot
