### ISSUE TITLE
Crash in script editor.

### ISSUE THREAD

**Issue by CielAl** [qupath/qupath#241]
Hi,

I am using the script editor in Qupath-0.1.2 for groovy.  The editor crashed when I attempted to delete the closing of the block comment (i.e. "*/"), following by a fair amount of code (196 word, 72 lines, characters without blanks 1728, total length 1872).

It appears the crash is not caused by lines but by the quantity of codes. To replicate the exception,
I simply create the code 
`
/*
1
*/

a=1
a=1 ... (with hundreds of repeat lines)

`
and then remove the "*/", the exception will be thrown.

**Comment by petebankhead** [comment]
Thanks, I can replicate this whenever I add enough lines.  It also happens with my experimental, much updated branch (Java 11, updated dependencies)... so none of the updates have addressed this.

The entire script editor needs an overhaul, and it seems the underlying text component that can provide the syntax highlighting (RichTextFX) isn't maintained any longer; JavaFX doesn't have something similar built-in, unfortunately.

I'll look to see if I can find a quick fix on the QuPath side.  If not, it adds to the urgency of updating the script editor... any suggestions for the best way to get a code editor with syntax highlighting into a JavaFX application welcome!

**Comment by bjtho08** [comment]
You probably already know this and maybe it's not even relevant any longer, but anyway: It appears the RichTextFX team has been replaced and is now actively maintained.

Also, [this](https://www.mirkosertic.de/blog/2015/04/a-javafx-based-lua-editor/) might be a simple way to implement a robust script editor. I hope this is useful 😄

**Comment by petebankhead** [comment]
Switching to apply the syntax highlighting asynchronously appears to address this issue... or at least make the error less obtrusive. This will be in v0.2.0-m4.

Replacing the script editor is still preferable in the longer term, for performance, features and maintainability.
