### ISSUE TITLE
Is there an earser tool?

### ISSUE THREAD

**Issue by ZhMJiang** [qupath/qupath#245]
Is there a tool or something that can do the opposite thing of brush tool?

**Comment by petebankhead** [comment]
Yes, just press the _Alt_ key with the Brush: https://github.com/qupath/qupath/wiki/Drawing-regions#-brush-tool

There's also a [video tutorial](https://www.youtube.com/watch?v=lGj3uyxUdgs&list=PL4ta8RxZklWkPB_pwW-ZDVAGPGktAlE5Y&index=5).

**Comment by ZhMJiang** [comment]
Thanks
