### ISSUE TITLE
Can I use a script to run same work repeatedly?

### ISSUE THREAD

**Issue by Kangyeol-Kim** [qupath/qupath#246]
Hi all, 

I want to make all of my .qupath data to patches. The problem is there are so many data to do so and I cannot find a way to do it automatically.

![2018-11-16_13-15-37](https://user-images.githubusercontent.com/26561999/48597716-744d5900-e9a2-11e8-8636-ef9211b098fb.png)

As you can see at above image, I have to deal with all of those data. The simple way is just to open each data manually and run a script. However, it would be better if I can do it without any care....
Can you give me any suggestion or advice to do so?
Thanks a lot!

**Comment by petebankhead** [comment]
This is what [Projects](https://github.com/qupath/qupath/wiki/Projects) are for.  You can then [run a script for multiple images in a project](https://github.com/qupath/qupath/wiki/From-workflows-to-scripts#running-a-script-for-multiple-images).

**Comment by Kangyeol-Kim** [comment]
Thanks, but I cannot import multiple [Qupath data file] unlike [.svs file]. I tried several time and always encountered 2 cases: 

1. Unable to import 1 paths

![2018-11-16_16-39-09](https://user-images.githubusercontent.com/26561999/48604755-33633d80-e9be-11e8-907f-fffe52f366d9.png)

2 . Alternatively, I opened the file and add it to the project. It worked fine but, I lost the annotation information attached by it when I was trying to import second image.

- First file: annotations are preserved

![1](https://user-images.githubusercontent.com/26561999/48604869-8b01a900-e9be-11e8-89cf-c13308782c7f.png)

- Second file: Cannot import the annotations

![2](https://user-images.githubusercontent.com/26561999/48604928-aa98d180-e9be-11e8-9160-ae1d30d2cb3f.png)

Thanks a lot!

**Comment by petebankhead** [comment]
It's intended that projects are set up first, and then QuPath will create and manage all the .qpdata files for you.  Adding .qpdata files later isn't supported through the user interface.

I'd suggest creating a project and annotating your images again... or at least starting to.  [Project structure](https://github.com/qupath/qupath/wiki/Project-structure) may help if you then want to manually replace the contends of the 'data' subfolder within the project to use your existing .qpdata files (to trick QuPath into using them).  These .qpdata files may need to be renamed for this to work.

[This video](https://www.youtube.com/watch?v=2yoRMl1IaJ4&index=3&list=PL4ta8RxZklWkPB_pwW-ZDVAGPGktAlE5Y) may also help.
