### ISSUE TITLE
Simple Tissue Detection within an annotation

### ISSUE THREAD

**Issue by ndtkinesin** [qupath/qupath#248]
I am working on the IHC staining of cancer slides. I want to do several annotations on a image and run the simple tissue detection to outline tissue areas within each annotations. However, every time I run simple tissue detection, it will annotate the whole slides and remove my annotations. Is that a way to limit the simple tissue detection within each annotation?

**Comment by DavidMHaumann** [comment]
actually there is. You can use a script that exporte your annotations. runs the simple tissue detection, re-imports your annotations, then substracts everything of simple tissue detection of your ROI. 

Then finally you have your annotations with simple tissue detection inside. 
That requires quite some scripting.

**Comment by petebankhead** [comment]
Old discussion, but the intended solution in v0.2.0 is to use *Create thresholder* instead. This gives much more control, in addition to the ability to preview the thresholded result:
https://qupath.readthedocs.io/en/latest/docs/tutorials/thresholding.html
