### ISSUE TITLE
Is there any way to discriminate stained cells based on the pixel colour, NOT the intensity of the colour?

### ISSUE THREAD

**Issue by pssaha** [qupath/qupath#250]
Dear @petebankhead 

Hope this finds you well. I am back again for your input on an issue.

First, let me tell briefly about **my task with the QuPath**. I stained slides of different mouse tissues. The main stain was X-gal stain (blue) to satin positive/expressed cells, and I co-stained the same section with Neutral red (red) to stain nuclei. Therefore, I have only two colours to play with. Overall, in a particular region  (or, annotation) in those sections, I need to figure out what is the percentage of the blue signals wrt red signals.

**Currently,** after annotating a region, I am mentioning QuPath to fetch me the two different signals based on the threshold chosen. Higher threshold values (say, 0.40) helped me to select blue signals, and low threshold (0.08) helped me to select both red and blue to denote the overall number of cells in that region (with all the other default settings as fixed). Till now everything was fine.

**Problem is that** some nuclei are stained too dark, and they also show up in high threshold values along with blue signals, accounting for a high, unreal figure for positive signals. I assume the darker red nuclei have an overlapped intensities to the blue signals.

**My question** to you: Is there any way to discriminate these cells based on the pixel colour, NOT the intensity of the colour so that I can avoid the artefacts? 

Please let me know if you need any further clarification. 

Many thanks in advance for your suggestion.

Sincerely,
Partha

**Here is the dropbox link to my image file:**
https://www.dropbox.com/s/vz8e0jssrr7ur2w/Image%20file.qpdata?dl=0

**And, I show my procedure pictorially here:**
[procedure.pdf](https://github.com/qupath/qupath/files/2678866/procedure.pdf)

**Comment by Svidro** [comment]
Cell detection or Positive Cell detection at the top of the same _Analysis->Cell Analysis_ menu should work. 

Set your first color vector to match the red stain (for nuclear detection) and the second stain to blue (for you X-Gal). More information on how to do that here:
https://github.com/qupath/qupath/wiki/Preprocessing
https://www.youtube.com/watch?v=IpCDnPnFvDc&t=7s

Either way you do it, you can use the first color vector to detect nuclei, and then the second color vector to judge whether the cells are positive or negative for X-Gal.
I would recommend leaving the names of the color vectors in the Image tab as they are and using Positive Cell Detection, with Hematoxylin OD (having been repurposed to "red") as the detection image, and Nucleus DAB OD (now "blue") mean as the Score Compartment.

I expect it would come out looking something like this, though the file you included is the data file, not the image file, so I don't have a full image to work with. QPDATA files only include the annotation, detections, and other drawn on objects.
![image](https://user-images.githubusercontent.com/23145209/49988566-158ce800-ff2c-11e8-8c57-cdab949e4ae0.png)

Once you choose your threshold, you should be good to go. I think he might be considering removing Watershed nucleus detection (experimental) as it is.

Cheers

**Comment by pssaha** [comment]
Dear @Svidro ,

Many thanks for your suggestions. I am extremely sorry as I did not attach the original image to my previous post. I thought that you got everything with enclosed QPDATA files. I, here, give a ****download link** (below) of the original image.**
https://my.pcloud.com/publink/show?code=XZN1HC7ZCU8ImbiEUGShoj457lSYa7TCxtEy

**I have tried the following things as you suggested but could come up of the following issues:**

1. I could not switch in-between diffient channels of colors as shown (comfortably) in the video. In other words, I could not check the _color deconvolution_ before estimating the vectors .

2. I wanted to get separate values for the number of cells with each color. But looks like, QuPath gives as a total number. Having them, is very important for me as 

3. In most cases, after _running_ the Positive Cell Detection, even some blue cells are not encircled, letting me assume that they were not counted probably. Image below:
![capture](https://user-images.githubusercontent.com/44507241/50253977-ea821880-03b1-11e9-826e-bb092ba9b087.JPG)

I admit that I am a newbie to QuPath. I apologize if you see these problems are because of very silly mistakes. 

Many thanks for helping me out!
sincerely,
Partha

**Comment by Svidro** [comment]
No problem, it is also challenging to advise correctly without having the full image, so thank you for that!
Changing channels should be possible with the 1/2/3/4 keys, but you can only do this once you have picked color vectors. They do not update "live."

I am not sure what you mean by #2, but hopefully the script below improves things for you, and I am sure if you play around with the values you can improve it even further!

Here is what I came up with for settings that seem to work for cell detection in the main bulk of your tissue:
```
setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "red blue", "Stain 1" : "Hematoxylin", "Values 1" : "0.18752 0.65887 0.72851 ", "Stain 2" : "DAB", "Values 2" : "0.72191 0.55664 0.41109 ", "Background" : " 255 255 255 "}');
selectAnnotations();
runPlugin('qupath.imagej.detect.nuclei.PositiveCellDetection', '{"detectionImageBrightfield": "Optical density sum",  "requestedPixelSizeMicrons": 0.27,  "backgroundRadiusMicrons": 0.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 2.0,  "minAreaMicrons": 30.0,  "maxAreaMicrons": 400.0,  "threshold": 0.6,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Nucleus: DAB OD mean",  "thresholdPositive1": 0.4,  "thresholdPositive2": 0.4,  "thresholdPositive3": 0.6,  "singleThreshold": true}');
```
![image](https://user-images.githubusercontent.com/23145209/50290376-79864380-0439-11e9-86dc-7b4375cee119.png)
![image](https://user-images.githubusercontent.com/23145209/50290399-873bc900-0439-11e9-937b-7dc5c5ce1139.png)

A couple of things to note about this, some cells in certain sections of your sample are so dark that they basically show up as all colors. That makes them very difficult to distinguish, although it might be possible to exclude them or classify them as a third type if it is important enough. The script above should work for the central areas with the blue stained cells. Your scanner/sample plane is also slightly off, and  you can see that in the above screenshots where the lower right corner of the (by image) frame changes focus. Small variations like that can have significant impacts on detecting faintly stained objects, so your negative nuclear accuracy may vary based on where in the frame you are counting.

![image](https://user-images.githubusercontent.com/23145209/50290628-43958f00-043a-11e9-9125-032f51c04a5d.png)

That said, hopefully the above script works well for you. I ended up selecting a small area that included a blue nucleus and manually adjusting the color vectors, which are included in the script.

**Comment by pssaha** [comment]
Hello @Svidro ,

Many thanks for your help!!

Lately, I understood all, but I am still stuck in the following:

- I asked you earlier how you got the Values 1 and Values 2 in your script:
"Stain 1" : "Hematoxylin", "Values 1" : "0.18752 0.65887 0.72851 ", "Stain 2" : "DAB", "Values 2" : "0.72191 0.55664 0.41109 "

- You replied: "For the stain vectors, I used the manual method shown in the video from the menu option Analyze->Preprocessing->Estimate Stain Vectors. I had a fairly large area in the middle of your sample selected with an annotation."

- I did the same as you, but my values came:
Hematoxylin, "Values 1" : "0.711 0.556 0.43
DAB, "Values 2" : "0.156 0.631 0.76

Things to notice:
Your perfectly functional values for these are different from me in two aspects:
1. Your values are 5 places after the decimal, and mine is 3.
2. your individual bands (RGB) are also differing with my one. Say, the first band for your Values 1 is 0.18752, whereas my one is 0.711.

Would you kindly help me out again? Thanks!

![image](https://user-images.githubusercontent.com/44507241/55165826-15f86a00-513c-11e9-81af-2a43648a6140.png)

**Comment by Svidro** [comment]
"I did the same as you, but my values came:
Hematoxylin, "Values 1" : "0.711 0.556 0.43
DAB, "Values 2" : "0.156 0.631 0.76"

That looks like pretty much the same vectors, just flipped. Normally hematoxylin is the more blue vector, but in this case I think I wanted the more common color to be "hematoxylin." You could get the same result if you took the blue and orange vectors in your last picture and exchanged their positions.

Or you can copy text values for the vectors, and paste them into the Image tab under each stain vector.

Another way to go about getting the same results, since you have swapped DAB and Hematoxylin, would be to edit the Classification script, and swap DAB and Hematoxylin there. In the end, they are just labels :)

**Comment by pssaha** [comment]
@Svidro Thanks again! The problem is solved.  :)
