### ISSUE TITLE
Exporting Detection as a labeled image

### ISSUE THREAD

**Issue by hrejali** [qupath/qupath#251]
Hi Pete,

 Very sorry if this issue has been addressed previously. I want to use QuPath as part of a project I am working on! I need a labelled image where each class represents a tissue type. The problem is I haven't been able to export the resulting detection as a labelled segmentation image. I went through the following script:  https://petebankhead.github.io/qupath/scripting/2018/03/14/script-export-labelled-images.html, if I understand correctly this script exports an labeled image for each annotations and not the detection, found within a particular annotation

So far I was able to create a classifier that will allow me to classify the 3 labels of interest (Grey Matter ==1, White Matter ==2, Background ==3). Also, I use this classifier to classify the tissue types within one annotation, ideally this annotation is the size of the original image. BTW the classification tools in QuPath is amazing!

An example Image is shown below. 

![image](https://user-images.githubusercontent.com/34345427/50388480-98652e00-06f6-11e9-9cf0-6f51b6526e66.png)

**What I want to do at this point is to be able to export the detection as a labelled segmentation image.** Thank you in advance!

**Comment by Svidro** [comment]
I would try using SLICs rather than tiles, but either way, it looks like you have the classification down. If you want a picture, do you mean something like the File->Export->Export Viewer Snapshot (but scripted)? Just trying to verify because there are a lot of image export options, though none of them will create a whole slide image.

This issue has a bunch of links to various options: https://github.com/qupath/qupath/issues/216

**Comment by petebankhead** [comment]
@hrejali  the script you've already found on my blog is the starting point I'd suggest.  It may be possible to do what you want through minor modifications, e.g. try changing `it.isAnnotation()` to `it.isDetection()`.

**Comment by hrejali** [comment]
Hi @Svidro,

Thanks for the reply - I did want everything to be scripted since I have a large number of images I need to be segmented.  I am looking through some of the various options now just in case I find something useful.

Thanks for the suggestion @petebankhead - I am going to try to see if I can get the modified version working, will let you know how it goes!

Happy Holidays from Canada
