### ISSUE TITLE
Mesh size

### ISSUE THREAD

**Issue by geodza** [qupath/qupath#252]
Hi!
Currently Qupath mesh has a step of 250mk. Is it possible to this value? Or what should i do, if I need a  mesh with a step size 500mk?
Thanks advance
Have a happy New Year!

**Comment by petebankhead** [comment]
Try _View &rarr; Set grid spacing_

**Comment by geodza** [comment]
Oh, that was fast.
Iˇve tried in preferences
Now it works :)
Thanks!

**Comment by petebankhead** [comment]
Good!  And good point - the preferences would be a more sensible place for that option.  I'll look into moving it now...

**Comment by petebankhead** [comment]
It will be possible to set the grid spacing from the preference pane in the next release.
https://github.com/petebankhead/qupath/commit/9f337258120125724e17c7f6985fdce495a230f0
