### ISSUE TITLE
Scripting for TMA

### ISSUE THREAD

**Issue by oriolarques** [qupath/qupath#255]
Hi!
I wrote a very simple script that works well for individual images. I would like to apply this to for TMA analysis andI would like to get the four printed values for each TMA core. Right now it only calculates the values for the whole image. Could you please indicate me a way to explicitly tell QuPath to evaluate each individual core at a time?

Thanks!

**Script:**
def positiveCells = getCellObjects().findAll{it.getPathClass() == getPathClass("Positive")}
def negativeCells = getCellObjects().findAll{it.getPathClass() == getPathClass("Negative")}
def nuclearDABpos = 0
def nuclearDABneg = 0
def numCellsPos = 0
def numCellsNeg = 0
for (cell in positiveCells){
   nuclearDABpos = nuclearDABpos + cell.getMeasurementList().getMeasurementValue("Nucleus: DAB OD mean")
   numCellsPos = numCellsPos + 1
}
for (cell in negativeCells){
   nuclearDABneg = nuclearDABneg + cell.getMeasurementList().getMeasurementValue("Nucleus: DAB OD mean")
   numCellsNeg = numCellsNeg + 1
}

println("Percentage of positive cells is: " + (numCellsPos/(numCellsPos+numCellsNeg))*100)

println("Mean Nuclear signal in the samples " + (nuclearDABpos+nuclearDABneg)/(numCellsPos+numCellsNeg))

println("Mean Nuclear signal in positive cells is: " + nuclearDABpos/numCellsPos)

println("Mean Nuclear signal in negative cells is: " + nuclearDABneg/numCellsNeg)

**Comment by Svidro** [comment]
It looks like you have things down pretty well on the scripting side, hopefully this gives you the extra nudge to get everything working in a TMA:
https://gist.github.com/Svidro/68dd668af64ad91b2f76022015dd8a45#file-class-percentages-to-tma-measurements-groovy
You will want to rewrite each of your cell lists for the current core's "total" (using another findAll), which is the total number of cellsObjects in that core.

In this case the measurements are placed into the TMA measurement list, but you could also print them out if desired.

**Comment by oriolarques** [comment]
I think I got it, with the following script! I can get the 4 values for each core. 
However, I would like also to print the identification of each core. What is the instruction to get for example A-1 for the first core, A-2 for the second and so on? 

**Script**
import qupath.lib.objects.PathCellObject
def hierarchy = getCurrentHierarchy()
def cores = hierarchy.getTMAGrid().getTMACoreList()


cores.each {
def total = hierarchy.getDescendantObjects(it, null, PathCellObject).size()
if (total != 0){
                def positiveCells = hierarchy.getDescendantObjects(it, null, PathCellObject).findAll{it.getPathClass() == getPathClass("Positive")}
		def negativeCells = hierarchy.getDescendantObjects(it, null, PathCellObject).findAll{it.getPathClass() == getPathClass("Negative")}
		def nuclearDABpos = 0
		def nuclearDABneg = 0
		def numCellsPos = 0
		def numCellsNeg = 0
		for (cell in positiveCells){
		   nuclearDABpos = nuclearDABpos + cell.getMeasurementList().getMeasurementValue("Nucleus: DAB OD mean")
		   numCellsPos = numCellsPos + 1
		}
		for (cell in negativeCells){
		   nuclearDABneg = nuclearDABneg + cell.getMeasurementList().getMeasurementValue("Nucleus: DAB OD mean")
		   numCellsNeg = numCellsNeg + 1
		}
				
		println("Percentage of positive cells is: " + (numCellsPos/(numCellsPos+numCellsNeg))*100)

		println("Mean Nuclear signal in the samples " + (nuclearDABpos+nuclearDABneg)/(numCellsPos+numCellsNeg))

		println("Mean Nuclear signal in positive cells is: " + nuclearDABpos/numCellsPos)

		println("Mean Nuclear signal in negative cells is: " + nuclearDABneg/numCellsNeg)
      
   }
}

**Comment by oriolarques** [comment]
It's perfect! 
Thanks again.
