### ISSUE TITLE
TMA registration extension

### ISSUE THREAD

**Issue by MIAUnimiB** [qupath/qupath#258]
Dear 
thanks for your work
I would like to write an extension to register the TMAgrid once placed on a new TMA image.
However, I can't find the code where the a copied TMA grid is placed and the one that creates it from the users' parameters. Could you tell me where I find the source

**Comment by petebankhead** [comment]
Hi, I'm not completely sure I understand - is this what you are looking for? https://github.com/qupath/qupath/blob/v0.1.2/qupath-processing-ij/src/main/java/qupath/imagej/detect/dearray/TMADearrayerPluginIJ.java
You can also search for 'TMA' within the QuPath GitHub repository.

This is shorter and might also help: https://github.com/qupath/qupath/issues/77#issuecomment-301234930

**Comment by MIAUnimiB** [comment]
Dear, Thanks a lot!
