### ISSUE TITLE
Calculate stroma/epithelial area and immune cell density H&E?

### ISSUE THREAD

**Issue by vasilisstavrinides** [qupath/qupath#262]
Dear Qupath users,

I am a fairly new Qupath user and I would like to calculate the proportion of stroma/epithelium in a given area of annotated tissue (prostate biopsy in particular) and also identify immune cells (lymphocytes) and express them as a density (cells/mm2) in stromal and epithelial areas. I am beginning with benign tissue but would like to move on to tumour-containing tissues as well down the line. I am also looking for an effective way to extract that data for multiple images (>500) into an Excel spreadsheet.

Unfortunately I cannot find any resources online for this. The Qupath classifier identifies individual cells and most responses are on IHC, whereas my images are H&E. Could anyone please help?

Thank you,

V

**Comment by Svidro** [comment]
You may want to open a [forum ](https://groups.google.com/forum/#!forum/qupath-users)thread where you can show some examples. Most examples I have seen of identifying TILs in HE staining were using deep learning, but if you can figure out a way to identify them among the rest of your cells, you should be able to do it.

Extracting the data into a single worksheet is fairly easy, and can been seen in the following two links:
https://petebankhead.github.io/qupath/scripting/2018/03/04/script-annotation-export.html
https://petebankhead.github.io/qupath/scripting/2018/03/05/script-annotation-results-merge.html

I generally use SLICs to classify sub-annotation areas, then merge them into annotations (after some smoothing) to separate out tissues for cell detection.

Aand I got horribly distracted by laser problems and Pete beat me to it :)

**Comment by vasilisstavrinides** [comment]
Thank you both for the input. I will post a question on the Google user group. Best of luck with the coding!
