### ISSUE TITLE
LGPL

### ISSUE THREAD

**Issue by betrw** [qupath/qupath#263]
I would be interested in two classes but the whole project is released under GPL. The program I have been developing will be free of charge but I am not very interested in disclosing the complete source code that I have written for six month. Maybe LGPL would have been a better choice for linking some library functions only.

**Comment by petebankhead** [comment]
Hi, I appreciate that there are arguments for and against the use difference open source licenses, and that the GPL can mean that some people won't use it in ways that they otherwise might.

I will close this because it seems more of an opinion than a genuine issue or question.
