### ISSUE TITLE
Desired Extensions to QuPath

### ISSUE THREAD

**Issue by MIAUnimiB** [qupath/qupath#269]
Dear Pete,
we are extensively using your QuPath, but we would need some extensions and modifications:
Precisely, what we would need is:

1. extending the image rotation range to  [-180 ,..., +180]; the reason for this request is that
we must deal with .svs slides that are scanned upside-down. Therefore, to match them a rotation of only -90 -> +90 degrees is not sufficient
2. we would need to rotate the whole TMA grid without rotating the image.
Indeed, after I define a TMA grid and an object grid over an image, I would like to apply them (EDIT -> Copy grid&objects, EDIT-> Paste grid&objects) to all the other images that are slightly rotated or not perfectly aligned between them. To this aim, I must place the grid and the objects, and I must be able to rotate them.
3. It would very useful to me to save the rotation information inside the project file. In this way when I open the project again the images are restored with the correct (previous) rotation
4. in multi view mode translations is not preserved when I change active panel
now translated image is moving back to the original place as soon as I click on another image
5. it would be very useful be able to save the TMA grid in a file on its own, and be able to load again in a different new project (save/load grid)
6. it could be very useful, when I align the core to the TMA grid, to be able to select the core with just 1 click and not double clicking  it this would speed up the process a lot.

I would be glad to be used as beta-tester for the next versions of your useful program.

hope the best
best regards

**Comment by petebankhead** [comment]
These are not small tasks and I am unable to make substantial custom extensions and modifications at this point due to the overwhelming demand and work involved, but fortunately many of these things are already on my roadmap. Announcement to come soon.

**Comment by MIAUnimiB** [comment]
Thanks so much Pete

**Comment by petebankhead** [comment]
I'll close this issue as rotation on image import is now possible in v0.2.0-m4: https://petebankhead.github.io/qupath/2019/08/20/fourth-milestone.html#more-options-when-importing-images-to-projects
When working in a project, the rotation should be preserved when you reopen the file and the software should act just the same as if the data was in the requested orientation.
