### ISSUE TITLE
New Computer having trouble opening .scn files using Bioformats extension

### ISSUE THREAD

**Issue by asasama12** [qupath/qupath#271]
I am working on getting QuPath up and running on a shared lab computer and am having issues opening .scn files using the bioformats extension.  I copied over all the same settings from my personal computer that are confirmed to be working for me, however when I try to open the same images, they import at an unnamed image that throws an error when I try to open it, and a zoomed out image of the whole slide named "macro."  In the properties panel all the information appears to be correct including the image type and the file name.  Any ideas? 

![capture2](https://user-images.githubusercontent.com/41748563/53506051-cc542b00-3a7a-11e9-9a1a-082354da8e42.PNG)
![capture3](https://user-images.githubusercontent.com/41748563/53506052-cc542b00-3a7a-11e9-94ae-c33569a3575a.PNG)
![capture](https://user-images.githubusercontent.com/41748563/53506053-cc542b00-3a7a-11e9-8e32-35189308a3d8.PNG)

**Comment by Svidro** [comment]
Not really a solution, but a thought... they just updated BioFormats to 6.0.0, so I am guessing you downloaded the newest version on the new computer. You might try copying the BioFormats jar files from your Extensions folder on the older PC, and using them instead to see if it allows you to open the files again.

If that works, there was probably something in the update that either messed up the .scn reader on the BioFormats end, or broke some kind of connection in the QuPath extension.

**Comment by asasama12** [comment]
That worked!  Seems like there's an issue with the newest version of BioFormats

**Comment by Svidro** [comment]
@petebankhead Might want to keep track of this one in case it is an extension thing rather than a BioFormats thing. If @asasama12 is willing to share a couple of the files I could do some tests and maybe open a ticket on the BioFormats forum, but without the files there isn't much I can do.

**Comment by petebankhead** [comment]
It may be this - https://github.com/qupath/qupath-bioformats-extension/issues/10 - in which case the Bio-Formats team probably see it as a QuPath issue (fix to come).
