### ISSUE TITLE
Workflow viewer

### ISSUE THREAD

**Issue by HMC9** [qupath/qupath#272]
Hello,

I have tried to make batch analysis from workflow viewer.
Whereas it showed "set image type" and "watershed cell detection" as workflow records, the 3rd command does not come up.
What I set as 3rd (and 4th) command is that "load classifier and run classifier".
![workflowviewer](https://user-images.githubusercontent.com/35938841/53768694-68709e80-3e8e-11e9-839e-48de35711579.JPG)

Attached image is showing a workflow window and a classifier window.
This was done with v0.1.2 QuPath.
Please give any suggestion to solve this issue.

**Comment by Svidro** [comment]
Not all commands currently show up in the workflow viewer. You would almost certainly want something like selectAnnotations() before your watershed cell detection (unless you want to manually select something before you run the script), and runClassifier("classifierlocation") for the classification. More on that here:
https://groups.google.com/d/msg/qupath-users/dgAabXK0eBU/W4Ex4KiQDAAJ

**Comment by HMC9** [comment]
Thank you for your quick response. 
I will check the link.

**Comment by petebankhead** [comment]
The appropriate classifier commands are logged when you first save it. So if you can find the image you had open at that time, you should find the commands in the workflow there.

The scripts & explanations in the supplementary material [here](https://www.nature.com/articles/s41598-017-17204-5#Sec15) might also help.
