### ISSUE TITLE
Reduce annotations

### ISSUE THREAD

**Issue by LiezeB** [qupath/qupath#274]
Hi, I have used the following method (https://petebankhead.github.io/qupath/scripts/2018/08/08/three-regions.html) to score postively stained lymphocytes in the different regions. (Many thanks for providing me with the script! It worked very well) 

I am wondering if I can reduce the annotation tumor center border (black) with 500µm whereby my tumor will consist out of several bands of 500µm in width without having to repeat the cell dedetection/classification steps? Thus further subdividing the tumor center in 500 µm bands, and assess the numer of positive and negative cells in eacht band. Hereby I can check if there is a gradient in the positivity of the cells in each band. 

Thanks in advance!
Kind regards,
Lieze

**Comment by petebankhead** [comment]
Discussion now at https://forum.image.sc/t/reduce-annotations/24305
