### ISSUE TITLE
Failed to build new version of QuPath

### ISSUE THREAD

**Issue by ConnorBarnhill** [qupath/qupath#281]
**Describe the bug**
Building the newly released QuPath failed for me, I think because I had previously built an unreleased version of QuPath

```
$ ./gradlew createPackage -Ppackager=/path/to/jpackage

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for excpwkpjzwio43djg1qkbjnq0 (~/.gradle/caches/5.0/scripts-remapped/settings_e1p4q7yyg2efzivqbknt4uiri/excpwkpjzwio43djg1qkbjnq0/settingsa9190c3ddc71e1450eb3f3e7bc6a334f).
> Could not open settings generic class cache for settings file '~/.../qupath/settings.gradle' (~/.gradle/caches/5.0/scripts/excpwkpjzwio43djg1qkbjnq0/settings/settingsa9190c3ddc71e1450eb3f3e7bc6a334f).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**To Reproduce**
Not sure. 

**Expected behavior**
Build to succeed

**Desktop (please complete the following information):**
 - OS: macOS
 - QuPath Version v0.2.0-m1

**Comment by ConnorBarnhill** [comment]
I was able to fix by instead running 

```
$ ./gradlew clean build createPackage -Ppackager=/path/to/jpackage
```

Posting in case others run into this problem

**Comment by Gebrugidey** [comment]
can you help me to fix this problem , i were using flutter in vscode macos10.14, 
the problem happens after i updated the sdk 
<img width="925" alt="Screen Shot 2019-12-31 at 10 53 48 AM" src="https://user-images.githubusercontent.com/58293521/71614299-e6d7c300-2bbb-11ea-9e1f-30c171196373.png">

**Comment by petebankhead** [comment]
I don't know anything about Flutter, but you need Gradle 6.0 with JDK 13.

It's a common problem independent of QuPath - the key line to search for is *Unsupported class file major version 57*.
