### ISSUE TITLE
Right-Click on Mac

### ISSUE THREAD

**Issue by nlonberg** [qupath/qupath#285]
**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

Good, then please fill in the template about the bug...

> For general questions about the software (not bugs) use [image.sc](https://forum.image.sc/tags/qupath)

----

**Describe the bug**
In order to right click while running QuPath on macOS, one must have a mouse that can right click.  The normal control-click shortcut in the absence of a mouse does not perform a right click in QuPath.  I could easily grab a mouse, but I am lazy and would rather control-click.

**To Reproduce**
1. Attempt to right-click on a mac without a mouse.
2. Try holding control and clicking on image or annotation.
3.  Nothing happens.

**Expected behavior**
Hold down control and click on image.  The right-click menu pops up.

**Desktop (please complete the following information):**
 - OS: macOS (10.14.3)
 - QuPath Version 0.2.0 m1

**Comment by petebankhead** [comment]
Attempted fix at https://github.com/petebankhead/qupath/commit/236a7d9572c3cb159d32cbcf74e7ef0d825b0d6e
If no problems emerge in the meantime, this will be in the next milestone...

**Comment by petebankhead** [comment]
Fixed in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3).
(Please reopen if this has caused any other unwelcome behavior...)
