### ISSUE TITLE
Space bar in multiview

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#288]
**Describe the bug**
Pressing the space bar with multiple viewers open triggers an error message and the log window opening. Other than that, nothing bad seems to happen.
From v 0.1.3
"ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.setSpaceDown(QuPathViewer.java:772)"

**To Reproduce**
Open two viewers (there do not have to be images open in both), select second window press space bar. The primary window does not seem to have the same effect if there is only one image open (primary viewer has image, secondary viewer has none). If you open an image in both viewers, both viewers trigger the space bar error. Simply creating two viewers that are empty does not trigger an error when pressing space bar.

**Expected behavior**
No errors ever. At all.

**Desktop (please complete the following information):**
Win10, 64 and Win7 64
Affects versions 0.2.0m1, m2 and 0.1.3

**Additional context**

**Comment by petebankhead** [comment]
Fixed in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3)
