### ISSUE TITLE
QuPath 0.2 Can't load saved classifiers

### ISSUE THREAD

**Issue by rati333** [qupath/qupath#290]
Hi Pete,

Even though still not complete, I love this new version of QuPath. It is so much better than previous.

I'm using Pixel classifier, it works just fine on a single slide. When I save, it saves without problem as a json file. But when I try to load it and try on a different slide I can't make it work. I use load classifier tool but it won't load anything. 

It also gets little messy when I try to train on more than 2 classes, it just doesn't show the third class.

**Comment by Svidro** [comment]
I don't think the pixel classifier save/load/run for project/macro functionality is in yet. This is just the first version of it.

There are two classes that do not work for the pixel classifier, Region and Ignore. Other than those I have used up to 5-6 classes without any problems. Not that I have run into any problems with higher numbers of classes, I just have not tried :)

**Comment by petebankhead** [comment]
Yes, support to reload the classifier isn't written yet... multiple classes should work though, assuming your third class isn't 'Ignore' or 'Region' (which are handled a bit differently).

**Comment by rati333** [comment]
Thanks guys for the prompt responses. I might have used 'region' class and it didn't work the way I expected, I'll give it a try again.

**Comment by AlineKARodrigues** [comment]
O meu já foi atualizado, porém não abre imagens já salvas. Como devo proceder?

**Comment by Svidro** [comment]
It depends on which versions are you switching between. More information would be needed. I recommend starting a post on the forum for non-bug issues.
https://forum.image.sc/tags/qupath

**Comment by petebankhead** [comment]
I'll close this issue because of lack of activity, and hopefully everything has been resolved by now...
