### ISSUE TITLE
Misaligned annotations in 0.2.0-m2 created in 0.1.3 (.mxrs files, relative filepaths)

### ISSUE THREAD

**Issue by Tkilvaer** [qupath/qupath#291]
This is the log from 0.1.3
![expected output](https://user-images.githubusercontent.com/33515823/54674681-3e111900-4afd-11e9-9396-0196a9651c5d.png)

ERROR: Openslide: Property not available: openslide.level[0].tile-width
ERROR: Openslide: Property not available: openslide.level[0].tile-height
INFO: Test reading thumbnail with openslide: passed (BufferedImage@5239565c: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 86 height = 200 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0)
INFO: Returning server: OpenSlide for /media/thomas/My Passport/images/WSI/CD8_CK/CD8_CK_area_data_0.1.3/../image_files/102.mrxs
INFO: Estimating H-DAB staining
INFO: Image data set to ImageData: Brightfield (H-DAB), 102
INFO: Reading data from 102.qpdata...
INFO: Hierarchy with 153193 object(s) read from /media/thomas/My Passport/images/WSI/CD8_CK/CD8_CK_area_data_0.1.3/data/102.qpdata in 1.55 seconds

This is the log from 0.2.0-m2
![observed output](https://user-images.githubusercontent.com/33515823/54674742-541ed980-4afd-11e9-8187-f4d32bf10136.png)

WARN: Openslide: Property 'openslide.level[0].tile-width' not available, will return default value 256.0
WARN: Openslide: Property 'openslide.level[0].tile-height' not available, will return default value 256.0
INFO: Test reading thumbnail with openslide: passed (BufferedImage@4cd960db: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 147 height = 200 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0)
INFO: Returning server: OpenSlide for file:/media/thomas/My%20Passport/images/WSI/CD8_CK/CD8_CK_area_data_0.2.0-m2/../image_files/102.mrxs
INFO: Reading data from 102.qpdata...
INFO: Image data set to ImageData: Brightfield (other), 102.mrxs

**Comment by petebankhead** [comment]
See https://forum.image.sc/t/two-questions-for-qupath/23736/3?u=petebankhead

**Comment by Tkilvaer** [comment]
Ok. So this  is intended. I guess there is no plan for a "convert to 0.2.0" for older projects that may benefit from the new features.

Is there an easy way to access the x, y dimensions of the whole slide image without the bounding box in order to calculate the translation?

**Comment by petebankhead** [comment]
It should be possible to do the conversion.  In v0.2.0-m2 you can get the key information with
```groovy
print getCurrentServer().dumpMetadata()
```
or, very unofficially (i.e. by accessing private fields...), this:
```groovy
def x = getCurrentServer().boundsX
def y = getCurrentServer().boundsY
```

The next step would be to apply a translation... the affine transform [here](https://forum.image.sc/t/interactive-image-alignment/23745/9?u=petebankhead) shows one way to approach that. Although in general you can translate a ROI with
```groovy
translated = roi.translate(-100, -200)
```
so long as the `TranslatableROI` interface is implemented (I think it always is....)
