### ISSUE TITLE
qupath fails to detect cells across entire TMA

### ISSUE THREAD

**Issue by rgranit** [qupath/qupath#294]
Hello,

I'm using V. 0.2.0-m1 or m2 on a Mac computer. Anytime I attempt to detect cells across an entire TMA grid it starts and shows the progres bar, but after a few seconds the command fails - any suggestions how to solve this issue?

Thanks!

**Comment by Svidro** [comment]
If there is nothing really in the error log, I would start with upping the memory available to QuPath. The m1 and m2 have their own independent max memory settings, and default to something like 1/4 of the total available.

**Comment by rgranit** [comment]
Thanks, but I cannot increase the memory beyond 2GB (despite the fact I have 8GB). Also, I'm not sure what you mean by m1, m2..

**Comment by Svidro** [comment]
You mentioned using m1 and m2, I was just pointing out that the memory setting for QuPath 0.1.2 and 0.1.3 does not apply.

**Comment by rgranit** [comment]
Oh.. I see, thanks for the clarification. I've managed to manually edit the cfg file and set the RAM maximum to 6GB, this solve my issue. Thanks.
