### ISSUE TITLE
.vsi format only open one of scaned region in QuPath

### ISSUE THREAD

**Issue by rmd06** [qupath/qupath#296]
When I open .vsi  file in QuPath, I can see a region of 20X scanned cells. However, if I open in Olympus OlyVIA viewer, there are a a dozen of rectangular cropped regions in the whole slide overview, and one of the region was indeed the one opende in QuPath.

So how to open the other regions in .vsi file?
Thanks.

**Comment by rmd06** [comment]
I found all the regions in the imageList panel.

Is there a command to get the imageList and show one of them in the window?
 When I run the script of .vsi files, it is always the thrid image in the imageList that was open and processed.

**Comment by rmd06** [comment]
I have tried to write several lines of code to get the subimage:


def imagelist = server.getSubImageList()
print("Note: .vsi image list detected" +imagelist)
def project = getProject() //usually is null if no project opened
print(project)
if (project != null){
def entries = project.getImageList()
}
def aSubImg = imagelist.getAt(4) 
print(aSubImg) //Series 4 (20x_04)
def aSubImgPath = server.getSubImagePath(aSubImg)
print(aSubImgPath) //file:/D:/QMDownload/6/BatchII%2024%20h%206%23_20190314.vsi#4

But now I can not find a way to set the subimage as active, so as to use the server to do further stuff on current active subimage

**Comment by petebankhead** [comment]
In general, it is strongly recommended to use projects.
* If you _are not_ using a project, double-click in the image list to open an image. You can request the path with `getCurrentImageData().getServer().getPath()`
* If you _are_ using a project, add the .vsi file to a project and all images should appear.  Run your script with _Run &rarr; Run for project_ and it should be possible to process them that way.

There is some further information [here](https://groups.google.com/d/msg/qupath-users/6FNFO-nPfvA/fY-XGUsjBQAJ) but some of the issues have already been solved in v0.2.0-m1.

**Comment by rmd06** [comment]
I have to run the script from command line in this way

>QuPath  -image imahepath  -script  scriptpath

The script only deals with the current opened images, and no GUI was involved in from beginning to end.

I can get the current file path in script, then how can I add load the current file path to the project in this headless mode?

**Comment by petebankhead** [comment]
You can get the individual image paths by running
```groovy
print getCurrentImageData().getServer().getPath()
```
for the project, or try _File &rarr; Project... &rarr; Export image list_.

Command line support is currently _very_ limited. Improving this is somewhere on a (very long) todo list.

> Please note that GitHub issues is intended only for bug reports and all other discussions will be closed soon.
>
>  https://forum.image.sc/tags/qupath is the right place for other questions and discussions, since this will make it much easier to find the answers in the future.
