### ISSUE TITLE
Problem with building QuPath with Gradle

### ISSUE THREAD

**Issue by avinash0309** [qupath/qupath#297]
I am not able to build QuPath with Gradle by following the procedure.
Below is the error I'm facing to create the Package:

> Task :createPackage FAILED
Task ':createPackage' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Using packager: C:\jdk13
C:\jdk13 create-image --input C:\QuPath\build\qupath --output C:\QuPath\build\dist --main-jar qupath-0.2.0-m2.jar --name QuPath-0.2.0-m2 --app-version 0.2.0-m2 --strip-native-commands --icon C:\QuPath\build\resources\main\package\windows\QuPath.ico --runtime-image C:\QuPath\build\jre
Starting process 'command 'C:\jdk13''. Working directory: C:\QuPath Command: C:\jdk13 create-image --input C:\QuPath\build\qupath --output C:\QuPath\build\dist --main-jar qupath-0.2.0-m2.jar --name QuPath-0.2.0-m2 --app-version 0.2.0-m2 --strip-native-commands --icon C:\QuPath\build\resources\main\package\windows\QuPath.ico --runtime-image C:\QuPath\build\jre
:createPackage (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.002 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createPackage'.
> A problem occurred starting process 'command 'C:\jdk13''

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 1s
63 actionable tasks: 63 executed 

C:\jdk13 - is my JPackage path.
Any idea of what I am doing wrong?
Many thanks in advance for any help!!

**Comment by petebankhead** [comment]
You need to give the full path to jpackage (which should be inside a 'bin' directory within the JDK).
