### ISSUE TITLE
export mean values of "detection measurement" results by class

### ISSUE THREAD

**Issue by pathy007** [qupath/qupath#299]
Dear Pete,

Is it possible to export the MEAN values of all 40 parameters of detection measurements by class or region? Currently, we can extract the values only on a single cell level. 
A workaround I see is to extract the mean in the "show histogram" section and stepwise clicking through all parameters. However, this is quite laborious for a TMA with many cores. 

Best regards
Mark

**Comment by Svidro** [comment]
This is more of a question for [the forums](https://forum.image.sc/tags/qupath) than a bug, but this sort of thing can generally be [handled through scripting](https://gist.github.com/Svidro/68dd668af64ad91b2f76022015dd8a45).

It sounds like you will want to calculate the mean for all child objects, and then add that value to the TMA core, or to the annotation within the TMA core.

Also [see here](https://groups.google.com/forum/#!searchin/qupath-users/summary$20measurements%7Csort:date/qupath-users/EUMQLmBHe2g/E2_v-xsxAQAJ).

**Comment by pathy007** [comment]
Thank you Svidro,
I think this topic can be closed.
