### ISSUE TITLE
Newbie asking installation of Qupath packages

### ISSUE THREAD

**Issue by r5ljq** [qupath/qupath#303]
Hi,

I have a problem installing QuPath packages in my desktop (Window 10).

First I downloaded QuPath 0.2.0 and installed it in 'My document'.

I then downloaded;
* A Java 11 JDK from https://jdk.java.net/11/
* JPackage from https://jdk.java.net/jpackage/
* The QuPath source code from https://github.com/qupath/qupath/releases/tag/v0.2.0-m2

I unzipped above zip three zip files under 'My document' but different folder respectively.
I did not see any installation file for above files.

Then, I started a command prompt, and move to the folder containing Qupath-0.2.0.exe file.
Then I ran ./gradlew.bat createPackage -Ppackager=/path/to/jpackage
I got error message saying; '.' is not recognized as an internal or external command,
operable program or batch file.

Can anybody tell me what I have done wrong or how to have packages installed in Qupath in my situation?

**Comment by komzy** [comment]
try using .\gradlew.bat

 instead of ./

**Comment by petebankhead** [comment]
You shouldn't have to do any of that just to run QuPath - download a release by following the links on the homepage at https://qupath.github.io/ or directly from https://github.com/qupath/qupath/releases

**Comment by petebankhead** [comment]
I've updated the ReadMe to remove the (out-of-date) reference to needing to build it yourself.
https://github.com/qupath/qupath/commit/3d2331fb2f0f169c35a3bd04f6026bd0d7bfecc9
