### ISSUE TITLE
Deletion of child objects depends on order of selection

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#310]
When selecting and then deleting multiple annotations, the user is prompted whether they want to keep child objects. Only child objects of the first object selected are kept.

![image](https://user-images.githubusercontent.com/23145209/56677307-16b9e880-6675-11e9-9395-b7e0a5b3190d.png)
For an example like the above, if the yellow annotation is selected first, then the blue, and keep child objects is chosen, the two red objects will remain. If the blue annotation is selected first, then yellow, the two red objects will be deleted regardless of the keep child objects being selected.

**Expected behavior**
I think the expected behavior would be that the two red objects would remain regardless of the order of selection. I ran into this first when deleting multiple whole image annotations, and every object in the image was deleted even if I wanted to keep it. I had to script their removal or delete them one at a time.

**Desktop (please complete the following information):**
 - OS: Win10
 - QuPath Version at least 0.1.3 and 0.2.0m2

**Comment by petebankhead** [comment]
Closing this, because I think that somewhere on the way to v0.2.0 it got fixed...
