### ISSUE TITLE
Gradle build - createPackage fails

### ISSUE THREAD

**Issue by f--f** [qupath/qupath#311]
**Describe the bug**
When running `./gradlew.bat createPackage -Ppackager=/path/to/jpackage`, the createPackage task fails with the errors "Invalid Option: [create-image]" and (after fixing the first error) "Invalid Option: [--strip-native-commands]".

**To Reproduce**
1. Clone the repo and run `./gradlew.bat createPackage -Ppackager=/path/to/jpackage` (see JDK/JPackage versions below).

**Expected behavior**
Successful build.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - QuPath Version: Trying to build from latest master (da83ef9)
 - Using JDK 11 & latest JPackage executable (Build 49) downloaded from https://jdk.java.net/jpackage/

**Comment by f--f** [comment]
Following up with my solution:

- The latest version of JPackage (Build 49) has renamed the `create-image` parameter to `create-app-image`, so this line needs to be changed accordingly to `params << 'create-app-image'`:

https://github.com/qupath/qupath/blob/da83ef9e809e18e4a99bf8510c03f42217bc1579/build.gradle#L415-L419

- Running the gradle build after doing this raised the "Invalid Option: [--strip-native-commands]" error, which I resolved by commenting out this line:

https://github.com/qupath/qupath/blob/da83ef9e809e18e4a99bf8510c03f42217bc1579/build.gradle#L439-L440

My understanding from [here](https://openjdk.java.net/jeps/343) is that `--strip-native-commands` is a jlink flag, and not a jpackage one?

Let me know if you have any questions!

**Comment by petebankhead** [comment]
I've made changes on my fork at https://github.com/petebankhead/qupath/commit/bfaa0bc7aed21c28497be064da3cd2009db249cb#diff-c197962302397baf3a4cc36463dce5ea but haven't merged these back yet. For now, jpackage remains a moving target and the build script will probably need further updates as it develops...
