### ISSUE TITLE
Using same Annotation box(Ex : Rectangle) on multiple images

### ISSUE THREAD

**Issue by pranathichunduru** [qupath/qupath#313]
**QuPath's 'Issues' section on GitHub is intended for bug reports!**

**For general questions about using the software try [image.sc](https://forum.image.sc/tags/qupath)**

**For documentation & tutorials, see [Getting started](https://github.com/qupath/qupath/wiki/Getting-started)**

**Comment by petebankhead** [comment]
Is this a bug report...?

**Comment by pranathichunduru** [comment]
No I would like to know how I can use the same ROI box on multiple images .Thanks !

**Comment by Svidro** [comment]
It does link to where you should ask this in your own post. But definitely not here.

There are many methods, but a scripted one [can be found here.](https://petebankhead.github.io/qupath/scripting/2018/03/09/script-create-fixed-size-region.html)

**Comment by petebankhead** [comment]
Yes, please do not ignore the instruction to use https://forum.image.sc/tags/qupath for questions and Issues for bug reports. Many questions are repeated so it is important to know where to find them.
