### ISSUE TITLE
Feature Request: Different Color Palettes for Measurements

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#315]
Not a huge issue, but due to some Nature articles and other papers on data representation, I have been made more aware of some of the problems with using rainbow representations to show data ranges. They tend to have brighter colors along certain areas, and sometimes the low end is what the user is interested in which will always show up as dark blue/black (say nuclear size looking for lymphocytes). 
https://serialmentor.com/dataviz/color-pitfalls.html
https://www.aje.com/dist/docs/Using_Color_In_Your_Manuscript_Figures.pdf
https://betterfigures.org/2015/06/23/picking-a-colour-scale-for-scientific-graphics/

Some resources for anyone interested in reading up on the topic. The first link was mostly worth reading through the entire book.

In general, I think it would be nice to have a dropdown selection of color palettes, including the original, but defaulting to a more colorblind friendly and brightness/intensity neutral one.

**Comment by Svidro** [comment]
Also, there is no feature request option.  Though I guess that would be dangerous... :)

**Comment by petebankhead** [comment]
New color maps included in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3).

Further information in [this tweet](https://twitter.com/petebankhead/status/1145616588823040000).
