### ISSUE TITLE
Saving Pictures (png or jpg) of Single TMA cores from TMA-dearraying?

### ISSUE THREAD

**Issue by Cocomolch4000** [qupath/qupath#317]
Hi everyone :)

I was wondering if there exists maybe a simple groovy or imageJ script for saving a png or jpg picture of each core from the TMA-dearraying?

Best
Cocomolch

**Comment by Svidro** [comment]
I think the Export TMA data menu option generates small images as overviews, is that what you are looking for? Or something larger? With or without overlays?

**Comment by Svidro** [comment]
A lot more information here: https://github.com/qupath/qupath/issues/97

**Comment by Cocomolch4000** [comment]
Thank you so much! In the best case I would like to have a downsampling factor of 1, so larger!
Maybe I was too dumb to see it, because I already had this issue open, but this:

`import javax.imageio.ImageIO
import qupath.lib.regions.RegionRequest

// Define resolution - 1.0 means full size
double downsample = 1.0

// Create output directory inside the project
def dirOutput = buildFilePath(PROJECT_BASE_DIR, 'cores')
mkdirs(dirOutput)

// Write the cores
def server = getCurrentImageData().getServer()
def path = server.getPath()
for (core in getTMACoreList()){
    // Stop if Run -> Kill running script is pressed   
    if (Thread.currentThread().isInterrupted())
        break
    // Write the image
    img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, core.getROI()))
    ImageIO.write(img, 'PNG', new File(dirOutput, core.getName() + '.png'))
}
print('Done!')`

is basically what I am searching for, isn't it (I never programmed Java or Groovy)? This posted Pete in Issue 97. 

One further question: To execute this within QuPath, do I have to install something before? 

Best

**Comment by petebankhead** [comment]
No need to install anything extra to run scripts, but you can also just change the downsample for TMA export in the preferences.

> Please use the forum at https://forum.image.sc/tags/qupath for questions as described whenever you try to create an issue here... it helps keep the answers in one, searchable place. GitHub issues is intended just for bugs.

**Comment by petebankhead** [comment]
There's more info in scripts on the wiki, including https://github.com/qupath/qupath/wiki/Writing-custom-scripts

**Comment by Cocomolch4000** [comment]
Thank you so much! Sorry, I am just starting to see how much QuPath is capable of.
Your code I cited from Issue 97 is the right one for my problem?
Sorry and thank you all again!

**Comment by petebankhead** [comment]
I think so, it's probably the most relevant link. But it can vary depending on what exactly you want, e.g.
* if you are working with brightfield/fluorescence images
* if you need the pixel size to be stored in microns within the image or not
* if you want compressed images or not
* if you're using QuPath v0.1.2 (the stable one) or the more recent milestones (which are a work in progress and requires some scripts to be updated)

I'd suggest giving it a try, and starting a thread at https://forum.image.sc/tags/qupath if more customization is needed.

**Comment by Cocomolch4000** [comment]
I am working with brightfield H&E stained TMAs, which I want to import to Matlab as my hole analysis is in Matlab. I do not need to store the pixelsize in my image, neither compression. I am using 0.2 and find it very nice! :)
Thanks for your help, I will try it now!

(Btw. I have developed an algorithm which segments nuclei of mammary glands in Matlab, as ordinary watershed (also merged results from watershed with different scales) fails there, if you are interested in it I can send you the code, which is unfortunately, as mentioned earlier, not written in Java.)

**Comment by Cocomolch4000** [comment]
Works perfectly, thank you! 
One last question: As your color deconvolution works somehow faster than mine, is there a way to export the H-channel of single cores?

**Comment by petebankhead** [comment]
It's certainly possible by scripting, but it involves digging deeper into the code - which I'm currently refactoring extensively, so a script written now might not work without changed when the refactoring is done. Also, the color deconvolution in QuPath produces a 32-bit result so the file format would need to be changed accordingly (e.g. to ImageJ TIFF).

I'll close this issue: please do post any further questions on the forum so that any answers are easier to find. I will soon go through all the GitHub issues that are not active issues/bugs to close them.

**Comment by petebankhead** [comment]
During my flurry of closing, I also saw this: https://github.com/qupath/qupath/issues/202
Posting here for reference, as the solution may involve that and pieces of [ColorDeconvolutionIJ](https://github.com/qupath/qupath/blob/87730c149e3be5d3ce4fb55a4b38f27123f24a4a/qupath-core-processing/src/main/java/qupath/imagej/color/ColorDeconvolutionIJ.java#L72)...
