### ISSUE TITLE
Filtering out carbon in samples

### ISSUE THREAD

**Issue by aapierce** [qupath/qupath#319]
Following up on https://github.com/qupath/qupath/issues/172. 
This is seeking help on how to detect the carbon vs DAB staining for digital analysis without having to manually delete the carbon regions that are positive. 

I have quite a few images (TMA cores) to sort through and cannot afford to do this manually as dougzy did, so I need some more details on setting up a proper classifier for black vs. DAB.  

I have attached a couple of files with examples of one of the stainings + carbon artifact. It is easily detected by eye, but harder (for me) to get the software to tell them apart. 

![carbon1](https://user-images.githubusercontent.com/40302478/58230113-3c73f500-7ce8-11e9-986f-093cdf4192f6.jpg)
![carbon2](https://user-images.githubusercontent.com/40302478/58230114-3c73f500-7ce8-11e9-8899-ab702e622081.jpg)

**Comment by petebankhead** [comment]
Please use https://forum.image.sc/tags/qupath for questions about using the software and other related discussions - GitHub issues is intended just for issues & bugs.

Anything else here will be closed to try to keep things organized and easier to find as the project gets bigger.

**Comment by aapierce** [comment]
Sorry to put the question in the wrong place. Thank you for making QuPath.
It is amazingly useful, and I am just starting to get the hang of some of
the features... I have much to learn.

All the best!

Andrew

**Comment by petebankhead** [comment]
No problem, there have been many posted questions here but I closed about 100 of them this week :)
It's a newish policy but hope it will help.
