### ISSUE TITLE
Unable to adjust memory

### ISSUE THREAD

**Issue by TardisBlue13** [qupath/qupath#321]
Unable to adjust/set max memory in QuPath, either in 0.1.2 or 0.2.0-m2. Running analysis on cell files fails, does not detect cell direction or anything. This still does work on v 0.1.1 with 0.50GB set...

1. Go to Help > Show Setup Options
2. Change Maximum memory from the default of 1 to any number (computer has 32GB avail)
3. Click Apply
4. Close QuPath and reopen
5. Go to Help > Show Setup Options; still shows "current maximum memory is 0.48GB (v 0.1.2) or 0.50GB (v 0.2.0-m2)

**Expected behavior**
Expect Max memory to change to what was set. Installed on a separate computer and Max was set without issue. Verified in 0.2.0-m2 that the .cfg file does change each time, however it still only displays "0.50GB".

**Screenshots**
![image](https://user-images.githubusercontent.com/51007080/58358449-cc728580-7e33-11e9-9c66-5ec6cd67bb9a.png)

![image](https://user-images.githubusercontent.com/51007080/58358462-da280b00-7e33-11e9-9897-0bf811ddfa88.png)

![image](https://user-images.githubusercontent.com/51007080/58358468-deecbf00-7e33-11e9-9233-f658233afbcb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise x64, latest build
 - QuPath Version 0.1.2 & 0.2.0-m2

**Additional context**
It's possible this is occurring due to multiple upgrades. This computer looks like it was upgraded from Win 7 to Win 8 to Win 10, or just one of those to Win 10 (inherited support on this one). Also running Leica imaging software. Will most likely try a fresh re-install of the OS at this point to rule that out.

**Comment by Svidro** [comment]
Sounds familiar but I don't think there was ever a resolution. Please do post if you figure it out.
https://github.com/qupath/qupath/issues/175

**Comment by petebankhead** [comment]
This is a mystery to me....

You could try launching it from the command line. To help ensure OpenSlide can be loaded successfully, it is best to do this from within the 'app' directory found within the QuPath installation. So on Windows for v0.2.0-m2 you'd use something like this at the command prompt:
```
cd path\to\qupath\app
..\runtime\bin\java -Xmx4G -jar qupath-0.2.0-m2.jar
```
This should attempt to start QuPath with a maximum of 4GB RAM... which of course you can adjust to whatever you need. The value show appear under 'Show setup options', and you can also visualize memory use with https://petebankhead.github.io/qupath/scripting/2018/03/06/script-memory-monitor.html

Does starting the software this way make any difference to the memory available?

**Comment by TardisBlue13** [comment]
Thanks to you both. Off for a long weekend, but will try command line and let you know how that goes. I suspect there's something there from being upgraded so often that's causing issues. Thanks again!!

**Comment by TardisBlue13** [comment]
An update on this. Ended up re-installing Win10 x64 and the problem was resolved. There must have been something preventing this from working correctly before; looks like it was upgraded from win8 home to win10 home, and then multiple upgrades since then. Thank you both for your input!
running into a different problem, but will try to replicate before posting that one.

**Comment by YubinXie** [comment]
Do you have solution for MAC?

**Comment by petebankhead** [comment]
@YubinXie yes, try https://qupath.readthedocs.io/en/latest/docs/reference/faqs.html#why-can-i-not-set-the-maximum-memory

**Comment by YubinXie** [comment]
> @YubinXie yes, try https://qupath.readthedocs.io/en/latest/docs/reference/faqs.html#why-can-i-not-set-the-maximum-memory

Thanks @petebankhead. and here is the path to change for MAC:

QuPATH-Contents-app-QuPath-0.2.3.cfg
