### ISSUE TITLE
Unable to view image when part of project

### ISSUE THREAD

**Issue by nicholasjmorriss** [qupath/qupath#322]
Using v0.2.0-m2. Recently I have been unable to actually view any image on a project file. I can open the images independently no problem, but when I have opened a project and try to navigate between images within that project, nothing pops up in the viewer window. 
I have tried resetting preferences. 
Thanks for the help

**Comment by Svidro** [comment]
That usually happens when the path is broken to the image. 0.2.0 is not as.. mobile as the earlier versions. If you check "View->show log," I suspect you will find an error showing that it cannot find the image.

You would need to move the project or images back to the original location.

**Comment by nicholasjmorriss** [comment]
Solved! Hard drive somehow became the E drive rather than D. 

Thanks a ton!
