### ISSUE TITLE
Subcellular spot detection not working in ubuntu ?

### ISSUE THREAD

**Issue by matiasandina** [qupath/qupath#328]
I'm trying to do subcellular spot detection in ubuntu 18.
The menu doesn't look like the one on the wiki. Looks like it's missing options.

![image](https://user-images.githubusercontent.com/7494967/58989186-6bdb3500-87b1-11e9-82a1-39c25b9c122a.png)

I have a 3 channel image, I got a script from somebody using Windows, when trying to run from a script, spots don't get detected.

```
// Detect in DAPI (channel 3)
runPlugin('qupath.imagej.detect.nuclei.WatershedCellDetection', '{"detectionImageFluorescence": 3,  "backgroundRadius": 15.0,  "medianRadius": 0.0,  "sigma": 3.0,  "minArea": 10.0,  "maxArea": 1000.0,  "threshold": 25.0,  "watershedPostProcess": true,  "cellExpansion": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');
// Run subcellular for channel 1
runPlugin('qupath.imagej.detect.cells.SubcellularDetection', '{"detection[Channel 1]": 0.1,  "detection[Channel 2]": -1,  "detection[Channel 3]": -1,  "doSmoothing": false,  "splitByIntensity": false,  "splitByShape": false'); 

```

**Comment by Svidro** [comment]
Your metadata in the Image tab probably shows the Pixel size as unknown.  That is the normal subcellular display for an image with missing metadata. It won't work without pixel sizes.

**Comment by Svidro** [comment]
Also, if you are new to using QuPath (and are using 0.1.2 or 0.1.3), there is a good chance you have not added BioFormats, which frequently does a better job of reading the metadata. 0.2.0 includes it automatically.

**Comment by matiasandina** [comment]
I'm quite sure my file has no metadata (might have given to me from a crop on photoshop). That could explain the error, I'm trying to get metadata info (px to um). I'm using version 0.1.2

**Comment by matiasandina** [comment]
This has been fixed exporting the `.czi` file into tif from ImageJ and keeping metadata.

**Comment by Svidro** [comment]
I generally prefer to work off of the original CZI (with BioFormats), but as long as you got it working.
