### ISSUE TITLE
Running full image annotation for multiple slides at once: 

### ISSUE THREAD

**Issue by themcatguy528** [qupath/qupath#333]
Hello all, 
I have about 20 slides that need to be analyzed and I was wondering if I can annotate all of them at once or maybe 10 each time. Thanks

**Comment by petebankhead** [comment]
Please post any questions about using QuPath to the forum at https://forum.image.sc/tags/qupath
GitHub Issues is only for bug reports, following the template provided.

**Comment by themcatguy528** [comment]
I am so sorry. Will do. Thanks, Pete

**Comment by petebankhead** [comment]
No problem :)
