### ISSUE TITLE
Quantification of positive areas in TMA with staining other than DAB

### ISSUE THREAD

**Issue by takakono** [qupath/qupath#335]
Allow me to thank you for the other day's issues.
I’ve been testing out the pixel classifier in QuPath to detect the collagen deposition using Masson's trichrome stain. 
I’d like to get the percentage of collagen fiber content in the tumor stroma for each TMA cores.

Although it seems possible by classifying  group stroma (as stroma), collagen (as other), and tumor (as ignore),  I couldn’t find the way to apply the classifier for each TMA cores. 
How should I solve that? 

I will be grateful for any help you can provide.
![Masson trichrome collagen db stroma](https://user-images.githubusercontent.com/51498119/60206037-8ed49400-9807-11e9-954a-df2a647cd46b.PNG)

**Comment by petebankhead** [comment]
The pixel classifier is not yet complete, see https://forum.image.sc/t/pixel-classifier/24350

Please note that, to help keep things organized, 'GitHub issues' should _only_ be used to report bugs and not for other QuPath questions & discussions - these belong on the forum https://forum.image.sc/tags/qupath

> Lots of questions are still posted here, so advice on making this instruction more prominent would be welcome... it is currently described on the [Getting help](https://github.com/qupath/qupath/wiki/Getting-help) page and on the [New issue](https://github.com/qupath/qupath/issues/new/choose) page.
>
> ---
> ![Getting help](https://user-images.githubusercontent.com/4690904/60244082-93ee1d80-98b1-11e9-9d41-d045129cc5d6.JPG)
> 
> ---
> ![Open issue](https://user-images.githubusercontent.com/4690904/60244086-95b7e100-98b1-11e9-9534-1a6266f1f4fe.JPG)
