### ISSUE TITLE
Tiles in px Size

### ISSUE THREAD

**Issue by bpmed12** [qupath/qupath#339]
I want to have an output of Tiles with a size of 224x224. I use following script for this purpose:

`setImageType('BRIGHTFIELD_H_E');
setColorDeconvolutionStains('{"Name" : "H&E default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "Eosin", "Values 2" : "0.2159 0.8012 0.5581 ", "Background" : " 255 255 255 "}');
selectAnnotations();
runPlugin('qupath.lib.algorithms.TilerPlugin', '{"tileSizePx": 100,  "trimToROI": false,  "makeAnnotations": true,  "removeParentAnnotation": false}');

import qupath.lib.gui.ImageWriterTools
import qupath.lib.regions.RegionRequest
import qupath.lib.gui.scripting.QPEx

def path = "C:/Tiles"
def imageData = QPEx.getCurrentImageData()
def server2 = imageData.getServer()
def filename = server2.getShortServerName()

i = 1

for (annotation in getAnnotationObjects()) {

   roi = annotation.getROI()
   
   def request = RegionRequest.createInstance(imageData.getServerPath(), 
       1, roi)
   
   String tiletype = annotation.getParent().getPathClass()
   
   if (!tiletype.equals("Image")) {
   
       String tilename = String.format("%s_%s%d.jpg", filename, tiletype, i)
   
       ImageWriterTools.writeImageRegion(server2, request, path + "/" + tilename);
   
       print("wrote " + tilename)
   
       i++
       
   }

}
print("Done!")`

But this does not work. All tiles have the size of 221x221 px.
runPlugin('qupath.lib.algorithms.TilerPlugin', '{"tileSizePx": 100,  "trimToROI": false,  "makeAnnotations": true,  "removeParentAnnotation": false}');

I checked also the TilerPlugin java code. Not sure what I should do:
https://github.com/qupath/qupath/blob/master/qupath-core/src/main/java/qupath/lib/algorithms/TilerPlugin.java

Thank you very much for your excellent software and your help!

**Comment by petebankhead** [comment]
Hi @bpmed12 - glad you like the software!

I'd ask that you please help keep things organised by posting any questions at https://forum.image.sc/tags/qupath - GitHub issues should only be used for bug reports.
(There should be notifications about this when you start to open an issue.)

Although while I'm here, I'll also link to https://petebankhead.github.io/qupath/scripting/2018/03/14/script-export-labelled-images.html in case it helps provide a better starting point for your script.

If this doesn't resolve the issue, let's continue at image.sc.
