### ISSUE TITLE
Not opening JPEG-XR compressed CZI

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#34]
JPEG-XR compressed CZI files cannot be open, however the last version of bioformat can now read this format (see http://www.openmicroscopy.org/site/news/release-of-bio-formats-5.3.0 )
Any chance of having the support of this format in qupath soon ?

Best,
Benjamin

**Comment by petebankhead** [comment]
Hi Benjamin,

It should work already.  If you download the [QuPath Bio-Formats extension](https://github.com/qupath/qupath-bioformats-extension), then so long as you add the latest Bio-Formats 5.3.0 then you should get CZI support immediately.  I've tried it with a couple of images and it seems to work well.

I have some plans to update the Bio-Formats extension to incorporate [memoization](https://www.openmicroscopy.org/site/support/bio-formats5.3/developers/matlab-dev.html#improving-reading-performance) to see if it improves performance... although it shouldn't be needed for CZI support in general.

Please let me know if it works for you as well, or if you find any problems.

Thanks,

Pete

**Comment by bpavie** [comment]
Hi Pete,

Whaoou, indeed, it works perfectly, thanks a lot!
Why not to include this extension by default in the installer (or may be add an option to install it) ?
Thanks again!
Benjamin

**Comment by petebankhead** [comment]
Hi Benjamin,

Great! Glad it works, thanks for letting me know.

Regarding including the extension by default, that would definitely be handy.  It should also be quite easy technically (thanks to Maven), but until now I've been a bit apprehensive about what requirements it would place on QuPath in terms of the GPL... i.e. providing source code, licenses for Bio-Formats and all its dependencies etc.  So while I'm still learning about that side of things, I thought that requiring a separate download direct from the OME website makes things simpler in one way, even if it's a bit inconvenient.

I'll give it a bit more thought though, and hopefully will be able to come up with a more streamlined way to install it at some point.

Pete
