### ISSUE TITLE
Run for project... impact on current image

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#340]
**This is only for bug reports - for questions or discussions, please use the forum at [image.sc](https://forum.image.sc/tags/qupath) instead**
Not exactly a bug report, but it would be nice if the Run for project... command alerted the user, especially new users, to the fact that the .qpdata file would be modified in the background, without displaying any of the results to the screen in the current image.

This can result in a mis-match between the current data on screen and the result of the script that was used in Run for project..., which results in a prompt to "Save your data?" when switching images to see the results of the script. Many nervous users (myself included, long long ago) might panic and be unsure whether it was referring to the results of their run for project script, or the current objects in the open image.

Spoiler: if you do choose to save, it will overwrite the results of the script with whatever you have left over in your current image.

**Desktop (please complete the following information):**
 - OS: all
 - QuPath Version all

**Comment by petebankhead** [comment]
Yes, this is important and should be addressed to avoid confusion.

(I think _File &rarr; Revert_ can be used to 'update' the data by reading it from the [now changed] data file, but this isn't documented...)

**Comment by petebankhead** [comment]
[v0.2.0-m5](https://github.com/qupath/qupath/releases/tag/v0.2.0-m5) now shows a warning message whenever using _Run for project_ on the current image.
