### ISSUE TITLE
Points annotation saving without spacing

### ISSUE THREAD

**Issue by smujiang** [qupath/qupath#347]
## Bug report

**Describe the bug**
Point annotation export format

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Points tool'
3. Annotate serveral points, and click on "Save points"
4. Open the txt file in the .zip, See error

**Expected behavior**
There should be some space missing between words/numbers

**Screenshots**
![2019-08-02_090429](https://user-images.githubusercontent.com/23193202/62375756-983ad580-b504-11e9-944b-266c55197f11.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - QuPath Version [0.2.0-m2 and 0.2.0-m3]

**Comment by petebankhead** [comment]
I expect that this is a difference in how line breaks are represented on Windows.

It's not clear which operating system you used to write the zip, or which operating system/software you used to read the text file.

It's also not clear for what purpose you are exporting. If it is to import the points again within QuPath have you tested to confirm if this works? If for some other purpose, can you please specify?

**Comment by smujiang** [comment]
I see. That's because it's shown in Windows notpad. 
Thanks.
