### ISSUE TITLE
Outdated scripting pages

### ISSUE THREAD

**Issue by zloysmiertniy** [qupath/qupath#350]
**Bug 1**

[Writing-custom-scripts](https://github.com/qupath/qupath/wiki/Writing-custom-scripts)
scroll to Static methods in QP & QPEx
links are broken.

**Bug 2**
Advanced-scripting-with-IntelliJ shows a diffferent project structure than the current one. I can't find "contents" or "sources" so I assume that now that I am working with qupath 0.2.0 m3 the project structure has changed. Or should I clone the repository to do the optional part of adding quapth source to my scripting project?

**Comment by petebankhead** [comment]
I've updated the page to clarify that it refers to v0.1.2. Everything will need to be revised for v0.2.0, but the priority for now is to work on the code.

You'll need to clone the repository to get the code, the sources are no longer included in the distribution.
