### ISSUE TITLE
Ignore class not ignored by pixel classifier

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#354]
In m3 and m4, the pixel classifier does not skip the "Ignore" class. It shows up in the live preview and will generate objects, just like any other class. Not sure if this is a bug or how it's supposed to work now. 

![image](https://user-images.githubusercontent.com/29264310/63395608-1ad2ea00-c379-11e9-94c2-8d8987196f9c.png)

**Comment by petebankhead** [comment]
If you reset the classes, you should see `Ignore*` is the new name.

This change was partly in response to a request to make it more visually obvious which classes will be ignored, and partly to give the opportunity to create other 'ignoreable' classes (e.g.'Artefact*', 'Background*').

There's also now a method: https://github.com/qupath/qupath/blob/835edddbc9c74fa4b78e4fe1cd1d437f18b6102a/qupath-core/src/main/java/qupath/lib/objects/classes/PathClassTools.java#L29-L31

I don't know if this is a good or maintainable design choice... but I think it's better than the previous way of just treating 'Ignore' differently.

**Comment by Svidro** [comment]
Oh right. There was some request about that wasn't there...

**Comment by petebankhead** [comment]
Yes, the change was made in response to user feedback but I didn't want to point fingers :point_up:

**Comment by saramcardle** [comment]
hahaha, nice :)
I just tried resetting all my classes and saw the Ignore*. It functions as expected. Thanks!
