### ISSUE TITLE
Cell Segmentation Freezes

### ISSUE THREAD

**Issue by michaelmooreny** [qupath/qupath#356]
## Bug report

**Describe the bug**
When I open QuPath version 0.1.2 or 0.2.0 and try to run cell detection on an H&E image I have run into two different errors, both of which do not produce a cell segmentation. 

In the first type of error when I clock run the patches are created in the annotation but then no output is produced and no cells are detected and the cell detection gui allows me to click run again. 

In the second type of error after I clock run it seems as if the detection is working properly- it outputs the tasks being executed and sows patches being created but no nuclei are detected. 

**To Reproduce**
1. Go to cell detection and enter parameters
2. Click on run
3. See error

**Expected behavior**
I expected the cell segmentation algorithm to work normally. I have been able to have it run without errors many time before on my machine so I was surprised to have developed this bug. 

**Screenshots**

![image](https://user-images.githubusercontent.com/10617598/64186357-b1ed7680-ce3c-11e9-9b03-034c8eaf5de3.png)

![image](https://user-images.githubusercontent.com/10617598/64186643-2f18eb80-ce3d-11e9-832a-0d1f337f7461.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - QuPath Version : 0.1.2 or 0.2.0

**Additional context**
I have been using QuPath 0.1.2 for over a year and while every now and then I have run into similar problems with cell detection, after a few times of restarting the program it would eventually work-this time it is consistently not working. Please let me know if there is any more information I can add to help you diagnose this problem! Thanks!

**Comment by petebankhead** [comment]
I notice in your screenshot, the dialog box shows values in pixels and not µm. Is it possible that the parameters need adjusting? The defaults can be very wrong whenever the µm information is missing from your image.

It is also essential that the image type is set appropriately under the 'Image' tab. It probably is here (since I see 'Optical density sum' as an option), but it can be another source of error - especially where the background is dark, and the image might wrongly be identified as fluorescence.

**Comment by petebankhead** [comment]
You may also find useful information under _View &rarr; Show log_

**Comment by Svidro** [comment]
Wouldn't be too surprised if that log is very handy for the second image.

**Comment by michaelmooreny** [comment]
@petebankhead Over the last year the project that my team and I have worked on has used pixel units rather than µm. I set the parameter values in that image to the parameters that have been working for this project in the past. Also the image type was set correctly. 

Here is the output of the log when I run cell detection:

INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: Project set to Project: MeganQuPath
WARN: Unable to open /home/local/ARCS/tdh2124/Desktop/IntelligentDiagnosis/data/images/00_05_2_2.tif with OpenSlide: /home/local/ARCS/tdh2124/Desktop/IntelligentDiagnosis/data/images/00_05_2_2.tif: Not a file that OpenSlide can recognize
INFO: Returning server: ImageJ server for /home/local/ARCS/tdh2124/Desktop/IntelligentDiagnosis/data/images/00_05_2_2.tif
INFO: Estimating H & E staining
INFO: Image data set to ImageData: Brightfield (H&E), 00_05_2_2
INFO: Adding Rectangle to hierarchy
ERROR: Error running plugin: java.lang.OutOfMemoryError: Java heap space
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:242)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:204)
    at qupath.lib.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:134)
    at qupath.lib.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:163)
    at java.lang.Thread.run(Thread.java:745)
  Caused by Java heap space        at ij.io.ImageReader.readCompressedChunkyRGB(ImageReader.java:443)
        at ij.io.ImageReader.readChunkyRGB(ImageReader.java:368)
        at ij.io.ImageReader.readPixels(ImageReader.java:808)
        at ij.io.FileOpener.readPixels(FileOpener.java:511)
        at ij.io.FileOpener.open(FileOpener.java:104)
        at ij.io.FileOpener.openImage(FileOpener.java:51)
        at ij.plugin.FileInfoVirtualStack.getProcessor(FileInfoVirtualStack.java:184)
        at ij.plugin.Duplicator.run(Duplicator.java:207)
        at qupath.imagej.images.servers.ImageJServer.readBufferedImage(ImageJServer.java:200)
        at qupath.imagej.images.servers.ImageJServer.readBufferedImage(ImageJServer.java:1)
        at qupath.imagej.images.servers.BufferedImagePlusServer.readBufferedImage(BufferedImagePlusServer.java:163)
        at qupath.imagej.images.servers.BufferedImagePlusServer.readImagePlusRegion(BufferedImagePlusServer.java:209)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:167)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:126)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:50)
        at qupath.imagej.detect.nuclei.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:263)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:120)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO: Processing complete in 20.34 seconds
INFO: Completed with error java.lang.OutOfMemoryError: Java heap space
INFO: 
qupath.imagej.detect.nuclei.WatershedCellDetection  {"detectionImageBrightfield": "Optical density sum",  "backgroundRadius": 25.0,  "medianRadius": 3.0,  "sigma": 10.0,  "minArea": 90.0,  "maxArea": 1600.0,  "threshold": 0.2,  "maxBackground": 0.0,  "watershedPostProcess": true,  "cellExpansion": 7.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}
INFO: 0 nuclei detected (processing time: 38.87 seconds)
INFO: 0 nuclei detected (processing time: 38.88 seconds)
INFO: 0 nuclei detected (processing time: 38.87 seconds)
INFO: 0 nuclei detected (processing time: 38.88 seconds)
INFO: 0 nuclei detected (processing time: 38.87 seconds)

**Comment by Svidro** [comment]
Yep, 
ERROR: Error running plugin: java.lang.OutOfMemoryError: Java heap space

Try giving QuPath more memory using the Help->Show setup options, or free up more memory before running the program, or you might need more memory on the computer. Pete has also mentioned reducing the number of parallel processors a few places, which can be found in Preferences.

**Comment by petebankhead** [comment]
There are tips on memory at https://github.com/qupath/qupath/wiki/Troubleshooting

However the underlying problem in this case is likely that the image either isn't pyramidal, or at least isn't being read as pyramidal by OpenSlide or Bio-Formats (where Bio-Formats needs to be installed as a separate extension for v0.1.2 but not the recent milestones).

Under the 'Image' tab you can see what library was used to open the image. If it says something like 'OpenSlide server' or 'Bio-Formats server' then it is (probably) being read as an image pyramid.

If it says 'ImageJ server' (my expectation here) then it is not. Rather, the image is being read at the full resolution and all of it is being held in memory. If this is very large, then processing is _much_ less efficient.

Some changes in v0.2.0-m4 can substantially improve performance with 'quite-large-but-not-pyramidal' images.

What is the original source of the image, i.e. what software was used to write it?

**Comment by michaelmooreny** [comment]
@Svidro I just freed up the space from 24 to 80 GB and it looks like it ran but now there is a strange error where the cell segmentation seems to have been cut into different pieces and translated to the left : 

![Screenshot from 2019-09-11 10-57-48](https://user-images.githubusercontent.com/10617598/64708735-16cf4f00-d483-11e9-9342-2b3189a87b1a.png)


@petebankhead under server type in the image tab it says "Image J server". The file was produced from first scanning with an aperio scanner to produce a .scn file. An image conversion program called "objective converter" was then used to convert the files from .scn to .tif.

**Comment by petebankhead** [comment]
Is the conversion necessary? Did you try using the .scn file with QuPath directly?

**Comment by michaelmooreny** [comment]
@petebankhead I believe the conversion is necessary for other steps in the workflow for our project.

**Comment by petebankhead** [comment]
> @petebankhead under server type in the image tab it says "Image J server".
Is this true for the other images you have tried?

The strange detection issue you see may be this one: https://github.com/qupath/qupath/issues/110

This is fixed in the latest milestone releases, alongside many other issues connected to reading images with Bio-Formats or OpenSlide (including .scn).

QuPath works best with calibrated pyramidal images. It sounds like you probably have this (in the .scn), but along the way convert it to an uncalibrated, non-pyramidal TIFF - and this seems likely to be the source of the trouble.

I understand it may have worked before, but I'm not able to make any further updates to v0.1.2 - which means either switching to the (currently unfinished) milestone releases or adapting your workflow to fit with v0.1.2 to get this to work in QuPath.

**Comment by michaelmooreny** [comment]
@petebankhead yes all of the other images we have worked with have also had "Image J server" in the past. Is there a way for me to check if my tif file is pyramidal? Do you think if I begin working with 0.2.0 this may fix these problems?

**Comment by petebankhead** [comment]
I really can't say, I don't know enough about your workflow and v0.2.0 remains a work in progress to use with some caution. I would definitely advise against mixing analysis between QuPath versions: better to use one or the other.

If you are able to send one of your images then I could have a look to better understand its behavior.

**Comment by Svidro** [comment]
Yeah, it does look like the repeat ROI thing, where the ROI is one cell detection tile, so maybe limiting to 1 processor will work. It looks like the tiles weren't shifted so much as the last tile to be processed was used in place of all tiles. You can see that the cell detection is exactly the same for each tile.

**Comment by michaelmooreny** [comment]
@petebankhead I could send you one of our images, is there an email that I could send it to?

@Svidro How would I limit to one processor? Is this outlined in #110 or https://github.com/qupath/qupath/wiki/Troubleshooting ?

**Comment by michaelmooreny** [comment]
After switching to 1 processor it looks like the problems have gone away, thanks!

**Comment by petebankhead** [comment]
If you still want to send the image, you should be able to send a link by private message through the forum at https://forum.image.sc/tags/qupath
(I expect the file itself is too big to send as an attachment by email)

**Comment by petebankhead** [comment]
I'll close this issue because of lack of activity, and it has been addressed in the milestone releases (which will be the basis of the next stable release).

**Comment by michaelmooreny** [comment]
Can you please delete this thread.
