### ISSUE TITLE
Questions about Requested Pixel Size

### ISSUE THREAD

**Issue by michaelmooreny** [qupath/qupath#357]
Hi, 

I have been using QuPath's cell detection algorithm on my H&E images for over a year now and I noticed a new parameter when running it today that I had not seen in the past- Requested pixel size. I'm not sure if I accidentally chose the wrong segmentation algorithm but usually when I do the watershed cell detection it looks exactly like the image posted below except without that parameter. Let me know if there is any other information I can give to help you understand this question. Thanks!

![image](https://user-images.githubusercontent.com/10617598/64191503-a010d100-ce46-11e9-8b9b-78c79931fbe9.png)

**Comment by Svidro** [comment]
It will only show up when your pixels have a size. Your previous post showed that your images were missing metadata indicating what size each pixel was, so that option would not have been useful.

**Comment by petebankhead** [comment]
Please use http://forum.image.sc/tags/qupath for questions to help keep discussions in one centralized location - I'll close this issue because it isn't a bug report.

It is also related to my answer at https://github.com/qupath/qupath/issues/356
