### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [qupath/qupath#363]
Hello Pete,
I tried to install QuPATH latest version on linux CentOS.
I installed openjdk and JavaFX.
While I was installing with command:
./gradlew createPackage -Ppackager=~/tools/jdk-14/bin/jpackage
The following error occurred (which can also be seen from the 2 screenshots attached)
![error_message_part1](https://user-images.githubusercontent.com/9053403/65413033-1344ac00-de23-11e9-988e-3dc178c613c3.png)
![error_message_part2](https://user-images.githubusercontent.com/9053403/65413036-150e6f80-de23-11e9-9275-6fe70d290ece.png)

" Task :createRuntime
/public/home/yangzhzh/tools/jdk-12.0.2/bin/jlink --output /public/home/yangzhzh/tools/qupath-master/build/jre --add-modules java.desktop,java.xml,java.scripting,java.sql,java.naming,jdk.uns> Task :createPackage FAILED"

"FAILURE: Build failed with an exception." 

Does this mean that only this task failed (I could use some of the tasks) or the compilation failed completely?

Also, if it indicates some of the tasks can be used, is there a place showing how to use the command line to perform analyses?

I only tried it on my macMini, but it frequently aborted. That's why I switched to linux. But I wonder how to use the commands.

Looking forward to your response.
Zhenzhen

**Comment by petebankhead** [comment]
It looks like compilation mostly succeeded, but failed at the last step of creating the package. There seems to be a problem with the path provided to jpackage. It may help to give the full path explicitly rather than starting with `~`

There are quite a few discussions about using QuPath from the command line (here on GitHub or on the old Google Groups - although all further questions/discussions topics should be started at https://forum.image.sc/tags/qupath ).

The summary is that there is very minimal command line support currently - my focus for now is on interactive use & scripting within the GUI. Certainly it's intended to improve command line support eventually, but my priority is to stabilize other parts of the API first... which will in turn influence how QuPath can/should be used from the command line.

**Comment by zhenzhenyang-psu** [comment]
Hi Pete,
I gave the full path to compile, yet it still shows error:

(base) [yangzhzh@hpc-login-gpu01 qupath-master]$ ./gradlew createPackage -Ppackager=/public/home/yangzhzh/tools/jdk-14/bin
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)
Building QuPath version 0.2.0-m4
Current Java version: 12
/public/home/yangzhzh/tools/jdk-12.0.2
Operating system: Linux 3.10.0-862.14.4.el7.x86_64 amd64
Copying license directories: 
  /public/home/yangzhzh/tools/qupath-master/qupath-core/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-core-processing/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-bioformats/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-openslide/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-pen/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-processing/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-script-editor/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-gui-fx/src/main/resources/licenses
Extracting native libraries from /public/home/yangzhzh/tools/qupath-master/maven/repo/org/openslide/openslide/3.4.1_2/openslide-3.4.1_2-natives-linux.jar into build/qupath
Extracting native libraries from /public/home/yangzhzh/tools/qupath-master/maven/repo/net/sourceforge/jpen/jpen/2-150301/jpen-2-150301-natives-linux.jar into build/qupath
LICENSE PATH: /public/home/yangzhzh/tools/qupath-master/license-unknown.txt
> Task :createPackage FAILED
Using packager: /public/home/yangzhzh/tools/jdk-14/bin
/public/home/yangzhzh/tools/jdk-14/bin --input /public/home/yangzhzh/tools/qupath-master/build/qupath --output /public/home/yangzhzh/tools/qupath-master/build/dist --main-jar qupath-0.2.0-m4.jar --name QuPath-0.2.0-m4 --java-options -XX:MaxRAMPercentage=50 --app-version 0.2.0-m4 --icon /public/home/yangzhzh/tools/qupath-master/build/resources/main/package/linux/QuPath.png --runtime-image /public/home/yangzhzh/tools/qupath-master/build/jre

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createPackage'.
> A problem occurred starting process 'command '/public/home/yangzhzh/tools/jdk-14/bin''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
41 actionable tasks: 3 executed, 38 up-to-date

Any idea of why?
Thanks,
Zhenzhen

**Comment by petebankhead** [comment]
Hi, try it with `-Ppackager=/public/home/yangzhzh/tools/jdk-14/bin/jpackage`

**Comment by zhenzhenyang-psu** [comment]
Thanks for your quick reply. My bad, how could I forget to add jpackage. Yet I tried it, the error seems to be different:
  ./gradlew createPackage -Ppackager=/public/home/yangzhzh/tools/jdk-14/bin/jpackage

> Configure project :
I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)
Building QuPath version 0.2.0-m4
Current Java version: 12
/public/home/yangzhzh/tools/jdk-12.0.2
Operating system: Linux 3.10.0-862.14.4.el7.x86_64 amd64
Copying license directories: 
  /public/home/yangzhzh/tools/qupath-master/qupath-core/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-core-processing/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-bioformats/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-openslide/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-pen/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-processing/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-extension-script-editor/src/main/resources/licenses
  /public/home/yangzhzh/tools/qupath-master/qupath-gui-fx/src/main/resources/licenses
Extracting native libraries from /public/home/yangzhzh/tools/qupath-master/maven/repo/org/openslide/openslide/3.4.1_2/openslide-3.4.1_2-natives-linux.jar into build/qupath
Extracting native libraries from /public/home/yangzhzh/tools/qupath-master/maven/repo/net/sourceforge/jpen/jpen/2-150301/jpen-2-150301-natives-linux.jar into build/qupath
LICENSE PATH: /public/home/yangzhzh/tools/qupath-master/license-unknown.txt
> Task :createPackage FAILED
Using packager: /public/home/yangzhzh/tools/jdk-14/bin/jpackage
/public/home/yangzhzh/tools/jdk-14/bin/jpackage --input /public/home/yangzhzh/tools/qupath-master/build/qupath --output /public/home/yangzhzh/tools/qupath-master/build/dist --main-jar qupath-0.2.0-m4.jar --name QuPath-0.2.0-m4 --java-options -XX:MaxRAMPercentage=50 --app-version 0.2.0-m4 --icon /public/home/yangzhzh/tools/qupath-master/build/resources/main/package/linux/QuPath.png --runtime-image /public/home/yangzhzh/tools/qupath-master/build/jre
/public/home/yangzhzh/tools/jdk-14/bin/jpackage: symbol lookup error: /public/home/yangzhzh/tools/jdk-14/bin/jpackage: undefined symbol: JLI_InitArgProcessing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createPackage'.
> Process 'command '/public/home/yangzhzh/tools/jdk-14/bin/jpackage'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
41 actionable tasks: 5 executed, 36 up-to-date

**Comment by zhenzhenyang-psu** [comment]
Hi Pete,
It's okay if this doesn't work. Since command line usage is not well supported, there is no point in running it on a linux server.
I will later try this with a better Mac then. 

Thanks,,
Zhenzhen

**Comment by petebankhead** [comment]
I'm afraid `undefined symbol: JLI_InitArgProcessing` looks like some deep error independent of QuPath. I know that jpackage is also a work in progress.

I've build QuPath successfully on Windows, Mac & Ubuntu but don't know how well it works anywhere else. The build script does sometimes need to be updated whenever jpackage is updated because the command line arguments it requires change.

I'll close this issue as there doesn't seem to be a QuPath problem to solve - hope you find a solution that lets you do what you need to.

**Comment by brijeshwar2002** [comment]
Hi Pete
i tried to install qupath on my mac 
and while i was installing with command the following error occured

> Configure project :
Building QuPath version 0.2.0-m9
Current Java version: 13
/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)
Operating system: Mac OS X 10.15.4 x86_64
Copying license directories: 
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-core/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-core-processing/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-experimental/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-bioformats/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-openslide/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-pen/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-processing/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-script-editor/src/main/resources/licenses
  /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-gui-fx/src/main/resources/licenses
Extracting native libraries from /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/maven/repo/org/openslide/openslide/3.4.1_2/openslide-3.4.1_2-natives-osx.jar into build/qupath
Extracting native libraries from /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/maven/repo/net/sourceforge/jpen/jpen/2-150301/jpen-2-150301-natives-osx.jar into build/qupath
LICENSE PATH: /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/license-unknown.txt
> Task :createPackage FAILED
-------
Please specify where I can find a suitable packager!  Something like this:
gradlew createPackage -Ppackager=/full/path/to/jpackage
Current value of -Ppackager is /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/jdk-13/bin/jpackage
Note: You can also specify this in a gradle.properties file
-------

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/build.gradle' line: 622

* What went wrong:
Execution failed for task ':createPackage'.
> Please specify where I can find a suitable jpackage!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
41 actionable tasks: 16 executed, 25 up-to-date


Looking forward fro your response 
Brijeshwar,

**Comment by petebankhead** [comment]
@brijeshwar2002  you need jpackage, as described at https://qupath.readthedocs.io/en/latest/docs/reference/building.html

(Note this won't be necessary for the next release; the build script will change and require JDK 14, which includes jpackage already.)
