### ISSUE TITLE
Predict tumor percentage

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [qupath/qupath#364]
Hi Pete,
I was wondering if QuPath is capable of predicting tumor percentage.
If the answer is, could you write up a brief summary?
Thanks,
Zhenzhen

**Comment by petebankhead** [comment]
Please use https://forum.image.sc/tags/qupath for questions about using QuPath.

Also, more detail about what precisely you want would be helpful. It looks like it would be covered in the existing documentation to train a cell classifier. You will have numbers of cell for different cell types already: https://github.com/qupath/qupath/wiki/Classifying-objects

There are also links to lots more sources of information at  https://github.com/qupath/qupath/wiki/Getting-started

**Comment by zhenzhenyang-psu** [comment]
Got it, thanks for your reply! It's very helpful.
It looks like it has to do a supervised learning. Oh, I meant calculating tumor purity for H&E slides.
