### ISSUE TITLE
MPP of TIF not read by BioFormats but by Openslide

### ISSUE THREAD

**Issue by skrackow** [qupath/qupath#366]
Using QuPath 020-m4, pixel width and height are given as Unknown using Server Type Bio-Formats, but correctly shown using Server-Type OpenSlide in project Image tab, when opening a  .tif (from a Ventana Scanner).

**Comment by petebankhead** [comment]
This is a known issue in Bio-Formats, see https://forum.image.sc/t/missing-metadata-for-ventana-images-in-qupath-with-bio-formats/28123

I will close the issue as it does not appear to be a bug in QuPath.
