### ISSUE TITLE
Annotation suddenly becomes unmodifiable

### ISSUE THREAD

**Issue by VINcristin** [qupath/qupath#381]
I have difficulties reproducing the following bug, but - since it happens to me at least once daily - I am sure this doesn't happen on a random pattern:

Sometimes upon anotating an area the brush/magic wand all of a sudden won't be able to further extend the existing anotation and the miniature version of the anotation depicted next to the term 'Annotation (Geometry)' in the list on the left will have got lost. I have even tried saving the file, rebooting my PC and opening the file anew, but I still wouldn't be able to expand the annotated area and in the list of annotations, the miniature depiction of the annotation would still be gone. So, the only solution left is to delete the annotation and start a new one.
P.S.: Of course, I have also tried the Undo feature - lamentably, in vain, though...

![QuPath bug ](https://user-images.githubusercontent.com/58481912/70072532-77d87000-15f7-11ea-8ca5-68a2b23396c6.jpg)

**Comment by Svidro** [comment]
It is important to include the version, and occasionally OS. I vaguely remember something like this happening in M5, but haven't seen it in M6 or M7.

**Comment by petebankhead** [comment]
I expect it starts from the underlying Geometry becoming somehow invalid. However I don't know for sure if this is the case, haven't experienced it myself and have no idea how to reproduce it.

If you _do_ press undo, have you tried doing so multiple times? I mean, if the shape is being modified then a 'valid' version might be 'several undos back'.

Apart from that, I would likely need one or all of the following:
* the contents of _View &rarr; Show log_ (if any errors are reported)
* a .qpdata file with a misbehaving annotation
* steps or a script that enable me to reproduce it

Oh yes, and as @Svidro says - the version number is essential. If it only happens before v0.2.0-m7 then it may already have been fixed (as I have made many changes in this area).

**Comment by VINcristin** [comment]
Sorry, you're right: I am currently using QuPath 0.2.0-m6 on Windows 10 Professional

**Comment by VINcristin** [comment]
'If you do press undo, have you tried doing so multiple times? I mean, if the shape is being modified then a 'valid' version might be 'several undos back'.'
Yep, that's exactly what I hoped for but it seems as if the geometry below is somehow corrupted. The shape of the annotation is still visible on the slide an can still be moved around on the slide. However, no modification whatsoever is possible any more if this bug appears. 

I'll just try installing the M7 version. Didn't even know, M7 has already beeen released until Svidro mentioned that in his post 7 minutes ago.

I deleted the annotation just after taking the screenshot. Sorry for that. If it happens again, I will follow your instructions :)

Very pleased about your fast answer. Thanks a lot, folks! :)

**Comment by petebankhead** [comment]
I'll close this issue. Please reopen it if you it reoccurs with the latest milestone (currently m8) - especially if you can find steps to reproduce it.
