### ISSUE TITLE
Error with opening VSI files

### ISSUE THREAD

**Issue by hsynn3** [qupath/qupath#387]
Hello,

when I tried to open an image (.vsi format) of tissue with qupath m5, the image had completely wrong colors (the tissue was stained with CD3 Staining, but via qupath it looks like it's stained with LFB-PAS). The image is opened ,,normally'' (with correct coloring) on Olyvia or Ubuntu. Could this be an error with bioformat extensions? Thank you in advance!

**Comment by petebankhead** [comment]
It might be Bio-Formats related, please try opening it with Fiji. If the issue remains then it is likely Bio-Formats and not QuPath.

See also https://forum.image.sc/t/converting-vsi-to-tiff-causes-undesired-color-changes/27603

If the solution doesn't come from these, it would be helpful if you could show a screenshot with the 'Image' tab open in QuPath to make the metadata visible to help diagnose the problem.

**Comment by martyna90** [comment]
![image](https://user-images.githubusercontent.com/60140243/72807082-40815980-3c5f-11ea-8429-ef7339054b88.png)


I have similar error, the drop option doesn't work and when I just try to open image this is message I get. In previous version when bioformats weren't loaded in QuPath I could open vsi files

**Comment by petebankhead** [comment]
@martyna90 Could you copy & paste the text of the error, or else scroll up a bit when making the screenshot? The bit with the most valuable information is usually near the top of the long list of 'at' statements; I'd need to see the first lines to better understand the problem. Thanks!

As far as I recall, VSI is *only* supported through Bio-Formats, but this is built-in with v0.2.0-m8. If you are using v0.2.0-m8, but still have the *old* Bio-Formats extension installed (for v0.1.2), then I believe both may fail to work properly.

In case that's the issue, you can remove the Bio-Formats extension .jar files from QuPath's extensions folder, or use *Edit &rarr; Reset preferences* to reset the extensions folder itself in v0.2.0-m8. The second option leaves things unchanged for v0.1.2, in case you need to be able to use both versions on the same computer.

**Comment by petebankhead** [comment]
I will close this issue because of lack of activity, and it is not clear if there is an issue within QuPath that can be solved.
