### ISSUE TITLE
Checking Big TIFF images currently not supported

### ISSUE THREAD

**Issue by Echopei** [qupath/qupath#389]
### issue
I cannot do cell detection  when I use 
`ImageServerProvider.buildServer(imagePath, BufferedImage.class);`
### detail：
05:43:43.770 [main] [ERROR] q.lib.images.servers.FileFormatInfo - Checking Big TIFF images currently not supported!!!
celery_qupath_1  | 05:43:43.787 [main] [ERROR] q.l.i.s.o.OpenslideServerBuilder - Could not load OpenSlide native libraries
celery_qupath_1  | java.lang.UnsatisfiedLinkError: no openslide-jni in java.library.path: [/usr/local/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
celery_qupath_1  | 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
celery_qupath_1  | 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
celery_qupath_1  | 	at java.base/java.lang.System.loadLibrary(System.java:1902)
celery_qupath_1  | 	at org.openslide.OpenSlideJNI.<clinit>(OpenSlideJNI.java:55)
celery_qupath_1  | 	at org.openslide.OpenSlide.<clinit>(OpenSlide.java:53)
celery_qupath_1  | 	at qupath.lib.images.servers.openslide.OpenslideServerBuilder.<clinit>(OpenslideServerBuilder.java:87)
celery_qupath_1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
celery_qupath_1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
celery_qupath_1  | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
celery_qupath_1  | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
celery_qupath_1  | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
celery_qupath_1  | 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:781)
celery_qupath_1  | 	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:723)
celery_qupath_1  | 	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
celery_qupath_1  | 	at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:135)
celery_qupath_1  | 	at qupath.lib.GenowisAPI.cellSegmentation(GenowisAPI.java:69)
celery_qupath_1  | 	at qupath.lib.GenowisAPI.getPNPolygon(GenowisAPI.java:172)
celery_qupath_1  | 05:43:43.787 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - If you want to use OpenSlide, you'll need to get the native libraries (either building from source or with a packager manager)
celery_qupath_1  | and add them to your system PATH, including openslide-jni.
celery_qupath_1  | 05:43:44.319 [main] [INFO ] loci.formats.ImageReader - TiffDelegateReader initializing /mnt/sdb/docker_disk/DATA/maijie01/test1.tif
celery_qupath_1  | 05:43:44.323 [main] [INFO ] loci.formats.in.MinimalTiffReader - Reading IFDs
celery_qupath_1  | 05:43:44.336 [main] [INFO ] loci.formats.in.MinimalTiffReader - Populating metadata
celery_qupath_1  | 05:43:44.349 [main] [INFO ] loci.formats.in.TiffReader - Checking comment style
celery_qupath_1  | 05:43:44.350 [main] [INFO ] loci.formats.in.BaseTiffReader - Populating OME metadata
celery_qupath_1  | 05:43:44.364 [main] [INFO ] q.l.i.s.b.BioFormatsImageServer - No memoization file generated for /mnt/sdb/docker_disk/DATA/maijie01/test1.tif
celery_qupath_1  | 05:43:44.396 [main] [INFO ] q.l.i.servers.ImageServerProvider - Returning server: Bio-Formats for /mnt/sdb/docker_disk/DATA/maijie01/test1.tif
celery_qupath_1  | 05:43:53.593 [plugin-runner-0-1] [INFO ] q.lib.plugins.DetectionPluginTools - 0 nuclei detected (processing time: 9.12 seconds)
celery_qupath_1  | 05:43:53.610 [main] [INFO ] q.l.p.CommandLinePluginRunner$CommandLineProgressMonitor - 0 nuclei detected (100%)
celery_qupath_1  | 05:43:53.611 [main] [INFO ] q.l.p.CommandLinePluginRunner$CommandLineProgressMonitor - Processing complete in 9.14 seconds
celery_qupath_1  | 05:43:53.611 [main] [INFO ] q.l.p.CommandLinePluginRunner$CommandLineProgressMonitor - Tasks completed!
celery_qupath_1  | 05:43:53.612 [main] [INFO ] qupath.lib.plugins.AbstractPlugin - 
celery_qupath_1  | qupath.imagej.detect.cells.PositiveCellDetection  null

**Comment by petebankhead** [comment]
Please provide more information about what exactly you are doing and with which version of QuPath.

The issue seems to be that the OpenSlide native libraries are not found, which often means you are calling QuPath in some non-standard way without the Java library path set correctly. But really there is not enough information to diagnose the problem or distinguish if it is related to any bug without QuPath.

**Comment by Echopei** [comment]
qupath version 0.0.2-alpha
After I install OpenSlide native libraries

`09:47:53.189 [main] [ERROR] q.lib.images.servers.FileFormatInfo - Checking Big TIFF images currently not supported!!!
09:47:53.200 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.0
09:47:53.640 [main] [ERROR] q.l.i.s.b.BioFormatsServerBuilder - Unable to open file:/app/101.0.img.tif: {}
java.lang.NullPointerException: null
 at loci.formats.in.APLReader.isThisType(APLReader.java:98)
 at loci.formats.ImageReader.getReader(ImageReader.java:188)
 at loci.formats.ImageReader.setId(ImageReader.java:839)
 at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
 at loci.formats.Memoizer.setId(Memoizer.java:690)
 at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1148)
 at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1082)
 at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.getPrimaryReader(BioFormatsImageServer.java:996)
 at qupath.lib.images.servers.bioformats.BioFormatsImageServer.<init>(BioFormatsImageServer.java:215)
 at qupath.lib.images.servers.bioformats.BioFormatsImageServer.<init>(BioFormatsImageServer.java:179)
 at qupath.lib.images.servers.bioformats.BioFormatsServerBuilder.buildServer(BioFormatsServerBuilder.java:53)
 at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:166)
 at qupath.lib.GenowisAPI.cellSegmentation(GenowisAPI.java:69)`

**Comment by petebankhead** [comment]
There is no version with precisely the name v0.0.2-alpha. I see the error log mentions files that are not part of QuPath (e.g. `qupath.lib.GenowisAPI`), and refers indeed to 'celery_qupath_1'. Therefore it appears you are using a completely different distribution of QuPath modified by someone else and of which I know nothing. I am closing this issue because it is not related to the 'official' QuPath distribution and source code hosted here.

**Comment by Echopei** [comment]
I just want to use qupath by script

```
private String lastOpenPath = "";
    private ImageServer<BufferedImage> server;
    private ImageData<BufferedImage> imageData;
    private ObjectDetector<BufferedImage> detector;
    private Collection<PathObject> cells;
    public double threshold, thresholdPositive, expansions = 5;
    public int threadNum = 4;
    public String positiveMode = "Cell: DAB OD mean";
public Collection<PathObject> cellSegmentation(
            String imagePath,
            double x, double y,
            double width, double height
    ) throws IOException {

        if (!imagePath.equals(lastOpenPath)) {
            server = ImageServerProvider.buildServer(imagePath, BufferedImage.class);
            imageData = new ImageData<>(server, ImageData.ImageType.BRIGHTFIELD_H_DAB);
            lastOpenPath = imagePath;
        }

        RectangleROI roi = new RectangleROI(x, y, width, height);
        ROI  dup_roi =roi.duplicate();
        PathAnnotationObject object = new PathAnnotationObject();
        object.setROI(dup_roi);
        imageData.getHierarchy().getSelectionModel().setSelectedObject(object);

        PositiveCellDetection  watershedDetector = new PositiveCellDetection();
        watershedDetector.params.addDoubleParameter("threshold", "Threshold", threshold, null, "Intensity threshold - detected nuclei must have a mean intensity >= threshold");
        watershedDetector.params.addDoubleParameter("thresholdPositive1", "Threshold 1+", thresholdPositive, null, 0, 1.5);

        //ParameterList params = watershedDetector.getDefaultParameterList(imageData);
        AbstractPluginRunner.setNumThreadsRequested(threadNum);
        PluginRunner<BufferedImage> runner = new CommandLinePluginRunner<BufferedImage>(imageData,false);
        watershedDetector.runPlugin(runner,null);
        cells = imageData.getHierarchy().getSelectionModel().getSelectedObject().getChildObjects();

        return cells;
    }
```
