### ISSUE TITLE
how can i translate a .qpdata file to a json file, 

### ISSUE THREAD

**Issue by NCEPUYTL** [qupath/qupath#390]
I just open an annotated project,but i can not open it ,so is there a python script used for  translate a .qpdata file to a json file, thanks!

**Comment by petebankhead** [comment]
No, see for example https://github.com/qupath/qupath/issues/122 and also [this blog post](https://petebankhead.github.io/qupath/2019/08/21/scripting-in-v020.html#serialization--json).

> **Please avoid creating issues for anything other than bug reports; use [the forum](http://forum.image.sc/tags/qupath/) instead.**
> 
> <img width="696" alt="Issues" src="https://user-images.githubusercontent.com/4690904/71262757-5afea500-2338-11ea-8c14-91f68652c70b.png">
