### ISSUE TITLE
[wishlist] Portable version

### ISSUE THREAD

**Issue by gdeda** [qupath/qupath#391]
Hello!

As a pathologist, I use QuPath very much in my work. Though, the IT support of my institution hardly provides to install it in the hospital computers which are not assigned to the pathology department.
As I use QuPath also for labmeetings which often are held in other departments (pneumology, radiology, dermatology etc), I wonder if it would be possible to develop a portable version of QuPath.
Thank you!

**Comment by petebankhead** [comment]
I'm not sure what you mean by 'portable version', but it should be possible to use QuPath without installation, e.g. from a folder on the desktop.

For Windows, you'd need to download the .zip distribution (not the .msi - which is the only one that required installation).

**Comment by gdeda** [comment]
Hi!

Yes, for "portable" I was meaning a version quich does not require installation and thus admin priviledges.
Silly me, I hadn't tried the .zip distribution even if it was written _and it should work without further installation_ :-/

Anyway, I just tried and works as intended.
Thank you! I can flag this as closed
