### ISSUE TITLE
3DHistech .mrxs images not shown correctly

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#392]
Hello Pete,

Trying m8 in Linux just noticed .mrxs images are not correctly displayed. Attaching a shot of a H&E.

![Screenshot from 2020-01-05 15-24-57](https://user-images.githubusercontent.com/6029017/71781494-debebf80-2fcf-11ea-891d-d57a103a83de.png)

Best wishes,
Carlos

**Comment by Tkilvaer** [comment]
Hi
This is most likely due to a known issue not related to QuPath

https://forum.image.sc/t/known-issues-with-or-related-to-running-qupath-on-linux/30908

**Comment by petebankhead** [comment]
Closing this issue because I think @Tkilvaer's answer resolves it - please reopen if not.
