### ISSUE TITLE
%Area Measurement

### ISSUE THREAD

**Issue by Sakaguchi0471** [qupath/qupath#395]
Hello,

When calculating the area and %area of my ROI on ImageJ, there is an option that allows me to select and get those values. However, how would I get the %area of my ROI using QuPath? It seems like I could get the area of my image but not the %area. Is anyone aware of a method to calculate the %area manually? I am trying to skip the whole ImageJ process and solely use QuPath for this project I am working on.

**Comment by petebankhead** [comment]
**Please avoid creating issues for anything other than bug reports; use [the forum](http://forum.image.sc/tags/qupath/) instead.**

<img width="696" alt="Issues" src="https://user-images.githubusercontent.com/4690904/71262757-5afea500-2338-11ea-8c14-91f68652c70b.png">
