### ISSUE TITLE
Tiling at a particular zoom level

### ISSUE THREAD

**Issue by Mahad-M** [qupath/qupath#397]
There is a script for producing image tiles https://github.com/qupath/qupath/wiki/Tips-and-tricks
How can I make it give me tiles at a particular magnification, say 10x. In my case the pixel size in 0.4952 um, image width is 61199px, image height is 35221 px and magnification is 20x

**Comment by Svidro** [comment]
Please avoid creating issues for anything other than bug reports; [use the forum instead](http://forum.image.sc/tags/qupath/).
![image](https://user-images.githubusercontent.com/23145209/73910566-914ea000-4864-11ea-8072-8310ead5efb2.png)
