### ISSUE TITLE
Importing NDPA annotation files (code attached)

### ISSUE THREAD

**Issue by zindy** [qupath/qupath#398]
Hello,

this is to follow on the Google groups thread about [importing NDPA annotation files into QuPath](https://groups.google.com/forum/#!topic/qupath-users/xhCx_nhbWQQ).

I adapted the groovy script written by John Pan to
* work with 0.2.0-m8
* be able to import a few more shapes besides polygons (rectangles, circles, polylines, pins, lines).

The script isn't super clean (sorry if I butchered John's code, I'm very new to groovy) but works for us (Hamamatsu NanoZoomer NDPI files / NDPA generated with NDP.view 2.6.8).

Once launched, it will look for an NDPA file which has the same name as the NDPI file selected in QuPath and load all the annotations.

Then for each annotation:
* *The title* becomes the QuPath annotation's class
* *The details* are transferred to the QuPath annotation's description

Cheers,
Egor

**Attached:**   [NDPA.zip](https://github.com/qupath/qupath/files/4165181/NDPA.zip)

**Comment by petebankhead** [comment]
Thanks @zindy ! I'd recommend posting on the forum at https://forum.image.sc/tags/qupath as GitHub issues for QuPath is really intended *only* for bug reports - and anything that is resolved/isn't a bug will be closed (and therefore harder to find).

If you write something on the forum I can add a link to the (upcoming...) new documentation.

**Comment by zindy** [comment]
Thanks Pete, I just did: https://forum.image.sc/t/importing-ndpa-annotation-files-into-qupath-code-attached/33721

Kind regards,
Egor
