### ISSUE TITLE
Can't load qdata

### ISSUE THREAD

**Issue by Acmenwangtuo** [qupath/qupath#399]
when i try to open a qdata 
![图片1](https://user-images.githubusercontent.com/25858179/74319399-d4a39400-4db9-11ea-8989-d610f792d22a.png)

## IMPORTANT!

**This is only for bug reports - for questions or discussions, please use the forum at [image.sc](https://forum.image.sc/tags/qupath) instead**

## Before we begin...

**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

If not, please do these things first.

Otherwise, please fill in the template below with as much information as possible to help us reproduce the bug & fix it.

## Bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS, Ubuntu...]
 - QuPath Version [e.g. 0.1.2]

**Additional context**

**Comment by petebankhead** [comment]
There are many possible explanations (e.g. your images have changed location, you are trying to open a data file written with another version of QuPath), but without further information it is really not possible to help.

Please complete the information requested or report if the issue has been resolved.

Note that QuPath (especially v0.2.0-mx) is designed primarily for use with projects, enabling QuPath to manage your data files. Saving/reloading individual .qpdata files outside of a project is not recommended.
