### ISSUE TITLE
Labels are not displayed correctly for some image formats

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#40]
The recently added *Show slide label* command can display slide labels if there is an 'associated image' called 'label'.

This is something OpenSlide often provides, however not for all formats.  In cases where it is missing, QuPath should probably also look for an image called 'macro' instead, rather than showing nothing.

Additionally, QuPath shows associated images at full size - but this can be larger than the screen, and there is no scrollbar.  A better viewer for associated images is needed, or at the very least automatic rescaling of the image to fit the window.

> This issue was discussed at [Google Groups](https://groups.google.com/d/msg/qupath-users/ZLaN62_MD_Q/7UEhwOF-BgAJ)

**Comment by cfmoro** [comment]
Hi,

Congratulations for QuPath v2-mx series, amazing work!

Working with .ndpi files, "No label available". It would be useful to see the label in QuPath, e.g. when working with large collections of images from different experimental conditions, errors can easily occur when renaming the files after scanning, and being able to view the label would be valuable to detect possible errors, while at the same time adding an alternative to only relying on the file name for slide identification.

Kind regards,
Carlos

**Comment by Svidro** [comment]
Have you tried the Image tab macro? That is the current workaround for NDPI files for me, for now.
![image](https://user-images.githubusercontent.com/23145209/80758409-7a79bb80-8aea-11ea-85dd-5270e1ab754e.png)
Double click on the macro.

**Comment by cfmoro** [comment]
Thank you, works nicely!

Best wishes,
Carlos

**Comment by petebankhead** [comment]
Labels don't seem to be stored in a consistently identifiable away across scanners and file formats, and I'm afraid I don't think there is any reliable way for QuPath to identify automatically if a 'small image' within a larger file really is a slide label or something else.

This would all be much easier if QuPath only needed to support a few scanners, and especially if it was written with file format specifications available, but unfortunately we don't have that much information :)
