### ISSUE TITLE
Can't load a detection classifier

### ISSUE THREAD

**Issue by SWFarag** [qupath/qupath#402]
With QuPath v0.2.0, I am having an issue with loading a detection classifier. The classifier is obtained from https://github.com/acsbal/Automated-TIL-scoring-QuPath-Classifier-for-Melanoma. When I try to locate and load the classifier, the classifier window doesn't show anything. With QuPath v0.1.2 this feature works as it should. Please advise.

**Comment by petebankhead** [comment]
Classifiers trained in v0.1.2 aren't compatible with v0.2.0. Some of the many changes (e.g. to cell detection) mean that the features calculated would not be identical, and so results are expected to differ. Classifiers should really only be used in the same version of the software for which they were trained.

**Comment by SWFarag** [comment]
Thank you Pete for your clarification!
