### ISSUE TITLE
Unable to create objects after loading Simple thresholder.

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#403]
## Bug report

**Describe the bug**
_Load Classifier_ attempts, or scripts which attempt to run pixel classifiers automatically, fail without error for the _Create simple thresholder_ (experimental) function.
![image](https://user-images.githubusercontent.com/23145209/74885105-a11cb880-5329-11ea-8165-f6e20af6cc91.png)

**To Reproduce**
Create a Create simple thresholder.
Save it.
![image](https://user-images.githubusercontent.com/23145209/74885541-acbcaf00-532a-11ea-8554-2a6bf622b709.png)

(Optional) Create annotation or detection objects (Success!)
Close the pixel classifier
Load Pixel Classifier
Select your pixel classifier and see that the overlay looks correct for the previously created thresholder.
**Attempt to _Create objects_ creates no objects.**

**Expected behavior**
After loading the classifier successfully, objects are create-able.

**Screenshots**

**Desktop (please complete the following information):**
Windows7,10. QuPath 0.2.0m8,m9

Side note: _Classify Detections_, when working off of a loaded classifier, seems to try to do something, then fails with a whole lot of:
`WARN: Classification Unclassified is invalid! Will be set to null instead`

**Comment by Svidro** [comment]
Working off of the last line of the previous post, I found that I can load and create objects if I set the other areas to some sort of a classification and create objects for them as well.

Unfortunately, the primary "Above Threshold" objects are never created, which was the issue. So **objects can be created for "below" threshold classes,** but not above threshold classes. This was confusing since that behavior makes sense for brightfield images, but the current implementation favors fluorescent images until deconvolved channels are included.

**Comment by petebankhead** [comment]
Thanks, the command is unfinished & needs more attention at some point, but the fact it works for 'below threshold' is probably why I've never seen the issue (and it seemed to work for me when I tried it).

> Side note: Classify Detections, when working off of a loaded classifier, seems to try to do something, then fails with a whole lot of:
`WARN: Classification Unclassified is invalid! Will be set to null instead`

Does it fail or is it just wordy? Because warnings aren't errors, this alone does not necessarily mean it fails.

**Comment by Svidro** [comment]
Fails in the same way as above; Tumor or other "above" thresholded cells are not classified. The warning isn't important, but it did let me figure out why I thought the command wasn't working overall when loaded.

It does create "Above" objects and classify them when initially creating the classifier.

**Comment by petebankhead** [comment]
I'll close this as the proposed fix is available in v0.2.0-m10 - please reopen if the problem persists.
