### ISSUE TITLE
Detection Centroid Distance interacts awkwardly with multiplexing

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#405]
I love the new multiplex object classification in m9! However, when you calculate detection centroid distances on objects with multiple classifications, the results are difficult to interpret. It gives a separate measurement for the distance to the nearest cell of each permutation of classes individually. So, it gives the shortest distance to a cell of classA: classB, then separately to classA: classC, etc. But often what I want to know is the distance from a cell to another of classA of any subtype. Can you add a summary measurement for the shortest distance to any cell of classA, maybe like a classA*?

**Comment by Svidro** [comment]
In case this is still an issue for one of your projects, I think the best workaround would be to run each of the individual classifiers and the distance to detections right after it by script using

https://forum.image.sc/t/scripting-json-classifiers-in-qupath-0-2-0-m9/34614/2

followed by detectionCentroidDistances()

Both functions tend to run pretty fast, so it shouldn't be too problematic to write or run.

**Comment by petebankhead** [comment]
This is now included in v0.2.0-m12.
