### ISSUE TITLE
Unable to load object classifier

### ISSUE THREAD

**Issue by JayJaques** [qupath/qupath#406]
## Bug report
I've created an object classifier and I am unable to load it on other images in the project. I am also unable to reload the classifier on the image it was originally classified from. I'm working in version (0.2.0-m8), with H&E Brightfield. On a windows PC.

**To Reproduce**
1. Go to 'Automate'
2. Click on 'script editor'
3. Run script runClassifier(with its location\\classifiername.qpclassifier)

INFO: Training size: org.bytedeco.opencv.opencv_core.Size[address=0x21bc548ef30,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x21bc548ef30,deallocatorAddress=0x7fffcf445770]]
INFO: Responses size: org.bytedeco.opencv.opencv_core.Size[address=0x21bc548eee0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x21bc548eee0,deallocatorAddress=0x7fffcf445770]]
INFO: RTrees classifier termination criteria: org.bytedeco.opencv.opencv_core.TermCriteria[address=0x21bd927fa80,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x21bd927fa80,deallocatorAddress=0x7fffcf445930]]
INFO: Classifier trained with 31 samples
INFO: Reading classifier qupath.opencv.classify.RTreesClassifier@66e8a849 complete!
INFO: Classification time: 0.00 seconds
WARN: No objects classified!

I'm expecting the cells to be differentiated into immune cells and non-immune cells

**Comment by petebankhead** [comment]
I am closing this issue because you have also created an identical post on image.sc [here](https://forum.image.sc/t/object-classifier-loading-issue/34622). 

Not enough information is provided to demonstrate that there is a bug in QuPath. so I'll respond at image.sc.
