### ISSUE TITLE
Incorrect changelog link on https://github.com/qupath/qupath/releases/tag/v0.2.0-m9

### ISSUE THREAD

**Issue by manics** [qupath/qupath#407]
https://github.com/qupath/qupath/releases/tag/v0.2.0-m9: The link to the changelog in `Much more, as described on the Changelog` doesn't exist. Presumably it should be https://github.com/qupath/qupath/releases/tag/v0.2.0-m9 instead.

**Comment by petebankhead** [comment]
Thanks, fixed!
