### ISSUE TITLE
Link to OpenCV on QuPath wiki

### ISSUE THREAD

**Issue by christianrickert** [qupath/qupath#408]
Hello,

There is a minor issue with the link to OpenCV on 
`https://github.com/qupath/qupath/wiki`
which links to
`https://github.com/qupath/qupath/wiki/www.opencv.org`
instead of
`www.opencv.org`

Chris

**Comment by petebankhead** [comment]
Thanks, fixed now.

**Comment by christianrickert** [comment]
Great, thanks!
