### ISSUE TITLE
Setting Threshold for in situ hybridization experiments

### ISSUE THREAD

**Issue by vetdocjim** [qupath/qupath#409]
Dear colleagues:

I am writing to ask a question about QuPath sensitivity adjustments during in situ hybridization studies. In essence, I have been using QuPath to generate H-scores for ISH studies. The program does an excellent job of enumerating spots, binning cells into 4 categories and calculating the H-score. 

I have noticed that if I keep the same color settings and DAB threshold settings between ISH experiments, sometimes the software only recognizes a subset of the spots in the new experiment unless I adjust the color or DAB threshold. It seems like subtle changes in spot color and / or size may impact spot recognition. I was wondering if other users adjust color and / or threshold settings between experiments (or even between samples within the same experiment) to maximize spot recognition?

Thank you for your opinions.

Jim

**Comment by Svidro** [comment]
I think that since this is not an issue/bug/error, it should be posted on the forum, as indicated during the process of creating the issue :)

**Comment by vetdocjim** [comment]
Apologies...…. Will post to the forum.
