### ISSUE TITLE
Order of listed annotations is unpredictable

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#42]
The order in which annotations are listed in the *Annotations* tab is... unpredictable at best.

It would be helpful to have them sorted consistently in a similar way to how they are displayed in the *Hierarchy* tab, i.e. parent annotations first.

The possibility of changing the sorted order may also be beneficial.

**Comment by murbano89** [comment]
I also support this enhancement as a simple way that QuPath could enhance the environment. 

Another possibility would be the ability to rename annotations from the hierarchy view, which would be very helpful for many of my workflows.

**Comment by petebankhead** [comment]
Hmmm, I opened this wondering who had originally asked for this enhancement and now I see it was me....

In v0.2.0 the annotation ordering should be less 'jumpy' than it previously was, even if the exact logic is not always easy to fathom.

You can also rename annotations but selecting them in the viewer and pressing `Enter`.  @murbano89 
Is this sufficient, or would it still be helpful to be able to rename them from within the hierarchy view?  If so, would you envisage it by right-clicking and choosing 'Set properties' (like in the Annotation tab) or some other way?

**Comment by murbano89** [comment]
Thanks for considering the request. I think it would still be nice to be able to re-name within the hierarchy view. The pattern could be homologous to as in the "Annotations" view where under the "Hierarchy" view (right-click --> set-properties), so that users can predict and expect the behavior that they have already learned in the "Annotations" view ~ just as you suggested above.

**Comment by petebankhead** [comment]
Closing this now... still not possible to rename in the *Hierarchy* view (sorry), but at least in v0.2.0 one can now access a consistent annotations menu by right-clicking on the viewer.

This gives another way to set the properties, in addition to choosing from the *Annotations* tab or pressing `Enter`.
