### ISSUE TITLE
having problem in installing qupath in my mac

### ISSUE THREAD

**Issue by brijeshwar2002** [qupath/qupath#426]
Hello Pete
i tried to install qupath on my mac
and while i was installing with command the following error occured

Configure project :
Building QuPath version 0.2.0-m9
Current Java version: 13
/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)
Operating system: Mac OS X 10.15.4 x86_64
Copying license directories:
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-core/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-core-processing/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-experimental/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-bioformats/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-openslide/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-pen/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-processing/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-extension-script-editor/src/main/resources/licenses
/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/qupath-gui-fx/src/main/resources/licenses
Extracting native libraries from /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/maven/repo/org/openslide/openslide/3.4.1_2/openslide-3.4.1_2-natives-osx.jar into build/qupath
Extracting native libraries from /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/maven/repo/net/sourceforge/jpen/jpen/2-150301/jpen-2-150301-natives-osx.jar into build/qupath
LICENSE PATH: /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/license-unknown.txt
Task :createPackage FAILED

Please specify where I can find a suitable packager! Something like this:
gradlew createPackage -Ppackager=/full/path/to/jpackage
Current value of -Ppackager is /Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/jdk-13/bin/jpackage
Note: You can also specify this in a gradle.properties file
FAILURE: Build failed with an exception.

Where:
Build file '/Users/Gurjeetarora/Desktop/programming/GITHUB/qupath/build.gradle' line: 622

What went wrong:
Execution failed for task ':createPackage'.

Please specify where I can find a suitable jpackage!

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
41 actionable tasks: 16 executed, 25 up-to-date

Looking forward fro your response
Brijeshwar,

**Comment by petebankhead** [comment]
To troubleshoot installation issues, including recent Mac issues, see https://qupath.readthedocs.io/en/latest/docs/intro/installation.html

The error you get when building from source is because you need jpackage, as described at https://qupath.readthedocs.io/en/latest/docs/reference/building.html

(Note this won't be necessary for the next release; the build script will change and require JDK 14, which includes jpackage already.)
