### ISSUE TITLE
Error converting AreaROI to Geometry: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)

### ISSUE THREAD

**Issue by sdvillal** [qupath/qupath#429]
We are happy QuPath early adopters and have annotated many different images during the last year using QuPath v0.2.0m2 and v0.2.0m5. Now we are trying to convert the annotations to v0.2.0m9, wishing to get all the great benefits in later releases, specially everything related to the move to JTS.

We can convert the projects to v0.2.0m5 without problems, but when trying to convert to later versions (we have tried with v0.2.0m6 and v0.2.0m9), there are many AreaROIs that seem to carry invalid geometries and so JTS chokes. The error (using v0.2.0m9) is always the same ```Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)'```.

```java
ERROR: QuPath exception: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
    at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:94)
    at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:85)
    at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:356)
    at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:343)
    at org.locationtech.jts.geom.GeometryFactory.createPolygon(GeometryFactory.java:464)
    at qupath.lib.roi.GeometryTools$GeometryConverter.convertAreaToGeometry(GeometryTools.java:592)
    at qupath.lib.roi.GeometryTools$GeometryConverter.areaToGeometry(GeometryTools.java:492)
    at qupath.lib.roi.GeometryTools$GeometryConverter.areaToGeometry(GeometryTools.java:476)
    at qupath.lib.roi.GeometryTools$GeometryConverter.roiToGeometry(GeometryTools.java:440)
    at qupath.lib.roi.AbstractPathROI.getGeometry(AbstractPathROI.java:172)
    at qupath.lib.roi.AreaROI.getGeometry(AreaROI.java:355)
    at ...
```

This makes it impossible to use anything depending on conversion to JTS geometry: from converting to GeoJSON (our main goal) to simply view the slide. For example, this fails:

```python
GeometryTools.geometryToROI(roi.getGeometry(), roi.getImagePlane())
```
I attach a serialized example of one such ROIs, and I would be happy to send a project if needed.
[broken_area_roi.ser.tar.gz](https://github.com/qupath/qupath/files/4416890/broken_area_roi.ser.tar.gz)

 I wonder if there is anything we can do to clean these geometries before sending them to JTS.

**Comment by sdvillal** [comment]
This is how it looks like one of the offending AreaROIs. Just a hypothesis, but zooming in one can spot tiny spurious subregions that might be the cause of the error.

![Screenshot 2020-04-01 at 20 53 08](https://user-images.githubusercontent.com/642252/78175265-dfde7c00-745a-11ea-98be-62f14f087079.png)

**Comment by petebankhead** [comment]
Converting arbitrary shapes to Geometry objects has proven horribly difficult, although m9 should be better than any previous version. From your example I can see a way to improve the conversion a bit in the next release. New complex annotations should be Geometry objects immediately, avoiding the need for the conversion later.

In the meantime, this script works for me to create a slightly simplified shape that can be converted to a valid Geometry for your example:
```groovy
def file = new File('/path/to/broken_area_roi.ser')

def obj
file.withObjectInputStream {
    obj = it.readObject()
}

obj = ROIs.createAreaROI(obj.getShape(), obj.getImagePlane())
roi = qupath.lib.roi.ShapeSimplifier.simplifyShape(obj, 0.5)

println roi.getGeometry()
println roi.getGeometry().isValid()

println obj.getArea()
println roi.getGeometry().getArea()
```
The area has been changed slightly, but not by much. Perhaps this, or the *Objects &rarr; Annotations... &rarr; Simplify shape* command might help resolve the conversion for you?

**Comment by petebankhead** [comment]
You can try building the v0.2.0-m10 snapshot from the `dev` branch to see if the change helps, or alternatively wait until it is released (should be in the next week or so).

To build, you'll need to use JDK 14 (there's no longer any need to add jpackage separately as described [here](https://qupath.readthedocs.io/en/latest/docs/reference/building.html)).

**Comment by sdvillal** [comment]
Awesome, I have tried with a few images and this seems to make the trick. I will convert everything when I have a minute this weekend and hopefully close the issue.

**Comment by sdvillal** [comment]
We do not have any more problems of this type, but still have other conversion problems. I will open new issues for these and provide test cases.

Thanks a lot @petebankhead
