### ISSUE TITLE
CZI support with bioformat

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#43]
This is not really an existing issue since I solve it but I faced the problem.

In addition to drag and drop `bioformats_package.jar` and `qupath-extension-bioformats.jar`, opening the CZI files will also require to install **Visual C++ Redistributable for Visual Studio 2015** (you can find it here [https://www.microsoft.com/en-us/download/details.aspx?id=48145](https://www.microsoft.com/en-us/download/details.aspx?id=48145) ) for Microsoft Windows.
It's something I missed and made the usage of bioformat to open CZI hectic (works on some computer where Visual C++ was installed but not where it was not installed.
See https://www.openmicroscopy.org/site/support/bio-formats5.3/formats/zeiss-czi.html for the bioformat documentation.

It would be useful to add this information to the documentation.

Thanks again for this very nice software!
Benjamin

**Comment by petebankhead** [comment]
Thanks Benjamin!  That's really good to know, I had not realised that installing the redistributable was necessary.

I have added the link to https://github.com/qupath/qupath/wiki/Supported-image-formats#zeiss-czi

On the topic of CZI support, I have recently learned there may be some memory issues connected to reading CZI files that have been 'prestitched' using QuPath + Bio-Formats... is this something you have encountered / solved at all?

In the example I looked at, reading a single tile at the highest resolution would require preallocating an array that is the size of the entire full-resolution image whenever JPEG-XR compression was used... which would lead to out-of-memory errors in most cases.  However I am not clear on the exact cause of this, and any insights would be very welcome.
