### ISSUE TITLE
Cannot type in Local normalization scale box

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#432]
I think I found a tiny little bug in the GUI for the pixel classifier in m9:

Under Train Pixel Classifier  > Edit Features, there is a box where you input the Local Normalization Scale. It feels like you should be able to type in a number, but it does not accept input from the keyboard. You have to click the up and down arrows, which gets annoying if you are trying to change the value much. Could you either enable typing, or this was intentional, change the box type so that it doesn't look like a user can type?

![image](https://user-images.githubusercontent.com/29264310/78305960-14077a80-74f7-11ea-9f96-05caf9f6fabd.png)

**Comment by petebankhead** [comment]
This should ow be fixed in https://github.com/qupath/qupath/pull/438
