### ISSUE TITLE
Create new script for project- no .groovy

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#433]
Quick note, but using the  _Automate/Project Scripts/New Script_ does not automatically append .groovy to the name that is typed in, while Shared and User scripts do. Not sure if intentional. Could cause problems for people creating project scripts and then trying to run the non-groovy text file.

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version 0.2.0M9- (not sure how far back)

**Comment by melvingelbard** [comment]
I created a new script with _Automate/Project Scripts/New Script_ (and _Automate/Shared Scripts/New Script_) but it seems to add '.groovy' each time appropriately. Did you try with the latest changes (QuPath/dev, which I used to test this)?

Tested on: Windows 10/MacOS

**Comment by petebankhead** [comment]
I had the same experience as @melvingelbard using v0.2.0-m9 - I couldn't replicate the bug.

**Comment by Svidro** [comment]
Hmm, I am no longer seeing this behavior (no changes that I am aware of). It was the full release of M9. I am actually using the same project now that I was before, with untyped files still in the project Scripts folder when I was testing it before. I will reopen if I can reproduce the exact steps, since it seems to be more involved than simply happening every time.

**Comment by Svidro** [comment]
Not reopening this, but in case anyone else came across it, I was trying to put the version number in the script name for the Project, apparently. When I use a '.' within the script name, it no longer appends the .groovy since, I guess, it is assuming that anything after the last . is an extension.

Takehome, manually add .groovy to the script name, or force check the Language -> Groovy when creating scripts with a full stop in the name.
