### ISSUE TITLE
QuPathException converting AreaROIs to Geometry: Area after 0.0 => Envelop.intersects NullPointerException

### ISSUE THREAD

**Issue by sdvillal** [qupath/qupath#434]
This is a continuation from #429. After the fix in there, we have seen the number of AreaROIs we cannot convert to JTS Geometry reduced from 187 to 24. Over thousands of "naturally occurring" ROIs, so I believe conversion is becoming really robust.

On a typical error we still get, first we receive a warning "Unable to fix geometry, (area before x, **area after 0.0**)" and then a NullPointerException with a stacktrace like this (note, line numbers correspond to current 0.2.0m10 "dev" branch):

```java
WARN: Unable to fix geometry (area before: 63.93478012084961, area after: 0.0)
ERROR: QuPath exception
    at org.locationtech.jts.geom.Envelope.intersects(Envelope.java:576)
    at org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.locate(SimplePointInAreaLocator.java:71)
    at org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.isContained(SimplePointInAreaLocator.java:90)
    at qupath.lib.roi.GeometryTools$GeometryConverter.convertAreaToGeometry(GeometryTools.java:742)
    at qupath.lib.roi.GeometryTools$GeometryConverter.areaToGeometry(GeometryTools.java:509)
    at qupath.lib.roi.GeometryTools$GeometryConverter.areaToGeometry(GeometryTools.java:493)
    at qupath.lib.roi.GeometryTools$GeometryConverter.roiToGeometry(GeometryTools.java:457)
    at qupath.lib.roi.AbstractPathROI.getGeometry(AbstractPathROI.java:172)
    at qupath.lib.roi.AreaROI.getGeometry(AreaROI.java:355)
    at qupath.lib.gui.viewer.tools.AbstractPathTool.setConstrainedAreaParent(AbstractPathTool.java:231)
    at qupath.lib.gui.viewer.tools.MoveTool.mousePressed(MoveTool.java:138)
    at qupath.lib.gui.viewer.tools.AbstractPathTool.lambda$registerTool$7(AbstractPathTool.java:441)
...
```

[This is an example serialized ROI](https://github.com/qupath/qupath/files/4442109/broken_area_roi_Liver_Necroses_mf_hp_01_0.ser.tar.gz) that corresponds to this image (this kind of complex geometries happen often in our dataset, blame nature and our super-careful pathologists).

![Screenshot 2020-04-07 at 06 57 48](https://user-images.githubusercontent.com/642252/78631688-50432e00-789d-11ea-9de4-bfe43035cf3f.png)

**Side note**

We are converting this using a small qupath-as-a-python-library wrapper we are putting together (our data scientists are not fluent in java/groovy and all our other data management and ML code is in python, so somewhat this makes sense). As part of it, we have a [simple conda recipe for qupath](https://github.com/sdvillal/qupath-feedstock) capable of both repackaging releases or building qupath from source (for this I went the rabbit whole of also repackaging OpenJDK 14 over the weekend) in a continuous delivery fashion. At the moment I'm publishing these qupath packages to [my personal conda channel](https://anaconda.org/sdvillal/qupath/files). Conda packages are kind of cool in the sense that conda is a nice package manager that allows to quickly swapping qupath versions and, for example, ensuring that native libraries do not have known bugs, like, for example, [this pixman bug that made so many demos look badly](https://github.com/qupath/qupath/issues/355).

**Comment by petebankhead** [comment]
Thanks for the clear description & example - could you have a look at the pull request to see if that resolves the problem? If you're able to test it with all your thousands of ROIs that would be great, in case any new badness has been introduced.

My hope is that this will only be important for updating 'old' ROIs, since anything new created in v0.2.0 from now on will use JTS from an earlier stage and avoid the Shape &rarr; Geometry pain.

(Side note is interesting, I'll check it out!)

**Comment by sdvillal** [comment]
It seems to work, not a single failure reported. Some stats:

```
Converted 47303 regions.
43 small regions had "warnings" on conversion
The warnings affected 64 "problematic but small" regions.
Area changes stats (original_pixel_sq - fixed_pixel_sq):
mean      0.903476
std       1.829168
min      -0.032314
25%      -0.003454
50%      -0.000293
75%       0.732723
max       7.054605
```
![area_changes](https://user-images.githubusercontent.com/642252/78652097-8f837600-78c1-11ea-9345-c8e58fcf69b8.png)

We are missing some visual inspection that I hope will happen soon, but I would tentatively declare this case closed.

Thank you so much for your prompt help, this is the classiest support I have seen in quite a long time.

**Comment by sdvillal** [comment]
By the way, feel free to use the serialized regions I uploaded if you want to add some regression tests.

**Comment by petebankhead** [comment]
Excellent, thanks - I wanted to ask about using the regions in future tests.
Also the classiest bug reporting & follow-up I've seen in a long time :)
