### ISSUE TITLE
Silent crash upon start when loading a broken extension

### ISSUE THREAD

**Issue by sdvillal** [qupath/qupath#454]
Trying to run v0.2.0m10 with the Google Cloud Healthcare API extension installed crashes "silently" QuPath. This is so because the extension has not been adapted to the new QuPath API, but one needs to look at the logs (or manually run java to get them on the CLI) to figure out.

I think we could improve this by:
- Being resilient to extension errors at start time and list problematic ones with suggestions of how to look for help.
- Maybe introducing some sort of protocol for extensions to check if they are compatible with current QuPath (although this likely would add some overhead to extension maintainers). I see this would actually be a "soft" restriction asking the user whether to disable an extension or run it at her own risk.

**Comment by petebankhead** [comment]
Proposed improvement at https://github.com/petebankhead/qupath/commit/601605c0339cec278499b570972175aef65ee028
This should automatically open the log window with more information and advice.

Note that v0.2.0-m10 introduces a [BuildInfo](https://github.com/qupath/qupath/blob/master/qupath-gui-fx/src/main/java/qupath/lib/gui/BuildInfo.java) class to query QuPath's version, which may be used by developers of new extensions to help fail as elegantly as they wish.

**Comment by sdvillal** [comment]
These solutions sound good. Feel free to close when you are happy.
