### ISSUE TITLE
groovy.xml.XmlSlurper not included in build

### ISSUE THREAD

**Issue by skalteis** [qupath/qupath#455]
## Bug report

**Describe the bug**
I tried to run EP.Zindy's script for importing NDPA annotations for Hamamatsu's NDPI image files
(https://forum.image.sc/t/importing-ndpa-annotation-files-into-qupath-code-attached/33721)
and the interpreter cannot find the XmlSlurper Groovy class.
`ERROR: It looks like you have tried to import a class 'XmlSlurper' that doesn't exist!`

However, modifying the build.gradle file to include groovy-all, like this:
`	groovy "org.codehaus.groovy:groovy-all:${groovyVersion}"`
fixed this, at least for the -M10-SNAPSHOT code from last friday. :-)

**To Reproduce**
1. Install -M10
2. open NDPI file
3. try running something like this:
`def list = new XmlSlurper().parseText(text)`

**Expected behavior**
 Script running smoothly.

**Desktop (please complete the following information):**
 - OS: Windows 10, OpenJDK 14.0.1
 - QuPath Version 0.2.0-m10

Thank you!

**Comment by petebankhead** [comment]
This isn't a bug, `groovy-xml` has never been included with QuPath... you need to add it as an extension (which ought to be documented with scripts using it).

I've been wondering if it ought to be included since I know a few people have written scripts that use it, but nothing within QuPath requires it and I don't really want to increase the dependencies unnecessarily. Java has a lot built in to work with XML, even if it might not be quite as Groovy...

**Comment by skalteis** [comment]
Ah, ok - the instructions to add the extension were missing from the image.sc thread. No worries then, I can understand not wanting to inflate the number of external dependencies. Thank you!

**Comment by petebankhead** [comment]
It's probably useful enough to earn its place for scripting. Added now https://github.com/qupath/qupath/pull/452

**Comment by drbergman** [comment]
I'm trying to use a similar script for creating an annotation from an XML, but I cannot get XMLSlurper to work. If I understand this thread correctly, `groovy-xml` should be included in base QuPath. I do indeed see `groovy-xml-4.0.15.jar` in `/Applications/QuPath-0.5.0-arm64.app/Contents/app/` (I'm on an M2 Mac). I did try dropping that jar file on QuPath to add to extensions and met the same result. This is the error I get:

```
ERROR: It looks like you've tried to import a class 'XmlSlurper' that couldn't be found


ERROR: startup failed:
QuPathScript: 7: unable to resolve class XmlSlurper
 @ line 6, column 12.
   def list = new XmlSlurper().parseText(file.getText())
              ^
```

Here's the (minimal) code that produces this. Of course, the error occurs on startup, so all that matters here is the import list, I believe.
```
import qupath.lib.scripting.QP
import qupath.fx.dialogs.Dialogs
import qupath.fx.dialogs.FileChoosers

def file = FileChoosers.promptForFile("Choose file")
def list = new XmlSlurper().parseText(file.getText())
```

**Comment by petebankhead** [comment]
There should be an import statement for `XmlSlurper`, e.g.
```java
 import groovy.xml.XmlSlurper
```

**Comment by drbergman** [comment]
Thank you so much! It seems to be working now
