### ISSUE TITLE
Train pixel and object classifiers from multiple images

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#462]
'Old' detection classifiers can be trained using multiple images.

'New' object and pixel classifiers currently only support training using multiple images if these are concatenated into a single image using *Create combined training image*.

They should also support being built using training samples from multiple images, to facilitate refining classifiers later if more training becomes available.

**Comment by lacan** [comment]
Definitely +1 this. 

Also my colleagues noticed that when we use _Create combined training image_, there are edge artifacts appearing when looking at the feature maps. This is especially true for when using a rather high scale for the features.

Thanks!

**Comment by petebankhead** [comment]
Boundary artifacts are to be expected, just as if images were cropped and concatenated in any other software. But it should be possible to overcome that by ensuring that the selected regions have a bit of extra space at the sides that will not be annotated.

**Comment by petebankhead** [comment]
This is now possible in v0.2.0-m12.
