### ISSUE TITLE
Unsaved changes to project are lost without warning when closing QuPath without closing project

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#465]
Hi,

When changing e.g. the image name in a project and then exiting QuPath by File > Quit or closing the window (x) the changes are lost without warning. A warning save dialog (as with the individual images) asking to save changes to project would be useful. 

Changes are correctly saved exiting by File > Project > Close project.

Best wishes,
Carlos

**Comment by petebankhead** [comment]
Thanks @cfmoro, I'll close this since it should now be fixed in v0.2.0-m12. Just let me know if you find the issue remains.
