### ISSUE TITLE
QuPath 0.2.0-m11 Projects no longer able to recognize relative image paths

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#468]
In the previous QuPath version (0.1.3), when images were added from a location within the QuPath Project folder, these were then identified by their relative path. 

This is an issue for us now as the images are contained in QuPath project folders living on a server. When we collaborate on a common project, some of us have macs, others PCs so relative paths meant everyone could open the project at one point or another, offer modifications, and there was no need to change file paths.

Is there currently a way to have people be able to view a project on a server from different machines? Our users appreciated this feature a lot.

**Comment by petebankhead** [comment]
The behavior has been unchanged in v0.2.0 milestones for many months (without previous complaint) and it is now too late to make any substantial change before v0.2.0.

QuPath v0.1.2 handled projects in a much simpler way, but this is insufficient for many recent and planned features for which a single local file path isn't enough to identify an image.

v0.2.0 therefore stores both the absolute and relative paths. If the relative path to the project file is maintained, QuPath will show a dialog and prepopulate the necessary changes to the absolute paths to update the project. The user only has to accept these changes and the project will be updated.

This should allow everything to be 'corrected' immediately when the project is opened. If the absolute paths were *not* updated, then resolving relative paths every time they are required would be rather a lot more complex, and could result in projects being silently updated in unexpected ways (e.g. when changing an image name, trigging the project file to be rewritten). The current behavior aims to strike a compromise between being easy to use and not causing unexpected problems.

To avoid the 'update URIs' dialog in am multi-user setting, each user can duplicate the *project.qpproj* file and use the duplicate as their own view on it, i.e. they open and update the project file to contain the absolute paths relevant to them. To facilitate this, when dragging a project directory on top of QuPath one can choose the precise file to open from a drop-down list. There is also a *Recent Projects* option to reopen the last project.

> **Please respect the request to use image.sc for questions and discussions, not GitHub.**
> ![bug report](https://user-images.githubusercontent.com/4690904/80976463-68b25400-8e1b-11ea-8c19-739a35dd4942.png)

**Comment by lacan** [comment]
> To avoid the 'update URIs' dialog in am multi-user setting, each user can duplicate the project.qpproj file and use the duplicate as their own view on it, i.e. they open and update the project file to contain the absolute paths relevant to them. To facilitate this, when dragging a project directory on top of QuPath one can choose the precise file to open from a drop-down list. There is also a Recent Projects option to reopen the last project.

Thanks for the suggestion, we will be doing that then. I apologize for the use of GitHub issues. I really thought that for some reason it was not taking the relative paths in windows and not that the feature had been removed.
