### ISSUE TITLE
py4J

### ISSUE THREAD

**Issue by delta2golf** [qupath/qupath#474]
I was able to run the example with py4j. https://github.com/qupath/qupath/wiki/Working-with-Python

However, I am still not sure how to create useful scripts. 
If I want to create the script below to call from python what modifications are needed?

import qupath.lib.regions.*
import ij.*
import java.awt.Color
import java.awt.image.BufferedImage

// Read RGB image & show in ImageJ (won't work for multichannel!)
def server = getCurrentServer()
def roi = getSelectedROI()
double downsample = 4.0
def request = RegionRequest.createInstance(server.getPath(), downsample, roi)
def img = server.readBufferedImage(request)
new ImagePlus("Image", img).show()

**Comment by petebankhead** [comment]
The wiki refers to QuPath v0.1.2; the current development version is v0.2.0, with documentation at https://qupath.readthedocs.io/ - this does not contain any planned support for Py4J.

As requested in several places before submitting this issue, **please do not use GitHub issues to ask general questions**. Use instead http://forum.image.sc/tag/qupath

I will close this issue; unfortunately I am unable to help further.

![bug report](https://user-images.githubusercontent.com/4690904/81527389-0349f000-9352-11ea-8546-9d892f5986c5.png)
