### ISSUE TITLE
Qupath with tensorflow closing while running Stardist on large images

### ISSUE THREAD

**Issue by SahPet** [qupath/qupath#481]
Qupath with tensorflow build (https://qupath.readthedocs.io/en/latest/docs/advanced/stardist.html) keeps closing while running Stardist on large images. I get the following error report in the QuPath directory (hs_err_pid1260.txt - first parts of error report included) - any idea what's wrong? I see maximum memory can only be set to 32 GB, even though 64 GB is available.

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9724d7c77, pid=1260, tid=17968
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, tiered, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ff9724d7c77
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Djava.library.path=C:\Users\IT-bruker\Documents\GitHub\qupath\build\dist\QuPath-0.2.0-m12-SNAPSHOT\app;C:\Users\IT-bruker\Documents\GitHub\qupath\build\dist\QuPath-0.2.0-m12-SNAPSHOT -Djava.launcher.path=C:\Users\IT-bruker\Documents\GitHub\qupath\build\dist\QuPath-0.2.0-m12-SNAPSHOT -XX:MaxRAMPercentage=50 qupath.QuPath

Host: Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz, 20 cores, 63G,  Windows 10 , 64 bit Build 18362 (10.0.18362.778)
Time: Mon May 18 12:40:22 2020 Vest-Europa (sommertid) elapsed time: 599 seconds (0d 0h 9m 59s)

---------------  T H R E A D  ---------------

Current thread (0x00000295c2dd7000):  JavaThread "ForkJoinPool.commonPool-worker-37" daemon [_thread_in_native, id=17968, stack(0x000000f49ec00000,0x000000f49ed00000)]

Stack: [0x000000f49ec00000,0x000000f49ed00000],  sp=0x000000f49ecfe350,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007ff9724d7c77

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 15220  org.bytedeco.tensorflow.Tensor.TotalBytes()J (0 bytes) @ 0x00000295f511ebdb [0x00000295f511eba0+0x000000000000003b]
J 15218 c1 org.bytedeco.tensorflow.AbstractTensor.createBuffer(J)Ljava/nio/Buffer; (239 bytes) @ 0x00000295ee61b3b4 [0x00000295ee61b200+0x00000000000001b4]
J 15772 c1 qupath.tensorflow.TensorFlowTools.convertToMat(Lorg/bytedeco/tensorflow/Tensor;)Lorg/bytedeco/opencv/opencv_core/Mat; (126 bytes) @ 0x00000295ed11bd9c [0x00000295ed11b4e0+0x00000000000008bc]
J 15939 c1 qupath.tensorflow.TensorFlowOp$TensorFlowBundle.run(Lorg/bytedeco/opencv/opencv_core/Mat;)Lorg/bytedeco/opencv/opencv_core/Mat; (137 bytes) @ 0x00000295ed3e4534 [0x00000295ed3e37a0+0x0000000000000d94]
J 15727 c1 qupath.tensorflow.TensorFlowOp$$Lambda$2527.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00000295ed526544 [0x00000295ed5263c0+0x0000000000000184]
J 15724 c1 qupath.opencv.tools.OpenCVTools.applyTiled(Ljava/util/function/Function;Lorg/bytedeco/opencv/opencv_core/Mat;III)Lorg/bytedeco/opencv/opencv_core/Mat; (386 bytes) @ 0x00000295ee04c3a4 [0x00000295ee04aee0+0x00000000000014c4]
J 15721 c1 qupath.tensorflow.TensorFlowOp.transformPadded(Lorg/bytedeco/opencv/opencv_core/Mat;)Lorg/bytedeco/opencv/opencv_core/Mat; (64 bytes) @ 0x00000295ed0a7154 [0x00000295ed0a6c40+0x0000000000000514]
J 15720 c1 qupath.opencv.ops.ImageOps$PaddedOp.apply(Lorg/bytedeco/opencv/opencv_core/Mat;)Lorg/bytedeco/opencv/opencv_core/Mat; (35 bytes) @ 0x00000295ed1d409c [0x00000295ed1d3fa0+0x00000000000000fc]
J 15713 c1 qupath.opencv.ops.ImageOps$Core$SequentialMultiOp.apply(Lorg/bytedeco/opencv/opencv_core/Mat;)Lorg/bytedeco/opencv/opencv_core/Mat; (42 bytes) @ 0x00000295ed5c8654 [0x00000295ed5c8300+0x0000000000000354]
J 15744 c1 qupath.opencv.ops.ImageOps$DefaultImageDataOp.apply(Lqupath/lib/images/ImageData;Lqupath/lib/regions/RegionRequest;)Lorg/bytedeco/opencv/opencv_core/Mat; (74 bytes) @ 0x00000295ed0532ac [0x00000295ed052e20+0x000000000000048c]
J 14791 c2 qupath.tensorflow.stardist.StarDist2D.detectObjectsForTile(Lqupath/opencv/ops/ImageDataOp;Lqupath/lib/images/ImageData;Lqupath/lib/regions/RegionRequest;ZLorg/locationtech/jts/geom/Geometry;)Ljava/util/List; (146 bytes) @ 0x00000295f4f057b8 [0x00000295f4f05760+0x0000000000000058]
J 15706 c1 qupath.tensorflow.stardist.StarDist2D.lambda$detectObjects$1(Lqupath/lib/images/ImageData;Ljava/util/Collection;Lorg/locationtech/jts/geom/Geometry;Lqupath/lib/images/servers/TileRequest;)Ljava/util/stream/Stream; (36 bytes) @ 0x00000295ed75f334 [0x00000295ed75f160+0x00000000000001d4]
J 15743 c1 qupath.tensorflow.stardist.StarDist2D$$Lambda$2526.apply(Ljava/lang/Object;)Ljava/lang/Object; (24 bytes) @ 0x00000295ee0909ac [0x00000295ee090840+0x000000000000016c]
J 15156 c1 java.util.stream.ReferencePipeline$7$1.accept(Ljava/lang/Object;)V java.base@14.0.1 (127 bytes) @ 0x00000295edec35a4 [0x00000295edec34a0+0x0000000000000104]
J 15667 c2 java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Ljava/util/function/Consumer;)V java.base@14.0.1 (127 bytes) @ 0x00000295f51c2d44 [0x00000295f51c2c00+0x0000000000000144]
J 11772 c2 java.util.stream.AbstractPipeline.wrapAndCopyInto(Ljava/util/stream/Sink;Ljava/util/Spliterator;)Ljava/util/stream/Sink; java.base@14.0.1 (18 bytes) @ 0x00000295f4ba1aa8 [0x00000295f4ba19a0+0x0000000000000108]
j  java.util.stream.ReduceOps$ReduceTask.doLeaf()Ljava/util/stream/ReduceOps$AccumulatingSink;+15 java.base@14.0.1
j  java.util.stream.ReduceOps$ReduceTask.doLeaf()Ljava/lang/Object;+1 java.base@14.0.1
j  java.util.stream.AbstractTask.compute()V+129 java.base@14.0.1
j  java.util.concurrent.CountedCompleter.exec()Z+1 java.base@14.0.1
j  java.util.concurrent.ForkJoinTask.doExec()I+10 java.base@14.0.1
j  java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Ljava/util/concurrent/ForkJoinTask;Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)V+11 java.base@14.0.1
j  java.util.concurrent.ForkJoinPool.scan(Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)Z+185 java.base@14.0.1
j  java.util.concurrent.ForkJoinPool.runWorker(Ljava/util/concurrent/ForkJoinPool$WorkQueue;)V+25 java.base@14.0.1
j  java.util.concurrent.ForkJoinWorkerThread.run()V+24 java.base@14.0.1
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff

**Comment by petebankhead** [comment]
I'm afraid not, since `The crash happened outside the Java Virtual Machine in native code.` it will probably be very hard to debug. The actual problem has happened outside of QuPath, and the best QuPath can do is to try to avoid calling the problematic code.

Such errors have been quite common when using OpenCV, and it is a constant battle to eliminate them as far as possible...

I will look out for it, but since the TensorFlow code is still at a very early and experimental stage (and not part of the public release) I'm afraid it really isn't something I'm able to support at this stage.

If you are able to replicate it with a minimal sequence of steps and/or find any solution, please do let me know.

**Comment by SahPet** [comment]
Thanks for the reply - I'll let you know if I am able to replicate it with a minimal sequence of steps and/or find any solution:)

**Comment by petebankhead** [comment]
@SahPet can you confirm:
* Are you using TensorFlow CPU or GPU?
* Does it work for small images?
* Does it run for a bit and *then* crash terribly, or does it not run at all?

In the past with OpenCV/JavaCPP these errors have often been because an object (e.g. a Mat) has been freed too soon and then some later code tries to use it... which is often prompted by the garbage collector running during some intensive processing. If this is the issue, then I'd expect that it works for a while... and then suddenly everything disappears.

Does that fit what you're seeing?

**Comment by SahPet** [comment]
Yes, that fits. Answer to your questions below:

**Are you using TensorFlow CPU or GPU?**
First I made a Qupath Tensorflow GPU-build, but read your warnings, so I made a CPU build. Perhaps a bit more stable, but generally crashes the same way after 0 to 1 completed images trying to batch process a project.

**Does it work for small images?**
I does generally work better for small images, I think, but still crashes.

**Does it run for a bit and then crash terribly, or does it not run at all?**
It runs for several minutes to hours, then crashes.

**Comment by petebankhead** [comment]
Hmmm, I can't replicate any problem on my Mac but it will be a while before I can try it for any really long-running process. I've worked with large regions before and not seen problems like this.

I have just submitted a small commit that introduces a `nThreads(n)` option to the builder to control the parallelisation. You can also use the `doLog()` option to get a little bit more information being printed.
https://github.com/petebankhead/qupath/commit/cb9b0a7473d084f37a1482bf8426a5d8030a1dc4

You can also use the *Memory monitor* to track memory use, and occasionally force the garbage collector with the *Reclaim memory* button. It would be interesting to know if the issue coincides with garbage collection, or if the memory steadily increases with time -- regardless of garbage collection.

Please do add any further information that may be relevant (e.g. the type of the image [RGB, fluorescence], approximate size/number of nuclei, anything else that happens in your script...)

**Comment by SahPet** [comment]
For small TMA cores and small biopsies (*.vsi and *.ndpi files, H-DAB, RGB, 100 - 500 mb, small images with one core or biopsy per image) the simple tissue detection and Stardist script often worked through the entire project in batch mode, about 100 images, without issues. For whole slides image projects (100 mb - 3,5 GB images) it can do 0 -1 images before crashing and more often crashes on the gigabyte whole slide images, so some sort of memory trouble can indeed be a possible issue (the m12 Tensorflow Qupath build only allows 32 GB memory I see, even though 64 GB is available - any way of forcing it to expand that?).

**Comment by petebankhead** [comment]
How does the limit reveal itself?

**Comment by SahPet** [comment]
Not quite sure what you mean, but Qupath just closes. Attaching some error reports.

[hs_err_pid19784.log](https://github.com/qupath/qupath/files/4650037/hs_err_pid19784.log)
[hs_err_pid1100.log](https://github.com/qupath/qupath/files/4650038/hs_err_pid1100.log)
[hs_err_pid17304.log](https://github.com/qupath/qupath/files/4650039/hs_err_pid17304.log)

**Comment by petebankhead** [comment]
I mean the memory limit - does it show an error, or just ignore your request? How are you setting the request for increased memory?
Is 64 GB the total amount for the system, or the total amount you want QuPath to use?
Is the behavior any different in v0.2.0-m11?

I do not recall any intentional change that would make this any different from m11, but I don't have so much RAM myself...

**Comment by SahPet** [comment]
Oh, that limit :) Trying to change the maximum memory from 32 to e.g. 50 gb in the initial setup screen does not work, just goes back to 32, even after restarting the program. I think I managed to change it higher than 32 gb in a previous milestone version.

**Comment by petebankhead** [comment]
It's not something I'm able to check, and it probably wouldn't resolve the issue anyway - at best it might delay it. But you can enter an `-Xmx` value for memory in the java options of the `.cfg` file. This is all the prompt is trying to do anyway.

If it doesn't impact QuPath on startup, then I don't have a solution that... since the menu can't be readjusted after startup.

**Comment by SahPet** [comment]
Ok, I understand. No one expects support on one week old experimental features on an experimental build of a testversion of 0.2.0:) Got an error message from Windows this time, by the way, and it seems to be a memory issue.

![error message qupath memory](https://user-images.githubusercontent.com/43611111/82339241-1d3ca000-99ee-11ea-830f-7595fa33621b.png)

**Comment by SahPet** [comment]
And this is the memory monitor and system monitor right before it crashes.

![Skjermbilde (199)](https://user-images.githubusercontent.com/43611111/82342768-524af180-99f2-11ea-9d24-27af3ab82c7f.png)

**Comment by petebankhead** [comment]
Hmmm, so the rising memory is to be expected - but it should decrease again any time the garbage collector/Reclaim memory is called.

I've just tried it several times with a moderately large region (> 50,000 nuclei) on my moderately old computer and can find no sign of a memory leak. You'll certainly have more threads on your better computer than my meagre 8, but I found it worked fine... sometimes rising > 10 GB, but regularly dropping down to ~1.5 GB when the garbage collector was triggered (either automatically or manually). And after everything was done, if I cleaned up the objects the memory use for QuPath as a whole went down to < 400 MB... so nothing was lingering too long.

However I've just made a change that will try to make memory available again sooner: https://github.com/petebankhead/qupath/commit/9d2150ae1d2b08e6eefd2d9800baf6eecf6336cc
This may or may not help. You could also try the `nThreads()` option. Your bug report indicates you've 20 cores... not sure if that means 20 threads are working with stardist, or 40. Either way, it's probably worth reducing that number, e.g. by inserting `nThreads(10)` to your script in the place where the stardist model is being customized.

Finally, from the look of your profiling, QuPath never gets close to its personal maximum of 32 GB -- but your 64 GB is pretty much full. Could something else be stealing memory that QuPath really wants?

**Comment by petebankhead** [comment]
https://visualvm.github.io is also excellent for finding out exactly what is using up memory.

**Comment by SahPet** [comment]
Thanks for the tip. 
![Skjermbilde (205)](https://user-images.githubusercontent.com/43611111/82345329-6e9c5d80-99f5-11ea-9534-a5303ee739bf.png)
Seems like the 64 GB system memory fills up quite quickly, while the Qupath program itself in the windows systems monitor actually reads out as using much less memory (down below 1 GB at times) after a while (while 99 percent of the system memory still used).

**Comment by petebankhead** [comment]
That *might* be normal behavior with Java... I'm not 100% sure but I think that, by default, once Java has grabbed some memory, it is reluctant to give it back until shutting down. But it shouldn't go beyond the maximum of 32 GB.

Since it is calling TensorFlow and OpenCV, which are outside Java's normal world, normal rules might not apply entirely. The last changes I made are my current best guess for something that might help.

**Comment by SahPet** [comment]
Thanks again. Tried to rebuild Qupath to get the new changes, but now the build failed. Updated Java, maybe I need a previous version of Java... Anyway, here is the command prompt with the failed build. Don't want to take more of your time, Pete, so just leave it if you feel like it's unimportant:

Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. Med enerett.

C:\Users\IT-bruker\Documents\GitHub\qupath>gradlew clean build createPackage -Ptensorflow-cpu=true
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Building QuPath version 0.2.0-m12-SNAPSHOT
Current Java version: 1.8
C:\Program Files (x86)\Java\jre1.8.0_251
I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)
Operating system: Windows 10 10.0 x86
You appear to be using a 32-bit JDK - If I can't find a 32-bit version of JavaFX, this will fail! Probably at the 'test' stage.
Requesting TensorFlow (CPU) subproject
Copying license directories:
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-core\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-core-processing\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-bioformats\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-openslide\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-pen\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-processing\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-script-editor\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-extension-svg\src\main\resources\licenses
  C:\Users\IT-bruker\Documents\GitHub\qupath\qupath-gui-fx\src\main\resources\licenses

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\IT-bruker\Documents\GitHub\qupath\build.gradle' line: 569

* What went wrong:
A problem occurred evaluating root project 'qupath'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find tensorflow-1.15.2-1.5.3-windows-x86.jar (org.bytedeco:tensorflow:1.15.2-1.5.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/bytedeco/tensorflow/1.15.2-1.5.3/tensorflow-1.15.2-1.5.3-windows-x86.jar
   > Could not find mkl-dnn-0.21.4-1.5.3-windows-x86.jar (org.bytedeco:mkl-dnn:0.21.4-1.5.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/bytedeco/mkl-dnn/0.21.4-1.5.3/mkl-dnn-0.21.4-1.5.3-windows-x86.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

C:\Users\IT-bruker\Documents\GitHub\qupath>

**Comment by SahPet** [comment]
Uninstalled Java and was able to make a new build from the updated master - and now, (so far) IT WORKS! No seeming memory leakage (system RAM use keeps under 45 GB, not contantly pushing 64 GB like before). Did not add any nThreads() command or anything, so I guess it's your memory trick that did the trick:
"[...] However I've just made a change that will try to make memory available again sooner: petebankhead@9d2150a
This may or may not help. [...]"

Thanks so much, Pete!

**Comment by petebankhead** [comment]
Excellent - I hope it continues! I'll close the issue for now then.

Let me know if the problem resurfaces, otherwise I'll investigate if the same trick might help elsewhere in the software.
