### ISSUE TITLE
Failed to launch JVM (SOLVED)

### ISSUE THREAD

**Issue by PT312** [qupath/qupath#497]
Hello,

I've recently installed the most recent version of QuPath (0.2.0-m12) and am getting an error message saying "Failed to launch JVM" when I try to launch the software.

I am opening the software by double clicking on the actual QuPath application, not through opening a .svs file or any other image file.

I had a similar issue when I installed a new-at-the-time vesion of QuPath (0.2.0-m8) but was eventually able to run it through means that I do not recall.

Can anyone please help me out with what could be going wrong? I've attached a log from the debug version when I try to open it. I'm not very strong in computer science so unfortunately I could not decipher these hieroglyphics.

-Phil 

![Qupath Error](https://user-images.githubusercontent.com/62361137/82617731-dda8bc00-9b85-11ea-8a6f-5f85cc40539a.PNG)

**Comment by wongdickson89** [comment]
I have the same problem with m12. At the beginning I tried to load a SCN file and it worked. After I closed the and opened the m12 version again the message poped out and I cannot run the m12 anymore.

**Comment by Svidro** [comment]
Have you tried removing the Weka extension? I don't think that has been updated since 0.1.2.

**Comment by PT312** [comment]
> I have the same problem with m12. At the beginning I tried to load a SCN file and it worked. After I closed the and opened the m12 version again the message poped out and I cannot run the m12 anymore.

UPDATE: After another examination of the debug log I saw that the error message came after QuPath tried to load extensions. I had previously installed the Weka extension which was still in my extentions folder. I removed the weka extention and it opened without problems.

**Comment by PT312** [comment]
> Have you tried removing the Weka extension? I don't think that has been updated since 0.1.2.

Yes I just realized a few minutes ago that it was the Weka extention that might have been causing the problem, which it was.

**Comment by wongdickson89** [comment]
Where could you find the Weka extention? thanks

**Comment by PT312** [comment]
> Where could you find the Weka extention? thanks

For me it was in C:\Users\(Your Name)\QuPath\extensions

It was in the 7th line of code in the debug image from my original post above.

Weka is an extension that I downloaded for a previous project so it must have been outdated (as suggested by @Svidro above). I would try removing all extensions to rule out any outdated / buggy ones causing the issue.

If removing all the extensions does not work, could you post a screenshot of a log after opening QuPath through the debug application?

**Comment by wongdickson89** [comment]
Thanks. Never aware of that folder which has the extension. Now it is working! Thanks so much!

**Comment by PT312** [comment]
> Thanks. Never aware of that folder which has the extension. Now it is working! Thanks so much!

Neither was I until 15 minutes ago. Glad we both got it working.

**Comment by petebankhead** [comment]
Glad it's resolved - I've just made a small change that will hopefully make QuPath's inability to load the old Weka extension a bit more graceful in v0.2.0, and also added a note on the downloads page for the extension to warn that it is incompatible.

**Comment by wongdickson89** [comment]
Hi Pete,

Sorry I just saw your email in the junkbox. Thanks for informing that.
I have tried to look up the new writings for calling imageJ somewhere and modified a bit in my script and now it is working.

P.S. I am a very beginner for writing the script.
