### ISSUE TITLE
QuPath m12 - Selected images in Run for project persist in the dialog window

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#501]
Hi,

In m12, when executing a script by "Run for project" and selecting the target images, these keep appearing in the "Selected" panel when the "Run for project" dialog is opened again, even after closing the project and reopening another one.

Kind regards,
Carlos

**Comment by petebankhead** [comment]
Thanks @cfmoro, I think it should now be fixed by the last commit.
