### ISSUE TITLE
m12 - Error dialog(s) appear when closing QuPath after work with pixel classifiers

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#503]
Hi,

It occurred that after being working with pixel classifiers and closed the project, when quitting QuPath one or several error dialogs appear briefly in the bottom right corner of QuPath window (as in screenshot).

![image](https://user-images.githubusercontent.com/6029017/82741310-18ab1b00-9d51-11ea-876b-c0a653d28279.png)

Best regards,
Carlos

**Comment by petebankhead** [comment]
The last commit should avoid showing an error message unnecessarily.
