### ISSUE TITLE
Class label entry adds space after a colon

### ISSUE THREAD

**Issue by tvalerius** [qupath/qupath#507]
(Yes, did search for this bug before entering this issue.)

## Bug report

**Describe the bug**
When pasting in or typing in class names that include a colon in the text, QuPath adds a spce after the colon and this is also the resulting label in the class json file. 
 
**To Reproduce**
1. Add a new class and a name that includes a colon without a trailing space. For example `myID:1234` 

2. After adding the class, simply look at the resulting class name. In my insance there is now a space between the `myID:` and the `1234` to get `myID: 1234`

**Expected behavior**
I expect the pasted or typed text to be exactly the same in the resulting class label. The goal for us is to use these tags for parsing links down the road. In our case we are entering anatomy IDs from ontologies.

**Screenshots**
![Screenshot 2020-05-29 19 57 29](https://user-images.githubusercontent.com/8427219/83314085-c3ef2080-a1e6-11ea-90be-811622ed6c86.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5 (19F96)
 - QuPath Version : QuPath-0.2.0-m12.app

**Additional context**
Eventually we would want to get the classes assigned to various annotations exported so it is important to get the IDs correctly formatted if possible.

**Comment by petebankhead** [comment]
This is intended behavior that cannot be easily changed; doing so could cause many other problems.

The colon is used as a separator indicating 'sub-classifications'.
https://qupath.readthedocs.io/en/latest/docs/concepts/classifications.html#double-positive-triple-positive
You may instead need to use an alternative separator, and replace it later.

**Comment by tvalerius** [comment]
OK, and thanks for the swift response! We will change our separator and handle it in scripts outside of QuPath.
