### ISSUE TITLE
CLI does not load image

### ISSUE THREAD

**Issue by rvanguri** [qupath/qupath#513]
I can't seem to get the CLI to load an image. I am trying this:

/Applications/QuPath-0.2.0.app/Contents/MacOS/QuPath-0.2.0 --image=/fullpath_to_image/image.svs script /fullpath_to_script/run.groovy

run.groovy only contains:
import qupath.lib.scripting.QP
import qupath.lib.gui.scripting.QPEx
print QP.getCurrentImageData()

The script only prints "null" and any further scripting, such as loading a pixel classifier, does not initiate,. If I take out everything starting at script QuPath successfully loads the image in the GUI so there are no clear issues with the path or the image itself.

Any advice would be appreciated!

**Comment by petebankhead** [comment]
I'm not sure if you're basing this on out-of-date documentation for v0.1.2. See:
* https://qupath.readthedocs.io/en/latest/docs/advanced/command_line.html
* https://github.com/qupath/qupath/issues/511
* https://forum.image.sc/t/unexpected-command-line-usage-in-0-2-0-m10-and-greater/38548

**Comment by rvanguri** [comment]
My command should be consistent with the latest documentation. The script does in fact run but it prints "null" for the current image data which seems to mean that the image is never loaded. If I try to run a pixel classifier in the same script I get an error which seems consistent with the image not being loaded:

UnsupportedOperationException at line 9: Interface can't be instantiated! Interface name: qupath.lib.classifiers.pixel.PixelClassifier

**Comment by petebankhead** [comment]
It isn't - `script` is a subcommand, not a parameter name (i.e. it doesn't start with `--`). You need to put it first to call it.

Because you specify the image first, the image parameter is never passed to the subcommand.

**Comment by rvanguri** [comment]
Fixed, thanks!
