### ISSUE TITLE
Importing an old QuPath 0.1.2 Project into QuPath 0.2.0 Fails for multiseries files if some images were removed from Project

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#515]
## Bug report

**Describe the bug**
When using the File > Project > Import Images from QuPath 0.1.2, projects containing multi-series files are not imported correctly. 

This is the case when the user imports a VSI file into QuPath (Which can contain several series) but deletes one or several series from the project. 

**To Reproduce** 
See provided zip containing:
[ Download Zip File (239MB) ](https://drive.switch.ch/index.php/s/fCOEPp2DIQD8qv1)
QuPath 0.1.2 Original Project
QuPath 0.2.0 Imported Project
QuPath 0.2.0 Created from scratch, with images deleted to match QuPath 0.1.2 Original Project
(Notice differences in 'data' folder of both QuPath 0.2.0 projects)

**Steps to reproduce the behavior:**
1. Create a QuPath 0.1.2 Project with a VSI file that has multiple series
2. After importing delete one image (not the last image or you will not see the effect)
3. Save the project
4. Create a new Project in QuPath 0.2.0
5. Use File > Project > Import Images from QuPath 0.1.2
6. After import, notice how QuPath 0.2.0 loads the wrong images

**Expected behavior**
QuPath Projects that are re-imported from multi-series file should be consistent even if the user did not keep all files in the project.

**Screenshots**
![Side-by-side](https://user-images.githubusercontent.com/319932/84012181-75285000-a977-11ea-84b2-b10688ecdbcb.jpg)
Left: QuPath 0.1.2
Right: QuPath 0.2.0
The thumbnail for both images is the same and it opens the same image twice

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - QuPath Version 0.2.0

**Additional context**
When replicating what the user did from scratch in QuPath 0.2.0, we end up with the following the structure in 'data' is not the same as from the  Import Images from QuPath 0.1.2 command.

**Comment by petebankhead** [comment]
Thanks @lacan for the detailed description and example. I've just pushed a commit to my fork that I think should fix this.
If you have a chance to build it, could you let me know if it seems to resolve the issue for you?

**Comment by lacan** [comment]
Hi @petebankhead I tested your latest `master` branch on a project with about 40 VSI files and 90 H&E images in the original project (some of which were removed by the user) and the import worked perfectly. Thank you very much for the prompt reply and fix!
