### ISSUE TITLE
Orphaned Choose File GUI window

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#519]
**Describe the bug**
If you begin the process of updating a file URI, but then cancel it in the middle, the Choose File window remains open. Then, if you restart the process, QuPath gets confused and shows a blank pop up.  

**To Reproduce**
1) Open a project with incorrect file links
2) Double click on one of them to change it. A small Change URI window will pop up. 
3) Click "Choose File". A file choosing window will pop up.
4) In the small Change URI window from step 3, hit cancel. The Choose File window remains open. 
5) Double click on another image name. The pop up is blank. You must close both windows and restart the process to continue. The Choose File window can be a little hard to find.  

**Expected behavior**
The Choose File window should close automatically when the process is canceled. Or, make the Change URI window unresponsive while the gui is up. Or anything else to prevent people from doing what I did.

**Screenshots**
![image](https://user-images.githubusercontent.com/29264310/84078848-731dbb80-a98e-11ea-92b8-6eba07c24fd9.png)

**Desktop (please complete the following information):**
Windows 10, QuPath 0.2.0

**Additional context**
Sorry I click buttons I shouldn't click :/

**Comment by petebankhead** [comment]
Thanks @saramcardle, I think my last commit resolves this - but so far I've only been able to test it on a Mac.

**Comment by melvingelbard** [comment]
I just tested your last commit on Windows and it seems to resolve the problem for me as well.

**Comment by petebankhead** [comment]
I'll close this issue, v0.2.1 should be available next week containing this and some other minor fixes.
