### ISSUE TITLE
Problem in Exporting Binary Mask

### ISSUE THREAD

**Issue by GiovannaMariaDimitri** [qupath/qupath#538]
Hi! 

First of all thanks so much for the amazing QuPath project, and for all of the documentation online.
I have however a question. I am trying to export a binary mask of my image (where I have segmented glomeruli), but the following script, only export saves in the masks image the tiles where the segmentations are but not the actual entire image binarized as shown here: 

https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html

Could you help me out with this? 
Thanks 

Giovanna

**Comment by petebankhead** [comment]
Hi Giovanna, please use the forum for questions - GitHub issues should only be for bug reports.
Here's the link: https://forum.image.sc/tag/qupath

See also https://qupath.readthedocs.io/en/latest/docs/advanced/exporting_annotations.html
In general, there are lots of different ways to export images depending upon what information is needed precisely (and the image size) - the details are really important.

I'll close this issue, feel free to create a topic on the forum if the docs don't answer your question.
