### ISSUE TITLE
OpenWebpageCommand hangs (Linux)

### ISSUE THREAD

**Issue by Alanocallaghan** [qupath/qupath#54]
Using any of the web links within QuPath on Linux does not open a browser page or window and causes QuPath to hang indefinitely

Ubuntu 16.0.4, Oracle Java 1.8.0_121

**Comment by petebankhead** [comment]
Should be address in change to use `HostServices`: https://github.com/qupath/qupath/commit/2eb8935144a7a939310acc5ad79ef34ef9edb889
