### ISSUE TITLE
Replacement URI not found/suggested when a project is moved to different HDD

### ISSUE THREAD

**Issue by SoerenXD** [qupath/qupath#543]
## Bug report

**Describe the bug**
When moving a folder (under Windows) that includes a project folder and an image to a different hard drive, QuPath does not find a suitable Replacement URI for the image when opening the project.

**To Reproduce**
1. Create a QuPath project and include an optical image in the same folder structure, e.g.:
```
G:\QPB
│   testdata.svs
│
└───Annotations
    │   project.qpproj
    │   project.qpproj.backup
    │
```

2. Move the parent folder to a different hard drive. E.g. to E:\QPB

3. Open the project in the new location.
4. The Update URI dialog doesn't show a suggested replacement URI, although the relative path of the image to the project hasn't changed.

**Expected behavior**
The replacement URI field should be pre-populated with the path to the image at its new location.

**Screenshots**
After folder is moved to different drive:
![screenshot_project_moved_to different_folder](https://user-images.githubusercontent.com/44832494/85672373-1c6ced00-b6c3-11ea-9795-5078d0b595e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version 0.2.1

**Additional context**
The problem only occurs if moving the folder to a different hard drive. Moving the folder to a different location on the same hard drive shows the expected behavior of suggesting the correct replacement URI.

**Comment by Tkilvaer** [comment]
We had this same problem when moving a harddrive between a linux and a windows computer in 0.2m5

**Comment by petebankhead** [comment]
I've just submitted a pull request to try to fix this. If anyone can check if it resolves the issue please do let me know.

**Comment by petebankhead** [comment]
Closing this as the fix has now been merged.
