### ISSUE TITLE
Phantom Polylines created with Pixel Classifier

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#544]
## Bug report

**Describe the bug**
If I create objects using a pixel classifier, but set the minimum size to larger than any object that would be created, it creates a phantom polyline object. This does not appear on the image, and has a centroid position of NaN, but is listed in the hierarchy. It happens for either type of pixel classifier and for annotation or detection objects.  If I create objects inside a collection of parent annotations, the regions that have valid new detection work fine, but the ones that don't each get a polyline. 

**To Reproduce**
1. Train a pixel classifier.
2. Create objects (detection or annotation). Set the minimum size to be larger than whatever region this classifier is selecting. 
3. A surprise polyline object appears in the hierarchy. 

**Expected behavior**
No object should be created at all.

**Screenshots**
Set up:
![image](https://user-images.githubusercontent.com/29264310/85805453-34fbf800-b701-11ea-95ae-3b2463227743.png)

Invisible Polyline:
![image](https://user-images.githubusercontent.com/29264310/85805506-5f4db580-b701-11ea-9265-bc5dae3f29db.png)

**Desktop (please complete the following information):**
Windows 10. 
QuPath 0.2.1 (tensorflow-cpu build).

**Comment by petebankhead** [comment]
Thanks Sara, I think this should fix it: https://github.com/qupath/qupath/pull/545
