### ISSUE TITLE
Java heap space error 

### ISSUE THREAD

**Issue by AliSyedRaza** [qupath/qupath#55]
Hi, 

This is Ali here. Thank you for your wonderful application. I had this error saying 'Java heap space' when trying to automate estimation of stain vectors. Does this have to do with low memory/specifications of my PC? Cause mine is i5 processor with 4GB RAM. Thanks.

**Comment by Svidro** [comment]
4GB is fairly low, I had trouble running much with even 8GB on an older laptop, but if you can replicate and post more details on the error (a screenshot?) maybe Peter can help you.

**Comment by petebankhead** [comment]
Hi, yes I'm afraid the error is related to memory and unfortunately 4GB is probably not enough to do much analysis with QuPath.  For browsing and annotating images it should be ok.

Nevertheless, you might be able to get further if you adjust the memory settings and then restart QuPath for them to take effect - there is some information [here](https://github.com/qupath/qupath/wiki/Troubleshooting#setting-memory-limits).

The above link also contains instructions for how to reduce the number of things QuPath does in parallel, which can reduce the amount of memory needed for processing (at the cost of things taking longer to run).  In this situation, it would be best to run QuPath with as few other applications as possible open on your computer at the same time.

For the specific example of getting the *Estimate stain vectors* command to work, you can also try selecting a smaller rectangle in your image, as described [here](https://github.com/qupath/qupath/wiki/Preprocessing#find-a-representative-region).
