### ISSUE TITLE
convert stardist .h5 to .pb 

### ISSUE THREAD

**Issue by gawells** [qupath/qupath#566]
Hi 

I'm not sure if this is the right forum to ask, but I'm busy trying to run some of the stardist Jupyter notebooks to generate custom stardist models to use in QuPath (I ultimately want to train on some of our own HDAB slides). I've managed to modify the 2D training notebook to generate a model on the HE MoNuSeg dataset. But it generates .h5 files instead of .pb. Can these be converted or do I have to modify the notebook to generate .pb files?

**Comment by petebankhead** [comment]
I really don't know; I'd suggest posting a question on https://forum.image.sc - there are many StarDist discussions there (with and without QuPath) involving the StarDist developers.

(QuPath's GitHub issues section is *only* intended for QuPath bugs - all other questions should really be posted on the forum to help keep things organized.)
