### ISSUE TITLE
names of hidden annotations are displayed

### ISSUE THREAD

**Issue by ofrag** [qupath/qupath#572]
Hi,

When I hide annotations for which I have set names, the names are displayed, although the annotations are hidden.

I would expect names of hidden annotations to be hidden as well. 

Ofra

PS: would this be considered a bug, or would you like such issues to be discussed on the forum?

**Comment by petebankhead** [comment]
It already came up on the forum, I created an Issue for it, and @melvingelbard fixed it :)
https://github.com/qupath/qupath/issues/557

Fix will be available in v0.2.2 (planned to be available in the next day or two, if nothing else comes up before then...)
