### ISSUE TITLE
Typo- "Unable to estimated"

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#583]
Just a minor typo in a warning. 

![image](https://user-images.githubusercontent.com/29264310/89352544-3528d500-d669-11ea-924f-c7c9c8142143.png)

"Unable to estimated transform - result did not converge"

Code: https://github.com/qupath/qupath/blob/master/qupath-experimental/src/main/java/qupath/lib/gui/align/ImageAlignmentPane.java#L833

**Comment by petebankhead** [comment]
Thanks, fixed now.
