### ISSUE TITLE
Cell expansion code can fail due to TopologyException

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#587]
## Bug report

**Describe the bug**
Cell expansion (including nucleus size constraint) can fail due to a TopologyException.

See:
* https://forum.image.sc/t/stardist-in-qupath-error-message/41242
* https://forum.image.sc/t/topologyexception-found-non-noded-intersection-between-linestring/38549

**To Reproduce**
Hard to reproduce... but depends upon running StarDist cell detection in QuPath v0.2.2 with cell expansion set. Fails intermittently.

**Expected behavior**
A single cell failure doesn't cause everything to break down.

**Additional context**
Adding in validity checks along the way risks having a substantial performance impact in the majority of cases that *do* work fine, so a more graceful recovery from errors may be sufficient.

**Comment by Alident** [comment]
Hi Peter I have a question regarding using QuPath StarDist extension by using widows 10

I will so much appreciate if you could help
thanks

**Comment by petebankhead** [comment]
Hi @Alident please use the forum - there are lots of questions there about QuPath and StarDist already: https://forum.image.sc/search?q=qupath%20stardist
