### ISSUE TITLE
Labelled Image Server loses manually input pixel size

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#591]
**Describe the bug**
I'm working with PNG images that do not store pixel size in their metadata. I manually input the correct pixel size (50 um) into the Image tab. If I call the pixel calibration from the image server, it returns the correct value. But, when I build a LabeledImageServer, it loses the pixel size and units, and instead returns that the calibration equal 1px. I've also tried overwriting the pixel calibration of a tiff file that has it stored in the metadata, and the Labeled Image Server continues to return the original pixel size. It seems that somewhere along the way, the labeled image server builder calls the real file metadata, not wherever the information in the image tab is stored.  

**To Reproduce**
1. Load any png or jpg
2. Change the pixel size in the image tab to a number
3. Run this code: 

```
import qupath.lib.images.servers.ImageServer
import qupath.lib.objects.classes.PathClassFactory

import java.awt.image.BufferedImage

import static qupath.lib.gui.scripting.QPEx.*

def imageData=getCurrentImageData()
Map<PathClass, Integer> labels = new LinkedHashMap<>();
int label = 1
labels.put(PathClassFactory.getPathClassUnclassified(), label++);
for (def annotation : imageData.getHierarchy().getAnnotationObjects()) {
    def pathClass = annotation.getPathClass();
    if (pathClass != null && !labels.containsKey(pathClass))
        labels.put(pathClass, label++);
}

for (def annotation : imageData.getHierarchy().getAnnotationObjects()) {
    def pathClass = annotation.getPathClass();
    if (pathClass != null && !labels.containsKey(pathClass))
        labels.put(pathClass, label++);
}


double downsample=1
ImageServer<BufferedImage> server = new LabeledImageServer.Builder(imageData)
        .backgroundLabel(0)
        .addLabels(labels)
        .downsample(downsample)
        .build();



print('Original Image Server')
print(imageData.getServer().getPixelCalibration().getAveragedPixelSize())
print(imageData.getServer().getPixelCalibration().getPixelWidthUnit())
print(imageData.getServer().getPixelCalibration().getAveragedPixelSizeMicrons())

print('Labeled Image Server')
print(server.getPixelCalibration().getAveragedPixelSize())
print(server.getPixelCalibration().getPixelWidthUnit())
print(server.getPixelCalibration().getAveragedPixelSizeMicrons())
```

**Expected behavior**
The labeled image server should know the pixel calibration input in the image tab. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29264310/90062797-16e05c00-dc9d-11ea-978b-4c321ce7dffb.png)

**Desktop (please complete the following information):**
 - Windows 10
 - QuPath 0.2.2

**Additional context**

**Comment by petebankhead** [comment]
Thanks, the `LabeledImageServer` code is explicitly using the original metadata rather than the current metadata, although I don't recall why... I'll look into it.

**Comment by petebankhead** [comment]
Is there a scenario when this causes a problem, or is it just unexpected?

I can make a change easy to use the pixel size of the image at the time the `LabeledImageServer` is created (I'll think more about it, but I haven't come up with a reason not to do this yet). However, this still won't be able to recognize any changes to the metadata of the underlying image... so if you were to change the pixel size after creating the labeled server this change would not filter through. That might then also be unexpected.

An alternative (but consistent) change would be for the labeled server to *always* be uncalibrated.

And as you may have seen, labelled servers can't currently have their metadata updated at all. Perhaps they should permit this.

I tend towards the first proposal (use the pixel size at the time the `LabeledImageServer` is created, but before committing to any one solution I'd like to better understand when the pixel size matters for labelled images.

**Comment by saramcardle** [comment]
Yes, it does cause a problem for me, but I have a feeling your response is going to be "stop abusing the alignment function"...

I'm trying to align images of the same slide taken with 2 different imaging modalities and with different resolutions. One is a normal slide scanner image with typical metadata; one is from an imaging mass spectrometer that gives an odd format that I convert to a png. I'm writing a script to do annotation-based alignment between the two images and I'm largely just copying and slightly modifying the source code from the ImageAlignmentPane.  (I'm still working on the math to deal with the scaling issues, but I think/hope I can solve that). This converts the annotations to LabeledImages, and then downsamples the labeled images and aligns them. But, at the step where it's trying to downsample the images, it calls `getAveragedPixelSizeMicrons()` and gets a NaN. From there it just guesses at a reasonable downsample value, guesses incorrectly, and then fails to align because the "result did not converge". 

This is likely to be an issue any time people are aligning images with missing or incorrect metadata, even through the interactive alignment pane. Also, I just tested this, and if you export a labeled .tiff using 'writeImage' calling a 'LabeledImageServer', it writes the metadata of that tiff incorrectly (when doing this on a normal calibrated image, the correct pixel size is written). 

In my case, I have a slightly scary work around. I can just code directly in my script that pixelSize=50 and hope that I remember to change that if I ever want to use this script in another project.

**Comment by petebankhead** [comment]
> Yes, it does cause a problem for me, but I have a feeling your response is going to be "stop abusing the alignment function"...

Aha! It does sound like parts of this specific problem could/should be addressed within InteractiveImageAlignment.

To use the current metadata, the only change I think is needed is to use `getMetadata()` instead of `getOriginalMetadata()` [here](https://github.com/qupath/qupath/blob/a03756328188999c0b7f12c290cda0589c50bd4b/qupath-core/src/main/java/qupath/lib/images/servers/LabeledImageServer.java#L157). You could try changing that to see if it works.

Alternatively, without needing to edit or rebuild anything, can you simply convert your PNG to a calibrated TIFF within ImageJ (setting the pixel size there) *before* it is read into QuPath?

**Comment by saramcardle** [comment]
> can you simply convert your PNG to a calibrated TIFF within ImageJ (setting the pixel size there) before it is read into QuPath?

Wow, yes, that is a much better solution than writing the pixel size into my script. Thank you! 
The original vs current metadata might still be a problem for anyone exporting labeled tiffs, but I don't foresee that coming up often.

**Comment by petebankhead** [comment]
Yes, I think probably best use `getMetadata()` in the future... just not sure if I had a reason not to at the time.
If you decide to try that workaround too, please let me know if you find any bad behavior.
