### ISSUE TITLE
Save Button for the classifier of the Create Thresholder stay disabled

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#599]
Threshold using `Classify>Pixel Classification>Create thresholder` on a RGB ome.tiff pyramidal slide but cannot save the classifier event after having filled the classifier name (button status stay disabled).
Should be enable to save the classifier (according to the documentation _"Keep QuPath happy by entering a classifier name and pressing Save. The buttons below should become magically activated."_) once a classifier name is entered but it doesn't.

On:
Version: 0.2.2
Build time: 2020-07-28, 14:23
Latest commit tag: 'ecac7c44'
Java version:		14.0.2
Java vendor: 		AdoptOpenJDK  -  https://adoptopenjdk.net/
Operating system:		Windows 10  -  10.0

Dataset:
Pixel type: uint8 (rgb)
Server type: Bio-Format
Image: Pyramidal ome.tiff created using bfconvert

See screenshot for proof:
![image](https://user-images.githubusercontent.com/1775952/92460321-1f5a8280-f1c8-11ea-828f-5c2dc3f2e83a.png)

Benjamin

**Comment by petebankhead** [comment]
Do you have a project open?

Currently, saving classifiers is supported *only* within a project... because other bad things can happen when projects aren't used (see for example this issue from today: https://github.com/qupath/qupath/issues/598 ).

**Comment by bpavie** [comment]
Ah, no thanks, I didn't see that mention in the documentation, thanks we can close the issue then ;-)

**Comment by petebankhead** [comment]
Added a line to the documentation now!
