### ISSUE TITLE
What units and resolution level are these coordinates from QuPath? 

### ISSUE THREAD

**Issue by tfisher1995** [qupath/qupath#605]
Hey Peter,

This is my first time commenting, but I have been following your forums on QuPath for a while. I want to apologize in advance if I do not post my question correctly. I developed a groovy script based on the comments posted on this issue. The output is a spreadsheet of points from each annotation made (code is shown below). With a little bash scripting, I can format these two spreadsheets into one CSV file that looks like the attached picture (attachment). However, I am not familiar with groovy nor the syntax of groovy. I am not sure if the points per annotation are the pixel units at level 0 (highest resolution) or micrometer at level 0 or something completely different. My question to you is, what are the points units, and at what level/resolution are these taken? Please ask any questions, and I am happy to answer them. 

![Screenshot from 2020-09-10 20-15-22](https://user-images.githubusercontent.com/41245184/92829599-643a1100-f3a2-11ea-8599-77236dbde92a.png)

`
setImageType('BRIGHTFIELD_H_E');
setColorDeconvolutionStains('{"Name" : "H&E default", "Stain 1" : "Hematoxylin", "Values 1" : "0.63348 0.72052 0.28205 ", "Stain 2" : "Eosin", "Values 2" : "0.16986 0.95793 0.23134 ", "Background" : " 229 221 218 "}');

// Create an empty text file
def name = getProjectEntry().getImageName() + '.txt'
def path = buildFilePath(PROJECT_BASE_DIR, 'points_results')
mkdirs(path)
def file = new File(path,name)
file.text = ''

// Loop through all objects & write the points to the file
// for (pathObject in getAllObjects()) {
for (pathObject in getAnnotationObjects()) {
    // Check for interrupt (Run -> Kill running script)
    if (Thread.interrupted())
        break
    // Get the ROI
    def roi = pathObject.getROI()
    if (roi == null)
        continue
    // Write the points; but beware areas, and also ellipses!
    file << roi.getPolygonPoints() << System.lineSeparator()
}
print 'Done!'

// Annotations
def name2 = getProjectEntry().getImageName() + '.txt'
def path2 = buildFilePath(PROJECT_BASE_DIR, 'annotation_results')
mkdirs(path2)
path = buildFilePath(path2, name2)
saveAnnotationMeasurements(path2)
print 'Results exported to ' + path2
`

_Originally posted by @tfisher1995 in https://github.com/qupath/qupath/issues/95#issuecomment-690799112_

**Comment by petebankhead** [comment]
Hi @tfisher1995 , no problem - I answered under the original post - https://github.com/qupath/qupath/issues/95#issuecomment-690799112

Please do use the forum for questions though, it makes it much easier to manage things if GitHub issues is *only* used for bugs (so I've started closing any issues that aren't bugs). The forum is at http://forum.image.sc/tag/qupath
