### ISSUE TITLE
Exception when pressing 'Create workflow' if no image is open

### ISSUE THREAD

**Issue by banatus** [qupath/qupath#608]
Dear Guru
I tried to useQupath Version: 0.2.3.
I found some issues when I click created workflow.
Please see in an attachment and kindly give me some advice.

![creatworkflow_err](https://user-images.githubusercontent.com/11736344/93363469-7c61d280-f871-11ea-80fd-eb9470d3ff43.jpg)

**Comment by petebankhead** [comment]
You need to have an image open for 'Create workflow' to work (although QuPath should tell you this more gracefully - throwing an exception is a bug).

**Comment by banatus** [comment]
Thank you I added an image , the issuess disappeared .

**Comment by petebankhead** [comment]
Fix has been merged, in v0.3 the 'Create workflow' button will be deactivated if no image is open.
