### ISSUE TITLE
CLI's help message does not match ScriptCommand behaviour

### ISSUE THREAD

**Issue by melvingelbard** [qupath/qupath#609]
## Bug report

**Describe the bug**
When using the `script` command in the CLI, the `-i` parameter is used to match an [entry's name](https://github.com/qupath/qupath/blob/43aad4ecda893a7eb03c30774e64da5b9547bc86/src/main/java/qupath/QuPath.java#L290), when the `--help` message indicates that the user must specified a path (`-i, --image=image: Path to an image file.`).

**To Reproduce**
1. Run the `script` command from the CLI with path (e.g. `QuPath.exe script -p path/to/project.qpproj -i path/to/image.tif path/to/script.groovy`) -> won't run the script on the specified image
2. Run the `script` command from the CLI with image name(e.g. `QuPath.exe script -p path/to/project.qpproj -i image-name path/to/script.groovy`) -> runs the script on the specified image

**Expected behavior**
Matching description and behaviour.

**Additional context**
The description ([here](https://github.com/qupath/qupath/blob/43aad4ecda893a7eb03c30774e64da5b9547bc86/src/main/java/qupath/QuPath.java#L257)) needs to change.

**Comment by petebankhead** [comment]
Fixed in https://github.com/qupath/qupath/pull/610 - will be included in v0.3.0.
