### ISSUE TITLE
scripting: export tiles within annotation?

### ISSUE THREAD

**Issue by schmolze** [qupath/qupath#62]
I'd like to use QuPath to generate training data for a deep learning model. I am annotating various features (let's say, tumor and stroma), and generating tiles within the annotated regions via Analyze -> Region identification -> Tiles & superpixels -> Create tiles. So far so good. Next I want to export the tiles as separate images, generating a file name according to the enclosing annotation name (e.g. "tumor_tile01.tiff"). I would have thought the following code would give me the enclosing annotation name:

`for (annotation in getAnnotationObjects()) {`
`    pathClass = annotation.getPathClass()`
`    print(pathClass)`
`}`

But instead the console prints (a bunch of times):

`INFO: null`

Any suggestions would be appreciated.

**Comment by Svidro** [comment]
You should get null for any tiles or annotations with no class set, and Tumor, or whatever class is set for any annotations with a set class.  If the tiles do not have a class, they will return null.  

If the tiles are detections, and have a parent annotation with a class name, you should be able to use something like for all detections, p= detection.getParent() followed by p.getPathClass() being assigned to a value in order to find out what the parent annotation's class was.  I am not sure this works if you have converted all of the tiles to annotations (maybe it does!).

**Comment by Svidro** [comment]
Peter also had an imageJ script which might be useful to you in his fourth option on one of the lower responses in this topic.  
https://github.com/qupath/qupath/issues/57
It involves using the macro runner to export TMA cores, but I suspect you could use it for tiles as well.

I have run into some issues handling names as well, apparently the names are frequently dynamically generated based on the class, so the getName function behaves oddly.  Please let me know if you find a workable solution!

**Comment by schmolze** [comment]
Thanks Svidro, the getParent() idea seems to be working. I will update this thread with the full script once I have tile export working.

**Comment by Svidro** [comment]
It seems like the easiest way to resolve the minor issue would be swapping the for loop/tiles to detections, if that works with the imagewritertools.

**Comment by schmolze** [comment]
I modified the body of the loop as follows, which seems to work for now:

```
for (annotation in getAnnotationObjects()) {

    roi = annotation.getROI()
    
    def request = RegionRequest.createInstance(imageData.getServerPath(), 
        1, roi)
    
    String tiletype = annotation.getParent().getPathClass()
    
    if (!tiletype.equals("Image")) {
    
        String tilename = String.format("%s_%s%d.jpg", filename, tiletype, i)
    
        ImageWriterTools.writeImageRegion(server, request, path + "/" + tilename);
    
        print("wrote " + tilename)
    
        i++
        
    }

}
```
I guess you could also explicitly check the enclosing annotation type, like:

```
if (tiletype.equals("Tumor") || tiletype.equals("Stroma")) {
    // write tile
}
```
