### ISSUE TITLE
WatershedCellMembraneDetection 

### ISSUE THREAD

**Issue by bpuladi** [qupath/qupath#624]
The cell recognition does not work for WatershedCellMembraneDetection via script. It executes it, but recognizes 0 cells or rarely times 1 cell. If you replace WatershedCellMembraneDetection with WatershedCellDetection, everything works fine. When called from the GUI, WatershedCellMembraneDetection also works fine. I have tried it under version 0.2.3.

`runPlugin('qupath.imagej.detect.cells.WatershedCellMembraneDetection', '{"detectionImageBrightfield": "Hematoxylin",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');`

**Comment by bpuladi** [comment]
Found the solution:
`runPlugin('qupath.imagej.detect.cells.WatershedCellMembraneDetection', '{"detectionImageBrightfield": "Hematoxylin",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 1000.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": true,  "cellExpansionMicrons": 8.0,  "includeNuclei": true, "limitExpansionByNucleusSize": false, "smoothBoundaries": true,  "makeMeasurements": true}');`

**Comment by petebankhead** [comment]
I can't replicate any problem; it works for me, assuming that
* the image type has been set
* I use the scripting command exactly as recorded under the 'Workflow' tab
* I have an annotation selected

I'll close the issue.
