### ISSUE TITLE
compressed, tiled TIFFs do not load on macOS Catalina

### ISSUE THREAD

**Issue by jcupitt** [qupath/qupath#627]
* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**

On macOS 10.15.4, QuPath 0.2.3, compressed, tiled tiff images do not load correctly: only the top-left corner tile appears, the rest of the image is black.

macOS Preview shows the same incorrect behaviour. Perhaps QuPath on macOS is using the platform libtiff rather than bundling its own?

**To Reproduce**

Download this image: 

http://www.rollthepotato.net/~john/tiled-jpeg-tiff-pyramid.tif

Start QuPath 0.2.3 on macOS Catalina. Select File / Open .... Select the image and press OK. Only a small white tile in the top-left appears.

I tried a few more things:

- If you use homebrew's tiffcp to transform the image to uncompressed tiled, it works (`tiffcp -c none x.tif y.tif`, then open `y.tif` in QuPath)
- macOS Preview shows the same behaviour (just displays one tile)
- the same image loads fine into `eog` on Ubuntu 20.04, image preview on win10, gimp on ubuntu

**Desktop (please complete the following information):**
 - macOS 10.15.7
 - QuPath 0.2.3

**Additional context**

Some more notes in this issue:

https://github.com/libvips/libvips/issues/1862

**Comment by petebankhead** [comment]
Thanks @jcupitt , hmmm it seems to be working for me in Catalina 10.15.7.
I see the same (full) image in Preview and in QuPath v0.2.3, using either OpenSlide or Bio-Formats.

It sounds like QuPath must be doing something wrong with linking, but I don't know what.

More generally, attempting to include OpenSlide within QuPath has proven troublesome before - I'm a lot happier with Java classpaths than trying to get it to properly handle native libraries (particularly with subdependencies). I have been considering whether to drop OpenSlide support or leave it up to people to install it separate via a package manager in general... but it is still very useful for some file formats.

I'd be grateful for any tips or suggestions to resolve the tiling problem, or the inclusion of OpenSlide in general.

**Comment by jcupitt** [comment]
Hi @petebankhead, thank you for looking at this.

Does Preview work for you on this image? I was struck by the way Preview and QuPath fail in the same way for me. Do you have a homebrew install?

You're probably doing all this already, but my macos .app builds have all native libraries in `Contents/Resources/lib/`, then a wrapper script in `Contents/MacOS/` that sets `DYLD_LIBRARY_PATH` to point to the lib directory. I include my own libtiff.

My macOS build scripts are here:

https://github.com/jcupitt/build-osx/

It's gtk-osx plus some tweaks. You probably have something much fancier!

**Comment by petebankhead** [comment]
Preview & QuPath both look ok to me:

![Screenshot 2020-10-23 at 20 49 48](https://user-images.githubusercontent.com/4690904/97047805-6bdc0080-1571-11eb-8a78-f2ec9652945c.png)

I do have a homebrew install as well:

![Screenshot 2020-10-23 at 20 52 12](https://user-images.githubusercontent.com/4690904/97048049-ba899a80-1571-11eb-8751-6dc0394469e5.png)

----

Thanks very much for the link, I'll check your build scripts - I think it is already safe to say they are a lot more sophisticated than anything used for QuPath! I'm afraid I'm one of the people who has spent too long with Java and Python...

Do you think there would be any sense in trying to include libvips with QuPath? We could put some work into that from our side - especially if it would help us incorporate OpenSlide more reliably into QuPath while also giving access to some of libvips' other functionality (like faster image pyramid-writing?) - but I'm not sure if there are reasons that's a bad idea.

**Comment by jcupitt** [comment]
I think I found the problem -- it's the libtiff in homebrew. It's a vanilla build of libtiff 4.1 and it's missing a series of patches which Ubuntu have applied to fix problems with things like YCbCR and JPEG-in-TIFF. This means that TIFFs created on mac tend to be broken :(

Sorry for the noise, I'll close.

**Comment by jcupitt** [comment]
libvips in QuPath: I'd be very flattered, of course! The difficulty might be in how to integrate it.

The simplest way would be to bundle the binary and just shell out to it. As you say, things like deepzoom and TIFF pyramid build might benefit, but of course you'd need a test case and some benchmarks to try to quantify any possible improvement.

There are Java bindings for libvips, but I've not been involved with them and I don't how complete they are, or if they are tough enough for a demanding program like QuPath. That would need a chunk of work.

I did pyvips and it should be complete and reliable. Do you use much Python inside QuPath? That might be the simplest way to experiment with more integration, such as using openslide via libvips.

**Comment by petebankhead** [comment]
Thanks @jcupitt I've created a new issue for the more general QuPath OpenSlide troubles at https://github.com/qupath/qupath/issues/629

I'm afraid we have no easy way to connect with Python. For native libraries there is JNI and JavaCPP, but my trouble is usually that I can't figure out how to build them in a properly portable way across macOS and Linux :(
