### ISSUE TITLE
"No features selected!" when attempting to create detection classifier

### ISSUE THREAD

**Issue by elijahedmondson** [qupath/qupath#63]
I am not able to create classifiers because I am not able to select features. "No features selected!" when attempting to create detection classifier in the "Advanced options" drop down under "Classifier" in "Create detection classifier". 

Seems like I am missing something simple -- any ideas?

**Comment by petebankhead** [comment]
It sounds like maybe you used *Create tiles* or one of the superpixel commands?

If so, these don't produce any features/measurements by default, as required by the classifier.

You can add some by running *Analyze &rarr; Calculate features &rarr; Add intensity features*.
But be warned... you generally need to choose the *Process all: Detections* option after you press *Run*.  Otherwise the features might be calculated for something else (e.g. the annotation containing your tiles/superpixels... but not the tiles/superpixels themselves).

**Comment by Svidro** [comment]
Have you clicked on the Select... button or Use All to the right side of the no features selected message?  You will need cells or some kinds of detections to already exist in that image in order to populate the list.

**Comment by elijahedmondson** [comment]
Ok, looks like by first applying "Analyze -> Cell analysis -> Cell detection" I was able to generate features for Classification.

Using "Analyze -> Calculate features -> Add intensity features (experimental)" did not provide features.

Thanks a lot!

**Comment by Svidro** [comment]
The latter will only provide features depending on what boxes are checked, and only for the detections you choose (cells, SLICS, whatever you happen to have selected, etc).  I don't know that it will work if you just have large annotations, but if you choose annotations after running it, it will look "inside" all annotations for detections to apply the Calculate Features to.

**Comment by Svidro** [comment]
And back again.  I just noticed on one of my slides I was adding features to today, that one particular value of preferred pixel size resulted in no intensity features being added (in this case 1um) while 2um did return values.  I wasn't able to pinpoint why one value would work, but it could be the case that the resolution needs to be tweaked.

**Comment by ranadeyuq** [comment]
Hi Pete, 

If you can help me with. I have followed the commands: 

1. analyse- cell analysis. 
2. show measurement maps- add smoothed intensity feature (50)
3. built classifier
     use all features
     intensity- H&E mean
     threshold- single (0.25)
NO OUTPUT RESULT- CLASSIFIER SHOWING, VOID CLASSIFIER. 

Please let me know your comments. 

Thanks.

**Comment by ranadeyuq** [comment]
![image](https://user-images.githubusercontent.com/54789655/64934856-e9beda00-d890-11e9-9137-7e8d843a7459.png)

**Comment by petebankhead** [comment]
@ranadeyuq You don't mention annotating the images to give examples of cells of different classes, which is essential. I've written some tutorials and recorded videos to show how to do this: https://github.com/qupath/qupath/wiki/Getting-started

If that does not resolve the problem, please use https://forum.image.sc/tags/qupath for questions about the software.

**Comment by ranadeyuq** [comment]
![image](https://user-images.githubusercontent.com/54789655/64935207-40c5ae80-d893-11e9-8b91-5b6648b570b3.png)

**Comment by ranadeyuq** [comment]
Thanks for your reply Pete. 

I have classified the cells before creating a detection classifier. Still its void classifier after wards.
