### ISSUE TITLE
GUI automate unresponsive/slow

### ISSUE THREAD

**Issue by imgifty** [qupath/qupath#631]
**Describe the bug**
The GUI element for 'Automate' is not responsive, takes very long time to load sub-elements. All other elements of the other GUI elements show instantly (e.g. File, Edit etc.).

**To Reproduce**
1. Open QuPath 0.2.3
2. Hover over Automate

**Expected behavior**
Faster elements showing when hovering over Automate.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - QuPath Version 0.2.3

**Comment by petebankhead** [comment]
Can you try resetting the preferences? For more details see https://forum.image.sc/t/qupath-stalls-when-trying-to-open-script-editor/44058/2

**Comment by imgifty** [comment]
That seems to have been the case, it added my whole code repository haveing to load a bunch of folders in User scripts. 
Thanks a lot for the help, sorry I couldn't find any related issue!
