### ISSUE TITLE
Positive cell detection

### ISSUE THREAD

**Issue by Kakathrin** [qupath/qupath#64]
Hey Guys!
I try to define cells into tumor and non-tumor cells with the detection classifier and determine afterwards the positive and negative cells in the respective class (with help of positive cell detection), but this second step doesn't work. Does anyone know how to search for positive and negative cells in already defined classes over a whole TMA-slide? Thanks a lot for your help!!

**Comment by Svidro** [comment]
Positive cell detection only works on the first go.  Other ways to do it involve using the Classify by specific feature option under the Classify menu and choosing your cutoff there, while choosing the cutoff for your specific measurement for the given cell type (IE choose tumor as the input, and then positive tumor or negative tumor as the output).   You may have to create the extra classes.  The other way involves a one line script that classifies as positive or negative by the value you input.  


setCellIntensityClassifications("Cytoplasm: DAB OD mean", 0.15)

**Comment by Kakathrin** [comment]
Thanks for the answer! I already tried this but I only could differ in
tumor cells between positive and negative. Is it possible to differ also
between positive and negative cells in the other classes I created in the
same step?

**Comment by Svidro** [comment]
I thought that the set cell intensity script should work for that.  It sounds similar to what was discussed here:
https://groups.google.com/forum/#!topic/qupath-users/Toc0SMDNJ4k

**Comment by Svidro** [comment]
Plus the script allows you to run one bit of code across multiple images!

**Comment by Kakathrin** [comment]
Thanks this group helped me a lot! But I still have one question. Do I have
to define tumor and non tumor cells with the help of the classifier before
or after using the setcellintensityscript? For me it only works seperately
but after using the other command it deletes the previous results.

2017-04-12 8:31 GMT+02:00 Svidro <notifications@github.com>:

**Comment by Svidro** [comment]
I am not completely sure what you are asking, but the setCellIntensity script should work with whatever classification you have done, it creates a subset of those classifications.  Running the classifier from the menu again (or anything that writes basic classes, I think) will overwrite the previous positive/negative subsets since they were part of the first classification.  In other words, the positive/negative are linked to the tumor and stroma classes (derived classes) not a separate population.

More here: https://github.com/qupath/qupath/wiki/Object-classifications

**Comment by petebankhead** [comment]
You would need to run the classifier first to distinguish (for example) tumor vs. stromal cells.

Once you are happy with that, be sure to turn off the 'Auto-update' setting if you were using it... and then run ```setCellIntensityClassifications``` to further subclassify cells of each type according to their intensities.

Note that you can use a single intensity threshold, to distinguish positive/negative cells only, e.g.
```groovy
setCellIntensityClassifications("Nucleus: DAB OD mean", 0.2)
```
or 3 thresholds to get positive/negative, 1+, 2+, 3+ and H-scores
```groovy
setCellIntensityClassifications("Nucleus: DAB OD mean", 0.2, 0.4, 0.6)
```

It's true that the sliders that allow you to set intensity classifications when you create the classifier at the start will only result in tumor cells being classified.  At the time I wrote that command, I was only interested in classifying tumor cells.... and it was much later that I realized that applying intensity classifications to other kinds of cell would be important too.  There is no button/menu item for that yet, so the ```setCellIntensityClassifications``` script is the best way to do that currently.

**Comment by Kakathrin** [comment]
Thanks a lot for your help! Only one last question: Is it possible to use 3
thresholds for the tumor cells (e.g. by using the classifier first) and
distinguish afterwards only the stroma cells with help of
setcellintensityclassifications into positive/negative cells? If so what do
I have to put in the script?
I'm sorry for my bad skills in programming.

2017-04-13 6:32 GMT+02:00 Pete <notifications@github.com>:

**Comment by petebankhead** [comment]
I'm not sure I understand.  Using the (one-line) script above you would get measurements for tumor and stroma both... percentage positive (which is anything scored as 1+ and above) as well as H-score.

Measurements like *Tumor: Positive %* and *Stroma: Positive %* should appear automatically when you create a results table / export.

If you'd like to set different thresholds for the tumour and non-tumour cells this would be possible... but more awkward, and I'm not sure if it would be a good idea.

Does that answer your question?  If not, could you give a bit more detail on your application / the final output you'd like to see?

**Comment by Svidro** [comment]
The only quick way I could think of for the final question would be to not use the script at all, but use the Classify by specific feature menu option, select Stroma as your input, and create the Stroma-positive and Stroma-negative classes yourself (right click in the right hand column of the Annotations tab), then use those as the outputs above or below your selected threshold.

**Comment by Kakathrin** [comment]
Ok thanks à lot for your help! I finally worked it out!
