### ISSUE TITLE
Return value after command-line script crashes is EXIT_SUCCESS rather than EXIT_FAILURE

### ISSUE THREAD

**Issue by juliangilbey** [qupath/qupath#654]
With QuPath-0.2.3, I ran a broken script like this:
```
QuPath-0.2.3 script -i /path/to/image.tif brokenscript
```
where `brokenscript` gave a Java exception.  Unfortunately, QuPath then exited with status 0 (EXIT_SUCCESS), meaning that my calling script cannot easily test whether the script worked or not.

It would be great if QuPath exited with an error status if the script exits with an error.

Best wishes,  Julian

**Comment by juliangilbey** [comment]
A little more on this: it is partly a Java issue - see [this StackExchange](https://softwareengineering.stackexchange.com/questions/20573/why-does-java-exit-with-success-after-an-uncaught-exception) post: Java exits with EXIT_SUCCESS on an uncaught exception.  I have found the source of this uncaught exception: in `src/main/java/qupath/QuPath.java`, there are three different places where `runScript` is called, only one of which is protected by a `try`/`catch` construct, so if an exception is thrown in one of the other two cases (as happened to me), the exception is not caught but instead causes Java to crash.  In particular, I can't then check for the logger message which is produced by this code in the first case:

```
logger.error("Error running script for image: " + entry.getImageName(), e);
```

So the solution would simply be to `try`/`catch` the other two cases as well.

Best wishes, Julian

**Comment by juliangilbey** [comment]
Ah, the whole thing is in a `try`/`catch` block, so that's not the problem.  My script threw an unhandled exception: `NumberFormatException at line 167: empty String`, and QuPath doesn't know what to do with that.  I can fix the bug in my script, but I can't see how to make QuPath fail more gracefully.

Best wishes, Julian

**Comment by petebankhead** [comment]
Hi @juliangilbey, I've tried to tackle this in https://github.com/qupath/qupath/pull/676

I'm not sure if I've taken the cleanest approach - if you've time to have a look I'd be very interested in your feedback.
