### ISSUE TITLE
File names in QuPath on a Mac

### ISSUE THREAD

**Issue by 80knut** [qupath/qupath#655]
Hi all,
I have an issue on QuPath recently installed on a MacBook Pro (15-inch, 2016).
When I upload an image, in the dashboard the name displayed does not correspond to the name of the file I uploaded.
<img width="402" alt="Screenshot 2020-12-12 at 18 25 57" src="https://user-images.githubusercontent.com/66163009/101990545-bb07fd00-3ca7-11eb-9209-e9d5e8d1732a.png">
On the contrary I do not have this issue when I open the same version of QuPath on a PC.
My version of QuPath is the following: **version 0.2.3**

**Comment by petebankhead** [comment]
Under *Edit &rarr; Preferences...* check if *Mask image names in projects* is selected.

This is a feature that helps with analysis based on manual evaluation, where seeing the file name could bias the interpretation.
