### ISSUE TITLE
Gives warning on some Ventana BIFs when using BioFormats reader

### ISSUE THREAD

**Issue by juliangilbey** [qupath/qupath#658]
**Describe the bug/To Reproduce**

On some Ventana BIF images, there is a warning message:
`TIFFReadDirectory: Warning, Unknown field with tag 34677 (0x8775) encountered.`

I have specifically instructed QuPath to open the image using the BioFormats library, which knows how to handle this tag.  Here is the script:

```groovy
import qupath.lib.scripting.QP

// We want to specify the image server so that we get replicable results
// https://forum.image.sc/t/specifying-the-imageserver-image-provider-server-type>

// Get the URI of the image under consideration; we need to pass this
// to the new server.  The image is specified as a commandline parameter
// in the QuPath call.
def currentServer = getCurrentServer()
def uri = currentServer.getURIs()[0]

def server = new qupath.lib.images.servers.bioformats.BioFormatsServerBuilder().buildServer(uri)

// Get the current image and image name
def imageData = new ImageData(server)
def name = server.getMetadata().getName()

def save_path = "thumbnail_dir/" + name + ".png"

def scale_factor = 8.0

// Save the entire image downsampled by a factor of scale_factor
def requestFull = RegionRequest.createInstance(server, scale_factor)
writeImageRegion(server, requestFull, save_path)
```

I run it using the command line: 

```
qupath script -i "31629 HE.bif" image_thumbnail.groovy
```

and the output is as follows:

```
11:36:08.817 [main] [INFO ] qupath.ScriptCommand - Setting tile cache size to 8030.00 MB (25.0% max memory)
11:36:09.171 [main] [WARN ] q.l.i.s.b.BioFormatsImageServer - Temp memoization directory created at /tmp/qupath-memo-14642445523855977691
11:36:09.172 [main] [WARN ] q.l.i.s.b.BioFormatsImageServer - If you want to avoid this warning, either disable Bio-Formats memoization in the preferences or specify a directory to use
11:36:09.363 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1
TIFFReadDirectory: Warning, Unknown field with tag 34677 (0x8775) encountered.
11:36:09.429 [main] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.level[0].tile-width' not available, will return default value 256.0
11:36:09.429 [main] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.level[0].tile-height' not available, will return default value 256.0
11:36:09.999 [main] [INFO ] qupath.lib.scripting.QP - Initializing type adapters
```

Note the `TIFFReadDirectory` warning message in the middle of this.  This strongly suggests that the OpenslideServer is actually being used rather than the BioFormats server, despite the explicit commands in the script to use BioFormats.

**Expected behavior**
The BioFormats server should be used to open and read the image, as instructed.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - QuPath Version 0.2.3

Thanks!

**Comment by petebankhead** [comment]
This looks expected to me, and not a bug. The image will be opened using the server defined within the project. The script simply re-opens the same image using Bio-Formats.

If you are generating a project, you can specify the *Image provider* to be Bio-Formats at that point, thereby avoiding the need to use the script at all.
https://qupath.readthedocs.io/en/latest/docs/tutorials/projects.html#add-images

**Comment by juliangilbey** [comment]
Ah, thanks! I didn't realise that it did most of the image reading *before* reading the script!

Closing this report.
