### ISSUE TITLE
How can I remove annotations from folded tissue? I tried using the polygon tool to create an object and by hitting delete I only delete the object. The version I am using is 0.2.3. 

### ISSUE THREAD

**Issue by DrashtiJain** [qupath/qupath#660]
## Please do not post questions here - use [image.sc](https://forum.image.sc/tags/qupath) instead!

QuPath's 'Issues' section on GitHub is used by developers to manage bugs and priorities - please do **NOT** post general questions here about the software.

Rather, post any questions to the official QuPath forum at https://forum.image.sc/tags/qupath

Be sure also to check out the [documentation & tutorials](https://qupath.readthedocs.io/en/latest/docs/starting/index.html).

**Comment by petebankhead** [comment]
The content of your post is also my response - please use http://image.sc/tag/qupath for questions!!
