### ISSUE TITLE
showConfirmDialog method never uses its title parameter

### ISSUE THREAD

**Issue by melvingelbard** [qupath/qupath#662]
## Bug report

**Describe the bug**
`showConfirmDialog()` in the `Dialogs` class never uses the `title` parameter, and uses the `text` as a title instead. This results in confirm dialogs showing their `text` in the main content pane as well as in their title. 

**Expected behavior**
The title is used as title and text as main text.

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version 0.2.3

**Additional context**
The issue is located [here](https://github.com/qupath/qupath/blob/main/qupath-gui-fx/src/main/java/qupath/lib/gui/dialogs/Dialogs.java#L100).
There are around 30 calls to this method in other parts of the code.

**Comment by petebankhead** [comment]
Fix will be in v0.3.0.
