### ISSUE TITLE
Persian text problem in menus

### ISSUE THREAD

**Issue by MOstadi** [qupath/qupath#683]
when i change a text in menu to persian it's showing like this : 
![image](https://user-images.githubusercontent.com/26692474/111035297-0c529480-842f-11eb-9a5c-f3131efbbfda.png)
I changed fonts to tahoma but nothing happens.

**Comment by petebankhead** [comment]
> when i change a text in menu to persian it's showing like this

In what way are you changing the setting? QuPath doesn't support languages other than English.

If you find it is displaying wrongly, under *Help &rarr; Show setup options*, what is the 'Region' option set to?

Location settings are buried deep within Java and your operating system, and can be combined in multiple ways (for text, numbers, dates etc.). It isn't possible for us to test how behavior changes for many different combinations, therefore it is recommended to set it to 'English (US)' for consistency.

If the *Help &rarr; Show setup options* setting doesn't fix things, could you please tell me what you see if you run the following script?
```groovy
println Locale.getDefault()
println Locale.getDefault(Locale.Category.DISPLAY)
println Locale.getDefault(Locale.Category.FORMAT)
```

If you find that any of these are not English, you could try running this script to set the locale more forcibly:
```groovy
import qupath.lib.gui.prefs.PathPrefs
PathPrefs.defaultLocaleFormatProperty().set(Locale.US)
PathPrefs.defaultLocaleDisplayProperty().set(Locale.US)
```
You may need to restart QuPath to see the effect of any changes.

If you don't like the results of changing any preferences, you can use *Edit &rarr; Reset preferences* to restore all preferences to their defaults.

**Comment by petebankhead** [comment]
I'll close this due to lack of a response. At this point we don't have enough information to understand if there is a bug and we have no way of addressing it.
