### ISSUE TITLE
Issue opening some images in QuPath (nd2 file type)

### ISSUE THREAD

**Issue by Sudaaaaaa** [qupath/qupath#690]
7/10 images that I have tried to open in QuPath will not open correctly. The 3 that have opened correctly are the same file type. When I open the images in NIS Elements, they look fine. The files that work correctly vary in size from 300,000 KB-1,500,000 KB. The files that don't work are within that range as well. I increased the maximum memory from 16 GB to 24 GB, but it did not make a difference. We tried different computers with more RAM, but it did not make a difference. I attached images of the problem and what it's supposed to look like below. Why are some of the images uploading correctly while others are not or how can I get these problem files to open correctly? My coworkers are having the same issue with their nd2 files as well.

![Correct Small Section](https://user-images.githubusercontent.com/81709406/113194852-92444d00-922f-11eb-9d94-38c74c2c2967.png)
![Correct Whole Tissue](https://user-images.githubusercontent.com/81709406/113194853-92dce380-922f-11eb-88d2-cc424dd9c512.png)
![Problem file](https://user-images.githubusercontent.com/81709406/113193596-23b2bf80-922e-11eb-9f17-ce5c9d553539.png)
![Problem Small Section 2](https://user-images.githubusercontent.com/81709406/113193597-23b2bf80-922e-11eb-8f80-29cbf5a9c7af.png)
![Problem Small Section](https://user-images.githubusercontent.com/81709406/113193599-244b5600-922e-11eb-87fa-c8b1ea7bb024.png)
![Problem Whole Tissue](https://user-images.githubusercontent.com/81709406/113193600-244b5600-922e-11eb-930d-d59094ce087e.png)

**Comment by Svidro** [comment]
Ah, ok, I noticed that in the one image that appeared to be "good" the Pyramid was "No," though maybe the last image is also large and worked with an autogenerated pyramid.

**Comment by petebankhead** [comment]
I will close this issue because, without an example image, there is nothing further we can do - and it is likely already covered by the Bio-Formats issue anyway.
