### ISSUE TITLE
setIntensityClassification(..) does not ignore 'ignored classes'

### ISSUE THREAD

**Issue by melvingelbard** [qupath/qupath#691]
## Bug report

**Describe the bug**
`setIntensityClassification(..)` in `PathClassifierTools` does not ignore 'ignored classes'. It only ignores the `Ignore*` class, as defined in `PathClassFactory.StandardPathClasses.IGNORE`, but not custom 'ignored' classes, as defined in `PathClassTools.isIgnoredClass()`.

**To Reproduce**
1. Create a `PathObject`.
2. Create an 'ignored' `PathClass` (e.g. `test*`) and create relevant measurements.
3. Set the `PathObject` class to the newly created `PathClass` (e.g. `pathObject.setPathClass(getPathClass("test*"))`)
3. Run `setIntensityClassification(..)` with the created `PathClass`.
4. The 'ignored' `PathClass` will be 'intensity classified', even though it should be ignored.

**Expected behavior**
The method does **not** classify the object if it belongs to an 'ignored' class (e.g. `test*`).

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version 0.2.3

**Additional context**
An additional `isNullClass()` companion method should be added to filter out which `PathObject`s should not be classified.
This is because the method should still be able to 'intensity classify' `null` `PathClass`es (e.g. `null` would be classified as `Positive`/`Negative`).

**Comment by petebankhead** [comment]
Fixed in https://github.com/qupath/qupath/pull/687/commits/e031575b40e13684b3f1205178ad2cdf2d7a6327
