### ISSUE TITLE
Screen sharing problems on Mac (teams / zoom)

### ISSUE THREAD

**Issue by proukakis** [qupath/qupath#693]
Hello, we are using it on a Windows machine and Macs (with Big Sur, Catalina and Mojave OS).

When sharing screen on Teams from windows, it is great.

When sharing screen on teams (or Zoom) from Mac, the main view is shared, but the "box" that shows the adjustments as they are being made (brightness etc) is not shared with any of the three Macs (with different OS) we tried. I have given full disk access etc as much as I could figure it, but maybe there are settings I haven't identified.

It will be great if we can solve this
thanks,
christos

**Comment by petebankhead** [comment]
It sounds like the QuPath window only is being shared, but not the entire screen - and you need to share the entire screen for it to work.

I use a Mac myself, and I find I always need to share the entire screen if I want to demo something in QuPath and have all the windows appear. I also avoid using full screen mode with QuPath.

**Comment by proukakis** [comment]
ok many thanks
