### ISSUE TITLE
Contour Export

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#70]
Hi,

Is it possible to export "contours" delineating different cell types from one another in quPath (or possible to access some data which might make that easy enough to script? I realize that quPath strives at doing the classification it on a cell-cell basis, but possibly iso-lines from heatmaps produced by the "Add Smoothed Features" command would do the trick.

Best,
Colin

**Comment by petebankhead** [comment]
One idea may be to forego cell detection (at least as a first step), and instead create square tiles or superpixels, add intensity/texture features to them, and then classify these.  There is then a *Tile classification to annotations* command to merge the classified tiles.  Cells could optionally be detected inside the annotations at the end, if still required.

Alternatively, you could use *Extensions &rarr; ImageJ &rarr; Send region to ImageJ* to get a (possibly heavily downsampled) version of the image into ImageJ.  The cells will be passed along too on an ImageJ overlay, with colors and names set according to their original classification.  Then it becomes an ImageJ scripting/macro problem to combine these into regions - maybe using distance or voronoi transforms.  *Plugins &rarr; Send ROI to QuPath* can be use to send back annotations to QuPath, if they are needed.

In the event that you don't really care about the cell boundaries, you can open up the *Point* tool (three circles) and choose *Convert detections to points* first to get centroids only before sending them to ImageJ.

I'm not sure if either of these do what you need, and the second may be a bit overly complicated.  Could you say a bit more about the aim?
