### ISSUE TITLE
Cannot  open project

### ISSUE THREAD

**Issue by jjohn972** [qupath/qupath#745]
error showing
java.long.NullpointException
I tired Reset preferences, but did not work
could you help?

**Comment by petebankhead** [comment]
Please follow the [issue template to create a Bug Report](https://github.com/qupath/qupath/issues/new/choose) or post a question on [the forum at image.sc](http://image.sc/tag/qupath). `java.long.NullpointException` is not enough to know what the problem might be - we'd need more information about which version(s) of the software you are using, what previously did/didn't work, and the full information from the log.

**Comment by petebankhead** [comment]
Closing this issue as there is not enough information for us to do anything further.
