### ISSUE TITLE
Sometimes getSelectedObject() returns null unexpectedly

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#758]
## Bug report

**Describe the bug**
In QuPath <= 0.2, it's possible to have selected objects but for `getSelectedObject()` to still return null.

This is kind of a bug, while kind of not. It happens because QuPath distinguishes between the 'primary' selected object, and the set of all selected objects.

However, it often *feels* buggy and understandably causes confusion at times, e.g. https://forum.image.sc/t/error-when-exporting-region-of-the-image-in-script/50269/3

**To Reproduce**
Run the following script in v0.2.3 on an image that contains annotations:
```groovy
resetSelection()
selectAnnotations()
println getSelectedObject()
println getSelectedObjects()
```
You should find that it prints `null` for `getSelectedObject()` selected object, *even though clearly annotations are selected*.

This is most confusing whenever there is only one annotation on the image, and there would be no ambiguity as to which one is the primary.

**Expected behavior**
I don't know... but my feeling is that, if there are multiple selected objects, QuPath should always enforce that one is the primary.

That means a [`PathObjectSelectionModel`](https://github.com/qupath/qupath/blob/88c7cc45648c1d5b09a840bd1e497ea9a46453aa/qupath-core/src/main/java/qupath/lib/objects/hierarchy/events/PathObjectSelectionModel.java#L62) change for whenever a set is selected but the primary is `null`.

I propose:
* If a primary selected object is specified, use that. Otherwise
  * If the current primary selected object remains selected (i.e. it's still in the collection passed to the method), just keep it selected. Otherwise
    * Select the first object in the collection passed to the select method to use as the primary

Another idea was to keep the object with the largest ROI, or at the lowest hierarchy level... but those all sounded more involved.

**Desktop (please complete the following information):**
 - QuPath v0.2.3 and earlier

**Additional context**
I've changed the code already and was planning to merge it, but then figured I'd post here first. If anyone is watching, feedback / opinions / objections welcome!

**Comment by camlloyd** [comment]
> You should find that it prints null for getSelectedObject() selected object, even though clearly annotations are selected. 

Correct.


> I propose:
> 
>     * If a primary selected object is specified, use that. Otherwise
>       
>       * If the current primary selected object remains selected (i.e. it's still in the collection passed to the method), just keep it selected. Otherwise
>         
>         * Select the first object in the collection passed to the select method to use as the primary
> 
> 
This makes sense, but are there use cases where it would not be appropriate?

> Another idea was to keep the object with the largest ROI, or at the lowest hierarchy level... but those all sounded more involved.

Or at least to me, this does _not_ make sense. Not only does it quickly become more complex, but I personally don't believe a larger ROI is any more important than a smaller one. Perhaps it depends on the context.

**Comment by MichaelSNelson** [comment]
I am not sure about null, but if having a primary selected object is important, not having one could throw a meaningful error rather than returning null.

"No primary object is selected and you have attempted to select a single object when multiple objects are selected. Please add more logic to your statement to determine which object you want, if you only want one object."

That could probably be phrased better, but maybe it gets the idea across?

**Comment by petebankhead** [comment]
Thank you both for answering!

> This makes sense, but are there use cases where it would not be appropriate?

I can't think of any myself... however, if you run a command like
```
selectAnnotations()
```
then if there is more than 1 annotation available, the one that will become the 'primary' selected annotation is (from the user's perspectively) essentially random. Randomness doesn't feel good in this scenario, but neither does seemingly not having a selected object when you can plainly see that you definitely have selected object**s** (as is currently the case).

> Or at least to me, this does not make sense. Not only does it quickly become more complex, but I personally don't believe a larger ROI is any more important than a smaller one. Perhaps it depends on the context.

Good! Inasmuch as I don't like the idea much either. Its only benefit really is that it makes the choice non-random. I think sometimes it would 'feel' like the right choice, e.g. imagine if you have one large tissue annotation and two little annotations inside. I think making the large one the primary selection would feel somehow intuitive. But if, on the other hand, you have three annotations of similar size and importance I agree it doesn't make much sense. And it's probably better not to introduce too much predictable-but-dubious behavior, lest *someone* make it a key part of their workflow...

So yeah, I think the size-based idea can be discarded.

> I am not sure about null, but if having a primary selected object is important, not having one could throw a meaningful error rather than returning null.

Hmmm, that sounds like it could work for code internal to QuPath, as long as it always checks both for `getSelectedObject()` and `getSelectedObjects()`. Although if calling either method in a script, the ambiguity and potential for confusion remains.

Although then the question resurfaces, is it better to just leave things as they are?

In any case, the proposed change is implemented at https://github.com/qupath/qupath/pull/759

**Comment by petebankhead** [comment]
Thinking a bit more, a compromise option could be:
* keep the primary selected object if it's still selected in the new group, and
* set the primary selected object if there is only one object in the selection group, but not if there is more than one

Might be safer than selecting an object at random, and reduce the instances where the primary selected object is null slightly. What do you think?

**Comment by MichaelSNelson** [comment]
> Although if calling either method in a script, the ambiguity and potential for confusion remains.
I had mostly been thinking about scripting. If there is no primary selected object, and getSelectedObject() is used, the script would simply break and provide an informative error message. The user is trying to do something (get a particular object) while providing insufficient information (which object? multiple are selected).

I suppose there could be an even worse option where you also encode getASelectedObject() which returns the first, or largest, or some other logic.

> keep the primary selected object if it's still selected in the new group, and
> set the primary selected object if there is only one object in the selection group, but not if there is more than one
I was also just thinking about this - what situations lead to there being no primary object, and could those be addressed instead?

Alternatively, specially code getSelectedObject() to allow for an array, check for an array size of 1, and handle that situation specifically if it arises. Still return null in other situations, along with an informative error message (or warning).

**Comment by petebankhead** [comment]
> I suppose there could be an even worse option where you also encode getASelectedObject() which returns the first, or largest, or some other logic.

Hmmm, might need to think about it some more but I think that risks increasing rather than reducing complexity. I'd rather have fewer options with more predictable behavior - in rare cases where something more complex is needed, it's always possible to query all the selected objects and then filter them however you like. But I don't think that should be part of the core API.

> I was also just thinking about this - what situations lead to there being no primary object, and could those be addressed instead?

`selectAnnotations()` is a good example. Basically, anything that can select multiple objects without a clear 'main' object. So if you would run another command like `selectObjects(p -> p.getPathClass() == getPathClass('Tumor'))` you'd see the same: possibly multiple objects selected, but no 'main' selection.

Or, with my pull request, a 'main' selection plucked more or less randomly - *unless* only one object is available, in which case it's just what you'd expect.

> Alternatively, specially code getSelectedObject() to allow for an array, check for an array size of 1, and handle that situation specifically if it arises. Still return null in other situations, along with an informative error message (or warning).

Internally there is already a set of selected objects - distinct from the main selected object. However, if there is a main selected object then it should always be included in the set.

I think errors/warnings need to be used very sparingly to avoid causing undue alarm. But I'm coming around to the compromise I mentioned above, which I think falls somewhere between my pull request and your original suggestion.

**Comment by petebankhead** [comment]
Closing this in favor of https://github.com/qupath/qupath/pull/768
Discussion convinced me that the change might cause more confusion than it resolves, so for now leaving it up to a very minor logging change (and a bigger logging change that makes setting the log level easier).
