### ISSUE TITLE
Unable to set the color of a class to a custom color with opacity set to 0%

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#770]
## Bug report

**Describe the bug**
Unable to set the color of a class to a custom color with opacity set to 0%.

When previewing a pixel-level single measurement thresholder, I'd like to create a negative class with opacity set to 0, so that I can still view any pixels below or above a threshold. Given that I can set the opacity to 1%, with no visually imperceptible difference to a 0% opacity, this is a very minor issue.

**To Reproduce**
1. Double click on a class in the annotations tab
2. In the dropdown color menu, select custom color
3. Set opacity to 0%
4. Select "Use"
5. Select "Okay"
6. Color of class will revert to previous value, remaining unchanged

**Expected behavior**
Opacity of class should be set to 0%, as with any other value for opacity.

**Screenshots**
Setting opacity to 0%
![image](https://user-images.githubusercontent.com/52012166/124034644-7d5f8d00-d9c9-11eb-85f4-f4c692f5e349.png)
Class color remains unchanged
![image](https://user-images.githubusercontent.com/52012166/124034717-92d4b700-d9c9-11eb-9910-abd052b14d35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version 0.2.3 (build with StarDist)

**Additional context**
Very minor issue, given that I can set the opacity to 1% and greater without any issue.

**Comment by MichaelSNelson** [comment]
Hi!

I am not sure which option would be easier, but it also might be nice to be able to turn "on" or "off" the visibility of pixel classifier classes. Specifically, I mean in the same way that classes can be turned on or off for objects, using the space bar or context menu in the Annotation tab.

**Comment by petebankhead** [comment]
I'm not sure supporting opacity with classifications is a good thing - to be honest, I had no idea it worked at all and I'm not sure that opacity = 0 *should* be allowed. Although I'm also not sure I've totally understood the issue.

@MarkZaidi Does toggling the display of the classification under the annotation tab (with spacebar or right-click) handle the original problem?

@MichaelSNelson I think the original post was more about object classification than pixel classification. I'm not sure if supporting class toggling with pixel classification is likely any time soon, since it could open a whole world of awkwardness with tile caching and color models.

**Comment by MarkZaidi** [comment]
> 
> 
> I'm not sure supporting opacity with classifications is a good thing - to be honest, I had no idea it worked at all and I'm not sure that opacity = 0 _should_ be allowed. Although I'm also not sure I've totally understood the issue.
> 
> @MarkZaidi Does toggling the display of the classification under the annotation tab (with spacebar or right-click) handle the original problem?
> 
> @MichaelSNelson I think the original post was more about object classification than pixel classification. I'm not sure if supporting class toggling with pixel classification is likely any time soon, since it could open a whole world of awkwardness with tile caching and color models.

Toggling the display of the classification doesn't appear to have any effect, since the objects don't technically exist yet in the preview state. I should have clarified that I'm referring to the preview state of the pixel thresholder.


> 
> I am not sure which option would be easier, but it also might be nice to be able to turn "on" or "off" the visibility of pixel classifier classes. Specifically, I mean in the same way that classes can be turned on or off for objects, using the space bar or context menu in the Annotation tab.

So apparently, although the class appears to be at 100% opacity by looking at the icon of "GFAP_negative_area", the opacity seems to have been successfully set to 0% when previewing the pixel thresholder, as it allows the user to see the underlying image. This is doing exactly what I would want it to do; it's just that the icon gave the misleading impression that the opacity was not set to 0%
![image](https://user-images.githubusercontent.com/52012166/124038468-2d83c480-d9cf-11eb-9b94-e37c902cb0b9.png)

In the example above, "GFAP_positive_area" has 100% opacity and "GFAP_negative_area" has 0% opacity. "50pct_opacity" is an unused class, with color #0000ff set to 50% opacity.

**Comment by MichaelSNelson** [comment]
Two thoughts there:
1. Hitting the C key to flip back and forth between opaque and transparent will not get you the information you need?
2. You should be able to select no class (Unclassified, maybe? I forget) for the negative area when setting the threshold, if you want to see through it. Then select a negative class prior to saving the classifier.

**Comment by MarkZaidi** [comment]
> 
> 
> Two thoughts there:
> 
>     1. Hitting the C key to flip back and forth between opaque and transparent will not get you the information you need?
> 
>     2. You should be able to select no class (Unclassified, maybe? I forget) for the negative area when setting the threshold, if you want to see through it. Then select a negative class prior to saving the classifier.

1. 100% true, no new information is visualized when using the C key to swap between showing and not showing the overlay. More of a quality-of-life thing to have the ability to selectively omit a class in preview mode from being displayed

2. Correct, for pixel thresholding like in the previous example; that'll have the same effect. But for object classifiers (i.e. single measurement classifier), the unclassified class is opaque and red, as shown below:
![image](https://user-images.githubusercontent.com/52012166/124044794-33cc6d80-d9dc-11eb-8c57-e34785076df9.png)
But if I use a class with an opacity of 1%, this allows me to selectively hide any objects that would be assigned to that class
![image](https://user-images.githubusercontent.com/52012166/124044856-5a8aa400-d9dc-11eb-9967-b0a302d7bcb1.png)

Having the unclassified class be transparent/hidden not only in the pixel classifier but also object classifier approach would make the need (or rather a very small desire) for adjusting opacity to 0% unnecessary

**Comment by MichaelSNelson** [comment]
> Having the unclassified class be transparent/hidden not only in the pixel classifier but also object classifier approach would make the need (or rather a very small desire) for adjusting opacity to 0% unnecessary

I think you would want to turn off the "None" classification in the Annotations tab using the spacebar.

**Comment by MarkZaidi** [comment]
> 
> 
> > Having the unclassified class be transparent/hidden not only in the pixel classifier but also object classifier approach would make the need (or rather a very small desire) for adjusting opacity to 0% unnecessary
> 
> I think you would want to turn off the "None" classification in the Annotations tab using the spacebar.

Oh wow, did not know you could do that! This hides the display of the unclassified objects. Given that this can be used to omit objects below a threshold in object classifiers, and that leaving the "below threshold" field blank in pixel classifiers will omit those as well, there isn't any point towards addressing this 0% opacity class bug.

I'll go ahead and close this issue, but feel free to reopen if there's any other limitation of not being able to set opacities of classes to 0%.

Thanks for all your help!
