### ISSUE TITLE
Redundancy in if-else condition of ImageWriteTools.java

### ISSUE THREAD

**Issue by CielAl** [qupath/qupath#816]
* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ ] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [ ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ ] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**

Redundancy in if-else condition to throw IOException in [ImageWriteTools.java](https://github.com/qupath/qupath/blob/6b8bafc566356fe9b97770fb88227e9e768f14da/qupath-core/src/main/java/qupath/lib/images/writers/ImageWriterTools.java#L176)

`		
```
        if (firstException == null && firstException == null)
			throw new IOException("Unable to write " + path + "!  No compatible writer found.");
		else
			throw new IOException("Unable to write " + path + "!", firstException);
	}
```
`

**Expected behavior**
A

**Comment by petebankhead** [comment]
Thanks, resolved in the last commit.
