### ISSUE TITLE
Location text does not update when navigating with keyboard

### ISSUE THREAD

**Issue by mdtgif** [qupath/qupath#819]
## Bug report

**Describe the bug**
While jumping between different TMA cores using arrows - the core name (e.g A1) does not change unless you make an additional gesture, such as move the picture, go over with a mouse cursor

**To Reproduce**
1. Use disarrayed TMA
2. Use right and left keys on the keyboard to move between cores (zoom on any core first)
3. Check the core name at the low right corner - it does not change!
4. Move the cursor and then the core name updates

**Expected behavior**
Core name is correct when a core appears after using the keyboard only

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - QuPath 0.3

**Additional context**
One can jump through many cores with arrows with the core name staying the same.

**Comment by petebankhead** [comment]
Thanks, this should be fixed in the next release (code linked above).
