### ISSUE TITLE
simple tissue detection cannot be trimmed by "Alt+Brush"  - bug

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#82]
annotations, automaticly generated by simple tissue detection function cannot be trimmed with the "alt+brush" or "alt+wand" tool. 
Normally every annotation can be trimmed like that/reagions from annotation can be deleted. 
I you paint an adjacent second annotation, merge it with the annotations generated by simple tissue detection, trimming will work afterwards. 
I guess that is a bug, that trimming is not directly possible.

**Comment by DHaumannHSA** [comment]
test

**Comment by DHaumannHSA** [comment]
test

**Comment by DavidMHaumann** [comment]
test

**Comment by petebankhead** [comment]
This isn't a bug - by default annotations created this way are 'locked' to reduce the risk of editing them accidentally.

There is some more information about locking [here](https://github.com/qupath/qupath/wiki/Working-with-objects#editing--locking-objects).

You can right-click on the image and choose *Annotations &rarr; Unlock* if you need to be able to edit a locked annotation.
