### ISSUE TITLE
Positive Cell Detection misses sections

### ISSUE THREAD

**Issue by andyp05** [qupath/qupath#828]
**Describe the bug**
Create a box annotation of the entire slide and run positive cell detection. Some slides work fine, others seem to just stop with no error. 

**To Reproduce**
1. Go to 'Analyze' -> Cell Detection ->Positive Cell Detection
2. Accept defaults.
3. Runs with no errors. 

**Expected behavior**
A full slide with every cell detected and classified. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14006401/135633690-717d4fc9-6010-4de6-b235-54bd3dc98ea6.png)

**Desktop (please complete the following information):**
 - OS: Windows, 64GB RAM, 32 core processor, Nvidia GTX1060 with CUDA 11.1 installed.
 - QuPath Version 3.0

**Additional context**
RAM usage at around 60%, 
No plugins loaded after initial install.

**Comment by petebankhead** [comment]
@andyp05 have you checked for any errors under *View &rarr; Show log*?

I have not seen this behavior and have no way to replicate it, but my guess is that there may *possibly* be a memory error. You seem to have a lot of cores relative to the amount of available RAM, so reducing the *Number of parallel threads* option under *Edit &rarr; Preferences...* may help.

**Comment by andyp05** [comment]
Cut the processes from 63 to 24 and some improvement. When it happened again, I saw the following in the log, but I still have 15GB free. Can I increase java heap memory for qupath, or is there a memory leak? If I close qupath and come back in it will work for a couple of slides before failing.

Thanks,

Andy

```
ERROR: Error running plugin: java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:139)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:107)
    at qupath.lib.gui.PluginRunnerFX.runTasks(PluginRunnerFX.java:98)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:169)
    at qupath.lib.gui.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:192)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by Java heap space        at java.base/java.util.ArrayDeque.<init>(Unknown Source)
        at qupath.imagej.processing.Watershed$WatershedQueueWrapper.<init>(Watershed.java:242)
        at qupath.imagej.processing.Watershed.doWatershed(Watershed.java:83)
        at qupath.imagej.detect.cells.WatershedCellDetection$WatershedCellDetector.doDetection(WatershedCellDetection.java:852)
        at qupath.imagej.detect.cells.WatershedCellDetection$WatershedCellDetector.runDetection(WatershedCellDetection.java:1063)
        at qupath.imagej.detect.cells.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:303)
        at qupath.imagej.detect.cells.PositiveCellDetection$DetectorWrapper.runDetection(PositiveCellDetection.java:140)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:112)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by petebankhead** [comment]
Sounds like a potential memory leak, but I'm not aware of any that would cause this.

>  I still have 15GB free

Is this available to QuPath, or only to the operating system? You can track QuPath's memory use with *View &rarr; Show memory monitor* (although this won't include anything JavaCPP does... which mostly means things connected with pixel/object classifiers).

There are some instructions for making more memory available to QuPath [here](https://qupath.readthedocs.io/en/stable/docs/reference/faqs.html#set-max-memory).

If you're comfortable digging deeper, [VisualVM](https://visualvm.github.io) is extremely helpful for tracking memory in any running Java application (and is what I'd use if I could replicate the issue).

Apart from that, how are you running positive cell detection - interactively, or from a script? How do you define the regions within which cells are detected?

**Comment by andyp05** [comment]
was running a script but it never finishes.

```
setImageType('BRIGHTFIELD_H_E');
setColorDeconvolutionStains('{"Name" : "H&E default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049", "Stain 2" : "Eosin", "Values 2" : "0.2159 0.8012 0.5581", "Background" : " 244 244 244"}');
createSelectAllObject(true);
runPlugin('qupath.imagej.detect.cells.PositiveCellDetection', '{"detectionImageBrightfield": "Hematoxylin OD",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Nucleus: Eosin OD mean",  "thresholdPositive1": 0.2,  "thresholdPositive2": 0.4,  "thresholdPositive3": 0.6000000000000001,  "singleThreshold": true}');

```
If I run individually, exit, restart and run another it always works. It is when I try to run this on multiple slides without restarting that I run into trouble.

**Comment by petebankhead** [comment]
> was running a script but it never finishes.

I don't understand exactly what steps you are taking?
* Are you using *Run &rarr; Run* from the script editor, or *Run &rarr; Run for project*? *Run for project* enables you to [run the same script sequentially across multiple images](https://qupath.readthedocs.io/en/stable/docs/scripting/workflows_to_scripts.html#running-a-script-for-multiple-images), but I don't know if you're using this.
* Do you have multiple images open simultaneously in QuPath, or only a single image at a time?

Please see also my question above:

>> I still have 15GB free
> 
> Is this available to QuPath, or only to the operating system? You can track QuPath's memory use with View → Show memory monitor (although this won't include anything JavaCPP does... which mostly means things connected with pixel/object classifiers).

The memory monitor also provides ways to reclaim memory at any time.

Although problem **the most important thing** is that I can see in your script (and screenshot) that you are running the cell detection after
```groovy
createSelectAllObject(true);
```
This is likely to be **extremely** inefficient, because it will process all the empty white space as well.

Processing should be much faster, and memory use much lower, if you restrict cell detection to only the tissue regions.
See [Detecting tissue](https://qupath.readthedocs.io/en/stable/docs/tutorials/thresholding.html) for details; [Pixel classification](https://qupath.readthedocs.io/en/stable/docs/tutorials/pixel_classification.html) is another option.

**Comment by petebankhead** [comment]
Hopefully some of the tips in the last post were useful. I'll close this due to a lack of activity and I do not have a way to reproduce the exact problem.
