### ISSUE TITLE
How to detect nuclei with different staining

### ISSUE THREAD

**Issue by fabienneM** [qupath/qupath#83]
Hi, 

I am new with the program QuPath and had some problems with the nuclei classification. 
The cell nuclei I am looking for are blue with a stained red/pink surrounding. Unfortunately QuPath does not just identify those cells but also cells that have a pinkish color anywhere else in the cytoplasma- not just around the nuclei. How can I make a more specific classification?

Thanks for the help!

Best 
Fabienne

**Comment by Svidro** [comment]
Please post both a smallish picture, and a copy of your workflow (workflow tab, Create Script at the bottom).  Right off the top of my head, and based on your description, I would say tightening the Cell Expansion parameter to something more like 1um or even less would be your best bet, and then looking at the cytoplasmic color vector ODs.

**Comment by Svidro** [comment]
The other option, if the stain is overlapping the nucleus significantly, is to just use the subcellular detection tool (again with a smaller cell expansion), and set a threshold based on the amount of area that shows up "pink."

**Comment by fabienneM** [comment]
![cd8m](https://user-images.githubusercontent.com/30120607/28157091-a5bdd674-67b5-11e7-8756-2098a3172585.jpg)

This is the picture. We are in consultation with a pathologist and I will need my supervisors permission before I can post more details but essentially, we are trying to distinguish between putative membrane staining (indicated by arrows) vs. nonspecific red smears in the tissue (indicated by the circle). Is there any way to generate a classifier that incorporates both red-blue measurements vs red smears. I will post more details upon speaking to my supervisor. 

Thank you very much for your help,

**Comment by Svidro** [comment]
I completely understand, and don't really need more details beyond that snapshot, though I will have to make a few guesses without the Workflow script.  You should be able to do that with just the red OD in a narrow cytoplasmic band around the nucleus, as mentioned before.  I would definitely use the _Analyze -> preprocessing-> estimate stain vectors_ to get the best estimate of the red that you are looking for.  Another way is to draw a very small box around some of the red you want to find (make sure you keep that box selected), and then double click on the stain vector you want to set in the Image tab on the left.  You should get a popup, "Set new stain vector from ROI?"

You will have to generate your cells again once you have the stain vectors set correctly, but once you do, you should be able to use a simple one step script to find positivity.  

setCellIntensityClassifications("Cytoplasm: DAB OD mean", 0.15)

Just place that in a script window and run it, but replace DAB with whatever the color vector is for your "Red."  And you can just rename it red in the same Image tab from before.  The 0.15 can be whatever cutoff you find works for your data, and I prefer to use the heatmaps from _Measure-> Show measurement maps_ for this purpose.

Side note, you can use the _Positive cell detection_ for this purpose once you have determined what you want your cutoff to be, but you need to make sure you keep the color vector name as "DAB."

**Comment by Svidro** [comment]
Also, for questions like this, I would recommend using the Qupath users forum! https://groups.google.com/forum/#!forum/qupath-users

**Comment by fabienneM** [comment]
Hi Svidro,
Thank you so much for your quick and detailed response! I will try some of those useful suggestions and will get back to you to let you know how it worked.
