### ISSUE TITLE
QuPath menu too small, change of GUI resolution

### ISSUE THREAD

**Issue by mmfalco** [qupath/qupath#833]
I tried to use QuPath (v0.3.0) for inspecting my IHC slides but the menu is so small that I can't use it:
![image](https://user-images.githubusercontent.com/12033098/139060774-8092df7c-a477-48ec-89f4-5413caf5c22b.png)
Is there a way to modify the resolution for the application?
I don't want to change my display resolution since all the other windows has the proper appearance. As you can see in the screenshot the border and letters of the window has the proper size but it is not the case for the QuPath menu. It would be ideal if there was a way to modify “GUI scale” in the Edit>Preferences>Appearance dialog.  
Thanks in advance

**Comment by petebankhead** [comment]
@mmfalco I've just checked out the [JavaFX 17 release note](https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-17.md) and saw this fix: https://bugs.openjdk.java.net/browse/JDK-8248126

Currently QuPath is using JavaFX 16, although if you'd like to try it with 17 you'd probably only need to change one line [here](https://github.com/qupath/qupath/blob/main/buildSrc/src/main/groovy/qupath.common-conventions.gradle#L70), then build from source as described [here](https://qupath.readthedocs.io/en/stable/docs/reference/building.html).

QuPath v0.4.x will use Java/JavaFX 17. I'm a little tempted to introduce JavaFX 17 already in v0.3.1, especially if it resolves this problem (and doesn't [break our own versioning rules](https://qupath.readthedocs.io/en/stable/docs/intro/versions.html)).
