### ISSUE TITLE
QuPath 0.3.0 unreadable text after installation

### ISSUE THREAD

**Issue by ayushnoori** [qupath/qupath#866]
**Description**
When I attempt to install QuPath 0.3.0 on Windows 10, the text of QuPath is unreadable (please see screenshot below).

**To Reproduce**
1. Download QuPath from https://github.com/qupath/qupath/releases/download/v0.3.0/QuPath-0.3.0-Windows.msi.
2. Bypass Windows Defender security alerts.
3. Run the installer.
4. Open QuPath 0.3.0.

**Screenshots**

![image](https://user-images.githubusercontent.com/43010710/146222250-0d831aa3-f959-4bec-95d4-6af049cf994e.png)

**Desktop**
 - OS: Windows
 - QuPath Version: 0.3.0

**Hash**
The SHA256 hash of the file I downloaded is:
```
certutil -hashfile QuPath-0.3.0-Windows.msi SHA256
SHA256 hash of QuPath-0.3.0-Windows.msi:
d3661adca21ab8ea31acfa5d150345fb4b46a983526803fce3869f520949965e
```
However, I cannot find the hash of the file from the GitHub API: https://api.github.com/repos/qupath/qupath/releases (see [here](https://stackoverflow.com/questions/29671303/where-to-get-md5-hashes-from-a-github-release)).

**Comment by ayushnoori** [comment]
Hi @petebankhead, thanks for the pointer. To close the loop here, **my installation of QuPath is now working as expected**, and the text is displaying appropriately. In case others encounter a similar problem, here's what worked to solve it:

1. Download the Segoe UI font (e.g., from https://www.fontreach.com/segoe-ui-font-free-download/) and reinstall Segoe UI.

For future reference, the following steps did NOT work:

1. Reinstalling QuPath.

2. Using the `Repair` tool to repair the existing Qupath installation.

3. Updating Java to the latest version.

4. Updating OS from Windows 10 to Windows 11.

Here are some links I found on 'javafx unreadable text' and Segoe UI:

1. https://stackoverflow.com/questions/66747171/why-javafx-application-and-scene-builder-is-showing-garbled-text

2. https://stackoverflow.com/questions/14091011/how-to-add-utf-8-for-non-english-support-in-javafx

3. https://stackoverflow.com/questions/65150438/scene-builder-editor-displaying-weird-characters

**Comment by ayushnoori** [comment]
Alas, some text remains garbled:

![image](https://user-images.githubusercontent.com/43010710/146457511-c60be044-961c-4130-ba9d-d7c198ad8ef4.png)

Any thoughts, @petebankhead? I suspect I may need to replace an additional font.

**Comment by petebankhead** [comment]
Thanks @ayushnoori do you maybe need to install additional versions? I guess the garbled text should be bold and I'm not sure if that requires another file.

**Comment by ayushnoori** [comment]
I tried to install Segoe UI Bold from an online vendor but doing so simply reverted all the text to the garbled version. Looks like you can't re-download the original TrueType font files directly from Microsoft (see https://docs.microsoft.com/en-us/typography/font-list/segoe-ui), so not sure where to obtain the correct `.ttf` files from.

**Comment by petebankhead** [comment]
If you can decipher enough, you could try opening the preferences (cog icon, or under *Edit &rarr; Preferences...*) and search for the 'Font' option. There should be three options: *Default*, *Sans-serif* and *Serif*. Hopefully one of them behaves.

![Screenshot 2021-12-17 at 06 30 14](https://user-images.githubusercontent.com/4690904/146499627-2c8d7fb3-4db2-4b92-b109-6a34fe7cd711.png)

I had entirely forgotten about this preference, which was added at https://github.com/qupath/qupath/commit/039207fdd9bc013be38d8dce048ccc465aef39af
I am using a Mac, and the option was introduced to resolve some Mac-specific troubles back in 2019.

**Comment by ayushnoori** [comment]
Great, thanks @petebankhead! Changing to *Sans-serif* resolves the issue:

![image](https://user-images.githubusercontent.com/43010710/146500372-6ee67941-3000-4e26-9a25-93abdc72cbfc.png)

Although perhaps not as pretty as the default Segoe UI, QuPath is now working for me. I will close this issue, but will continue to try and make the default font display appropriately (and will follow up here if I am able to do so). Thanks again for the help!

**Comment by petebankhead** [comment]
Great, thanks for reporting back!
