### ISSUE TITLE
Compilation error on Eclipse

### ISSUE THREAD

**Issue by apurwamishra** [qupath/qupath#87]
Hi, 
I was hoping someone could help me out here. I am currently trying to set up and building QuPath on Eclipse and I keep running into a compilation error in multiple GUI classes. They're all the same errors: refresh() has private access/is not visible in javafx.scene.control.TableView. 
I am very confused especially because I have not made any changes to the code and so if someone could help me out, that would be great! 
Thanks in advance!

**Comment by Svidro** [comment]
I'm not sure if any of the posts in the forum will help with this, and I never got around to getting QuPath to compile.  Have you looked through https://github.com/qupath/qupath/issues/84 ?  Afraid that's all the help I can be until Pete is around or I have a chance to play with it.

**Comment by apurwamishra** [comment]
Thanks for the reply. I think I actually figured out why it wasn't working before. The refresh method's accessibility was changed in javafx from Java 8u60 and onwards. I didn't realize but I was running an older JRE on Eclipse and thus the compilation error.
