### ISSUE TITLE
tile classifications to annotations - are devided by edges of large tiles

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#89]
Qupath separates the image into a lot of tiles to process them step by step. 
If I do tissue recognition with a classifier and then convert the recognized objects into annotations with the function "tile classification to annotations", it happens that recognized connected areas that cross edges of the large tiles become separated exactly there. Here a pictures:
![grafik](https://user-images.githubusercontent.com/16352785/28976400-f9d7beac-793d-11e7-8603-2033b7292588.png)

Now i have 2 ROIs instead of one. That is a problem for ongoing analysis. And to merge all of them manually is quite some work. 
Is there a way to prevent the devision of ROIs at edges of tiles?

**Comment by Svidro** [comment]
Aside from altering the code and recompiling, I don't think there is any easy way to change the tiling size, but you may be able to script merging the correct annotations.  Depending on your sample, you might check annotations of the same class with centroids within a certain distance of each other, and select and merge them if they are close enough together.  If you are going to merge all of the data later on, you can also just select all "stroma" (or whatever class) annotations and merge them with a two line script:
```
selectObjects { p -> p.getPathClass() == getPathClass("Stroma") }
mergeSelectedAnnotations()
```

Pete might have some better ideas, but that's the best I have got based on the description!
