### ISSUE TITLE
Tiles are not being cached in v0.3.2 for ome.tiff images but are in v0.3.0

### ISSUE THREAD

**Issue by ajaysingh096** [qupath/qupath#904]
**Describe the bug**
While zooming into a pyramidal ome.tiff image, the resolution does not change and the image remains pixelated. This may be due to the number of cached tiles not increasing (tiles not being cached). This bug only exists in v0.3.2. 

For v0.3.0, the image resolution loads properly when zooming in.

**To Reproduce**
1. Open an ome.tiff file with QuPath v.0.3.2
2. Under the "View" option, choose "Show memory monitor"
3. Zoom into your image while monitoring the number beside "num cached files" in the memory monitor
(For a comparison, repeat steps 1 to 3 with QuPath v0.3.0)

**Expected behavior**
For v0.3.2, the value for num cached files remains the same.
For v0.3.0, the value for num cached files increases.

**Desktop:**
 - OS: 64-bit Windows 10

**Comment by petebankhead** [comment]
I could not replicate the problem. I opened the common sample image `CMU-1.svs` and used QuPath to write a pyramidal OME-TIFF with tile size 1024x1024 and default compression option (here, uses JPEG). After relaunching QuPath v0.3.2 (to ensure a clean start), It works properly with tile reading, caching and viewing across resolutions.

* Have you tested this with multiple OME-TIFF files?
* Which software was used to write the pyramidal OME-TIFF files that are misbehaving?
* Are there any clues / errors reported in QuPath under *View &rarr; Show log*?
* Can you share any example images exhibiting this issue?

Note that v0.3.1 temporarily used a different version of Bio-Formats (6.8.0), but v0.3.0 and v0.3.2 use the same version of Bio-Formats (6.7.0). If you could compare behavior across all three versions, this may help identify when any problem could have been introduced.

**Comment by petebankhead** [comment]
I'm closing this due to a lack of response - I cannot replicate the problem, and don't have enough information to address any potential issue.

Feel free to reopen with answers to my questions above.

**Comment by ajaysingh096** [comment]
Sorry about the wait.

**In response to your questions**

- I have tested zooming into an image with multiple OME-TIFF files and have gotten the same results.

- The software used to generate the OME-TIFF files was through a two-step process of converting MRXS files (written from 3DHISTECH software) into OME-TIFF files through the help of conversion tools from Glencoesoftware:

The first step used a tool called bioformats2raw (https://github.com/glencoesoftware/bioformats2raw) which converts MRXS files into Zarr file-type. 

The second step used a tool called raw2ometiff (https://github.com/glencoesoftware/raw2ometiff) which converts the Zarr file into an OME-TIFF file type.

- While viewing an image with QuPath-0.3.0 and checking _Show log_, these were the errors reported:

WARN: Unable to obtain full image format info for file:/C:/Users/aj_si/Desktop/poh_mrxs/OME-TIFF/C001110926E04.ome.tiff (class java.util.NoSuchElementException)
INFO: Image data set to ImageData: Not set, C001110926E04.ome.tiff - C001110926E04

For QuPath-0.3.2, the result was the same except it did not have the "WARN" error.

For QuPath-0.3.1 (which also can not cache tiles or load the resolution properly when zooming in), this was reported:

WARN: Unable to obtain full image format info for file:/C:/Users/aj_si/Desktop/poh_mrxs/OME-TIFF/C001110926E04.ome.tiff (class java.util.NoSuchElementException)
INFO: Setting max Bio-Formats readers to 4
INFO: Image data set to ImageData: Not set, C001110926E04.ome.tiff - C001110926E04



### Here is an example of my image while zoomed in using QuPath-0.3.0
<img width="960" alt="QuPath_030_zoomed" src="https://user-images.githubusercontent.com/98191884/157751366-613ce0e7-1dc4-4e03-a0f4-8a055db1f3d7.PNG">



### Here is an example of my image while zoomed in using QuPath-0.3.2 (looks the same on QuPath-0.3.1)
<img width="960" alt="QuPath_032_zoomed" src="https://user-images.githubusercontent.com/98191884/157751374-6702bd00-8f17-4005-a56c-7b3a96f6c258.PNG">


As well, here is a link to download two of my OME-TIFF images, if you would like to try viewing them on QuPath: http://gofile.me/6VSoS/CNJndmlCr

**Comment by petebankhead** [comment]
Thanks, your images work for me in QuPath v0.3.2 on my Mac. I will try to check on a Windows computer later to see if I can replicate the issue.

**Comment by petebankhead** [comment]
I've tried now on three computers (Windows 64, Mac M1, Mac Intel) and can't replicate any problem - the tiles open fine at all resolutions in QuPath v0.3.2. I see the warning in v0.3.1 but the image still opens without problems.

Two things you could try:
* Reset QuPath's preferences, with *Edit &rarr; Reset preferences*
* Increase the logging in the hope that a more useful error appears; to do this go to *Edit &rarr; Preferences...* and search for `Log level`, then set its value to `DEBUG`

(I do see that the images aren't recognised as RGB, but that's a different issue... I may need to update QuPath to convert it to a more standard RGB automatically)

**Comment by ajaysingh096** [comment]
@petebankhead , One thing that I forgot to mention: the samples that I provided have had their confidential patient data/slide labels removed from the OMETIFF files using a tool called "anonymize-slide" (https://github.com/bgilbert/anonymize-slide). This patient data would show up as a separate image containing a QR-code when opening the OME-TIFF file on all versions of QuPath.

After recently anonymizing these OMETIFF files with that tool, I have not had a chance to open them through QuPath-0.3.1 and QuPath-0.3.2. I have now tried to open them and it looks like the resolutions load correctly for these files just like you said! 

These are the actual files that did not have their resolutions loaded correctly: http://gofile.me/6VSoS/hqlOTZWmj

### To address your proposed solutions:

- Resetting QuPath's preferences did not fix the resolution loading problem
- After setting the _Log level_  value to _debug_ with QuPath v0.3.0, v0.3.1, and v0.3.2, the error messages remained the same

The patient data/slide label being present might be contributing to the resolution-misloading problem. It may also be helpful to know that the patient data has multiple resolutions as well.

**Comment by petebankhead** [comment]
@ajaysingh096 thanks, I've identified the source of the problem as being the same as https://github.com/qupath/qupath/issues/894 - although it appears in a slightly different way (just opening a low-res image rather than freezing).

It was also discussed [here](https://forum.image.sc/t/problem-about-opening-ndpis-files-in-qupath-v0-3-1/62184).

The bug is already fixed, and the fix will be included in the next QuPath release. In the meantime, it should be possible to open the images in QuPath as long as you [add them to a project first](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html).
