### ISSUE TITLE
Auto-complete throws IndexOutOfBoundsException after deleting completion

### ISSUE THREAD

**Issue by melvingelbard** [qupath/qupath#916]
## Bug report

**Describe the bug**
The ScriptEditor throws an `IndexOutOfBoundsException` when deleting text that was just inserted, having `CTRL` down (and probably `CMD` too?).

**To Reproduce**
1. Go to the script editor
2. Get the first auto-completed word by hitting `CTRL` + `SPACE` (i.e. `BRIGHTFIELD_H_DAB` at the time of writing)
3. Delete the word, by hitting the `CTRL` + `BACKSPACE` keys
4. Re-hit `CTRL` + `SPACE` to trigger the auto-complete again.
5. See Exception thrown

**Expected behavior**
The word should be auto-completed again (i.e. `BRIGHTFIELD_H_DAB` should be written)

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version: v0.3.2

**Additional context**
I believe the problem originates [here](https://github.com/qupath/qupath/blob/10b44a58b8c08ca925aa44bc08eaf1fa3eb70584/qupath-extension-script-editor/src/main/java/qupath/lib/gui/scripting/richtextfx/RichScriptEditor.java#L357), where reinitialising the `AutoCompletor` object is skipped and it shouldn't. However, the reason for this `if` block is to avoid the `AutoCompletor` object to be reinitialised when the user is iterating through all the possible completion suggestions (e.g. most users will naturally hit the `CTRL`/`CMD` key before the `SPACE` key, creating a `KeyEvent` in the middle that needs to be filtered out).

**Comment by petebankhead** [comment]
I couldn't replicate this on my Mac - however that may be because the bit you linked to is hard-coded to use `Ctrl` rather than adapting to use `Cmd`... which might also be an issue, I guess. I need to use `Cmd + Backspace` to delete the full word.

Either way, sounds like a bug that needs fixed for Windows & Linux.

**Comment by petebankhead** [comment]
Should be fixed now (since autocomplete was completely rewritten for v0.4.0, and after that I couldn't replicate the problem on Windows).
