### ISSUE TITLE
Saving image in jpeg/tiff/png format

### ISSUE THREAD

**Issue by andanis** [qupath/qupath#92]
Hi 
I am annotating on whole slide images and to save the images I only get .qpdata format. However I would like to save the image with annotations (smaller down-sampled image is fine too) in jpeg/tiff/png format. 
I tried using Extensions > ImageJ > Send region to ImageJ but is doesn't show annotated regions on saving. 
I can "Export Image Region" but that saves a png image without annotations.
Can you please guide me how to do that? 
Also, I can revert my last annotation but can't undo the last action while annotation while using the software. Is there a way to go back to previous steps while annotating?

**Comment by petebankhead** [comment]
Does *File &rarr; Export snapshot... &rarr; Viewer snapshot* do what you need?  This corresponds to *Edit &rarr; Copy view to clipboard*.

If more control is needed, there's also an export script [here](https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d) that may be useful as a starting point.

With regard to (the lack of) undo, *File &rarr; Revert* is likely to be the best option to go back to the last saved version.  With the help of shortcuts, you may press *Ctrl + S* to save regularly and then *Ctrl + R* to go back one step.  The *backspace* key can also be used to quickly remove an accidentally-drawn annotation.  *Objects &rarr; Transfer last annotation* (*Shift + E*) can also help sometimes in an emergency... although it only has a very short memory.
