### ISSUE TITLE
Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'. gradle-plugins-7.4.2.jar (No such file or directory)

### ISSUE THREAD

**Issue by monajalal** [qupath/qupath#950]
I am following the [instructions for building QuPath][1] from source on CentOS 7. I get the following error:

    [jalal@goku qupath]$ ./gradlew clean jpackage
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'.
    > java.io.FileNotFoundException: /scratch3/downloads/gradle-7.4.2/lib/plugins/gradle-plugins-7.4.2.jar (No such file or directory)
    
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 721ms

The instructions that I am following are as follows:

    $ git clone https://github.com/qupath/qupath
    $ cd qupath
    $ ./gradlew clean jpackage

 I have:
```
$ uname -a
Linux goku.bu.edu 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
and
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```

also:
```
$ java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)
```

I also don't understand why it is looking elsewhere than where I have zipped it and set the directory to it as in:
```
[jalal@goku downloads]$ sudo vi  /etc/profile.d/gradle.sh
[jalal@goku downloads]$ sudo chmod +x /etc/profile.d/gradle.sh
[jalal@goku downloads]$ source /etc/profile.d/gradle.sh
[jalal@goku downloads]$ gradle -v

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_322 (Red Hat, Inc. 25.322-b06)
OS:           Linux 3.10.0-1160.59.1.el7.x86_64 amd64

[jalal@goku downloads]$ cat /etc/profile.d/gradle.sh 

export GRADLE_HOME=/opt/gradle/gradle-7.4.2
export PATH=${GRADLE_HOME}/bin:${PATH}

$ tail -1 ~/.bashrc
export PATH=$PATH:/opt/gradle/gradle-7.4.2/bin
$ source ~/.bashrc

```

The plugin that is reported as missing in the error is in 
```
[jalal@goku ~]$ find /opt/gradle -name "gradle-plugins-7.4.2.jar"
/opt/gradle/gradle-7.4.2/lib/plugins/gradle-plugins-7.4.2.jar
```

Full log of `./gradlew clean jpackage --stacktrace`: https://pastebin.com/raw/RuuJnuTe

Full log of `./gradlew clean jpackage --debug`:
https://pastebin.com/raw/EPJs2jRR

Full log of `./gradlew clean jpackage --scan`:
https://pastebin.com/raw/TUGSM73K

  [1]: https://qupath.readthedocs.io/en/latest/docs/reference/building.html

@saudet I decided to create a separate issue for the Stackoverflow post since building QuPath on CentOS 7 also fails (not just running its binary)

**Comment by petebankhead** [comment]
Strange... if you install gradle separately, then you can also use `gradle clean jpackage` (i.e. avoid relying upon gradle wrapper).

I'm not sure if that'll help. I have limited experience using Linux, and none using CentOS. I don't know whether JavaFX 18 (used by QuPath now) is compatible with CentOS 7 so even if you overcome the building issue, I don't know if it will run.
* https://github.com/qupath/qupath/issues/825
* https://github.com/qupath/qupath/issues/949

**Comment by petebankhead** [comment]
I'll close this, since it has been over a year since the last comment, and I'm cleaning up our open issues to remove the ones we can't realistically solve.

QuPath v0.5.0 is coming soon; if there are still problems with it and CentOS, feel free to open a new issue then.
