### ISSUE TITLE
Youtube link for TMA CD3 analysis

### ISSUE THREAD

**Issue by arielyh** [qupath/qupath#955]
When I clicked the "Watch" link under TMA CD3 analysis page, it says "Video unavailable. This video is private". When will the videos for TMA analysis be available? Thanks.

**Comment by petebankhead** [comment]
It seems YouTube changed the access settings a while ago - they should be visible again now.

(Note that the wiki hasn't been updated since QuPath v0.1.2 - the current documentation is at https://qupath.readthedocs.io/ )
