### ISSUE TITLE
Are multiple annotations on a pixel via QuPath possible?

### ISSUE THREAD

**Issue by vatempeli** [qupath/qupath#969]
Hello everyone! Do you possibly know if I can do multiple annotations on a pixel via QuPath? I am currently using machine learning procedure for my classifications. But what can I do if a specific area is two things (e.g. a cell on a vessel) and I want the area etc. measurements of both of them?
![Στιγμιότυπο οθόνης 2022-05-21 170202](https://user-images.githubusercontent.com/105979314/169829073-5495bac3-8e1d-419b-a85d-c5b7f2be0473.png)

**Comment by petebankhead** [comment]
Hi @vatempeli please post your questions at https://forum.image.sc/tag/qupath
I'll close this because it's not a true 'issue' (i.e. a bug report following the required template).
