### ISSUE TITLE
Can't access WSI levels in MACOS Monterey 12.4

### ISSUE THREAD

**Issue by cossiomanuel** [qupath/qupath#973]
BUG:

WSI image will pixelate when trying to access deeper levels of magnification. Tested the soft in two different Macs with the same OS and the same happens. 

To reproduce:

1- Select Open and then the WSI image in .tif format.
2- Two files are available: Image and the Mask. Select the Image and select Open.
3- A dialogue will appear to select type of Image: select bright filed H&E
4- Scroll with the mouse to activate zoom or with right-click, select display and then different levels of zoom. 

Expected behavior
With the scroll, zoom should access higher levels of magnification and the image should not be pixelated. Cells must be able to be seen. 

Desktop
MACOS Monterey 12.4, 2GHZ Core i5 (2 cores), 8GB 1867 MHZ DDR3, Intel iris 540 1036 MB
QuPath version 0.3.2, Max memory JVM may try to use: 4096 MB

![DD0F3384-7024-455E-98AC-3916959D9B95](https://user-images.githubusercontent.com/53937441/170973697-316e32c0-6f1f-4de1-9d3e-d6a6134a34e3.jpeg)

**Comment by petebankhead** [comment]
Hi, some questions:
* What is the file format?
* Under the 'Image' tab, what is shown at the entry 'Server type'?
* Have you been able to view the whole slide image with any other version of QuPath (e.g. on Windows)?
* Is there any relevant information under *View &rarr; Show log*?

If you have an mrxs image, this may be relevant: https://forum.image.sc/t/potential-fix-for-problem-low-resolution-mrxs-3dhistech-scans/32917

If you have an mrxs or vsi image, you might be missing the folder the should exist alongside the main image file (the folder contains the high-resolution data).

**Comment by cossiomanuel** [comment]
HI,

Thanks for you help!

File format: .tif 

This is all the info of the image




I didn’t try with another version. Will do now. 

Info under show log:

INFO: Initializing type adapters
INFO: Bio-Formats version 6.7.0
INFO: Loaded extension Bio-Formats options (Bio-Formats 6.7.0) (18 ms)
INFO: Loaded extension ImageJ extension (69 ms)
INFO: Loaded extension Processing extension (30 ms)
INFO: Loaded extension Rich script editor extension (81 ms)
INFO: Loaded extension SVG export extension (1 ms)
INFO: OpenSlide version 3.4.1
INFO: Update check for https://github.com/qupath/qupath
INFO: Starting QuPath with parameters: []
INFO: Setting max Bio-Formats readers to 4
WARN: Temp memoization directory created at /var/folders/_v/1nq60v556l5cbwcdv47wq76w0000gn/T/qupath-memo-4532483650866269942
WARN: If you want to avoid this warning, either specify a memoization directory in the preferences or turn off memoization by setting the time to < 0
INFO: Image data set to ImageData: Not set, 16.tif - Series 0



Again, thank you very much for your incredible help!

Manuel

**Comment by cossiomanuel** [comment]
Tried with the version 0.3.1 and the problem remains.

**Comment by petebankhead** [comment]
Hi @cossiomanuel 

thanks for sharing an image. The underlying bug seems to be the same as these:
* https://github.com/qupath/qupath/issues/904
* https://github.com/qupath/qupath/issues/894

It will be fixed in the next QuPath release. In the meantime, the workaround is to [add images to a project](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html) first.

I'll close the issue because that resolved it for me on Monterey, but please do let me know if it works for you.
