### ISSUE TITLE
Full resolution labeled image export can fail without indicating correct approach

### ISSUE THREAD

**Issue by MichaelSNelson** [qupath/qupath#984]
**Describe the bug**
LabeledImageServers do not pyramidalize by default and so throw an error when a user tries to export a whole slide image as a label. This can be circumvented by pyramidalizing the labelServer, but the user would not necessarily know this from the error message.
See https://forum.image.sc/t/exporting-full-labelled-images-of-arbitrary-large-wsis/66708/11

**To Reproduce**
Create a tissue annotation of a very large whole slide image. Export as a downsample 1 labeled image.
Error: `IllegalArgumentException at line X: Dimensions (width=W height=H) are too large.`
**Expected behavior**
Possibly provide a warning that the labeledImageServer needs to be pyramidalized - alternatively default to using a pyramidalized image server if the image is "too large". The image output type would probably need to be overwritten to ome.tif if it was not already that, with yet another warning message.

**Comment by petebankhead** [comment]
I **think** this should now be resolved by https://github.com/qupath/qupath/pull/1010

Basically, pyramidalization should happen when needed -- no need for the user to do it themselves. But I haven't got a good example to replicate it with yet.

@MichaelSNelson If you have a chance, could you check out if it seems to resolve the issue for you?

**Comment by MichaelSNelson** [comment]
This update does allow the export to run as expected when saving as "ome.tif". It might be useful to have a check/warning prior to attempting to write a file that is too large to a basic .tif. If I attempt the same export to .tif, after a long pause I get:

`WARN: Unable to write image
ERROR: IOException at line 22: Unable to write F:\filepath\Sox2 region_0_annotationLabels.tif!  No compatible writer found.`

Oddly enough, I ran into trouble with the new Telerium openjdk not recognizing `gradlew ` when trying to set that up on my new computer, but was able to build and test things out on my old one so... I will look into that later.
