### ISSUE TITLE
Improve dialog that appears on startup

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#986]
## Bug report

**Describe the bug**
When QuPath is first launched, a few key options are presented to the user - which are currently the memory settings, locale and whether to check for updates.

Except that these are no longer really key.

The memory setting was important in early releases, when memory was specified in absolute terms (e.g. 4GB). Most users would want to increase it depending upon what is available. However, now memory defaults to 50% of the available system memory, which means it's less likely to require adjustment.

What's more, the memory can't even be adjusted on macOS anyway due to permissions limitations.

Changing the locale is also strongly discouraged, since it can cause confusion - especially when inputting numbers (using a comma or decimal separator).

Therefore space is give to a dialog that is no longer fully functional on all platforms, and isn't really needed.

**To Reproduce**
Check the current display via *Help &rarr; Show setup options*.

**Expected behavior**
Three main things:
* Show a more informative and useful startup dialog, e.g. to introduce the user interface, forum or documentation.
* Relegate non-essential options to the preferences.
* Retain a checkbox to specify whether to check for updates or not

**Screenshots**

Current dialog, as it appears on a Mac.
![Screenshot 2022-06-02 at 09 37 51](https://user-images.githubusercontent.com/4690904/171590676-2b69b837-681f-4838-9d9e-1fcf6ed5ab5d.png)

**Desktop (please complete the following information):**
 - OS: All
 - QuPath v0.3.2

**Additional context**
The locale settings have already been moved to the preferences in https://github.com/qupath/qupath/pull/971
This issue really exists to track the progress of the other required changes for v0.4.0.

**Comment by yau-lim** [comment]
> However, now memory defaults to 50% of the available system memory
I would understand that this works for computers with not much RAM (e.g. 8 GB or 16 GB). But when you have 64 GB RAM or more, will using only 50% of available system memory mean having the other half of the massive RAM essentially unused?

**Comment by petebankhead** [comment]
It will still be possible to change the RAM, it just wouldn't be such a prominent option on startup.

I'm not sure what the best default is, but I have the impression that more users will have too little RAM than too much - and the proportion needs to be defined when QuPath is built (I don't know any way to change it after it is installed).

**Comment by petebankhead** [comment]
Fixed by 
* https://github.com/qupath/qupath/pull/1124
* https://github.com/qupath/qupath/pull/1125

Extra comment on the memory: the limit affects Java, but JavaCPP can potentially access more memory. Therefore the most memory-hungry thing (pixel classification) isn't strictly subject to the same limit.

It should still be possible to specify the memory in the preferences on Windows/Linux, but this needs checked.
