### ISSUE TITLE
'Cannot invoke “java.lang.Double.doubleValue()”' exception in 'Create Thresholder'

### ISSUE THREAD

**Issue by vatempeli** [qupath/qupath#988]
It seems like my files cannot be recognised(?) anymore. They are 16-bit images 
and cropped many times (at about 50MB) so I suppose that memmory is not the problem. Actually when I try to type a specific number for the thresholder -where I am not even allowed to do it- this happens (image below). Can it be fixed? I am using the latest version of QuPath (QuPath-0.3.2)
![Στιγμιότυπο οθόνης 2022-06-03 110001](https://user-images.githubusercontent.com/105979314/171827128-5d2ada24-f5a2-4eb7-b288-cfd5fc786dea.png)

**Comment by petebankhead** [comment]
Hi @vatempeli 

I can replicate the bug if I delete one of the values in the *Create thresholder* dialog, and then press one of the associated up or down arrows. The solution is to type a valid number instead. Then the arrows should work.

If that's not the issue you're seeing, I'd need more details about *exactly* what steps you used. I'd also need the full log message (the top is cropped off in the screenshot, so it misses the most important information).
