### ISSUE TITLE
Feature request: Export masks without a color lookup table

### ISSUE THREAD

**Issue by MichaelSNelson** [qupath/qupath#993]
QuPath 0.3.2, and prior, I imagine.

Currently when exporting labels using the [LabeledImageServer](https://qupath.github.io/javadoc/docs/qupath/lib/images/servers/LabeledImageServer.Builder.html), the saved file includes a color lookup table which is quite nice in Windows for viewing the labels. In grayscale, low values would often disappear is 0,1 and 2 are fairly similar. However, some Python readers like PIL interpret the color lookup table as meaning that the image should be read in color, and a TIFF file with all 0, 1 and 2 values in a single channel will show up with 255s (for a white background) and other intermediate numbers. 

It would be nice if there were an option to not apply a lookup table when exporting the masks. For the moment, my workaround is to resave the images as 8bit through an ImageJ macroRunner at the end of the script that writes the labeled images - overwriting the original. I am not including it here as it makes some assumptions about the Hierarchy that may not be true in all cases.

Cheers,
Mike

**Comment by petebankhead** [comment]
Thanks for logging this after our chat about it, I agree QuPath should provide this option somewhere. I thought the LUT method was cleverer (and more effort to get working...), and it avoids some of the 'my image is all black' bug reports that otherwise ensue when exporting grayscale images that all have low pixel values and previewing them in the operating system's default viewer.

But Iit is indeed a bit annoying that it requires setting the `mode` to `L` when using PIL - and also requires getting that option somehow passed through to PIL if using some library on top of it (like `imageio`).

I'll try to get an optional alternative for the next QuPath release that can just output grayscale labelled images instead.

**Comment by petebankhead** [comment]
Actually... something that *might* help in the short term is to use the specify the color with [addLabel](https://qupath.github.io/javadoc/docs/qupath/lib/images/servers/LabeledImageServer.Builder.html#addLabel(qupath.lib.objects.classes.PathClass,int,java.lang.Integer))​, i.e.
```groovy
// Create an ImageServer where the pixels are derived from annotations
def labelServer = new LabeledImageServer.Builder(imageData)
    .backgroundLabel(0, ColorTools.BLACK) // Specify background label (usually 0 or 255)
    .downsample(downsample)    // Choose server resolution; this should match the resolution at which tiles are exported
    .addLabel('Tumor', 1, makeRGB(1, 1, 1))      // Choose output labels (the order matters!)
    .addLabel('Stroma', 2, makeRGB(2, 2, 2))
    .multichannelOutput(false) // If true, each label refers to the channel of a multichannel binary image (required for multiclass probability)
    .build()
```

You might still end up with an RGB image in Python, but when I tried it briefly it gave me a 2D image without LUT - as long as my RGB colors were all grayscale.

**Comment by MichaelSNelson** [comment]
Nice, I can confirm that does appear to be working through fast.ai - 
![image](https://user-images.githubusercontent.com/85200392/174496575-f5f147d1-855f-4ccb-81a5-d87fb78c5aa9.png)
The masks are loading the correct number of channels in the right places now, at least!

**Comment by MichaelSNelson** [comment]
I am glad I checked completely. Despite appearing to read in correctly, there is still some issue that saving using the LabeledImageServer does not resolve. I am not sure what the problem is, but my model, despite showing the mask correctly, trains as if the entire image is background. I am not happy to report "something does not work somewhere" since that will not help fix the problem, but that is where I am at. Running it through Fiji to convert to 8bit still works, however. 
Exporting the images both ways results in, as far as I can tell, identical images.
![image](https://user-images.githubusercontent.com/85200392/174497099-16e24bec-c6db-442c-abe3-03e26d1d408a.png)

However the one on the right was exported directly by the LabeledImageServer, and fails to work during training.

**Comment by MichaelSNelson** [comment]
I also checked the BioFormats importer, which tells a slightly different story. The BioFormats metadata is the exact same, but:
![image](https://user-images.githubusercontent.com/85200392/174497231-95dc70a4-0193-4fd3-a67b-eb546a90f932.png)
I am guessing that either the PhotometricInterpretation or NumberOfChannels is the cause.

**Comment by MichaelSNelson** [comment]
In case it helps test:
[LabeledImageServer.zip](https://github.com/qupath/qupath/files/8936245/LabeledImageServer.zip)
[Resaved as 8bit Fiji.zip](https://github.com/qupath/qupath/files/8936249/Resaved.as.8bit.Fiji.zip)

**Comment by petebankhead** [comment]
Rats... it makes sense that they are slightly different, but I hoped they would become the same when read. They seemed to when I used PIL via imageio, but I don't know what stuff fast.ai is doing. Calling [`Image.open_image(path)`](https://fastai1.fast.ai/vision.image.html#open_image) for both might (or might not) be useful.

**Comment by petebankhead** [comment]
I think this PR should help - there's now a `grayscale()` option in the builder: https://github.com/qupath/qupath/pull/1000

If you have a chance to try it out, please let me know if you find any problems (or successes).

**Comment by MichaelSNelson** [comment]
Thanks @petebankhead, I can confirm the new build plus grayscale() option allows me to use the labeled images without any modifications in PyTorch!

**Comment by petebankhead** [comment]
Excellent, thanks for checking!
