### ISSUE TITLE
QuPath detection cytoplasm Inclusions

### ISSUE THREAD

**Issue by pcaste14** [qupath/qupath#994]
Hello, 
I am using QuPath to detect inclusions in the cytoplasm for DAB stainning, They are small and I want to do a quantification of the number of inclusions. Can somebody help with this issue? Thank you

**Comment by MichaelSNelson** [comment]
You might want to try the image.sc forum where this type of question is supposed to be asked. As indicated in the automatic prompt when you create a post here!

**Comment by pcaste14** [comment]
Okay,
Thank you!
